### ISSUE TITLE
Web Editor not working

### ISSUE THREAD

**Issue by NightRider0** [lucko/LuckPerms#1000]
I get the following when i run /lp editor, i try to the url it compaining about and get "Invalid path"
```
 [09:33:54 WARN]: java.lang.RuntimeException: java.net.ConnectException: Failed to connect to bytebin.lucko.me/2400:cb00:2048:1:0:0:681b:976a:443
[09:33:54 WARN]:        at me.lucko.luckperms.common.web.StandardPastebin.post(StandardPastebin.java:156)
[09:33:54 WARN]:        at me.lucko.luckperms.common.web.StandardPastebin.postJson(StandardPastebin.java:123)
[09:33:54 WARN]:        at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:105)
[09:33:54 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:50)
[09:33:54 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:42)
[09:33:54 WARN]:        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:202)
[09:33:54 WARN]:        at me.lucko.luckperms.common.command.CommandManager.lambda$onCommand$0(CommandManager.java:147)
[09:33:54 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(java.base@9-internal/CompletableFuture.java:1651)
[09:33:54 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1158)
[09:33:54 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632)
[09:33:54 WARN]:        at java.lang.Thread.run(java.base@9-internal/Thread.java:804)
[09:33:54 WARN]: Caused by: java.net.ConnectException: Failed to connect to bytebin.lucko.me/2400:cb00:2048:1:0:0:681b:976a:443
[09:33:54 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:242)
[09:33:54 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
[09:33:54 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
[09:33:54 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
[09:33:54 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
[09:33:54 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
[09:33:54 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[09:33:54 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[09:33:54 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
[09:33:54 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[09:33:54 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[09:33:54 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[09:33:54 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[09:33:54 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
[09:33:54 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[09:33:54 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[09:33:54 WARN]:        at me.lucko.luckperms.common.web.HttpClient$LuckPermsUserAgentInterceptor.intercept(HttpClient.java:87)
[09:33:54 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[09:33:54 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[09:33:54 WARN]:        at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
[09:33:54 WARN]:        at me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:77)
[09:33:54 WARN]:        at me.lucko.luckperms.common.web.HttpClient.makeCall(HttpClient.java:60)
[09:33:54 WARN]:        at me.lucko.luckperms.common.web.StandardPastebin.post(StandardPastebin.java:141)
[09:33:54 WARN]:        ... 10 more
[09:33:54 WARN]: Caused by: java.net.ConnectException: Network is unreachable
[09:33:54 WARN]:        at java.net.PlainSocketImpl.socketConnect(java.base@9-internal/Native Method)
[09:33:54 WARN]:        at java.net.AbstractPlainSocketImpl.doConnect(java.base@9-internal/AbstractPlainSocketImpl.java:405)
[09:33:54 WARN]:        at java.net.AbstractPlainSocketImpl.connectToAddress(java.base@9-internal/AbstractPlainSocketImpl.java:248)
[09:33:54 WARN]:        at java.net.AbstractPlainSocketImpl.connect(java.base@9-internal/AbstractPlainSocketImpl.java:230)
[09:33:54 WARN]:        at java.net.SocksSocketImpl.connect(java.base@9-internal/SocksSocketImpl.java:402)
[09:33:54 WARN]:        at java.net.Socket.connect(java.base@9-internal/Socket.java:591)
[09:33:54 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
[09:33:54 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:240)
[09:33:54 WARN]:        ... 32 more
```

**Comment by lucko** [comment]
also: wew 1000 issues 😄

**Comment by NightRider0** [comment]
when i do a wget from the server as it is CLI only i get a response 200 OK, so i think its connecting just fine. 
![selection_051](https://user-images.githubusercontent.com/16971244/40095004-77f443b0-588f-11e8-8fe6-e3763d764a6d.png)

**Comment by lucko** [comment]
The error is being raised by the Java runtime, not LuckPerms:

`Caused by: java.net.ConnectException: Network is unreachable`

Perhaps you have a firewall blocking the connection for that user/process?

This definitely isn't an issue within LP.
