### ISSUE TITLE
PowerfulPerms migration issue

### ISSUE THREAD

**Issue by Miclebrick** [lucko/LuckPerms#1022]
[07:14:27 INFO]: [LP] MIGRATION [PowerfulPerms] > Starting.
[07:14:27 INFO]: [LP] MIGRATION [PowerfulPerms] > Getting a list of UUIDs to migrate.
[07:14:27 WARN]: java.lang.ArrayIndexOutOfBoundsException: 1
[07:14:27 WARN]:        at me.lucko.luckperms.bukkit.migration.MigrationPowerfulPerms$HikariSupplier.setup(MigrationPowerfulPerms.java:370)
[07:14:27 WARN]:        at me.lucko.luckperms.bukkit.migration.MigrationPowerfulPerms.execute(MigrationPowerfulPerms.java:111)
[07:14:27 WARN]:        at me.lucko.luckperms.common.command.abstraction.MainCommand.execute(MainCommand.java:103)
[07:14:27 WARN]:        at me.lucko.luckperms.common.command.abstraction.MainCommand.execute(MainCommand.java:46)
[07:14:27 WARN]:        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:202)
[07:14:27 WARN]:        at me.lucko.luckperms.common.command.CommandManager.lambda$onCommand$0(CommandManager.java:147)
[07:14:27 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[07:14:27 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[07:14:27 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[07:14:27 WARN]:        at java.lang.Thread.run(Thread.java:748)
[07:14:27 INFO]: [LP] MIGRATION [PowerfulPerms] > Error -> Unable to find any UUIDs to migrate.
>

Does this no matter what password I put in, positive that they are valid credentials, database, IP, etc.

**Comment by Miclebrick** [comment]
My bad, forgot to include a port. Maybe as an enhancement make it warn if you if you forget.
