### ISSUE TITLE
LP and Nucleus issue

### ISSUE THREAD

**Issue by Julio2546** [lucko/LuckPerms#1025]
Not quite sure what's going on here, any help would be appreciated.
Running the "Enigmatica 2" modpack, Nucleus-1.4.0-PR1-S7.0-MC1.12.2-plugin.jar, and LuckPerms-Sponge-4.2.17.jar. Don't know if this is a nucleus issue or an LP issue.
Let me know if you need anymore info:

```
[21:48:30] [pool-3-thread-76/ERROR] [Sponge]: The Scheduler tried to run the task nucleus-A-41 owned by Plugin{id=nucleus, name=Nucleus, version=1.4.0-PR1-S7.0, description=The Ultimate Essentials Plugin., url=http://nucleuspowered.org, source=./mods/Nucleus-1.4.0-PR1-S7.0-MC1.12.2-plugin.jar}, but an error occured.
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/caffeine/cache/RemovalCause$1
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_151]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_151]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592) ~[?:1.8.0_151]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2703-7.1.0-BETA-3119]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2703-7.1.0-BETA-3119]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/caffeine/cache/RemovalCause$1
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2058) ~[BoundedLocalCache.class:?]
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877) ~[?:1.8.0_151]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2037) ~[BoundedLocalCache.class:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2020) ~[BoundedLocalCache.class:?]
	at me.lucko.luckperms.lib.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112) ~[LocalCache.class:?]
	at me.lucko.luckperms.lib.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:67) ~[LocalLoadingCache.class:?]
	at me.lucko.luckperms.sponge.managers.SpongeUserManager.lambda$loadSubject$1(SpongeUserManager.java:150) ~[SpongeUserManager.class:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_151]
	... 7 more
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.caffeine.cache.RemovalCause$1
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2058) ~[BoundedLocalCache.class:?]
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877) ~[?:1.8.0_151]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2037) ~[BoundedLocalCache.class:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2020) ~[BoundedLocalCache.class:?]
	at me.lucko.luckperms.lib.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112) ~[LocalCache.class:?]
	at me.lucko.luckperms.lib.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:67) ~[LocalLoadingCache.class:?]
	at me.lucko.luckperms.sponge.managers.SpongeUserManager.lambda$loadSubject$1(SpongeUserManager.java:150) ~[SpongeUserManager.class:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_151]
	... 7 more
[21:51:29] [pool-3-thread-60/ERROR] [Sponge]: The Scheduler tried to run the task luckperms-A-22 owned by Plugin{id=luckperms, name=LuckPerms, version=4.2.17, description=A permissions plugin, url=https://github.com/lucko/LuckPerms, authors=[Luck], source=./mods/LuckPerms-Sponge-4.2.17.jar}, but an error occured.
java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/caffeine/cache/RemovalCause$1
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.expireAfterAccessEntries(BoundedLocalCache.java:701) ~[BoundedLocalCache.class:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.expireAfterAccessEntries(BoundedLocalCache.java:685) ~[BoundedLocalCache.class:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.expireEntries(BoundedLocalCache.java:673) ~[BoundedLocalCache.class:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.maintenance(BoundedLocalCache.java:1136) ~[BoundedLocalCache.class:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.performCleanUp(BoundedLocalCache.java:1108) ~[BoundedLocalCache.class:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.cleanUp(BoundedLocalCache.java:1093) ~[BoundedLocalCache.class:?]
	at me.lucko.luckperms.lib.caffeine.cache.LocalAsyncLoadingCache$LoadingCacheView.cleanUp(LocalAsyncLoadingCache.java:468) ~[LocalAsyncLoadingCache$LoadingCacheView.class:?]
	at me.lucko.luckperms.common.caching.AbstractCachedData.doCacheCleanup(AbstractCachedData.java:379) ~[AbstractCachedData.class:?]
	at me.lucko.luckperms.sponge.service.calculated.CalculatedSubject.performCleanup(CalculatedSubject.java:319) ~[CalculatedSubject.class:?]
	at me.lucko.luckperms.sponge.tasks.ServiceCacheHousekeepingTask.run(ServiceCacheHousekeepingTask.java:43) ~[ServiceCacheHousekeepingTask.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2703-7.1.0-BETA-3119]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2703-7.1.0-BETA-3119]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.caffeine.cache.RemovalCause$1
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	... 17 more
[21:51:29] [pool-3-thread-102/ERROR] [Sponge]: The Scheduler tried to run the task luckperms-A-21 owned by Plugin{id=luckperms, name=LuckPerms, version=4.2.17, description=A permissions plugin, url=https://github.com/lucko/LuckPerms, authors=[Luck], source=./mods/LuckPerms-Sponge-4.2.17.jar}, but an error occured.
java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/caffeine/cache/RemovalCause$1
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.expireAfterAccessEntries(BoundedLocalCache.java:701) ~[BoundedLocalCache.class:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.expireAfterAccessEntries(BoundedLocalCache.java:685) ~[BoundedLocalCache.class:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.expireEntries(BoundedLocalCache.java:673) ~[BoundedLocalCache.class:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.maintenance(BoundedLocalCache.java:1136) ~[BoundedLocalCache.class:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.performCleanUp(BoundedLocalCache.java:1108) ~[BoundedLocalCache.class:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.cleanUp(BoundedLocalCache.java:1093) ~[BoundedLocalCache.class:?]
	at me.lucko.luckperms.lib.caffeine.cache.LocalAsyncLoadingCache$LoadingCacheView.cleanUp(LocalAsyncLoadingCache.java:468) ~[LocalAsyncLoadingCache$LoadingCacheView.class:?]
	at me.lucko.luckperms.common.caching.AbstractCachedData.doCacheCleanup(AbstractCachedData.java:379) ~[AbstractCachedData.class:?]
	at me.lucko.luckperms.common.tasks.CacheHousekeepingTask.run(CacheHousekeepingTask.java:42) ~[CacheHousekeepingTask.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2703-7.1.0-BETA-3119]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2703-7.1.0-BETA-3119]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.caffeine.cache.RemovalCause$1
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	... 16 more
```

**Comment by lucko** [comment]
Indeed it looks like an LP issue.

Can you try stopping your server, then deleting the `/luckperms/lib` directory, and starting your server again
