### ISSUE TITLE
Can't load LuckPermsBungee

### ISSUE THREAD

**Issue by Eufranio** [lucko/LuckPerms#104]
When loading the plugin, it throws an exception:
```
Cannot create property=softdepends for JavaBean=PluginDescription(name=LuckPerms, main=me.lucko.luckperms.bungee.LPBungeePlugin, version=2.16.60, author=Luck, depends=[], softDepends=[], file=null, description=A permissions plugin)
 in 'reader', line 1, column 1:
    name: LuckPerms
    ^
Unable to find property 'softdepends' on class: net.md_5.bungee.api.plugin.PluginDescription
 in 'reader', line 6, column 14:
    softdepends: [PowerfulPerms] # For migration
                 ^

    at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:307)
    at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
    at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:340)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
    at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
    at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:475)
    at bungeepluginmanager.PluginUtils.loadPlugin(PluginUtils.java:115)
    at bungeepluginmanager.Commands.execute(Commands.java:51)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:169)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:116)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:118)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'softdepends' on class: net.md_5.bungee.api.plugin.PluginDescription
    at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:132)
    at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:121)
    at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:317)
    at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:240)
    ... 13 more
```

**Comment by Eufranio** [comment]
Happened because I wanted to load the plugin with BungeePluginManager, it doesn't seem to work with LuckPerms, unfortunately =/
Don't know if it still a issue, but I'm closing since it worked after a proxy restart.

**Comment by sgdc3** [comment]
BPM seems to load the plugin description in a different way, maybe it expects "softDepends" instead of "softdepends"

**Comment by lucko** [comment]
Strange. The code is seemingly identical. 

https://github.com/Shevchik/BungeePluginManager/blob/master/src/bungeepluginmanager/PluginUtils.java#L115
https://github.com/SpigotMC/BungeeCord/blob/master/api/src/main/java/net/md_5/bungee/api/plugin/PluginManager.java#L327
