### ISSUE TITLE
Error on PlayerJoin

### ISSUE THREAD

**Issue by DrPanic** [lucko/LuckPerms#1058]
Hey,

i try to switch over to LuckPerms but got an error.
When i attemp to connect to the server, the connection will be disconnected.

What can i do?

Thanks

Latest Paper-Build
Latest LuckPerms-Build

Log:
```
[23:14:58] [User Authenticator #1/INFO]: UUID of player DrPanic is 2c44636c-1408-48f8-9cda-d945698ebf2e
[23:14:58] [Server thread/WARN]: Failed to handle packet for /93.237.29.233:50183
java.lang.UnsupportedOperationException: null
	at com.google.common.collect.Sets$SetView.removeIf(Sets.java:689) ~[patched_1.12.2.jar:git-Paper-1463]
	at me.lucko.luckperms.bukkit.model.server.LPSubscriptionMap$LPSubscriptionValueMap.<init>(LPSubscriptionMap.java:166) ~[?:?]
	at me.lucko.luckperms.bukkit.model.server.LPSubscriptionMap$LPSubscriptionValueMap.<init>(LPSubscriptionMap.java:153) ~[?:?]
	at me.lucko.luckperms.bukkit.model.server.LPSubscriptionMap.get(LPSubscriptionMap.java:106) ~[?:?]
	at me.lucko.luckperms.bukkit.model.server.LPSubscriptionMap.get(LPSubscriptionMap.java:70) ~[?:?]
	at org.bukkit.plugin.SimplePluginManager.subscribeToPermission(SimplePluginManager.java:695) ~[patched_1.12.2.jar:git-Paper-1463]
	at org.bukkit.permissions.PermissibleBase.recalculatePermissions(PermissibleBase.java:156) ~[patched_1.12.2.jar:git-Paper-1463]
	at org.bukkit.permissions.PermissibleBase.<init>(PermissibleBase.java:29) ~[patched_1.12.2.jar:git-Paper-1463]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.<init>(CraftHumanEntity.java:40) ~[patched_1.12.2.jar:git-Paper-1463]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.<init>(CraftPlayer.java:100) ~[patched_1.12.2.jar:git-Paper-1463]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.getEntity(CraftEntity.java:49) ~[patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.Entity.getBukkitEntity(Entity.java:59) ~[patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.EntityHuman.getBukkitEntity(EntityHuman.java:76) ~[patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.EntityPlayer.getBukkitEntity(EntityPlayer.java:1547) ~[patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.PlayerList.attemptLogin(PlayerList.java:531) ~[patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:152) ~[patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68) ~[patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:255) ~[patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) [patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:941) [patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1463]
	at java.lang.Thread.run(Thread.java:844) [?:?]
[23:14:58] [Server thread/WARN]: Failed to handle packet for /93.237.29.233:50183
java.lang.UnsupportedOperationException: null
	at com.google.common.collect.Sets$SetView.removeIf(Sets.java:689) ~[patched_1.12.2.jar:git-Paper-1463]
	at me.lucko.luckperms.bukkit.model.server.LPSubscriptionMap$LPSubscriptionValueMap.<init>(LPSubscriptionMap.java:166) ~[?:?]
	at me.lucko.luckperms.bukkit.model.server.LPSubscriptionMap$LPSubscriptionValueMap.<init>(LPSubscriptionMap.java:153) ~[?:?]
	at me.lucko.luckperms.bukkit.model.server.LPSubscriptionMap.get(LPSubscriptionMap.java:106) ~[?:?]
	at me.lucko.luckperms.bukkit.model.server.LPSubscriptionMap.get(LPSubscriptionMap.java:70) ~[?:?]
	at org.bukkit.plugin.SimplePluginManager.subscribeToPermission(SimplePluginManager.java:695) ~[patched_1.12.2.jar:git-Paper-1463]
	at org.bukkit.permissions.PermissibleBase.recalculatePermissions(PermissibleBase.java:156) ~[patched_1.12.2.jar:git-Paper-1463]
	at org.bukkit.permissions.PermissibleBase.<init>(PermissibleBase.java:29) ~[patched_1.12.2.jar:git-Paper-1463]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.<init>(CraftHumanEntity.java:40) ~[patched_1.12.2.jar:git-Paper-1463]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.<init>(CraftPlayer.java:100) ~[patched_1.12.2.jar:git-Paper-1463]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.getEntity(CraftEntity.java:49) ~[patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.Entity.getBukkitEntity(Entity.java:59) ~[patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.EntityHuman.getBukkitEntity(EntityHuman.java:76) ~[patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.EntityPlayer.getBukkitEntity(EntityPlayer.java:1547) ~[patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.PlayerList.attemptLogin(PlayerList.java:531) ~[patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:152) ~[patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68) ~[patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:255) ~[patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) [patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:941) [patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1463]
	at java.lang.Thread.run(Thread.java:844) [?:?]
[23:14:58] [Server thread/INFO]: com.mojang.authlib.GameProfile@73ca65ad[id=2c44636c-1408-48f8-9cda-d945698ebf2e,name=DrPanic,properties={textures=[com.mojang.authlib.properties.Property@ae2a9a6], forgeClient=[com.mojang.authlib.properties.Property@425468a], extraData=[com.mojang.authlib.properties.Property@1ac2d6]},legacy=false] (/93.237.29.233:50183) lost connection: Internal server error
[23:15:14] [Server thread/INFO]: [DEBUG] [TerraconiaAwards] [Task] Running task for DrPanic
```

**Comment by lucko** [comment]
Hmm that's a strange error to have.

Could you give me a list of the other plugins you're using?

**Comment by DrPanic** [comment]
Sure. We have many cusom plugin that we developed for us, but the common one are:
`BanManager, ChestShop, Citizens, Denizen, DeathMessagesPrime, Dynmap, EntityLWC, Farmlimiter, FastAsyncWorldEdit, HolographicDisplays, iConomy, LogBlock, Multiverse, NoCheatPlus, PEX, PlayerSQL, ProtocolLib, SimplePets, SuperTrails, SuperVanish, Vault, WorldBorder, WorldEdit, WorldGuard`

Originally i've tested LuckPerms with version 4.1.87 and this version still works fine.

**Comment by lucko** [comment]
The error is because PEX is still installed - you can only use one permissions plugin at a time

**Comment by DrPanic** [comment]
Trank you, i will test this. But will the migration then be possible? The Wiki says it should be enabled for that.

**Comment by lucko** [comment]
Yes, you can also update to the latest dev build to resolve the issue

https://luckperms.github.io/
