### ISSUE TITLE
General Issue 

### ISSUE THREAD

**Issue by Trucasy0** [lucko/LuckPerms#1070]
Hello, 

today me and another friend tried to install LuckPerms on bungeecord. 

`21:59:31 [WARNING] Error enabling plugin LuckPerms
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:34)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:304)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:267)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.kroseida.launcher.Launcher.startServer(Launcher.java:104)
    at com.kroseida.launcher.Launcher.<init>(Launcher.java:37)
    at com.kroseida.launcher.Launcher.main(Launcher.java:22)
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 25 more`

This was the result. We werent able to figure out where the issue comes from. 
Using the latest version of bungeecord, all the requirements were met, including the things shown in the network installation wiki. 

Please help. 

Greetings

**Comment by BrainStone** [comment]
You should try to use the Bungee version instead of the Bukkit/Spigot version. I mean there's a reason the file is called `LuckPerms-Bukkit-4.x.x.jar`

Third sentence on the [wiki](https://github.com/lucko/LuckPerms/wiki) links you directly to the downloads.

**Comment by Trucasy0** [comment]
I am using the bungeecord-version. Thats the point.

**Comment by lucko** [comment]
You're not - you've installed the Bukkit version of LuckPerms to your proxy plugins folder.

You need to use the BungeeCord version instead.
https://luckperms.github.io/
