### ISSUE TITLE
Error on German translation

### ISSUE THREAD

**Issue by vr6syncro** [lucko/LuckPerms#1085]
`[21:51:15 INFO]: [LuckPerms] Loading configuration...
[21:51:15 INFO]: [LuckPerms] Found lang.yml - loading messages...
[21:51:15 WARN]: mapping values are not allowed here
 in 'reader', line 560, column 22:
    <!-- blob contrib key: blob_contributors:v21:9d84d4e4 ...
                         ^

[21:51:15 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:872)
[21:51:15 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360)
[21:51:15 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.peekToken(ScannerImpl.java:249)
[21:51:15 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentEnd.produce(ParserImpl.java:252)
[21:51:15 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
[21:51:15 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:167)
[21:51:15 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:124)
[21:51:15 WARN]:        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
[21:51:15 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:140)
[21:51:15 WARN]:        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
[21:51:15 WARN]:        at org.yaml.snakeyaml.Yaml.load(Yaml.java:467)
[21:51:15 WARN]:        at me.lucko.luckperms.common.locale.LocaleManager.loadFromFile(LocaleManager.java:78)
[21:51:15 WARN]:        at me.lucko.luckperms.common.locale.LocaleManager.tryLoad(LocaleManager.java:59)
[21:51:15 WARN]:        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:111)
[21:51:15 WARN]:        at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:152)
[21:51:15 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[21:51:15 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[21:51:15 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[21:51:15 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382)
[21:51:15 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331)
[21:51:15 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
[21:51:15 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[21:51:15 WARN]:        at java.lang.Thread.run(Unknown Source)
[21:51:15 INFO]: [LuckPerms] Loading storage provider... [H2]
[21:51:16 INFO]: [LuckPerms] Loading internal permission managers...
[21:51:16 INFO]: [LuckPerms] Performing initial data load...
[21:51:16 INFO]: [LuckPerms] Successfully enabled. (took 485ms)`

**Comment by Andre601** [comment]
Did you made sure, to use the file from [here](https://github.com/LuckPerms/locale/blob/master/de_DE.yml)?

**Comment by vr6syncro** [comment]
ok sorry my fault. yeah but i saved hole page instead of only the code. lol sorry.
