### ISSUE TITLE
LP 4.2.17 loads fine on pre7 but not on final 1.13

### ISSUE THREAD

**Issue by gerardvanschip** [lucko/LuckPerms#1114]
Clean empty server folder, fresh world, just build full 1.13, clean LuckyPerms and getting this error.

**CONSOLE**
[09:34:30] [Server thread/ERROR]: Could not load 'plugins/LuckPerms-Bukkit-4.2.17.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[custom.jar:git-Spigot-ed1cec9-4e2f571]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [custom.jar:git-Spigot-ed1cec9-4e2f571]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.loadPlugins(CraftServer.java:313) [custom.jar:git-Spigot-ed1cec9-4e2f571]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:213) [custom.jar:git-Spigot-ed1cec9-4e2f571]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [custom.jar:git-Spigot-ed1cec9-4e2f571]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
Caused by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_65]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_65]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_65]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_65]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_65]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[custom.jar:git-Spigot-ed1cec9-4e2f571]
	... 5 more
[09:34:38] [Server thread/INFO]: Set PluginClassLoader as parallel capable

**Comment by lucko** [comment]
Seems like you've downloaded a corrupted jar file.

Try redownloading? Definitely loads correctly for me.
