### ISSUE TITLE
Logout error with MassiveCombat

### ISSUE THREAD

**Issue by TheWranger** [lucko/LuckPerms#1117]
Running PaperSpigot 1.12.2 - 1506
Luck Perms v4.2.42
When I have both MassiveCombat and Luckperms installed and a player disconnects from the server, I get this error in the console:
```24.07 02:53:36 [Server] ERROR Could not pass event EventMassiveCorePlayerLeave to MassiveCombat v2.14.0
24.07 02:53:36 [Server] INFO org.bukkit.event.EventException: null
24.07 02:53:36 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1506]
24.07 02:53:36 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1506]
24.07 02:53:36 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1506]
24.07 02:53:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.12.2.jar:git-Paper-1506]
24.07 02:53:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.12.2.jar:git-Paper-1506]
24.07 02:53:36 [Server] INFO at com.massivecraft.massivecore.event.EventMassiveCorePlayerLeave.run(EventMassiveCorePlayerLeave.java:84) ~[?:?]
24.07 02:53:36 [Server] INFO at com.massivecraft.massivecore.engine.EngineMassiveCorePlayerLeave.runQuit(EngineMassiveCorePlayerLeave.java:57) ~[?:?]
24.07 02:53:36 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor115.execute(Unknown Source) ~[?:?]
24.07 02:53:36 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1506]
24.07 02:53:36 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1506]
24.07 02:53:36 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1506]
24.07 02:53:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.12.2.jar:git-Paper-1506]
24.07 02:53:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.12.2.jar:git-Paper-1506]
24.07 02:53:36 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:429) ~[patched_1.12.2.jar:git-Paper-1506]
24.07 02:53:36 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1148) ~[patched_1.12.2.jar:git-Paper-1506]
24.07 02:53:36 [Server] INFO at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:343) ~[patched_1.12.2.jar:git-Paper-1506]
24.07 02:53:36 [Server] INFO at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:184) ~[patched_1.12.2.jar:git-Paper-1506]
24.07 02:53:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:947) ~[patched_1.12.2.jar:git-Paper-1506]
24.07 02:53:36 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1506]
24.07 02:53:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[patched_1.12.2.jar:git-Paper-1506]
24.07 02:53:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) ~[patched_1.12.2.jar:git-Paper-1506]
24.07 02:53:36 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
24.07 02:53:36 [Server] INFO Caused by: java.lang.UnsupportedOperationException
24.07 02:53:36 [Server] INFO at java.util.AbstractList.add(AbstractList.java:148) ~[?:1.8.0_171]
24.07 02:53:36 [Server] INFO at java.util.AbstractList.add(AbstractList.java:108) ~[?:1.8.0_171]
24.07 02:53:36 [Server] INFO at com.massivecraft.massivecore.util.PermissionUtil.createPermissibleAttachment(PermissionUtil.java:430) ~[?:?]
24.07 02:53:36 [Server] INFO at com.massivecraft.massivecore.util.PermissionUtil.getPermissibleAttachment(PermissionUtil.java:455) ~[?:?]
24.07 02:53:36 [Server] INFO at com.massivecraft.massivecombat.entity.MPlayer.setFlaggedPermissions(MPlayer.java:228) ~[?:?]
24.07 02:53:36 [Server] INFO at com.massivecraft.massivecombat.entity.MPlayer.setFlaggedPermissions(MPlayer.java:218) ~[?:?]
24.07 02:53:36 [Server] INFO at com.massivecraft.massivecombat.entity.MPlayer.setFlaggedPermissions(MPlayer.java:212) ~[?:?]
24.07 02:53:36 [Server] INFO at com.massivecraft.massivecombat.entity.MPlayer.tickFlagged(MPlayer.java:287) ~[?:?]
24.07 02:53:36 [Server] INFO at com.massivecraft.massivecombat.entity.MPlayer.isFlagged(MPlayer.java:350) ~[?:?]
24.07 02:53:36 [Server] INFO at com.massivecraft.massivecombat.entity.MPlayer.isEnabled(MPlayer.java:102) ~[?:?]
24.07 02:53:36 [Server] INFO at com.massivecraft.massivecombat.entity.MPlayer.isEnabled(MPlayer.java:97) ~[?:?]
24.07 02:53:36 [Server] INFO at com.massivecraft.massivecombat.engine.EngineLogout.listener(EngineLogout.java:53) ~[?:?]
24.07 02:53:36 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor190.execute(Unknown Source) ~[?:?]
24.07 02:53:36 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1506]
24.07 02:53:36 [Server] INFO ... 21 more

**Comment by Andre601** [comment]
This is not a LuckPerms-issue at all.
Please report that to the dev(s) of MassiveCombat

**Comment by lucko** [comment]
Yeah uh, it makes no sense for MassiveCombat to add new permission attachments as the player leaves the server.

Would guess that's a mistake on their part - but I'll push a fix for LP anyway.

**Comment by TheWranger** [comment]
Thank you so much.
