### ISSUE TITLE
Minor bug when i start the server

### ISSUE THREAD

**Issue by montlikadani** [lucko/LuckPerms#1130]
Console error:
```
[14:05:58] [luckperms-2/WARN]: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@586091a4 rejected from me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$AsyncExecutor@1e277348[Shutting down, pool size = 4, active threads = 1, queued tasks = 1, completed tasks = 39]
[14:05:58] [luckperms-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
[14:05:58] [luckperms-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
[14:05:58] [luckperms-2/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
[14:05:58] [luckperms-2/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
[14:05:58] [luckperms-2/WARN]: 	at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler.asyncLater(AbstractJavaScheduler.java:49)
[14:05:58] [luckperms-2/WARN]: 	at me.lucko.luckperms.common.buffers.BufferedRequest$Processor.rescheduleTask(BufferedRequest.java:134)
[14:05:58] [luckperms-2/WARN]: 	at me.lucko.luckperms.common.buffers.BufferedRequest$Processor.<init>(BufferedRequest.java:123)
[14:05:58] [luckperms-2/WARN]: 	at me.lucko.luckperms.common.buffers.BufferedRequest.request(BufferedRequest.java:83)
[14:05:58] [luckperms-2/WARN]: 	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.lambda$enable$1(AbstractLuckPermsPlugin.java:169)
[14:05:58] [luckperms-2/WARN]: 	at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$WrappedRunnable.run(AbstractJavaScheduler.java:79)
[14:05:58] [luckperms-2/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[14:05:58] [luckperms-2/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[14:05:58] [luckperms-2/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
[14:05:58] [luckperms-2/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
[14:05:58] [luckperms-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:05:58] [luckperms-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:05:58] [luckperms-2/WARN]: 	at java.lang.Thread.run(Unknown Source)
```
Plugin version: latest (from Jenkins)
Spigot version: 1.8-1.12 (all version)

So, as I run the server, this bug is spam in the console and shutdown server. ^ The server settings are all right, only this is displayed.

**Comment by codingJWilliams** [comment]
Hey, could you upload the full server log to https://hastebin.com please :)

**Comment by montlikadani** [comment]
Yep. https://hastebin.com/kesemopuka.sql

**Comment by lucko** [comment]
You just coincidentally shutdown your server 2 seconds after it started. 😄

**Comment by montlikadani** [comment]
Wat??, How would I stop the server when I can not write anything on the console? I see this, fixed it. [(link](https://github.com/lucko/LuckPerms/commit/381922fc023a8ab011c7a90315f2bb98ff81303e)
