### ISSUE TITLE
Import command

### ISSUE THREAD

**Issue by DaedalusPrime97** [lucko/LuckPerms#116]
me.lucko.luckperms.common.commands.misc.ImportCommand.execute(ImportCommand.java:73)
[17:41:13] [Craft Scheduler Thread - 6/WARN]: at me.lucko.luckperms.common.commands.SingleCommand.execute(SingleCommand.java:46)
[17:41:13] [Craft Scheduler Thread - 6/WARN]: at me.lucko.luckperms.common.commands.SingleCommand.execute(SingleCommand.java:34)
[17:41:13] [Craft Scheduler Thread - 6/WARN]: at me.lucko.luckperms.common.commands.CommandManager.onCommand(CommandManager.java:152)
[17:41:13] [Craft Scheduler Thread - 6/WARN]: at me.lucko.luckperms.common.commands.CommandManager.lambda$onCommand$1(CommandManager.java:98)
[17:41:13] [Craft Scheduler Thread - 6/WARN]: at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[17:41:13] [Craft Scheduler Thread - 6/WARN]: at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[17:41:13] [Craft Scheduler Thread - 6/WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[17:41:13] [Craft Scheduler Thread - 6/WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[17:41:13] [Craft Scheduler Thread - 6/WARN]: at java.lang.Thread.run(Thread.java:745)
[17:41:13] [Craft Scheduler Thread - 6/INFO]: [LP] An unexpected error occured whilst reading from the log file.

**Comment by lucko** [comment]
Need the rest of that stacktrace, please.

**Comment by lucko** [comment]
Please reopen if the error occurs again.
