### ISSUE TITLE
ExtraContexts causes server crash

### ISSUE THREAD

**Issue by SlimeDog** [lucko/LuckPerms#1178]
Spigot 1.13 latest
LuckPerm 4.2.82
ExtraContexts 3.2-b5

Crash on startup
```
[18:03:57] [Server thread/ERROR]: Could not pass event PlayerLoginEvent to LuckPerms v4.2.82
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.PlayerList.attemptLogin(PlayerList.java:531) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.LoginListener.b(LoginListener.java:130) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.LoginListener.Y_(LoginListener.java:54) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.NetworkManager.a(NetworkManager.java:231) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.ServerConnection.c(ServerConnection.java:120) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:984) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/WGBukkit
        at me.lucko.extracontexts.calculators.WorldGuardCalculator.giveApplicableContext(WorldGuardCalculator.java:27) ~[?:?]
        at me.lucko.extracontexts.calculators.WorldGuardCalculator.giveApplicableContext(WorldGuardCalculator.java:16) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextManager.calculate(ContextManager.java:225) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextsCache.supply(ContextsCache.java:54) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextsCache.supply(ContextsCache.java:41) ~[?:?]
        at me.lucko.luckperms.common.buffers.ExpiringCache.get(ExpiringCache.java:65) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextsCache.getContexts(ContextsCache.java:59) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextManager.getApplicableContexts(ContextManager.java:115) ~[?:?]
        at me.lucko.luckperms.bukkit.LPBukkitPlugin.refreshAutoOp(LPBukkitPlugin.java:335) ~[?:?]
        at me.lucko.luckperms.bukkit.listeners.BukkitConnectionListener.onPlayerLogin(BukkitConnectionListener.java:167) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        ... 13 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.bukkit.WGBukkit
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
        at me.lucko.extracontexts.calculators.WorldGuardCalculator.giveApplicableContext(WorldGuardCalculator.java:27) ~[?:?]
        at me.lucko.extracontexts.calculators.WorldGuardCalculator.giveApplicableContext(WorldGuardCalculator.java:16) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextManager.calculate(ContextManager.java:225) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextsCache.supply(ContextsCache.java:54) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextsCache.supply(ContextsCache.java:41) ~[?:?]
        at me.lucko.luckperms.common.buffers.ExpiringCache.get(ExpiringCache.java:65) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextsCache.getContexts(ContextsCache.java:59) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextManager.getApplicableContexts(ContextManager.java:115) ~[?:?]
        at me.lucko.luckperms.bukkit.LPBukkitPlugin.refreshAutoOp(LPBukkitPlugin.java:335) ~[?:?]
        at me.lucko.luckperms.bukkit.listeners.BukkitConnectionListener.onPlayerLogin(BukkitConnectionListener.java:167) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        ... 13 more
[18:03:57] [Server thread/ERROR]: Could not pass event PlayerLoginEvent to VoidGenerator v1.3.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.PlayerList.attemptLogin(PlayerList.java:531) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.LoginListener.b(LoginListener.java:130) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.LoginListener.Y_(LoginListener.java:54) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.NetworkManager.a(NetworkManager.java:231) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.ServerConnection.c(ServerConnection.java:120) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:984) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/WGBukkit
        at me.lucko.extracontexts.calculators.WorldGuardCalculator.giveApplicableContext(WorldGuardCalculator.java:27) ~[?:?]
        at me.lucko.extracontexts.calculators.WorldGuardCalculator.giveApplicableContext(WorldGuardCalculator.java:16) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextManager.calculate(ContextManager.java:225) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextsCache.supply(ContextsCache.java:54) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextsCache.supply(ContextsCache.java:41) ~[?:?]
        at me.lucko.luckperms.common.buffers.ExpiringCache.get(ExpiringCache.java:65) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextsCache.getContexts(ContextsCache.java:59) ~[?:?]
        at me.lucko.luckperms.bukkit.model.permissible.LPPermissible.hasPermission(LPPermissible.java:168) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R1.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:113) ~[spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at me.hx64.voidgenerator.b.b.a(PlayerLoginListener.java:33) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        ... 13 more
[18:03:57] [Server thread/ERROR]: Could not pass event PlayerLoginEvent to GriefPrevention v16.9.alpha
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.PlayerList.attemptLogin(PlayerList.java:531) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.LoginListener.b(LoginListener.java:130) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.LoginListener.Y_(LoginListener.java:54) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.NetworkManager.a(NetworkManager.java:231) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.ServerConnection.c(ServerConnection.java:120) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:984) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/WGBukkit
        at me.lucko.extracontexts.calculators.WorldGuardCalculator.giveApplicableContext(WorldGuardCalculator.java:27) ~[?:?]
        at me.lucko.extracontexts.calculators.WorldGuardCalculator.giveApplicableContext(WorldGuardCalculator.java:16) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextManager.calculate(ContextManager.java:225) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextsCache.supply(ContextsCache.java:54) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextsCache.supply(ContextsCache.java:41) ~[?:?]
        at me.lucko.luckperms.common.buffers.ExpiringCache.get(ExpiringCache.java:65) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextsCache.getContexts(ContextsCache.java:59) ~[?:?]
        at me.lucko.luckperms.bukkit.model.permissible.LPPermissible.hasPermission(LPPermissible.java:168) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R1.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:113) ~[spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerLogin(PlayerEventHandler.java:606) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        ... 13 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.bukkit.WGBukkit
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
        at me.lucko.extracontexts.calculators.WorldGuardCalculator.giveApplicableContext(WorldGuardCalculator.java:27) ~[?:?]
        at me.lucko.extracontexts.calculators.WorldGuardCalculator.giveApplicableContext(WorldGuardCalculator.java:16) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextManager.calculate(ContextManager.java:225) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextsCache.supply(ContextsCache.java:54) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextsCache.supply(ContextsCache.java:41) ~[?:?]
        at me.lucko.luckperms.common.buffers.ExpiringCache.get(ExpiringCache.java:65) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextsCache.getContexts(ContextsCache.java:59) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextManager.getApplicableContexts(ContextManager.java:115) ~[?:?]
        at me.lucko.luckperms.bukkit.LPBukkitPlugin.refreshAutoOp(LPBukkitPlugin.java:335) ~[?:?]
        at me.lucko.luckperms.bukkit.listeners.BukkitConnectionListener.onPlayerLogin(BukkitConnectionListener.java:167) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        ... 13 more
[18:03:57] [Server thread/ERROR]: Could not pass event PlayerLoginEvent to VoidGenerator v1.3.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.PlayerList.attemptLogin(PlayerList.java:531) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.LoginListener.b(LoginListener.java:130) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.LoginListener.Y_(LoginListener.java:54) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.NetworkManager.a(NetworkManager.java:231) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.ServerConnection.c(ServerConnection.java:120) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:984) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/WGBukkit
        at me.lucko.extracontexts.calculators.WorldGuardCalculator.giveApplicableContext(WorldGuardCalculator.java:27) ~[?:?]
        at me.lucko.extracontexts.calculators.WorldGuardCalculator.giveApplicableContext(WorldGuardCalculator.java:16) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextManager.calculate(ContextManager.java:225) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextsCache.supply(ContextsCache.java:54) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextsCache.supply(ContextsCache.java:41) ~[?:?]
        at me.lucko.luckperms.common.buffers.ExpiringCache.get(ExpiringCache.java:65) ~[?:?]
        at me.lucko.luckperms.common.contexts.ContextsCache.getContexts(ContextsCache.java:59) ~[?:?]
        at me.lucko.luckperms.bukkit.model.permissible.LPPermissible.hasPermission(LPPermissible.java:168) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R1.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:113) ~[spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at me.hx64.voidgenerator.b.b.a(PlayerLoginListener.java:33) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        ... 13 more
```
etc.

**Comment by lucko** [comment]
Please report on the ExtraContexts repo. 

Looks like it needs updating for 1.13 :)
