### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by InfamousYT** [lucko/LuckPerms#120]
Hi there,

I'm currently running the latest version of BungeeCord with LuckPerms, when I attempt to launch the server I get the following error:

16:34:48 [WARNING] Error enabling plugin LuckPerms
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:34)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:304)
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:263)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more

Thank you in advanced,

InfamousYT

**Comment by lucko** [comment]
Download from here: https://ci.lucko.me/job/LuckPerms/
