### ISSUE TITLE
BC Console Spam

### ISSUE THREAD

**Issue by ItzSheldor** [lucko/LuckPerms#1204]
```
07.09 20:25:13 [Server] INFORMATION __    
07.09 20:25:13 [Server] INFORMATION |    |__)   LuckPerms v4.2.89
07.09 20:25:13 [Server] INFORMATION |___ |      Running on Bungee - BungeeCord
07.09 20:25:13 [Server] INFORMATION [LuckPerms] Loading configuration...
07.09 20:25:13 [Server] INFORMATION [LuckPerms] Found lang.yml - loading messages...
07.09 20:25:13 [Server] SCHWERWIEGEND org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
07.09 20:25:13 [Server] SCHWERWIEGEND at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:218)
07.09 20:25:13 [Server] SCHWERWIEGEND at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176)
07.09 20:25:13 [Server] SCHWERWIEGEND at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171)
07.09 20:25:13 [Server] SCHWERWIEGEND at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126)
07.09 20:25:13 [Server] SCHWERWIEGEND at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1177)
07.09 20:25:13 [Server] SCHWERWIEGEND at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:287)
07.09 20:25:13 [Server] SCHWERWIEGEND at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)
07.09 20:25:13 [Server] SCHWERWIEGEND at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:195)
07.09 20:25:13 [Server] SCHWERWIEGEND at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
07.09 20:25:13 [Server] SCHWERWIEGEND at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
07.09 20:25:13 [Server] SCHWERWIEGEND at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:107)
07.09 20:25:13 [Server] SCHWERWIEGEND at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139)
07.09 20:25:13 [Server] SCHWERWIEGEND at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
07.09 20:25:13 [Server] SCHWERWIEGEND at org.yaml.snakeyaml.Yaml.load(Yaml.java:467)
07.09 20:25:13 [Server] SCHWERWIEGEND at me.lucko.luckperms.common.locale.LocaleManager.loadFromFile(LocaleManager.java:78)
07.09 20:25:13 [Server] SCHWERWIEGEND at me.lucko.luckperms.common.locale.LocaleManager.tryLoad(LocaleManager.java:59)
07.09 20:25:13 [Server] SCHWERWIEGEND at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:111)
07.09 20:25:13 [Server] SCHWERWIEGEND at me.lucko.luckperms.bungee.LPBungeeBootstrap.onEnable(LPBungeeBootstrap.java:124)
07.09 20:25:13 [Server] SCHWERWIEGEND at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
07.09 20:25:13 [Server] SCHWERWIEGEND at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
07.09 20:25:13 [Server] SCHWERWIEGEND at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
07.09 20:25:13 [Server] SCHWERWIEGEND at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
07.09 20:25:13 [Server] SCHWERWIEGEND Caused by: java.nio.charset.MalformedInputException: Input length = 1
07.09 20:25:13 [Server] SCHWERWIEGEND at java.nio.charset.CoderResult.throwException(Unknown Source)
07.09 20:25:13 [Server] SCHWERWIEGEND at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
07.09 20:25:13 [Server] SCHWERWIEGEND at sun.nio.cs.StreamDecoder.read(Unknown Source)
07.09 20:25:13 [Server] SCHWERWIEGEND at java.io.InputStreamReader.read(Unknown Source)
07.09 20:25:13 [Server] SCHWERWIEGEND at java.io.BufferedReader.fill(Unknown Source)
07.09 20:25:13 [Server] SCHWERWIEGEND at java.io.BufferedReader.read1(Unknown Source)
07.09 20:25:13 [Server] SCHWERWIEGEND at java.io.BufferedReader.read(Unknown Source)
07.09 20:25:13 [Server] SCHWERWIEGEND at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:183)
07.09 20:25:13 [Server] SCHWERWIEGEND ... 21 more
07.09 20:25:13 [Server] INFORMATION [LuckPerms] Loading storage provider... [MYSQL]
07.09 20:25:13 [Server] SCHWERWIEGEND SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
07.09 20:25:13 [Server] SCHWERWIEGEND SLF4J: Defaulting to no-operation (NOP) logger implementation
07.09 20:25:13 [Server] SCHWERWIEGEND SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
07.09 20:25:13 [Server] INFORMATION [LuckPerms] Loading messaging service... [BUNGEE]
07.09 20:25:13 [Server] INFORMATION [LuckPerms] Loading internal permission managers...
07.09 20:25:13 [Server] INFORMATION [LuckPerms] Performing initial data load...
07.09 20:25:14 [Server] INFORMATION [LuckPerms] Successfully enabled. (took 910ms)
```

**Comment by lucko** [comment]
Your locale file has invalid formatting.

Run it through a YAML parser. (https://yaml-online-parser.appspot.com/)
