### ISSUE TITLE
bungeecord no load

### ISSUE THREAD

**Issue by MrSuricate2** [lucko/LuckPerms#1217]
`03:34:30 [WARNING] Error enabling plugin LuckPerms
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:34)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:304)
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:267)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more`

i'm this log in log.yml  on bungeecord

**Comment by codingJWilliams** [comment]
What version of Luckperms are you using? I remember this being a problem with 4.2.85

**Comment by RJHaytree** [comment]
You're using the bukkit version of Luckperms on bungee. Please use the bungeecord version found here: https://luckperms.github.io/

**Comment by MrSuricate2** [comment]
Thank you but this is not explain on the site spigot or on the wiki

**Comment by BrainStone** [comment]
It says `Bukkit` (or `Bungee` for the Bungee version) in the file name. That is a dead giveaway to at least check for different versions.

But the central download page really needs to be linked on the Spigot and Ore pages @lucko

**Comment by lucko** [comment]
Added a more prominent link to the Spigot page.
