### ISSUE TITLE
How can i setup mysql using xampp?(It just throws exceptions)

### ISSUE THREAD

**Issue by EOT3000** [lucko/LuckPerms#1259]
*** WARNING: This is a development build. It is not meant for production server usage! Please keep backups and update frequently.
Loading libraries, please wait...
Loaded 0 recipes
[13:35:33 INFO]: Loaded 0 recipes
[13:35:33 INFO]: Starting minecraft server version 1.13.1
[13:35:33 INFO]: Loading properties
[13:35:33 INFO]: Default game type: SURVIVAL
[13:35:33 INFO]: This server is running CraftBukkit version git-Spigot-f6a273b-8ab46ff (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
[13:35:33 INFO]: Debug logging is disabled
[13:35:33 INFO]: Using 4 threads for Netty based IO
[13:35:33 INFO]: Server Ping Player Sample Count: 12
[13:35:33 INFO]: Generating keypair
[13:35:33 INFO]: Starting Minecraft server on 127.0.0.1:25565
[13:35:33 INFO]: Using default channel type
[13:35:37 INFO]: Set PluginClassLoader as parallel capable
>hWARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader (file:/C:/Users//Desktop/server/Lobby/plugins/LuckPerms-Bukkit-4.3.2.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[13:35:37 INFO]: [LuckPerms] Loading LuckPerms v4.3.2
[13:35:37 INFO]: [Essentials] Loading Essentials v2.15.0.45
[13:35:37 INFO]: [LuckPerms] Enabling LuckPerms v4.3.2
[13:35:37 INFO]:         __
[13:35:37 INFO]:   |    |__)   LuckPerms v4.3.2
[13:35:37 INFO]:   |___ |      Running on Bukkit - CraftBukkit
[13:35:37 INFO]:
[13:35:37 INFO]: [LuckPerms] Loading configuration...
[13:35:37 INFO]: [LuckPerms] Loading storage provider... [MYSQL]
[13:35:37 WARN]: [Server thread] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Starting...
[13:35:37 WARN]: [Server thread] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Start completed.
[13:35:42 ERROR]: [LuckPerms] Failed to init storage dao
[13:35:42 WARN]: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5001ms.
[13:35:42 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[13:35:42 WARN]:        at me.lucko.luckperms.common.storage.dao.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:128)
[13:35:42 WARN]:        at me.lucko.luckperms.common.storage.dao.sql.SqlDao.tableExists(SqlDao.java:145)
[13:35:42 WARN]:        at me.lucko.luckperms.common.storage.dao.sql.SqlDao.init(SqlDao.java:162)
[13:35:42 WARN]:        at me.lucko.luckperms.common.storage.AbstractStorage.init(AbstractStorage.java:122)
[13:35:42 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:35:42 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:35:42 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:35:42 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[13:35:42 WARN]:        at me.lucko.luckperms.common.storage.wrappings.PhasedStorage.lambda$wrap$0(PhasedStorage.java:64)
[13:35:42 WARN]:        at com.sun.proxy.$Proxy26.init(Unknown Source)
[13:35:42 WARN]:        at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:117)
[13:35:42 WARN]:        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:130)
[13:35:42 WARN]:        at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:153)
[13:35:42 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:35:42 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[13:35:42 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[13:35:42 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431)
[13:35:42 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345)
[13:35:42 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:214)
[13:35:42 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702)
[13:35:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:844)
[13:35:42 WARN]: Caused by: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'minecraft'
[13:35:42 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:35:42 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[13:35:42 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[13:35:42 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.Util.getInstance(Util.java:408)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2230)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2025)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[13:35:42 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:35:42 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[13:35:42 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[13:35:42 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706)
[13:35:42 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692)
[13:35:42 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[13:35:42 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
[13:35:42 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[13:35:42 WARN]:        ... 1 more
[13:35:42 INFO]: [LuckPerms] Loading messaging service... [SQL]
[13:35:47 WARN]: java.lang.RuntimeException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5002ms.
[13:35:47 WARN]:        at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:56)
[13:35:47 WARN]:        at me.lucko.luckperms.common.messaging.MessagingFactory$SqlMessengerProvider.obtain(MessagingFactory.java:132)
[13:35:47 WARN]:        at me.lucko.luckperms.common.messaging.LuckPermsMessagingService.<init>(LuckPermsMessagingService.java:75)
[13:35:47 WARN]:        at me.lucko.luckperms.common.messaging.MessagingFactory.getServiceFor(MessagingFactory.java:95)
[13:35:47 WARN]:        at me.lucko.luckperms.bukkit.messaging.BukkitMessagingFactory.getServiceFor(BukkitMessagingFactory.java:63)
[13:35:47 WARN]:        at me.lucko.luckperms.common.messaging.MessagingFactory.getInstance(MessagingFactory.java:73)
[13:35:47 WARN]:        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:131)
[13:35:47 WARN]:        at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:153)
[13:35:47 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:35:47 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[13:35:47 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[13:35:47 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431)
[13:35:47 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345)
[13:35:47 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:214)
[13:35:47 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702)
[13:35:47 WARN]:        at java.base/java.lang.Thread.run(Thread.java:844)
[13:35:47 WARN]: Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5002ms.
[13:35:47 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[13:35:47 WARN]:        at me.lucko.luckperms.common.storage.dao.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:128)
[13:35:47 WARN]:        at me.lucko.luckperms.common.messaging.sql.SqlMessenger.getConnection(SqlMessenger.java:84)
[13:35:47 WARN]:        at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.init(AbstractSqlMessenger.java:55)
[13:35:47 WARN]:        at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:54)
[13:35:47 WARN]:        ... 15 more
[13:35:47 WARN]: Caused by: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'minecraft'
[13:35:47 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:35:47 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[13:35:47 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[13:35:47 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.Util.getInstance(Util.java:408)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2230)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2025)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[13:35:47 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:35:47 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[13:35:47 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[13:35:47 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706)
[13:35:47 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692)
[13:35:47 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[13:35:47 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
[13:35:47 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[13:35:47 WARN]:        ... 1 more
[13:35:47 WARN]: [LuckPerms] Messaging service 'sql' not recognised.
[13:35:48 INFO]: [LuckPerms] Loading internal permission managers...
[13:35:48 INFO]: [LuckPerms] Performing initial data load...
[13:35:53 WARN]: java.util.concurrent.CompletionException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
[13:35:53 WARN]:        at me.lucko.luckperms.common.storage.AbstractStorage.lambda$makeFuture$1(AbstractStorage.java:105)
[13:35:53 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
[13:35:53 WARN]:        at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$WrappedRunnable.run(AbstractJavaScheduler.java:79)
[13:35:53 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
[13:35:53 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[13:35:53 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[13:35:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
[13:35:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[13:35:53 WARN]:        at java.base/java.lang.Thread.run(Thread.java:844)
[13:35:53 WARN]: Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
[13:35:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[13:35:53 WARN]:        at me.lucko.luckperms.common.storage.dao.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:128)
[13:35:53 WARN]:        at me.lucko.luckperms.common.storage.dao.sql.SqlDao.loadAllGroups(SqlDao.java:609)
[13:35:53 WARN]:        at me.lucko.luckperms.common.storage.AbstractStorage.lambda$loadAllGroups$10(AbstractStorage.java:214)
[13:35:53 WARN]:        at me.lucko.luckperms.common.storage.AbstractStorage.lambda$makeFuture$1(AbstractStorage.java:102)
[13:35:53 WARN]:        ... 8 more
[13:35:53 WARN]: Caused by: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'minecraft'
[13:35:53 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:35:53 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[13:35:53 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[13:35:53 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.Util.getInstance(Util.java:408)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2230)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2025)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[13:35:53 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:35:53 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[13:35:53 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[13:35:53 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706)
[13:35:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692)
[13:35:53 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[13:35:53 WARN]:        ... 3 more

JUST A BUNCH OF EXCEPTIONS!!!!!

**Comment by BrainStone** [comment]
You need to create a database and a user first.  
My earlier comment about being done was, that MySQL was installed entirely automatically with XAMPP.

Anyways, start the XAMPP Control Panel and start Apache and MySQL.  
And when you open http://localhost/phpmyadmin (The link will only work on your computer), then you can manage the database.

**Comment by EOT3000** [comment]
How do you make a user and database in http://localhost/phpmyadmin?

**Comment by BrainStone** [comment]
Google. There’s a billion tutorials out there.

**Comment by EOT3000** [comment]
ok

**Comment by EOT3000** [comment]
Yay, it worked!
