### ISSUE TITLE
ClassCastException, me.lucko.luckperms.sponge.model.SpongeGroup$GroupSubject to me.lucko.luckperms.sponge.model.SpongeGroup

### ISSUE THREAD

**Issue by dualspiral** [lucko/LuckPerms#126]
When I use the permission service to get a `GroupSubject` out by name using the standard Sponge methods, then set it to a player like so:

```java
player.getSubjectData().addParent(SubjectData.GLOBAL_CONTEXT, permissionService.getGroupSubjects().get("groupname"));
```

I get the following:

```
java.lang.ClassCastException: me.lucko.luckperms.sponge.model.SpongeGroup$GroupSubject cannot be cast to me.lucko.luckperms.sponge.model.SpongeGroup
        at me.lucko.luckperms.sponge.service.LuckPermsSubjectData.addParent(LuckPermsSubjectData.java:255) ~[LuckPermsSubjectData.class:?]
        at me.lucko.luckperms.sponge.service.base.LPSubjectData.addParent(LPSubjectData.java:148) ~[LPSubjectData.class:?]
```

Tested using v2.16.90

**Comment by lucko** [comment]
Thanks :)
