### ISSUE TITLE
Error by creating a new editor session

### ISSUE THREAD

**Issue by MoondostriaDE** [lucko/LuckPerms#1269]
Heyho, have get two errors by type in "/lp editor" or "/lp user X editor"

```
[15:50:25 WARN]: java.lang.ExceptionInInitializerError
[15:50:25 WARN]:        at me.lucko.luckperms.lib.okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:282)
[15:50:25 WARN]:        at me.lucko.luckperms.lib.okhttp3.OkHttpClient.<init>(OkHttpClient.java:249)
[15:50:25 WARN]:        at me.lucko.luckperms.lib.okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:927)
[15:50:25 WARN]:        at me.lucko.luckperms.common.web.HttpClient.getClient(HttpClient.java:54)
[15:50:25 WARN]:        at me.lucko.luckperms.common.web.HttpClient.makeCall(HttpClient.java:60)
[15:50:25 WARN]:        at me.lucko.luckperms.common.web.StandardPastebin.post(StandardPastebin.java:141)
[15:50:25 WARN]:        at me.lucko.luckperms.common.web.StandardPastebin.postJson(StandardPastebin.java:123)
[15:50:25 WARN]:        at me.lucko.luckperms.common.commands.generic.other.HolderEditor.execute(HolderEditor.java:73)
[15:50:25 WARN]:        at me.lucko.luckperms.common.commands.generic.other.HolderEditor.execute(HolderEditor.java:55)
[15:50:25 WARN]:        at me.lucko.luckperms.common.command.abstraction.MainCommand.execute(MainCommand.java:102)
[15:50:25 WARN]:        at me.lucko.luckperms.common.command.abstraction.MainCommand.execute(MainCommand.java:45)
[15:50:25 WARN]:        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:217)
[15:50:25 WARN]:        at me.lucko.luckperms.common.command.CommandManager.lambda$onCommand$0(CommandManager.java:157)
[15:50:25 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
[15:50:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[15:50:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[15:50:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:844)
[15:50:25 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[15:50:25 WARN]:        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:664)
[15:50:25 WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:301)
[15:50:25 WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:485)
[15:50:25 WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:447)
[15:50:25 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:120)
[15:50:25 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:191)
[15:50:25 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:115)
[15:50:25 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
[15:50:25 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
[15:50:25 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
[15:50:25 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[15:50:25 WARN]:        at java.base/java.lang.Class.forName(Class.java:292)
[15:50:25 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:239)
[15:50:25 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.platform.Platform.findPlatform(Platform.java:201)
[15:50:25 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.platform.Platform.<clinit>(Platform.java:78)
[15:50:25 WARN]:        ... 17 more
```

```
[15:50:48 WARN]: java.lang.NoClassDefFoundError: Could not initialize class me.lucko.luckperms.lib.okhttp3.internal.platform.Platform
[15:50:48 WARN]:        at me.lucko.luckperms.lib.okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:282)
[15:50:48 WARN]:        at me.lucko.luckperms.lib.okhttp3.OkHttpClient.<init>(OkHttpClient.java:249)
[15:50:48 WARN]:        at me.lucko.luckperms.lib.okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:927)
[15:50:48 WARN]:        at me.lucko.luckperms.common.web.HttpClient.getClient(HttpClient.java:54)
[15:50:48 WARN]:        at me.lucko.luckperms.common.web.HttpClient.makeCall(HttpClient.java:60)
[15:50:48 WARN]:        at me.lucko.luckperms.common.web.StandardPastebin.post(StandardPastebin.java:141)
[15:50:48 WARN]:        at me.lucko.luckperms.common.web.StandardPastebin.postJson(StandardPastebin.java:123)
[15:50:48 WARN]:        at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
[15:50:48 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:50)
[15:50:48 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:42)
[15:50:48 WARN]:        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:217)
[15:50:48 WARN]:        at me.lucko.luckperms.common.command.CommandManager.lambda$onCommand$0(CommandManager.java:157)
[15:50:48 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
[15:50:48 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[15:50:48 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[15:50:48 WARN]:        at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by MoondostriaDE** [comment]
After a fully network restart it is working, but I don't know, why I have get this warnings.

**Comment by MoondostriaDE** [comment]
I don't use reloads when on server x luckperms is running. I have specially for such things a test server, on which no luckperms runs.
