### ISSUE TITLE
LuckPerms doesn't play well with ExtraContexts and WG 7

### ISSUE THREAD

**Issue by SlimeDog** [lucko/LuckPerms#1289]
Spigot 1.13.2 latest
WG 7.0.0-b1754
ExtraContexts 1.0-b8
LuckPerms 4.3.25

ExtraContexts/config.yml sans comments
```
worldguard: true
gamemode: true
dimension: true
placeholderapi: false
placeholderapi-placeholders:
  allowflight: "%player_allow_flight%"
```
still blows up
```
[07:05:37] [Server thread/WARN]: [LuckPerms] An exception was thrown by me.lucko.extracontexts.calculators.WorldGuardCalculator whilst calculating the context of subject CraftPlayer{name=rambeau}
[07:05:37] [Server thread/WARN]: java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(Lorg/bukkit/World;)Lcom/sk89q/worldguard/protection/managers/RegionManager;
[07:05:37] [Server thread/WARN]: 	at me.lucko.extracontexts.calculators.WorldGuardCalculator.giveApplicableContext(WorldGuardCalculator.java:27)
[07:05:37] [Server thread/WARN]: 	at me.lucko.extracontexts.calculators.WorldGuardCalculator.giveApplicableContext(WorldGuardCalculator.java:16)
[07:05:37] [Server thread/WARN]: 	at me.lucko.luckperms.common.contexts.ContextManager.calculate(ContextManager.java:225)
[07:05:37] [Server thread/WARN]: 	at me.lucko.luckperms.common.contexts.ContextsCache.supply(ContextsCache.java:53)
[07:05:37] [Server thread/WARN]: 	at me.lucko.luckperms.common.contexts.ContextsCache.supply(ContextsCache.java:41)
[07:05:37] [Server thread/WARN]: 	at me.lucko.luckperms.common.buffers.ExpiringCache.get(ExpiringCache.java:64)
[07:05:37] [Server thread/WARN]: 	at me.lucko.luckperms.common.contexts.ContextsCache.getContexts(ContextsCache.java:58)
[07:05:37] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.model.permissible.LPPermissible.hasPermission(LPPermissible.java:167)
[07:05:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:118)
[07:05:37] [Server thread/WARN]: 	at com.endercrest.voidspawn.VoidListener.onMoveEvent(VoidListener.java:27)
[07:05:37] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07:05:37] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[07:05:37] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:05:37] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[07:05:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[07:05:37] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[07:05:37] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[07:05:37] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[07:05:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:948)
[07:05:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126)
[07:05:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInLook.a(SourceFile:88)
[07:05:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[07:05:37] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[07:05:37] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[07:05:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[07:05:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
[07:05:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[07:05:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[07:05:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[07:05:37] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[07:05:38] [luckperms-0/WARN]: [LuckPerms] An exception was thrown by me.lucko.extracontexts.calculators.WorldGuardCalculator whilst calculating the context of subject CraftPlayer{name=rambeau}
[07:05:38] [luckperms-0/WARN]: java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(Lorg/bukkit/World;)Lcom/sk89q/worldguard/protection/managers/RegionManager;
[07:05:38] [luckperms-0/WARN]: 	at me.lucko.extracontexts.calculators.WorldGuardCalculator.giveApplicableContext(WorldGuardCalculator.java:27)
[07:05:38] [luckperms-0/WARN]: 	at me.lucko.extracontexts.calculators.WorldGuardCalculator.giveApplicableContext(WorldGuardCalculator.java:16)
[07:05:38] [luckperms-0/WARN]: 	at me.lucko.luckperms.common.contexts.ContextManager.calculate(ContextManager.java:225)
[07:05:38] [luckperms-0/WARN]: 	at me.lucko.luckperms.common.contexts.ContextsCache.supply(ContextsCache.java:53)
[07:05:38] [luckperms-0/WARN]: 	at me.lucko.luckperms.common.contexts.ContextsCache.supply(ContextsCache.java:41)
[07:05:38] [luckperms-0/WARN]: 	at me.lucko.luckperms.common.buffers.ExpiringCache.get(ExpiringCache.java:64)
[07:05:38] [luckperms-0/WARN]: 	at me.lucko.luckperms.common.contexts.ContextsCache.getContexts(ContextsCache.java:58)
[07:05:38] [luckperms-0/WARN]: 	at me.lucko.luckperms.common.contexts.ContextManager.getApplicableContexts(ContextManager.java:115)
[07:05:38] [luckperms-0/WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitPlugin.refreshAutoOp(LPBukkitPlugin.java:335)
[07:05:38] [luckperms-0/WARN]: 	at java.util.Optional.ifPresent(Optional.java:159)
[07:05:38] [luckperms-0/WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitPlugin.lambda$performFinalSetup$1(LPBukkitPlugin.java:269)
[07:05:38] [luckperms-0/WARN]: 	at me.lucko.luckperms.common.event.LuckPermsEventHandler.invoke(LuckPermsEventHandler.java:108)
[07:05:38] [luckperms-0/WARN]: 	at me.lucko.luckperms.common.event.LuckPermsEventHandler.invoke(LuckPermsEventHandler.java:45)
[07:05:38] [luckperms-0/WARN]: 	at me.lucko.luckperms.lib.eventbus.SimpleEventBus.post(SimpleEventBus.java:107)
[07:05:38] [luckperms-0/WARN]: 	at me.lucko.luckperms.common.event.AbstractEventBus.post(AbstractEventBus.java:84)
[07:05:38] [luckperms-0/WARN]: 	at me.lucko.luckperms.common.event.EventFactory.lambda$post$0(EventFactory.java:124)
[07:05:38] [luckperms-0/WARN]: 	at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$WrappedRunnable.run(AbstractJavaScheduler.java:79)
[07:05:38] [luckperms-0/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[07:05:38] [luckperms-0/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[07:05:38] [luckperms-0/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[07:05:38] [luckperms-0/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[07:05:38] [luckperms-0/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[07:05:38] [luckperms-0/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[07:05:38] [luckperms-0/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by SlimeDog** [comment]
Related to 
[https://github.com/lucko/ExtraContexts/issues/4](https://github.com/lucko/ExtraContexts/issues/4)
but it's a LuckPerms issue.

**Comment by lucko** [comment]
It's not a LuckPerms issue.

**Comment by lucko** [comment]
I'll hopefully have time to look into updating ExtraContexts soon.
