### ISSUE TITLE
[mariadb] Failed to init storage dao error with paperspigot 1.13.2

### ISSUE THREAD

**Issue by tianji1993** [lucko/LuckPerms#1295]
PaperSpigot build #442 , luckperms 4.3.29
LP can load from db smoothly under Spigot, but when I switch to PaperSpigot, it starts to report an error.
### error message under paperspigot:
[03:07:27] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v4.3.2*
[03:07:27] [Server thread/INFO]:         __    
[03:07:27] [Server thread/INFO]:   |    |__)   LuckPerms v4.3.2
[03:07:27] [Server thread/INFO]:   |___ |      Running on Bukkit - Paper
[03:07:27] [Server thread/INFO]: 
[03:07:27] [Server thread/INFO]: [LuckPerms] Loading configuration...
[03:07:27] [Server thread/INFO]: [LuckPerms] Loading storage provider... [MARIADB]
[03:07:27] [Server thread/INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Starting...
[03:07:27] [Server thread/INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Start completed.
[03:07:32] [Server thread/ERROR]: [LuckPerms] Failed to init storage dao
[03:07:32] [Server thread/WARN]: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.dao.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:128)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.dao.sql.SqlDao.tableExists(SqlDao.java:145)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.dao.sql.SqlDao.init(SqlDao.java:162)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.AbstractStorage.init(AbstractStorage.java:122)
[03:07:32] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03:07:32] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[03:07:32] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03:07:32] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.wrappings.PhasedStorage.lambda$wrap$0(PhasedStorage.java:64)
[03:07:32] [Server thread/WARN]: 	at com.sun.proxy.$Proxy59.init(Unknown Source)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:117)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:130)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:153)
[03:07:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[03:07:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
[03:07:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[03:07:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[03:07:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[03:07:32] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:236)
[03:07:32] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791)
[03:07:32] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
### under Spigot:
[03:11:10] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v4.3.2
[03:11:10] [Server thread/INFO]: [0;36;1m       [0;36;22m __    [m
[03:11:10] [Server thread/INFO]: [0;36;1m  |    [0;36;22m|__)   [0;32;22mLuckPerms [0;36;1mv4.3.2[m
[03:11:10] [Server thread/INFO]: [0;36;1m  |___ [0;36;22m|      [0;30;1mRunning on Bukkit - CraftBukkit[m
[03:11:10] [Server thread/INFO]: [m
[03:11:10] [Server thread/INFO]: [LuckPerms] Loading configuration...
[03:11:10] [Server thread/INFO]: [LuckPerms] Loading storage provider... [MARIADB]
[03:11:10] [Server thread/INFO]: luckperms-hikari - Starting...
[03:11:10] [Server thread/INFO]: luckperms-hikari - Start completed.
[03:11:10] [Server thread/INFO]: [LuckPerms] Loading messaging service... [SQL]
[03:11:11] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[03:11:11] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[03:11:11] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 728ms)

**Comment by tianji1993** [comment]
@BrainStone thanks for your help,  it's ok in spigot but not work in paperspigot.

**Comment by BrainStone** [comment]
The error is happening outside LPs control. Your database settings are wrong. One way or another.

**Comment by tianji1993** [comment]
OK, maybe I need to seek paperspigot help, many thanks!

**Comment by Andre601** [comment]
This has nothing to do with Spigot or PaperSpigot.
As @BrainStone mentioned: (I highlighted the important part)
> The error is happening outside LPs control. **Your database settings are wrong**. One way or another.

Your login credentials are wrong.
You have to double-check if they are correct or not. Don't waste the time of the people from PaperSpigot by reporting an error, that is completely unrelated to PaperSpigot itself.

**Comment by tianji1993** [comment]
well actually the database settings are correct, same sql settings information works in spigot but cannot work in paperspigot, I wonder there have some performance tweaks that paperspigot does prevent the dao of luckperms to connect the mysql in the main thread. maybe there have some settings option waiting to discover. anyway, thanks for your kind help!

**Comment by tianji1993** [comment]
I double checked the db settings in the config and I can make sure those details are correct. LP can load from db smoothly under Spigot, but when I switch to PaperSpigot, it starts to report an error.
### error message under paperspigot:
[03:07:27] [Server thread/INFO]: [ViaBackwards] Enabling ViaBackwards v2.3.1*
[03:07:27] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v4.3.2*
[03:07:27] [Server thread/INFO]:         __    
[03:07:27] [Server thread/INFO]:   |    |__)   LuckPerms v4.3.2
[03:07:27] [Server thread/INFO]:   |___ |      Running on Bukkit - Paper
[03:07:27] [Server thread/INFO]: 
[03:07:27] [Server thread/INFO]: [LuckPerms] Loading configuration...
[03:07:27] [Server thread/INFO]: [LuckPerms] Loading storage provider... [MARIADB]
[03:07:27] [Server thread/INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Starting...
[03:07:27] [Server thread/INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Start completed.
[03:07:32] [Server thread/ERROR]: [LuckPerms] Failed to init storage dao
[03:07:32] [Server thread/WARN]: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.dao.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:128)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.dao.sql.SqlDao.tableExists(SqlDao.java:145)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.dao.sql.SqlDao.init(SqlDao.java:162)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.AbstractStorage.init(AbstractStorage.java:122)
[03:07:32] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03:07:32] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[03:07:32] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03:07:32] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.wrappings.PhasedStorage.lambda$wrap$0(PhasedStorage.java:64)
[03:07:32] [Server thread/WARN]: 	at com.sun.proxy.$Proxy59.init(Unknown Source)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:117)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:130)
[03:07:32] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:153)
[03:07:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[03:07:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
[03:07:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[03:07:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[03:07:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[03:07:32] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:236)
[03:07:32] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791)
[03:07:32] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
### under Spigot:
[03:11:10] [Server thread/INFO]: [LuckPerms] Loading configuration...
[03:11:10] [Server thread/INFO]: [LuckPerms] Loading storage provider... [MARIADB]
[03:11:10] [Server thread/INFO]: luckperms-hikari - Starting...
[03:11:10] [Server thread/INFO]: luckperms-hikari - Start completed.
[03:11:10] [Server thread/INFO]: [LuckPerms] Loading messaging service... [SQL]
[03:11:11] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[03:11:11] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[03:11:11] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 728ms)

**Comment by BrainStone** [comment]
Using the MySQL root user will not work under certain circumstances. And it shouldn't be used for basic database access anyways.

**Comment by lucko** [comment]
I've replied already here:
https://www.spigotmc.org/threads/luckperms-an-advanced-permissions-plugin.174259/page-125#post-3236462


In future, please only open an issue / report bugs in one place (preferably here on GitHub)
