### ISSUE TITLE
Please help me with this error

### ISSUE THREAD

**Issue by JuanFerGamerYT** [lucko/LuckPerms#1301]
I have a error when my BungeeCord (With the name LoboCord) starts to load de LuckPerms configuration. I really need fix this.

> 19:28:50 [INFORMACIÓN]         __
19:28:50 [INFORMACIÓN]   |    |__)   LuckPerms v4.3.29
19:28:50 [INFORMACIÓN]   |___ |      Running on Bungee - LoboCord
19:28:50 [INFORMACIÓN]
19:28:50 [INFORMACIÓN] [LuckPerms] Loading configuration...
19:28:50 [INFORMACIÓN] [LuckPerms] Loading storage provider... [MYSQL]
19:28:50 [ADVERTENCIA] Exception encountered when loading plugin: LuckPerms
java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
    at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:418)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
    at me.lucko.luckperms.lib.hikari.HikariConfig.<clinit>(HikariConfig.java:51)
    at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:75)
    at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:165)
    at me.lucko.luckperms.common.storage.Storage.init(Storage.java:110)
    at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:119)
    at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:130)
    at me.lucko.luckperms.bungee.LPBungeeBootstrap.onEnable(LPBungeeBootstrap.java:124)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:112)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by BrainStone** [comment]
Update your bungee.

**Comment by JuanFerGamerYT** [comment]
> Update your bungee.

I have my bunge updated.

**Comment by electronicboy** [comment]
You have two plugins which are bundling in their own versions of slf4j and causing issues due to the two different versions of the class existing, I'd consider giving waterfall a look as we bundle slf4j in the proxy jar itself

**Comment by JuanFerGamerYT** [comment]
I delete one plugin and the error appears
