### ISSUE TITLE
Mysql lags server

### ISSUE THREAD

**Issue by Meldiron** [lucko/LuckPerms#1306]
Problem: Sometimes when I am on testing server, Luck Perms give this error. It also lags server for like 5 seconds which is pretty bad. I have Luck Perms connected to mysql, connection works but it sometimes does this weird error&lag.

Error:

```
[K[13:58:44 WARN]: [me.lucko.luckperms.lib.hikari.pool.PoolBase] luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection@1890a3ba (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.[39;0m

[K[13:58:44 WARN]: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5005ms.[39;0m

[K[13:58:44 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)[39;0m

[K[13:58:44 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:190)[39;0m

[K[13:58:44 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:155)[39;0m

[K[13:58:44 WARN]: at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)[39;0m

[K[13:58:44 WARN]: at me.lucko.luckperms.common.storage.dao.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:128)[39;0m

[K[13:58:44 WARN]: at me.lucko.luckperms.common.messaging.sql.SqlMessenger.getConnection(SqlMessenger.java:84)[39;0m

[K[13:58:44 WARN]: at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.pollMessages(AbstractSqlMessenger.java:84)[39;0m

[K[13:58:44 WARN]: at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$WrappedRunnable.run(AbstractJavaScheduler.java:79)[39;0m

[K[13:58:44 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[39;0m

[K[13:58:44 WARN]: at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)[39;0m

[K[13:58:44 WARN]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)[39;0m

[K[13:58:44 WARN]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)[39;0m

[K[13:58:44 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[39;0m

[K[13:58:44 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[39;0m

[K[13:58:44 WARN]: at java.lang.Thread.run(Thread.java:748)[39;0m

[K[13:58:44 WARN]: Caused by: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.[39;0m

[K[13:58:44 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)[39;0m

[K[13:58:44 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)[39;0m

[K[13:58:44 WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)[39;0m

[K[13:58:44 WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)[39;0m

[K[13:58:44 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)[39;0m

[K[13:58:44 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.Util.getInstance(Util.java:408)[39;0m

[K[13:58:44 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)[39;0m

[K[13:58:44 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)[39;0m

[K[13:58:44 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)[39;0m

[K[13:58:44 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)[39;0m

[K[13:58:44 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)[39;0m

[K[13:58:44 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)[39;0m

[K[13:58:44 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:5483)[39;0m

[K[13:58:44 WARN]: at me.lucko.luckperms.lib.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:550)[39;0m

[K[13:58:44 WARN]: at me.lucko.luckperms.lib.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:165)[39;0m

[K[13:58:44 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:179)[39;0m

[K[13:58:44 WARN]: ... 13 more[39;0m

[K[13:58:47 WARN]: Meldiron moved too quickly! 9.49212090903917,6.176759275064228,-6.497974452580792[39;0m
```

**Comment by BrainStone** [comment]
The wiki page “Storage System Errors” has the solution to that.

For the future please check the wiki first.

**Comment by lucko** [comment]
^ - You can find some advice on how to resolve on that page.

Also to note I think it's quite likely that your server lag issue is unrelated to this. Login processing happens asynchronously, and unless you have a machine with only one CPU thread, or overloaded CPU activity, it should have no effect on the MC server itself.
