### ISSUE TITLE
Error enabling luck perms on linux ubuntu server

### ISSUE THREAD

**Issue by PaXo0** [lucko/LuckPerms#1312]
Hello i get this error when starting luckperms onto my mysql database all of the information is correct and i get this error

`[24.11.2018 13:14:02] INFO: [Lobby-1] [13:13:59 ERROR]: Error occurred while enabling LuckPerms v4.3.17 (Is it up to date?)
[24.11.2018 13:14:02] INFO: [Lobby-1] java.lang.NoSuchMethodError: org.apache.logging.log4j.spi.LoggerContext.getLogger(Ljava/lang/String;)Lorg/apache/logging/log4j/spi/ExtendedLogger;
[24.11.2018 13:14:02] INFO: [Lobby-1]   at org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:37) ~[?:?]
[24.11.2018 13:14:02] INFO: [Lobby-1]   at org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:29) ~[?:?]
[24.11.2018 13:14:02] INFO: [Lobby-1]   at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47) ~[?:?]
[24.11.2018 13:14:02] INFO: [Lobby-1]   at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29) ~[?:?]
[24.11.2018 13:14:02] INFO: [Lobby-1]   at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:277) ~[?:?]
[24.11.2018 13:14:02] INFO: [Lobby-1]   at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:288) ~[?:?]
[24.11.2018 13:14:02] INFO: [Lobby-1]   at me.lucko.luckperms.lib.hikari.HikariConfig.<clinit>(HikariConfig.java:51) ~[?:?]
[24.11.2018 13:14:02] INFO: [Lobby-1]   at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:75) ~[?:?]
[24.11.2018 13:14:02] INFO: [Lobby-1]   at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:165) ~[?:?]
[24.11.2018 13:14:02] INFO: [Lobby-1]   at me.lucko.luckperms.common.storage.Storage.init(Storage.java:110) ~[?:?]
[24.11.2018 13:14:02] INFO: [Lobby-1]   at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:119) ~[?:?]
[24.11.2018 13:14:02] INFO: [Lobby-1]   at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:130) ~[?:?]
[24.11.2018 13:14:02] INFO: [Lobby-1]   at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:153) ~[?:?]
[24.11.2018 13:14:02] INFO: [Lobby-1]   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
[24.11.2018 13:14:02] INFO: [Lobby-1]   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
[24.11.2018 13:14:02] INFO: [Lobby-1]   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
[24.11.2018 13:14:02] INFO: [Lobby-1]   at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
[24.11.2018 13:14:02] INFO: [Lobby-1]   at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
[24.11.2018 13:14:02] INFO: [Lobby-1]   at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [spigot.jar:git-Spigot-db6de12-18fbb24]
[24.11.2018 13:14:02] INFO: [Lobby-1]   at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
[24.11.2018 13:14:02] INFO: [Lobby-1]   at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]`

**Comment by BrainStone** [comment]
Use at least Spigot 1.8.8. The older 1.8 versions all have severe security issues. LP refuses to start on them on purpose.

**Comment by lucko** [comment]
The error itself doesn't seem to be related to Spigot version - did updating fix it?

**Comment by BrainStone** [comment]
I’ve seen this error on older Spigot versions occasionally. Updating usually helps.

**Comment by PaXo0** [comment]
It was to do with the SSL on the mysql it has now been fixed thx for the help/suggestions
