### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NetyTV** [lucko/LuckPerms#1318]
Hello, today I installed LuckPerms and migrated PEX to it. I am getting this error in console:

[PixelVip] Task #33237 for PixelVip v2.0.1 generated an exception
java.lang.RuntimeException: The operation to load user data for '2c38b7fc-82c9-3015-a5ac-1a53c7e78019' was cancelled by LuckPerms. This is NOT a bug.
The lookup request was made on the main server thread. It is not safe to execute a request to
load username data from the database in this context.
If you are a plugin author, please consider making your request asynchronously.
Alternatively, server admins can disable this catch by setting 'vault-unsafe-lookups' to true
in the LP config, but should consider the consequences (lag) before doing so.
at me.lucko.luckperms.bukkit.vault.VaultPermissionHook.lookupUser(VaultPermissionHook.java:136) ~[?:?]
at me.lucko.luckperms.bukkit.vault.VaultPermissionHook.userGetGroups(VaultPermissionHook.java:216) ~[?:?]
at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.getPlayerGroups(AbstractVaultPermission.java:360) ~[?:?]
at br.net.fabiozumbi12.PixelVip.PermsAPI.getGroups(PermsAPI.java:23) ~[?:?]
at br.net.fabiozumbi12.PixelVip.PixelVip$1.lambda$null$0(PixelVip.java:178) ~[?:?]
at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_74]
at br.net.fabiozumbi12.PixelVip.PixelVip$1.lambda$run$1(PixelVip.java:176) ~[?:?]
at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_74]
at br.net.fabiozumbi12.PixelVip.PixelVip$1.run(PixelVip.java:174) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]

**Comment by lucko** [comment]
Would help if you read the message :wink:

> java.lang.RuntimeException: The operation to load user data for '2c38b7fc-82c9-3015-a5ac-1a53c7e78019' was cancelled by LuckPerms. This is NOT a bug.
The lookup request was made on the main server thread. It is not safe to execute a request to
load username data from the database in this context.
If you are a plugin author, please consider making your request asynchronously.
Alternatively, server admins can disable this catch by setting 'vault-unsafe-lookups' to true
in the LP config, but should consider the consequences (lag) before doing so.

Importantly, the bit that says:

> This is NOT a bug

Soo, you have two options as explained in the error itself. Either enable unsafe Vault lookups in the LP config, or report the issue to the author of `br.net.fabiozumbi12.PixelVip` and wait for them to fix it. :)

**Comment by Andre601** [comment]
The error explains it.
PixelVip tries to load the data/permission through a synchronous action/through the main thread which should be avoided.
Let the author of the plugin know about that, so that he can change it.
For now can you change the mentioned setting in LPs config.
