### ISSUE TITLE
LuckPerms fails to start on Velocity

### ISSUE THREAD

**Issue by LXGaming** [lucko/LuckPerms#1319]
Environment:
 - LuckPerms v4.3.39
 - Velocity v394

```
[13:19:12 ERROR]: Some errors occurred whilst posting event ProxyInitializeEvent.
[13:19:12 ERROR]: #1:

java.lang.NoSuchMethodError: com.velocitypowered.api.proxy.ProxyServer.getConsoleCommandSource()Lcom/velocitypowered/api/command/CommandSource;
        at me.lucko.luckperms.velocity.LPVelocityPlugin.getConsoleSender(LPVelocityPlugin.java:199) ~[?:?]
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:96) ~[?:?]
        at me.lucko.luckperms.velocity.LPVelocityBootstrap.onEnable(LPVelocityBootstrap.java:140) ~[?:?]
        at net.kyori.event.asm.generated.88aa2440a9.LPVelocityBootstrap-onEnable-ProxyInitializeEvent-1.invoke(Unknown Source) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[velocity.jar:1.0-SNAPSHOT (git-5b9a8f16-b394)]
        at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[velocity.jar:1.0-SNAPSHOT (git-5b9a8f16-b394)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$0(VelocityEventManager.java:108) ~[velocity.jar:1.0-SNAPSHOT (git-5b9a8f16-b394)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$1(VelocityEventManager.java:120) ~[velocity.jar:1.0-SNAPSHOT (git-5b9a8f16-b394)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by lucko** [comment]
This is caused by Velocity API changes. I will update later, until then the easiest fix is to downgrade your Velocity version.
