### ISSUE TITLE
Unable to Connect to Editor Server

### ISSUE THREAD

**Issue by bartyrealms** [lucko/LuckPerms#1325]
When using /lp editor, it is unable to connect to the server.

[11:18:21] [pool-8-thread-1/WARN]: java.lang.RuntimeException: java.net.ConnectException: Failed to connect to bytebin.lucko.me/198.54.117.200:443
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.common.web.StandardPastebin.post(StandardPastebin.java:155)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.common.web.StandardPastebin.postJson(StandardPastebin.java:122)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:50)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:42)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:217)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.common.command.CommandManager.lambda$onCommand$0(CommandManager.java:157)
[11:18:21] [pool-8-thread-1/WARN]: 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[11:18:21] [pool-8-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[11:18:21] [pool-8-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[11:18:21] [pool-8-thread-1/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:18:21] [pool-8-thread-1/WARN]: Caused by: java.net.ConnectException: Failed to connect to bytebin.lucko.me/198.54.117.200:443
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.common.web.HttpClient$LuckPermsUserAgentInterceptor.intercept(HttpClient.java:87)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:77)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.common.web.HttpClient.makeCall(HttpClient.java:60)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.common.web.StandardPastebin.post(StandardPastebin.java:140)
[11:18:21] [pool-8-thread-1/WARN]: 	... 10 more
[11:18:21] [pool-8-thread-1/WARN]: Caused by: java.net.ConnectException: Connection refused (Connection refused)
[11:18:21] [pool-8-thread-1/WARN]: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[11:18:21] [pool-8-thread-1/WARN]: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[11:18:21] [pool-8-thread-1/WARN]: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[11:18:21] [pool-8-thread-1/WARN]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[11:18:21] [pool-8-thread-1/WARN]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[11:18:21] [pool-8-thread-1/WARN]: 	at java.net.Socket.connect(Socket.java:589)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
[11:18:21] [pool-8-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
[11:18:21] [pool-8-thread-1/WARN]: 	... 32 more

**Comment by Andre601** [comment]
Restart your server and try it again.

**Comment by bartyrealms** [comment]
> Restart your server and try it again.

This was 4 minutes after a server restart. This issue was experienced before and after the restart.

**Comment by bartyrealms** [comment]
Switching to Google's DNS servers fixed the problem.
