### ISSUE TITLE
Could not load LuckPerms due to Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by martixingwei** [lucko/LuckPerms#134]
Error message:
```
Could not load 'plugins/LuckPerms-Bukkit-2.17.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/lucko/luckperms/bukkit/LPBukkitPlugin : Unsupported major.minor version 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[server.jar:git-Spigot-7d78b81-775f1e1]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[server.jar:git-Spigot-7d78b81-775f1e1]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [server.jar:git-Spigot-7d78b81-775f1e1]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301) [server.jar:git-Spigot-7d78b81-775f1e1]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [server.jar:git-Spigot-7d78b81-775f1e1]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [server.jar:git-Spigot-7d78b81-775f1e1]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_121]
Caused by: java.lang.UnsupportedClassVersionError: me/lucko/luckperms/bukkit/LPBukkitPlugin : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_121]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803) ~[?:1.7.0_121]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_121]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:442) ~[?:1.7.0_121]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:64) ~[?:1.7.0_121]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:354) ~[?:1.7.0_121]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348) ~[?:1.7.0_121]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_121]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347) ~[?:1.7.0_121]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-Spigot-7d78b81-775f1e1]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-7d78b81-775f1e1]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_121]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_121]
        at java.lang.Class.forName0(Native Method) ~[?:1.7.0_121]
        at java.lang.Class.forName(Class.java:278) ~[?:1.7.0_121]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[server.jar:git-Spigot-7d78b81-775f1e1]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[server.jar:git-Spigot-7d78b81-775f1e1]
        ... 6 more
```

**Comment by Slind14** [comment]
Luckperms requires at least java 8.
