### ISSUE TITLE
Error sending component messages on older CB/S releases

### ISSUE THREAD

**Issue by JustProGit** [lucko/LuckPerms#1344]
This is the error code I get when I run any luckperm command.

```
[06:17:26 WARN]: java.lang.NoClassDefFoundError: Could not initialize class me.lucko.luckperms.lib.text.adapter.bukkit.TextAdapter0
[06:17:26 WARN]: at me.lucko.luckperms.lib.text.adapter.bukkit.TextAdapter.sendComponent(TextAdapter.java:59)
[06:17:26 WARN]: at me.lucko.luckperms.lib.text.adapter.bukkit.TextAdapter.sendComponent(TextAdapter.java:49)
[06:17:26 WARN]: at me.lucko.luckperms.bukkit.BukkitSenderFactory.sendMessage(BukkitSenderFactory.java:82)
[06:17:26 WARN]: at me.lucko.luckperms.bukkit.BukkitSenderFactory.sendMessage(BukkitSenderFactory.java:45)
[06:17:26 WARN]: at me.lucko.luckperms.common.sender.AbstractSender.sendMessage(AbstractSender.java:104)
[06:17:26 WARN]: at me.lucko.luckperms.common.command.CommandManager.lambda$sendCommandUsage$12(CommandManager.java:293)
[06:17:26 WARN]: at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[06:17:26 WARN]: at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[06:17:26 WARN]: at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[06:17:26 WARN]: at java.util.Iterator.forEachRemaining(Iterator.java:116)
[06:17:26 WARN]: at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
[06:17:26 WARN]: at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
[06:17:26 WARN]: at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[06:17:26 WARN]: at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[06:17:26 WARN]: at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[06:17:26 WARN]: at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[06:17:26 WARN]: at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[06:17:26 WARN]: at me.lucko.luckperms.common.command.CommandManager.sendCommandUsage(CommandManager.java:278)
[06:17:26 WARN]: at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:193)
[06:17:26 WARN]: at me.lucko.luckperms.common.command.CommandManager.lambda$onCommand$0(CommandManager.java:150)
[06:17:26 WARN]: at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[06:17:26 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[06:17:26 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[06:17:26 WARN]: at java.lang.Thread.run(Thread.java:748)
```

**Comment by JustProGit** [comment]
I'm running version 1.8.8 and that is the full error.

**Comment by JustProGit** [comment]
it starts without issues. It's when I run a luckperm command.

**Comment by lucko** [comment]
What version of LP?

**Comment by JustProGit** [comment]
newest..

**Comment by BrainStone** [comment]
Version number please. When asked for the version, always use the version number.

**Comment by lucko** [comment]
Newest is subjective, it depends on the time you downloaded & where you downloaded from. LuckPerms is distributed via a number of platforms, some of which are only occasionally updated to the "very latest" version.

So yes, in future, always try to give the exact version number! :)

I've managed to reproduce this issue myself on Spigot 1.8.8. The bug is actually in one of the upstream libraries LP uses, I've written & submitted a fix (linked above) - just waiting for it to be given the all clear and deployed, and then I'll include the fix in LuckPerms.

**Comment by lucko** [comment]
Should be fixed in the latest version.
