### ISSUE TITLE
Not loading 

### ISSUE THREAD

**Issue by BlazingTide** [lucko/LuckPerms#1367]
> [16:56:43 ERROR]: Error occurred while enabling LuckPerms v4.3.17 (Is it up to date?)
java.lang.NoSuchMethodError: com.google.common.collect.Range.closed(Ljava/lang/Comparable;Ljava/lang/Comparable;)Lcom/google/common/collect/Range;
at me.lucko.luckperms.common.utils.Predicates.notInRange(Predicates.java:60) ~[?:?]
at me.lucko.luckperms.common.commands.generic.permission.PermissionInfo.<init>(PermissionInfo.java:65) ~[?:?]
at me.lucko.luckperms.common.commands.generic.permission.CommandPermission.<init>(CommandPermission.java:38) ~[?:?]
at me.lucko.luckperms.common.commands.user.UserMainCommand.<init>(UserMainCommand.java:69) ~[?:?]
at me.lucko.luckperms.common.command.CommandManager.<init>(CommandManager.java:112) ~[?:?]
at me.lucko.luckperms.bukkit.BukkitCommandExecutor.<init>(BukkitCommandExecutor.java:49) ~[?:?]
at me.lucko.luckperms.bukkit.LPBukkitPlugin.registerCommands(LPBukkitPlugin.java:152) ~[?:?]
at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:137) ~[?:?]
at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:153) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[server.jar:cSpigot]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [server.jar:cSpigot]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [server.jar:cSpigot]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:493) [server.jar:cSpigot]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:411) [server.jar:cSpigot]
at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:148) [server.jar:cSpigot]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:481) [server.jar:cSpigot]
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [server.jar:cSpigot]

I'm using latest version and on 1.7 

What happens when player log's in:

> [17:00:42 ERROR]: [LuckPerms] Exception occurred whilst loading data for 93153d9a-b4a8-487b-ad6a-d84e1b8409ba - BlazingTide
> [17:00:42 WARN]: java.lang.NullPointerException
> [17:00:42 WARN]: at me.lucko.luckperms.common.plugin.util.AbstractConnectionListener.loadUser(AbstractConnectionListener.java:68)
> [17:00:42 WARN]: at me.lucko.luckperms.bukkit.listeners.BukkitConnectionListener.onPlayerPreLogin(BukkitConnectionListener.java:88)
> [17:00:42 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [17:00:42 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [17:00:42 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [17:00:42 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
> [17:00:42 WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298)
> [17:00:42 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [17:00:42 WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514)
> [17:00:42 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496)
> [17:00:42 WARN]: at net.minecraft.server.v1_7_R4.ThreadPlayerLookupUUID.fireLoginEvents(ThreadPlayerLookupUUID.java:110)
> [17:00:42 WARN]: at net.minecraft.server.v1_7_R4.ThreadPlayerLookupUUID.run(ThreadPlayerLookupUUID.java:63)
> [17:00:42 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [17:00:42 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [17:00:42 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by BrainStone** [comment]
Use LuckPerms-Bukkit-Legacy: https://ci.lucko.me/view/LuckPerms/job/LuckPerms/
