### ISSUE TITLE
MariaDB connection not working

### ISSUE THREAD

**Issue by BugabuseMe** [lucko/LuckPerms#1373]
[10:29:44] [Server thread/ERROR]: [LuckPerms] Failed to init storage dao
[10:29:44] [Server thread/WARN]: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
[10:29:44] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
[10:29:44] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
[10:29:44] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
[10:29:44] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[10:29:44] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:127)
[10:29:44] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.tableExists(SqlStorage.java:151)
[10:29:44] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:168)
[10:29:44] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.Storage.init(Storage.java:110)
[10:29:44] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:119)
[10:29:44] [Server thread/WARN]: 	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:130)
[10:29:44] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:153)
[10:29:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[10:29:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
[10:29:44] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[10:29:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[10:29:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[10:29:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:236)
[10:29:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786)
[10:29:44] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:844)
[10:29:44] [Server thread/INFO]: [LuckPerms] Loading messaging service... [SQL]
[10:29:49] [Server thread/WARN]: java.lang.RuntimeException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
[10:29:49] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:56)
[10:29:49] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.MessagingFactory$SqlMessengerProvider.obtain(MessagingFactory.java:132)
[10:29:49] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.LuckPermsMessagingService.<init>(LuckPermsMessagingService.java:72)
[10:29:49] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.MessagingFactory.getServiceFor(MessagingFactory.java:95)
[10:29:49] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.messaging.BukkitMessagingFactory.getServiceFor(BukkitMessagingFactory.java:63)
[10:29:49] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.MessagingFactory.getInstance(MessagingFactory.java:73)
[10:29:49] [Server thread/WARN]: 	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:131)
[10:29:49] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:153)
[10:29:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[10:29:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
[10:29:49] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[10:29:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[10:29:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[10:29:49] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:236)
[10:29:49] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786)
[10:29:49] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:844)
[10:29:49] [Server thread/WARN]: Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
[10:29:49] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
[10:29:49] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
[10:29:49] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
[10:29:49] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[10:29:49] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:127)
[10:29:49] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.sql.SqlMessenger.getConnection(SqlMessenger.java:84)
[10:29:49] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.init(AbstractSqlMessenger.java:55)
[10:29:49] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:54)
[10:29:49] [Server thread/WARN]: 	... 15 more
[10:29:49] [Server thread/WARN]: [LuckPerms] Messaging service 'sql' not recognised.
[10:29:49] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[10:29:49] [Server thread/INFO]: [LuckPerms] Performing initial data load...

**Comment by BugabuseMe** [comment]
edit: i set max global connections to 9000 so it's not that one the matter, i'm using paperspigot 1.13.2

**Comment by Imortalshard** [comment]
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#luckperms-cannot-connect-to-my-mysql-server

Have a read of that.

**Comment by BugabuseMe** [comment]
Solved it on my own, my database was broken, after reinstalling everything it worked again
