### ISSUE TITLE
SSLException: Unable to download dependencies

### ISSUE THREAD

**Issue by Kracher019** [lucko/LuckPerms#1390]
This error comes up several times on a fresh Spigot installation using OpenJDK11.

```
[Server thread/INFO]: This server is running CraftBukkit version git-Spigot-f56e2e7-07e504c (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[Server thread/INFO]: Debug logging is disabled
[Server thread/INFO]: Using 4 threads for Netty based IO
[Server thread/INFO]: Server Ping Player Sample Count: 12
[Server thread/INFO]: Generating keypair
[Server thread/INFO]: Starting Minecraft server on *:25565
[Server thread/INFO]: [LuckPerms] Loading LuckPerms v4.3.78
[Server thread/ERROR]: [LuckPerms] Exception whilst downloading dependency TEXT
[Server thread/WARN]: java.lang.RuntimeException: Unable to download
[Server thread/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManager.downloadDependency(DependencyManager.java:270)
[Server thread/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependencies(DependencyManager.java:144)
[Server thread/WARN]: 	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.load(AbstractLuckPermsPlugin.java:90)
[Server thread/WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onLoad(LPBukkitBootstrap.java:131)
[Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:328)
[Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213)
[Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
[Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[Server thread/WARN]: Caused by: javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[Server thread/WARN]: 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:129)
[Server thread/WARN]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
[Server thread/WARN]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
[Server thread/WARN]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
[Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1314)
[Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:408)
[Server thread/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
[Server thread/WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
[Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
[Server thread/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
[Server thread/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManager.downloadDependency(DependencyManager.java:240)
[Server thread/WARN]: 	... 7 more
[Server thread/WARN]: Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[Server thread/WARN]: 	at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:89)
[Server thread/WARN]: 	at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)
[Server thread/WARN]: 	at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:308)
[Server thread/WARN]: 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:176)
[Server thread/WARN]: 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:188)
[Server thread/WARN]: 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
[Server thread/WARN]: 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:626)
[Server thread/WARN]: 	at java.base/sun.security.ssl.CertificateStatus$CertificateStatusConsumer.consume(CertificateStatus.java:292)
[Server thread/WARN]: 	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
[Server thread/WARN]: 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
[Server thread/WARN]: 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
[Server thread/WARN]: 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:178)
[Server thread/WARN]: 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
[Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
[Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
[Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
[Server thread/WARN]: 	... 13 more
[Server thread/WARN]: Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[Server thread/WARN]: 	at java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
[Server thread/WARN]: 	at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
[Server thread/WARN]: 	at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
[Server thread/WARN]: 	at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:86)
[Server thread/WARN]: 	... 28 more
```

**Comment by electronicboy** [comment]
More than likely your ca-certificates aren't installed properly, on debian based distros, make sure that the ca-certificates-java package is installed, and run `update-ca-certificates -f`

**Comment by Kracher019** [comment]
@electronicboy Thanks for the reply!
I actually just found the problem.  The current stretch debian version is running an old ca-certificates-java version (20170531+nmu1) which had a bug.
I manually downloaded and installed the version 20180516.
Now everything runs fine.
