### ISSUE TITLE
LuckPerms won't load on latest bungee

### ISSUE THREAD

**Issue by g0d-gam3** [lucko/LuckPerms#1404]
After downloading the latest LuckPerms and latest Bungee I cannot get LuckPerms to load as it comes up with the follow error.

`17:53:54 [WARNING] Exception encountered when loading plugin: LuckPerms
java.lang.NoClassDefFoundError: com/google/common/collect/Streams
    at me.lucko.luckperms.lib.text.serializer.LegacyComponentSerializerImpl.<clinit>(LegacyComponentSerializerImpl.java:47)
    at me.lucko.luckperms.lib.text.serializer.ComponentSerializers.<clinit>(ComponentSerializers.java:47)
    at me.lucko.luckperms.common.util.TextUtils.fromLegacy(TextUtils.java:52)
    at me.lucko.luckperms.bungee.BungeeSenderFactory.sendMessage(BungeeSenderFactory.java:65)
    at me.lucko.luckperms.bungee.BungeeSenderFactory.sendMessage(BungeeSenderFactory.java:42)
    at me.lucko.luckperms.common.sender.AbstractSender.sendMessage(AbstractSender.java:89)
    at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.displayBanner(AbstractLuckPermsPlugin.java:328)
    at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:98)
    at me.lucko.luckperms.bungee.LPBungeeBootstrap.onEnable(LPBungeeBootstrap.java:124)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:247)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:280)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Streams
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 13 more`

**Comment by g0d-gam3** [comment]
I should note, I just tried the version before the dependency update (v4.3.80) and it loads just fine.

**Comment by Turbotailz** [comment]
A few people in the Discord have reported this as well @lucko 
Build 856 should be used in the mean time until this bug is resolved.
