### ISSUE TITLE
Server Randomly Crashes after adding 1 code line

### ISSUE THREAD

**Issue by Darkfield** [lucko/LuckPerms#1405]
Added this line so 1000 per second bots wouldn't crash server, but sometimes server crash with this error randomly not from bots, how to fix it?

Added line in:
https://cdn.discordapp.com/attachments/241667244927483904/539473496758157333/unknown.png

Crash error:
https://pastebin.com/qK40VDb2

**Comment by lucko** [comment]
The exception itself (it's not a crash) should be resolved in the latest version.

As for dealing with bot attacks, I don't see that as being a LP problem. It will load user data for any user who connects, as you would expect.

Either you need to get an anti-bot plugin which can cancel the connections before they are handled by plugins on the server, or enable online mode and let Mojang do that for you.

**Comment by Darkfield** [comment]
Haven't been fixed even without that line. Can you please try catch that error, so it wouldn't crash server?

**Comment by Darkfield** [comment]
`[15:57:27] [Server thread/ERROR]: Encountered an unexpected exception
java.util.NoSuchElementException
	at java.util.concurrent.ConcurrentSkipListMap$Iter.advance(ConcurrentSkipListMap.java:2316) ~[?:1.8.0_201]
	at java.util.concurrent.ConcurrentSkipListMap$KeyIterator.next(ConcurrentSkipListMap.java:2351) ~[?:1.8.0_201]
	at com.google.common.collect.AbstractMapBasedMultimap$Itr.next(AbstractMapBasedMultimap.java:1150) ~[spigot-1.8.8-8.jar:git-Spigot-21fe707-e1ebe52]
	at java.util.Collection.removeIf(Collection.java:414) ~[?:1.8.0_201]
	at me.lucko.luckperms.common.model.NodeMap.removeIf(NodeMap.java:244) ~[?:?]
	at me.lucko.luckperms.common.model.PermissionHolder.removeIfTransient(PermissionHolder.java:314) ~[?:?]
	at me.lucko.luckperms.bukkit.inject.permissible.LPPermissionAttachment.clearInternal(LPPermissionAttachment.java:208) ~[?:?]
	at me.lucko.luckperms.bukkit.inject.permissible.LPPermissionAttachment.remove(LPPermissionAttachment.java:218) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649) ~[?:1.8.0_201]
	at me.lucko.luckperms.bukkit.inject.permissible.LPPermissible.clearPermissions(LPPermissible.java:305) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.disconnect(CraftPlayer.java:1135) ~[spigot-1.8.8-8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerList.disconnect(PlayerList.java:349) ~[spigot-1.8.8-8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:871) ~[spigot-1.8.8-8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.NetworkManager.l(NetworkManager.java:314) ~[spigot-1.8.8-8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:145) ~[spigot-1.8.8-8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) ~[spigot-1.8.8-8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) ~[spigot-1.8.8-8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) ~[spigot-1.8.8-8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8-8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[15:57:27] [Server thread/ERROR]: This crash report has been saved to: /root/mc/./crash-reports/crash-2019-02-03_15.57.27-server.txt
[15:57:27] [Server thread/INFO]: Stopping server`

**Comment by lucko** [comment]
Moving discussion to #1416 - please don't open duplicate issues in the future, much easier to just keep everything in one place..
