### ISSUE TITLE
Web Editor Error

### ISSUE THREAD

**Issue by PlinioRasch** [lucko/LuckPerms#1412]
So I'm getting some huge errors when I type /lp editor, here they are...

[00:50:42] [pool-7-thread-1/WARN]: java.lang.RuntimeException: java.net.UnknownHostException: bytebin.lucko.me: Temporary failure in name resolution
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.common.web.StandardPastebin.post(StandardPastebin.java:156)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.common.web.StandardPastebin.postJson(StandardPastebin.java:123)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:50)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:42)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:217)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.common.command.CommandManager.lambda$onCommand$0(CommandManager.java:157)
[00:50:42] [pool-7-thread-1/WARN]: 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[00:50:42] [pool-7-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[00:50:42] [pool-7-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[00:50:42] [pool-7-thread-1/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[00:50:42] [pool-7-thread-1/WARN]: Caused by: java.net.UnknownHostException: bytebin.lucko.me: Temporary failure in name resolution
[00:50:42] [pool-7-thread-1/WARN]: 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
[00:50:42] [pool-7-thread-1/WARN]: 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
[00:50:42] [pool-7-thread-1/WARN]: 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
[00:50:42] [pool-7-thread-1/WARN]: 	at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
[00:50:42] [pool-7-thread-1/WARN]: 	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
[00:50:42] [pool-7-thread-1/WARN]: 	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.Dns$1.lookup(Dns.java:40)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.common.web.HttpClient$LuckPermsUserAgentInterceptor.intercept(HttpClient.java:87)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:77)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.common.web.HttpClient.makeCall(HttpClient.java:60)
[00:50:42] [pool-7-thread-1/WARN]: 	at me.lucko.luckperms.common.web.StandardPastebin.post(StandardPastebin.java:141)
[00:50:42] [pool-7-thread-1/WARN]: 	... 10 more

**Comment by Imortalshard** [comment]
Hi,
What version of luckperms are you using?

**Comment by PlinioRasch** [comment]
Hey, I ended up updating the plugin but it didn't work at all.

I'm using a dedicated machine and I tried on a normal mc server from a host and it worked fine, please help me, I don't know what's going on with my server. 

It's not resolving the host with most plugins, also with vault, buycraft and etc.
Please tell me or give me a hint on what could be happening with my server.

**Comment by PlinioRasch** [comment]
It's giving very similar errors with most plugins, such as this...

[02:24:39] [Thread-20/INFO]: [HeadsPluginAPI] null
java.net.UnknownHostException: freshcoal.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[?:1.8.0_191]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_191]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_191]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666) ~[?:1.8.0_191]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_191]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:1.8.0_191]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[?:1.8.0_191]

**Comment by PlinioRasch** [comment]
Here too...

[02:24:08] [Thread-12/ERROR]: [MinePacks] null
java.net.UnknownHostException: api.curseforge.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[?:1.8.0_191]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_191]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_191]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666) ~[?:1.8.0_191

**Comment by Andre601** [comment]
Well. If multiple plugins throw similar errors than you can safely assume that there is something not right with your host.
Perhaps they block a connection?

**Comment by Turbotailz** [comment]
I'm gonna take a wild guess and say that your version of Java might be outdated.

**Comment by Techno3600** [comment]
Yeah, this doesn't look like a plugin-related issue. I can't really see a pinpoint to an actual plugin error. Seems more of an actual minecraft jar or java version error.

**Comment by PlinioRasch** [comment]
Oh, alright thanks a lot guys, I'm gonna speak to my host about this!
