### ISSUE TITLE
Server Crashing LuckPerms-Bukkit-4.3.87

### ISSUE THREAD

**Issue by Darkfield** [lucko/LuckPerms#1416]
Hello, bug haven't been fixed:

```
[15:57:27] [Server thread/ERROR]: Encountered an unexpected exception
java.util.NoSuchElementException
	at java.util.concurrent.ConcurrentSkipListMap$Iter.advance(ConcurrentSkipListMap.java:2316) ~[?:1.8.0_201]
	at java.util.concurrent.ConcurrentSkipListMap$KeyIterator.next(ConcurrentSkipListMap.java:2351) ~[?:1.8.0_201]
	at com.google.common.collect.AbstractMapBasedMultimap$Itr.next(AbstractMapBasedMultimap.java:1150) ~[spigot-1.8.8-8.jar:git-Spigot-21fe707-e1ebe52]
	at java.util.Collection.removeIf(Collection.java:414) ~[?:1.8.0_201]
	at me.lucko.luckperms.common.model.NodeMap.removeIf(NodeMap.java:244) ~[?:?]
	at me.lucko.luckperms.common.model.PermissionHolder.removeIfTransient(PermissionHolder.java:314) ~[?:?]
	at me.lucko.luckperms.bukkit.inject.permissible.LPPermissionAttachment.clearInternal(LPPermissionAttachment.java:208) ~[?:?]
	at me.lucko.luckperms.bukkit.inject.permissible.LPPermissionAttachment.remove(LPPermissionAttachment.java:218) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649) ~[?:1.8.0_201]
	at me.lucko.luckperms.bukkit.inject.permissible.LPPermissible.clearPermissions(LPPermissible.java:305) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.disconnect(CraftPlayer.java:1135) ~[spigot-1.8.8-8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerList.disconnect(PlayerList.java:349) ~[spigot-1.8.8-8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:871) ~[spigot-1.8.8-8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.NetworkManager.l(NetworkManager.java:314) ~[spigot-1.8.8-8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:145) ~[spigot-1.8.8-8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) ~[spigot-1.8.8-8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) ~[spigot-1.8.8-8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) ~[spigot-1.8.8-8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8-8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[15:57:27] [Server thread/ERROR]: This crash report has been saved to: /root/mc/./crash-reports/crash-2019-02-03_15.57.27-server.txt
[15:57:27] [Server thread/INFO]: Stopping server
```

How to make that server wouldn't stop? It could throw that error, but it wouldn't stop the server.

**Comment by lucko** [comment]
Should be fixed by the above commit.

Please re-open this issue if this isn't the case.
