### ISSUE TITLE
/lp applyedits - 404

### ISSUE THREAD

**Issue by artur9010** [lucko/LuckPerms#1418]
```
[00:11:13 INFO]: artur9010 issued server command: /lp applyedits oN1YroJ8Bqv
[00:11:13 WARN]: java.lang.RuntimeException: Got response: 404 - Not Found - Invalid path
[00:11:13 WARN]:        at me.lucko.luckperms.common.web.HttpClient.exceptionForUnsuccessfulResponse(HttpClient.java:69)
[00:11:13 WARN]:        at me.lucko.luckperms.common.web.HttpClient.makeCall(HttpClient.java:55)
[00:11:13 WARN]:        at me.lucko.luckperms.common.web.WebEditor.getDataFromGist(WebEditor.java:152)
[00:11:13 WARN]:        at me.lucko.luckperms.common.commands.misc.ApplyEditsCommand.execute(ApplyEditsCommand.java:73)
[00:11:13 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:50)
[00:11:13 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:42)
[00:11:13 WARN]:        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:215)
[00:11:13 WARN]:        at me.lucko.luckperms.common.command.CommandManager.lambda$onCommand$0(CommandManager.java:150)
[00:11:13 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[00:11:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[00:11:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[00:11:13 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

LuckPerms 4.3.73
PaperSpigot Paper-509
Hosted on Google Compute Engine.

**Comment by BrainStone** [comment]
Either you didn’t paste the whole command or waited too long after saving. The links/commands expire after a while (like a few days)

**Comment by artur9010** [comment]
`too long`, 20-30 seconds?

I copied command by left clicking it in web editor

**Comment by BrainStone** [comment]
Then try to save again.

Did you maybe configure a custom data storage?

Though in any case this isn’t a LP issue as the data storage server returned the 404. If it persists I’d recommend making an issue on lucko/LuckPermsWeb.

**Comment by lucko** [comment]
I've checked the editor upload server logs and can't see any errors reported there - I added some extra logging, would you be able to try again?

**Comment by artur9010** [comment]
@lucko ok.

I typed `/lp group vip editor`
I got that url: https://luckperms.github.io/editor/#IT0j5MUhCJ

Added permission `essentials.compact`
Typed `/lp applyedits GWAuKJbmeu` on server
Got 404

```
[18:10:41 INFO]: artur9010 issued server command: /lp applyedits GWAuKJbmeuv
[18:10:41 WARN]: java.lang.RuntimeException: Got response: 404 - Not Found - Invalid path
[18:10:41 WARN]:        at me.lucko.luckperms.common.web.HttpClient.exceptionForUnsuccessfulResponse(HttpClient.java:69)
[18:10:41 WARN]:        at me.lucko.luckperms.common.web.HttpClient.makeCall(HttpClient.java:55)
[18:10:41 WARN]:        at me.lucko.luckperms.common.web.WebEditor.getDataFromGist(WebEditor.java:152)
[18:10:41 WARN]:        at me.lucko.luckperms.common.commands.misc.ApplyEditsCommand.execute(ApplyEditsCommand.java:73)
[18:10:41 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:50)
[18:10:41 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:42)
[18:10:41 WARN]:        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:215)
[18:10:41 WARN]:        at me.lucko.luckperms.common.command.CommandManager.lambda$onCommand$0(CommandManager.java:150)
[18:10:41 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[18:10:41 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[18:10:41 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[18:10:41 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

```
> lp info
[18:11:55 INFO]: [LP] Running LuckPerms v4.3.73 by Luck.
[18:11:55 INFO]: [LP] -  Platform: Bukkit
[18:11:55 INFO]: [LP] -  Server Brand: Paper
[18:11:55 INFO]: [LP] -  Server Version:
[18:11:55 INFO]: [LP] -  git-Paper-518 (MC: 1.13.2) - 1.13.2-R0.1-SNAPSHOT
[18:11:55 INFO]: [LP] -  Storage:
[18:11:55 INFO]: [LP] -     Type: H2
[18:11:55 INFO]: [LP] -     File Size: 0.19MB
[18:11:55 INFO]: [LP] -  Messaging: None
[18:11:55 INFO]: [LP] -  Instance:
[18:11:55 INFO]: [LP] -     Static contexts: None
[18:11:55 INFO]: [LP] -     Online Players: 3 (3 unique)
[18:11:55 INFO]: [LP] -     Uptime: 8m 14s
[18:11:55 INFO]: [LP] -     Local Data: 3 users, 5 groups, 0 tracks
```

**Comment by lucko** [comment]
Sorry for not replying here - I looked into this after your last message and think I found the issue.

I'm assuming this was resolved by that fix.
