### ISSUE TITLE
MYSQL multiserver

### ISSUE THREAD

**Issue by GGNoPotato** [lucko/LuckPerms#1432]
Upon attempting to have permissions synced via mysql I use the same config on multiple servers. Although one server will not run LuckPerms and throws this error
```
[05:46:27] [Server thread/INFO]: [LP] Loading storage provider... [MYSQL]
[05:46:27] [Server thread/ERROR]: Error occurred while enabling LuckPerms v4.2.17 (Is it up to date?)
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy20.init(Unknown Source) ~[?:?]
	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:117) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:136) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:139) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[paper_server.jar:git-PaperSpigot-unknown]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [paper_server.jar:git-PaperSpigot-unknown]
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins(1).jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [paper_server.jar:git-PaperSpigot-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [paper_server.jar:git-PaperSpigot-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [paper_server.jar:git-PaperSpigot-unknown]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203) [paper_server.jar:git-PaperSpigot-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [paper_server.jar:git-PaperSpigot-unknown]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at me.lucko.luckperms.common.storage.wrappings.PhasedStorage.lambda$wrap$0(PhasedStorage.java:69) ~[?:?]
	... 13 more
Caused by: java.lang.NoSuchMethodError: org.apache.logging.log4j.spi.LoggerContext.getLogger(Ljava/lang/String;)Lorg/apache/logging/log4j/spi/ExtendedLogger;
	at org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:37) ~[?:?]
	at org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:29) ~[?:?]
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47) ~[?:?]
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29) ~[?:?]
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358) ~[?:?]
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383) ~[?:?]
	at me.lucko.luckperms.lib.hikari.HikariConfig.<clinit>(HikariConfig.java:51) ~[?:?]
	at me.lucko.luckperms.common.storage.dao.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:77) ~[?:?]
	at me.lucko.luckperms.common.storage.dao.sql.SqlDao.init(SqlDao.java:159) ~[?:?]
	at me.lucko.luckperms.common.storage.AbstractStorage.init(AbstractStorage.java:122) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at me.lucko.luckperms.common.storage.wrappings.PhasedStorage.lambda$wrap$0(PhasedStorage.java:69) ~[?:?]
	... 13 more
[05:46:27] [Server thread/INFO]: [LuckPerms] Disabling LuckPerms v4.2.17
[05:46:27] [Server thread/INFO]: [LP] Closing storage...
[05:46:27] [Server thread/ERROR]: Error occurred while disabling LuckPerms v4.2.17 (Is it up to date?)
java.lang.NullPointerException
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.disable(AbstractLuckPermsPlugin.java:202) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onDisable(LPBukkitBootstrap.java:151) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[paper_server.jar:git-PaperSpigot-unknown]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [paper_server.jar:git-PaperSpigot-unknown]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) [paper_server.jar:git-PaperSpigot-unknown]
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins(1).jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [paper_server.jar:git-PaperSpigot-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [paper_server.jar:git-PaperSpigot-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [paper_server.jar:git-PaperSpigot-unknown]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203) [paper_server.jar:git-PaperSpigot-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [paper_server.jar:git-PaperSpigot-unknown]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by Imortalshard** [comment]
Hi GGNoPotato,
You are running a very outdated version of Luckperms. Please update ALL servers to the same version of luckperms from the following link:
https://luckperms.github.io/

Also, since you're using multiple servers make sure you're using the Luckperms-Bungee version on the bungeecord server & the Luckperms-Bukkit/Spigot version on the spigot servers.

**Comment by GGNoPotato** [comment]
Hi thanks for quick reply.

Even after updating it still does not work. Cant seem to figure out why...

New error:

> [06:04:18] [Server thread/INFO]: [LuckPerms] Attempting to apply relocations to hikari-3.3.0.jar...
[06:04:18] [Server thread/INFO]: [LuckPerms] Loading storage provider... [MYSQL]
[06:04:19] [Server thread/ERROR]: Error occurred while enabling LuckPerms v4.3.94 (Is it up to date?)
java.lang.NoSuchMethodError: org.apache.logging.log4j.spi.LoggerContext.getLogger(Ljava/lang/String;)Lorg/apache/logging/log4j/spi/ExtendedLogger;
	at org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:37) ~[?:?]
	at org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:29) ~[?:?]
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47) ~[?:?]
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29) ~[?:?]
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358) ~[?:?]
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383) ~[?:?]
	at me.lucko.luckperms.lib.hikari.HikariConfig.<clinit>(HikariConfig.java:51) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:76) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:165) ~[?:?]
	at me.lucko.luckperms.common.storage.Storage.init(Storage.java:110) ~[?:?]
	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:119) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:135) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:153) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[paper_server.jar:git-PaperSpigot-unknown]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [paper_server.jar:git-PaperSpigot-unknown]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [paper_server.jar:git-PaperSpigot-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [paper_server.jar:git-PaperSpigot-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [paper_server.jar:git-PaperSpigot-unknown]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203) [paper_server.jar:git-PaperSpigot-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [paper_server.jar:git-PaperSpigot-unknown]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[06:04:19] [Server thread/INFO]: [LuckPerms] Disabling LuckPerms v4.3.94
[06:04:19] [Server thread/INFO]: [LuckPerms] Closing storage...
[06:04:19] [Server thread/ERROR]: Error occurred while disabling LuckPerms v4.3.94 (Is it up to date?)
java.lang.NullPointerException
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.disable(AbstractLuckPermsPlugin.java:206) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onDisable(LPBukkitBootstrap.java:168) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[paper_server.jar:git-PaperSpigot-unknown]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [paper_server.jar:git-PaperSpigot-unknown]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) [paper_server.jar:git-PaperSpigot-unknown]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [paper_server.jar:git-PaperSpigot-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [paper_server.jar:git-PaperSpigot-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [paper_server.jar:git-PaperSpigot-unknown]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203) [paper_server.jar:git-PaperSpigot-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [paper_server.jar:git-PaperSpigot-unknown]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by GGNoPotato** [comment]
Both servers are running same spigot version, while one works the other doesnt. I tried disabling one server to see if it was somehow conflicting but it had no change.

**Comment by Imortalshard** [comment]
Because you are behind so many versions. It might be best to update your configs for all servers runnings Luckperms as well. Make sure the bungeecord server is runnings the same Luckperms version as well.

**Comment by GGNoPotato** [comment]
Currently im just trying to get it running on the one server first then I was going to add the bungeecord version. All the mysql instances are disabled and it still wont load for some reason...

**Comment by GGNoPotato** [comment]
After disabling all plugins and testing 1 by 1 it seems the latest versio of Staff+ breaks it...

https://www.spigotmc.org/resources/staff-the-ultimate-moderation-plugin-1-7-1-13.41500/

Not sure why, but removing it fixed my problem.

**Comment by lucko** [comment]
This is a caused when other plugins incorrectly shade the SLF4J logging library. Not something LuckPerms is causing or can fix.
