### ISSUE TITLE
Instance of API from proxy plugin

### ISSUE THREAD

**Issue by marshallwalker** [lucko/LuckPerms#1446]
unable to get instance of API inside a plugin running on the proxy (BungeeCord) all servers including the proxy are running LuckPerms, and my proxy plugin is depending on LuckPerms plugin.

Here's the error
`18:40:24 [INFO] Enabled plugin LuckPerms version 4.3.99 by Luck
18:40:24 [WARNING] Exception encountered when loading plugin: ProxyQueue
java.lang.IllegalStateException: API is not loaded.
    at me.lucko.luckperms.LuckPerms.getApi(LuckPerms.java:54)
    at ca.pureplugins.gg.dawn.ProxyQueuePlugin.onEnable(ProxyQueuePlugin.kt:17)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:247)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:280)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
18:40:24 [INFO] Enabled plugin cmd_find version git:cmd_find:1.`

**Comment by BrainStone** [comment]
Don’t shade the API in.
