### ISSUE TITLE
Can't open the editor

### ISSUE THREAD

**Issue by bobdabiulder** [lucko/LuckPerms#1448]
I try /lp editor and get this in the console:

[15:32:58 WARN]: java.lang.RuntimeException: java.net.SocketTimeoutException: Read timed out
[15:32:58 WARN]:        at me.lucko.luckperms.common.web.StandardPastebin.post(StandardPastebin.java:155)
[15:32:58 WARN]:        at me.lucko.luckperms.common.web.StandardPastebin.postJson(StandardPastebin.java:122)
[15:32:58 WARN]:        at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
[15:32:58 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:50)
[15:32:58 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:42)
[15:32:58 WARN]:        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:215)
[15:32:58 WARN]:        at me.lucko.luckperms.common.command.CommandManager.lambda$onCommand$0(CommandManager.java:150)
[15:32:58 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
[15:32:58 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[15:32:58 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[15:32:58 WARN]:        at java.lang.Thread.run(Unknown Source)
[15:32:58 WARN]: Caused by: java.net.SocketTimeoutException: Read timed out
[15:32:58 WARN]:        at java.net.SocketInputStream.socketRead0(Native Method)
[15:32:58 WARN]:        at java.net.SocketInputStream.socketRead(Unknown Source)
[15:32:58 WARN]:        at java.net.SocketInputStream.read(Unknown Source)
[15:32:58 WARN]:        at java.net.SocketInputStream.read(Unknown Source)
[15:32:58 WARN]:        at sun.security.ssl.InputRecord.readFully(Unknown Source)
[15:32:58 WARN]:        at sun.security.ssl.InputRecord.read(Unknown Source)
[15:32:58 WARN]:        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
[15:32:58 WARN]:        at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
[15:32:58 WARN]:        at sun.security.ssl.AppInputStream.read(Unknown Source)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okio.Okio$2.read(Okio.java:140)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okio.RealBufferedSource.indexOf(RealBufferedSource.java:358)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[15:32:58 WARN]:        at me.lucko.luckperms.common.web.HttpClient$LuckPermsUserAgentInterceptor.intercept(HttpClient.java:80)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
[15:32:58 WARN]:        at me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:92)
[15:32:58 WARN]:        at me.lucko.luckperms.common.web.HttpClient.makeCall(HttpClient.java:53)
[15:32:58 WARN]:        at me.lucko.luckperms.common.web.StandardPastebin.post(StandardPastebin.java:140)
[15:32:58 WARN]:        ... 10 more

**Comment by BrainStone** [comment]
The server behind the editor is currently experiencing issues.

I can't give you an ETA on when it will be back.

I apologize for the inconviniece.

**Comment by TRose2000** [comment]
Known. backend is offline

**Comment by BoozleDoof** [comment]
Thank you much for the update.
Was just wondering about this, same issue. 👍

**Comment by bobdabiulder** [comment]
Interesting.  I think it would be cool if the Minecraft server itself hosted the editor.  That would extend the life of the plugin significantly, and it could just snag any open port to run the editor out of.  I wouldn't expect such a setup to cause problems with hosting providers, either.

**Comment by BrainStone** [comment]
It's designed like that on purpose. Because most servers don't have the luxuxy of being able to have any additional port they like. Especially when using hosters.  
The solution with using an external datastorage allows everyone to use the editor without any additional setup.

Also the editor and the bytebin backend are open source aswell. There's a rough guide on how to set it up yourself and how to change the URLs, so it works with your selfhosted instances.

**Comment by bobdabiulder** [comment]
Oh, I see.  That makes sense, thanks.

**Comment by BrainStone** [comment]
It's possible to that with LP too, as I've mentioned.

**Comment by bobdabiulder** [comment]
Yep, that's what I said lol.  Great to see projects this old (and relatively small) being very well maintained!

**Comment by T3DDY14** [comment]
is it still down?
As i still cannot access it

**Comment by DevilishDante** [comment]
me too u.u so i think is still down X)

**Comment by DevilishDante** [comment]
@BrainStone  where is the guide for host editor please? :o it's quite interessting :)

**Comment by Turbotailz** [comment]
https://github.com/lucko/LuckPerms/wiki/Self-hosting-the-web-interfaces

**Comment by DevilishDante** [comment]
@Turbotailz thnaks you ! :)

**Comment by T3DDY14** [comment]
is this possible on a windows machine , as my server for the time being is on a windows machine

**Comment by nzminecraftDOTcom** [comment]
Yes it is possible to host it on a windows machine, I just now have it runing (only with 1 minor error that stops the whole lot working)

**Comment by T3DDY14** [comment]
okay i just installed ubuntu

**Comment by T3DDY14** [comment]
on the windows machine

**Comment by nzminecraftDOTcom** [comment]
You shouldn't need a full install of ubuntu, gitbash etc works fine to set it all up, I did the entire setup using windows and nothing else. You just need to have your own webserver to host the editor/verbose/tree pages. Apache webservers are great for that.

**Comment by lucko** [comment]
Thanks for reporting guys - I'm sorry for the inconvenience.

Should all be resolved now.

**Comment by T3DDY14** [comment]
okay im confused about the proxy, do i need it or not

**Comment by BrainStone** [comment]
No. It just allows you to have the bytebin available at a nicer URL
