### ISSUE TITLE
Bungeecord errors.

### ISSUE THREAD

**Issue by LeeGodSRC** [lucko/LuckPerms#1462]
i get this error on using luckperms with bungeecord
it's werid like the error is happens on randomly player
it's start spamming when that player online, it's stopped spamming when that player loggout

```
21:55:59 [嚴重] ?T?? 10, 2019 9:55:59 ?U?? net.md_5.bungee.event.EventBus post
??i: Error dispatching event PermissionCheckEvent(sender=migitpigie, permission=bungeecord.command.list, hasPermission=false) to listener me.lucko.luckperms.bungee.listeners.BungeePermissionCheckListener@aeab9a1
java.lang.IllegalStateException: No permissions data present for player: migitpigie - 016d715d-8520-431c-80d5-4a5438ca60d4
    at me.lucko.luckperms.bungee.listeners.BungeePermissionCheckListener.onPlayerPermissionCheck(BungeePermissionCheckListener.java:66)
    at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:377)
    at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:513)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:148)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:116)
    at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:144)
    at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
```

**Comment by Andre601** [comment]
What BungeeCord version do you use?
What LP version do you use?
Is your BungeeCord in online or offline-mode?

**Comment by LeeGodSRC** [comment]
Hexacord 1.7 to 1.12
Lastest build
Online mode

**Comment by LeeGodSRC** [comment]
uhh sorry i just click wrong button

**Comment by lucko** [comment]
Can you set this option to true

https://github.com/lucko/LuckPerms/blob/d1511e43f2e1d4e900e119756cc87ba76ded9a17/bungee/src/main/resources/config.yml#L458-L461

Then restart your proxy, try logging in, and then provide the newly generated log file.

**Comment by LeeGodSRC** [comment]
sorry for late, so i just have to open it login and give you logs?
because it's randomly picking players

**Comment by LeeGodSRC** [comment]
https://hastebin.com/ohuqebubev.makefile
this is the new logs when i open debug-login
i will give one more log when the error shown up

**Comment by lucko** [comment]
That log doesn't contain any of the errors?

**Comment by LeeGodSRC** [comment]
Since the error doesn't shown up for a long time
i used the lastest build, maybe it's fixed, i will reopen this issue when it's happend again

**Comment by LeeGodSRC** [comment]
i'm sorry that i didn't catch the moment that the error start spamming up
it's ended when the target player logout, i will try to catch the moment
https://hastebin.com/kelusoyeke.rb

**Comment by LeeGodSRC** [comment]
It’s not even have login message when the error start spamming, can you make a debug for this, like kicking that player when the data not existsing

**Comment by SimonOrJ** [comment]
Hello, I also got the error myself just today.  Something hung my server up soon thereafter.

```
[01:18:46] [Netty Worker IO Thread #7/WARN]: Error dispatching event PermissionCheckEvent(sender=[redacted], permission=[redacted.perm.node], hasPermission=false) to listener me.lucko.luckperms.b
ungee.listeners.BungeePermissionCheckListener@143d9a93
java.lang.IllegalStateException: No permissions data present for player: Babybread - 61aa3342-21e6-41a5-8f71-cda7da2cda44
        at me.lucko.luckperms.bungee.listeners.BungeePermissionCheckListener.onPlayerPermissionCheck(BungeePermissionCheckListener.java:66) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:46) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:432) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:558) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at com.arcaneminecraft.bungee.SpyAlert.onCommand(SpyAlert.java:160) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:46) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:432) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:146) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:104) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by SimonOrJ** [comment]
Hello, I also got the error myself just today. Something hung my server up soon thereafter.  The `[redacted]` player has been playing on the server for a while, so their data definitely exists on the server.

```
[01:18:46] [Netty Worker IO Thread #7/WARN]: Error dispatching event PermissionCheckEvent(sender=[redacted], permission=[redacted.perm.node], hasPermission=false) to listener me.lucko.luckperms.b
ungee.listeners.BungeePermissionCheckListener@143d9a93
java.lang.IllegalStateException: No permissions data present for player: [redacted] - [redacted-uuid]
        at me.lucko.luckperms.bungee.listeners.BungeePermissionCheckListener.onPlayerPermissionCheck(BungeePermissionCheckListener.java:66) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:46) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:432) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:558) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at com.arcaneminecraft.bungee.SpyAlert.onCommand(SpyAlert.java:160) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:46) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:432) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:146) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:104) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by LeeGodSRC** [comment]
does it getting fixed in lastest version?

**Comment by lucko** [comment]
I need to see a full log (with this step https://github.com/lucko/LuckPerms/issues/1462#issuecomment-471543139 applied already) to attempt to work out why this is happening. 

The error stack track doesn't give me much to go by.

**Comment by LeeGodSRC** [comment]
hey lucko, seems it's not happen again after i changed bungeecord to Travertine
i will check for a while, maybe @SimonOrJ can reply the problems

**Comment by LeeGodSRC** [comment]
https://pastebin.com/8MwLU3Zf
happend again
it's seems after logout
i don't see anymore login after this

please reply me if you needed any info

**Comment by lucko** [comment]
I need to see the log entry when LuckPerms processed the login for the `ggka` user.

It will look at bit like this:

> [LuckPerms] Processing pre-login for b01f0239-fe4b-4c89-9a49-371823eabc3c - MCIDT

**Comment by LeeGodSRC** [comment]
https://pastebin.com/aQxiFtn3
alright

**Comment by lucko** [comment]
```
20:05:38 [資訊] [ggka] disconnected with: §f[Proxy] Lost connection to server.
20:05:38 [資訊] [ggka] <-> DownstreamBridge <-> [duel] has disconnected

...

20:05:50 [警告] Error dispatching event PermissionCheckEvent(sender=ggka, permission=bungeecord.command.list, hasPermission=false) to listener me.lucko.luckperms.bungee.listeners.BungeePermissionCheckListener@2a79d4b1
java.lang.IllegalStateException: No permissions data present for player: ggka - e1f86c95-1917-4796-833f-8c7f36c6db76
    at 
```

So, it seems like that player has disconnected from the proxy - and then a permission check runs for them?

Sooo, their commands are being processed even though they disconnected - maybe a BungeeCord bug?

**Comment by LeeGodSRC** [comment]
im not sure
hexacord always disconnecting the player whos using 1.7
do you recommend me to use travertine?
anyway i think it's would able to do a debug for this?

**Comment by lucko** [comment]
Yes, give Travertine a try.

**Comment by LeeGodSRC** [comment]
its still not fixed with travertine
