### ISSUE TITLE
Sql random error

### ISSUE THREAD

**Issue by DevilishDante** [lucko/LuckPerms#1469]
Hello i have a litle problem with luckperm with SQL in deed:
``` 
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[05:00:32 WARN]:        at sun.reflect.GeneratedConstructorAccessor264.newInstance(Unknown Source)
[05:00:32 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[05:00:32 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[05:00:32 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[05:00:32 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
[05:00:32 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:342)
[05:00:32 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2197)
[05:00:32 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2230)
[05:00:32 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2025)
[05:00:32 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
[05:00:32 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[05:00:32 WARN]:        at sun.reflect.GeneratedConstructorAccessor257.newInstance(Unknown Source)
[05:00:32 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[05:00:32 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[05:00:32 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[05:00:32 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
[05:00:32 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
[05:00:32 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428)
[05:00:32 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136)
[05:00:32 WARN]:        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
[05:00:32 WARN]:        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
[05:00:32 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
[05:00:32 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
[05:00:32 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706)
[05:00:32 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692)
[05:00:32 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[05:00:32 WARN]:        ... 3 more
[05:00:32 WARN]: Caused by: java.net.ConnectException: Connexion refusée (Connection refused)
[05:00:32 WARN]:        at java.net.PlainSocketImpl.socketConnect(Native Method)
[05:00:32 WARN]:        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[05:00:32 WARN]:        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[05:00:32 WARN]:        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[05:00:32 WARN]:        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[05:00:32 WARN]:        at java.net.Socket.connect(Socket.java:589)
[05:00:32 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
[05:00:32 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:301)
[05:00:32 WARN]:        ... 23 more
>
```
thanks to read me

**Comment by lucko** [comment]
This isn't a LuckPerms error.

See here for more info: https://github.com/lucko/LuckPerms/wiki/Storage-system-errors

**Comment by DevilishDante** [comment]
@lucko Hello, thanks for the information 👍
