### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by RikoDEV** [lucko/LuckPerms#147]
I have this error on startup:
[06:58:25] [Server thread/INFO]: [0;32;22m  Loading version [0;36;1mv2.17.29[0;32;22m on Bukkit - Paper[m
[06:58:25] [Server thread/INFO]:  [m
[06:58:25] [Server thread/INFO]: [0;37;22m[21m[[0;36;1mL[0;36;22mP[0;37;22m[21m] [0;36;22mLoading configuration...[m
[06:58:25] [Server thread/ERROR]: Error occurred while enabling LuckPerms v2.17.29 (Is it up to date?)
com.google.common.cache.CacheLoader$InvalidCacheLoadException: CacheLoader returned null for key me.lucko.luckperms.common.config.keys.EnduringKey@1bdaec80.
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2348) ~[patched_1.11.2.jar:git-Paper-1042]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2318) ~[patched_1.11.2.jar:git-Paper-1042]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) ~[patched_1.11.2.jar:git-Paper-1042]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) ~[patched_1.11.2.jar:git-Paper-1042]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934) ~[patched_1.11.2.jar:git-Paper-1042]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) ~[patched_1.11.2.jar:git-Paper-1042]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) ~[patched_1.11.2.jar:git-Paper-1042]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) ~[patched_1.11.2.jar:git-Paper-1042]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_121]
	at me.lucko.luckperms.common.config.AbstractConfiguration.loadAll(AbstractConfiguration.java:51) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitPlugin.onEnable(LPBukkitPlugin.java:161) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.2.jar:git-Paper-1042]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.2.jar:git-Paper-1042]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1042]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1042]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1042]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:209) [patched_1.11.2.jar:git-Paper-1042]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:599) [patched_1.11.2.jar:git-Paper-1042]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

Latest PaperSpigot 1.11.2

**Comment by lucko** [comment]
Thanks for reporting :)
