### ISSUE TITLE
Not an issues

### ISSUE THREAD

**Issue by DevilishDante** [lucko/LuckPerms#1484]
hi i have this error when i change group for some user
``` 
[19:50:32 INFO]: [LP] LOG > parent remove voyageur server=survie
[19:50:32 WARN]: [LuckPerms] Unable to pass event NodeRemoveEvent to handler us._donut_.skuniversal.luckperms.LuckPermsListener$$Lambda$2565/907807372
[19:50:32 WARN]: java.lang.reflect.UndeclaredThrowableException
[19:50:32 WARN]:        at com.sun.proxy.$Proxy125.isUser(Unknown Source)
[19:50:32 WARN]:        at us._donut_.skuniversal.luckperms.LuckPermsListener.onGroupChange(LuckPermsListener.java:37)
[19:50:32 WARN]:        at me.lucko.luckperms.common.event.LuckPermsEventHandler.invoke(LuckPermsEventHandler.java:108)
[19:50:32 WARN]:        at me.lucko.luckperms.common.event.LuckPermsEventHandler.invoke(LuckPermsEventHandler.java:45)
[19:50:32 WARN]:        at me.lucko.luckperms.lib.eventbus.SimpleEventBus.post(SimpleEventBus.java:107)
[19:50:32 WARN]:        at me.lucko.luckperms.common.event.AbstractEventBus.post(AbstractEventBus.java:84)
[19:50:32 WARN]:        at me.lucko.luckperms.common.event.EventFactory.post(EventFactory.java:111)
[19:50:32 WARN]:        at me.lucko.luckperms.common.event.EventFactory.lambda$post$0(EventFactory.java:124)
[19:50:32 WARN]:        at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$WrappedRunnable.run(AbstractJavaScheduler.java:79)
[19:50:32 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[19:50:32 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[19:50:32 WARN]:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[19:50:32 WARN]:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[19:50:32 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[19:50:32 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[19:50:32 WARN]:        at java.lang.Thread.run(Thread.java:748)
[19:50:32 WARN]: Caused by: java.lang.IllegalAccessException: no private access for invokespecial: interface me.lucko.luckperms.api.event.node.NodeMutateEvent, from me.lucko.luckperms.api.event.node.NodeMutateEvent/public
[19:50:32 WARN]:        at java.lang.invoke.MemberName.makeAccessException(MemberName.java:850)
[19:50:32 WARN]:        at java.lang.invoke.MethodHandles$Lookup.checkSpecialCaller(MethodHandles.java:1572)
[19:50:32 WARN]:        at java.lang.invoke.MethodHandles$Lookup.unreflectSpecial(MethodHandles.java:1231)
[19:50:32 WARN]:        at me.lucko.luckperms.common.event.gen.GeneratedEventSpec$EventInvocationHandler.invoke(GeneratedEventSpec.java:153)
[19:50:32 WARN]:        ... 16 more
[19:50:32 INFO]: [LuckPerms] [Messaging] Sending user ping for 'xvtito' with id: 4f9cf6c2-0732-4181-a4bc-3c07843cbdf5
```
and when plugins start i have this error
``` 
[19:52:00] [Server thread/INFO]: [LuckPerms] Loading storage provider... [MYSQL]
[19:52:00] [Server thread/WARN]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[19:52:00] [Server thread/WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[19:52:00] [Server thread/WARN]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
I don't understand why i have it because i don't touch anything in config, or sql :x

**Comment by DevilishDante** [comment]
Nevermind isn't a issues about luck perm :/

**Comment by lucko** [comment]
First error is fixed already in the latest version.

The second isn't a LP error. :)

**Comment by DevilishDante** [comment]
@lucko thanks you :o
