### ISSUE TITLE
WorldEdit and LuckPerms doesnt work together on my server

### ISSUE THREAD

**Issue by Vecarn** [lucko/LuckPerms#1502]
So, I know there is another closed case of this, but none of the solutions worked on my server.
Facts first:

I installed these Mods on my Server (Spigot 1.13.2):
Dynmap 3.0
EssentialsX 2.16.1.125
EssentialsXChat
LuckPerms 4.4.1
Vault
WorldEdit 6.1.9

I set the ''no-op-permissions: true'' in the WorldEdit Config.

WorldEdit doesn't show up in the lp tree, but when I type in /plugins it's shown as installed.
And I certainly do not know how to re-add them there or something.

I tried to understand how /lp verbose works, but honestly I guess my english is just too bad for the explanations on the internet. (I'm german)
I tried to figure my problem out, but I just can't find anything that helps.
I tried rebuilding the server with every plugin newly, but it didn't change anything.

Maybe someone here is able to help me? :/

**Comment by electronicboy** [comment]
Worldedit doesn't define permissions in its plugin.yml file, meaning that LP won't know about any permissions that worldedit uses until WE actually does a permission lookup, I'd suggest referring to the documentation: http://wiki.sk89q.com/wiki/WorldEdit/Permissions

**Comment by BrainStone** [comment]
Well, just add the permissions to the appropriate groups. They are very well documented on the WE docs.

And as a little explanation, `/lp tree` shows all permissions that have been checked since the server is running. If a plugin isn’t showing up there that doesn’t mean it’s not working. It just means no permissions of it have been checked so far.

And if you’re struggling with English, try https://deepl.com

**Comment by Vecarn** [comment]
> Worldedit doesn't define permissions in its plugin.yml file, meaning that LP won't know about any permissions that worldedit uses until WE actually does a permission lookup, I'd suggest referring to the documentation: http://wiki.sk89q.com/wiki/WorldEdit/Permissions

That helped, thank you!

**Comment by Vecarn** [comment]
> Well, just add the permissions to the appropriate groups. They are very well documented on the WE docs.
> 
> And as a little explanation, `/lp tree` shows all permissions that have been checked since the server is running. If a plugin isn’t showing up there that doesn’t mean it’s not working. It just means no permissions of it have been checked so far.
> 
> And if you’re struggling with English, try https://deepl.com

Ahh, thank you for the explanation!

**Comment by Reyoking** [comment]
Try:
Change world edit setting config.yml:
    allow-symbolic-links: true

**Comment by Foling-sky** [comment]
Здравствуйте, у меня ворлд эдит вообще не хочет работать с ворлд гуард, уже сколько всего переустановил, ворлд эдит конфликтует, с лаки пермс и не может из-за этого запустить ворлд гуард

**Comment by Foling-sky** [comment]
`[21:04:24] [Server thread/ERROR]: Could not dispatch event: com.sk89q.worldedit.event.platform.PlatformReadyEvent@34afd85b to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupWorldData(WorldEditPlugin.java:194) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.access$100(WorldEditPlugin.java:98) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin$WorldInitListener.onWorldInit(WorldEditPlugin.java:515) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:629) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:596) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:263) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1007) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        ... 20 more
Caused by: java.lang.NoSuchMethodError: 'com.sk89q.worldedit.world.registry.BlockMaterial com.sk89q.worldedit.world.block.BlockState.getMaterial()'
        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_18_R2.PaperweightFaweAdapter.getInternalBlockStateId(PaperweightFaweAdapter.java:376) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitBlockRegistry.getInternalBlockStateId(BukkitBlockRegistry.java:69) ~[?:?]
        at com.sk89q.worldedit.extension.platform.Capability$4.initialize(Capability.java:94) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformManager.choosePreferred(PlatformManager.java:187) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlatformReady(PlatformManager.java:300) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        ... 20 more`
        
        `[21:04:58] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v7.0.7+216b061
[21:04:58] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[21:04:58] [Server thread/WARN]: [LuckPerms] Loaded class org.enginehub.piston.exception.CommandException from WorldEdit v7.2.5+57d5ac9 which is not a depend or softdepend of this plugin.
[21:04:59] [Server thread/ERROR]: Error occurred while enabling WorldGuard v7.0.7+216b061 (Is it up to date?)
java.lang.LinkageError: loader constraint violation in interface itable initialization for class com.sk89q.worldedit.command.argument.AbstractDirectionConverter: when selecting method 'com.sk89q.worldedit.util.formatting.text.Component org.enginehub.piston.converter.ArgumentConverter.describeAcceptableArguments()' the class loader org.bukkit.plugin.java.PluginClassLoader @1dc7412 for super interface org.enginehub.piston.converter.ArgumentConverter, and the class loader org.bukkit.plugin.java.PluginClassLoader @5524ceec of the selected method's abstract class, com.sk89q.worldedit.command.argument.AbstractDirectionConverter have different Class objects for the type com.sk89q.worldedit.util.formatting.text.Component used in the signature (org.enginehub.piston.converter.ArgumentConverter is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @1dc7412, parent loader java.net.URLClassLoader @722c41f4; com.sk89q.worldedit.command.argument.AbstractDirectionConverter is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @5524ceec, parent loader java.net.URLClassLoader @722c41f4)
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.registerArgumentConverters(PlatformCommandManager.java:250) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.initialize(PlatformCommandManager.java:245) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.<init>(PlatformCommandManager.java:233) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformManager.<init>(PlatformManager.java:93) ~[?:?]
        at com.sk89q.worldedit.WorldEdit.<init>(WorldEdit.java:125) ~[?:?]
        at com.sk89q.worldedit.WorldEdit.<clinit>(WorldEdit.java:121) ~[?:?]
        at com.sk89q.worldguard.bukkit.BukkitConfigurationManager.postLoad(BukkitConfigurationManager.java:82) ~[?:?]
        at com.sk89q.worldguard.config.YamlConfigurationManager.load(YamlConfigurationManager.java:113) ~[?:?]
        at com.sk89q.worldguard.bukkit.BukkitConfigurationManager.load(BukkitConfigurationManager.java:58) ~[?:?]
        at com.sk89q.worldguard.bukkit.BukkitWorldGuardPlatform.load(BukkitWorldGuardPlatform.java:140) ~[?:?]
        at com.sk89q.worldguard.WorldGuard.setup(WorldGuard.java:91) ~[?:?]
        at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onEnable(WorldGuardPlugin.java:150) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:518) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:432) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:263) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1007) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[21:04:59] [Server thread/INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.3.12
[21:04:59] [Server thread/WARN]: [Multiverse-Core] "Multiverse-Core v4.3.12" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].
[21:04:59] [Server thread/INFO]: [Multiverse-Core] §aWe are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
[21:04:59] [Server thread/WARN]: [Multiverse-Core] WorldManager: Can't load this world because the folder was deleted/moved: nether`
