### ISSUE TITLE
Cannot load LuckPerms API for BungeeCord Plugin

### ISSUE THREAD

**Issue by BomBardyGamer** [lucko/LuckPerms#1517]
I keep getting this error: java.lang.IllegalStateException: API is not loaded. every time I try to run a command in my plugin.
My plugin gets the API from the LuckPerms.getApi() static method and uses it from there, but it does not load apparently...?

**Comment by BrainStone** [comment]
Make sure you’re depending on LP in your plugin/bungee.yml. Also don’t try to access before your `onEnable`

**Comment by ptrcnull** [comment]
Sorry for bumping such an old issue, but I have the same problem.
LuckPerms is added to `depend`:
```yaml
name: ChatManager
version: ${project.version}
author: ptrcnull
main: me.ptrcnull.chatmanager.ChatManager
depend: [LuckPerms]
```
and I'm getting the API instance in `onEnable`:
```java
    @Override
    public void onEnable() {
        LuckPerms luckPerms = LuckPermsProvider.get();

        getProxy().getPluginManager().registerListener(this, this);
    }
```
Somehow, it still doesn't work and throws the `IllegalStateException`:
```
java.lang.IllegalStateException: The LuckPerms API is not loaded.
	at net.luckperms.api.LuckPermsProvider.get(LuckPermsProvider.java:50) ~[?:?]
	at me.ptrcnull.chatmanager.ChatManager.onEnable(ChatManager.java:32) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:285) ~[waterfall-323.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:282) ~[waterfall-323.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[waterfall-323.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-323.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
```
