### ISSUE TITLE
Could not load plugins - Thermos-1.7.10-1614-server

### ISSUE THREAD

**Issue by Westus** [lucko/LuckPerms#153]
`[01:54:09] [main/INFO] [FML/]: Forge Mod Loader version 7.99.4.1614 for Minecraft 1.7.10 loading
[01:54:10] [main/INFO] [FML/]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_121, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_121
[01:54:10] [main/INFO] [STDERR/]: [pw.prok.imagine.ImagineLoadingPlugin:<clinit>:26]: Loading plugin initialized!
[01:54:10] [main/INFO] [LaunchWrapper/]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[01:54:10] [main/INFO] [LaunchWrapper/]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[01:54:10] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[01:54:10] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[01:54:10] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[01:54:11] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[01:54:11] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[01:54:12] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[01:54:12] [main/INFO] [LaunchWrapper/]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[01:54:12] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[01:54:13] [main/INFO] [LaunchWrapper/]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[01:54:18] [Server thread/INFO] [MinecraftForge/]: Attempting early MinecraftForge initialization
[01:54:18] [Server thread/INFO] [FML/]: MinecraftForge v10.13.4.1614 Initialized
[01:54:18] [Server thread/INFO] [FML/]: Replaced 184 ore recipies
[01:54:18] [Server thread/INFO] [MinecraftForge/]: Completed early MinecraftForge initialization
[01:54:18] [Server thread/INFO] [FML/]: Found 0 mods from the command line. Injecting into mod discoverer
[01:54:18] [Server thread/INFO] [FML/]: Searching D:\Temp\VanillaServer-1710\mods for mods
[01:54:19] [Server thread/INFO] [FML/]: Forge Mod Loader has identified 4 mods to load
[01:54:19] [Server thread/INFO] [FML/FML]: Attempting connection with missing mods [mcp, FML, Forge, kimagine] at CLIENT
[01:54:19] [Server thread/INFO] [FML/FML]: Attempting connection with missing mods [mcp, FML, Forge, kimagine] at SERVER
[01:54:19] [Server thread/INFO] [FML/]: Processing ObjectHolder annotations
[01:54:20] [Server thread/INFO] [FML/]: Found 341 ObjectHolder annotations
[01:54:20] [Server thread/INFO] [FML/]: Identifying ItemStackHolder annotations
[01:54:20] [Server thread/INFO] [FML/]: Found 0 ItemStackHolder annotations
[01:54:20] [Server thread/INFO] [FML/Forge]: Configured a dormant chunk cache size of 0
[01:54:20] [Server thread/INFO] [FML/]: Applying holder lookups
[01:54:20] [Server thread/INFO] [FML/]: Holder lookups applied
[01:54:20] [Server thread/INFO] [FML/]: Injecting itemstacks
[01:54:20] [Server thread/INFO] [FML/]: Itemstack injection complete
[01:54:20] [Server thread/INFO] [Minecraft/]: This server is running Cauldron version 1.7.10-1614.58 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
[01:54:20] [Server thread/INFO] [Minecraft/]: Using 4 threads for Netty based IO
[01:54:20] [Server thread/INFO] [/]: Server Ping Player Sample Count: 12
[01:54:20] [Server thread/INFO] [FML/]: Injecting itemstacks
[01:54:20] [Server thread/INFO] [FML/]: Itemstack injection complete
[01:54:21] [Server thread/INFO] [FML/]: Forge Mod Loader has successfully loaded 4 mods
[01:54:21] [Server thread/INFO] [FML/]: Injecting existing block and item data into this server instance
[01:54:21] [Server thread/INFO] [FML/]: Applying holder lookups
[01:54:21] [Server thread/INFO] [FML/]: Holder lookups applied
[01:54:21] [Server thread/INFO] [/]: Mapping loaded 11 packages, 7841 classes, 26711 fields, 53884 methods, flags 1ffa
[01:54:21] [Server thread/INFO] [/]: Loaded inheritance map of 895 classes
[01:54:22] [Server thread/ERROR] [Minecraft/]: Could not load 'plugins\LuckPerms-Bukkit-Legacy-2.17.37.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `me.lucko.luckperms.bukkit.LPBukkitPlugin'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:191) ~[PluginClassLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[JavaPluginLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:343) [CraftServer.class:1.7.10-1614.58]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:374) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: Failed to remap class me.lucko.luckperms.bukkit.LPBukkitPlugin
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:534) ~[PluginClassLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:455) ~[PluginClassLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.58]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:189) ~[PluginClassLoader.class:1.7.10-1614.58]
	... 12 more
Caused by: java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
	at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:246) ~[JarRemapper.class:?]
	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:232) ~[JarRemapper.class:?]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:499) ~[PluginClassLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:455) ~[PluginClassLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.58]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:189) ~[PluginClassLoader.class:1.7.10-1614.58]
	... 12 more
[01:54:22] [Server thread/INFO] [FML/]: Loading dimension 0 (world) (net.minecraft.server.dedicated.DedicatedServer@2393d819)
[01:54:22] [Server thread/INFO] [FML/]: Loading dimension 1 (DIM1) (net.minecraft.server.dedicated.DedicatedServer@2393d819)
[01:54:22] [Server thread/INFO] [FML/]: Loading dimension -1 (DIM-1) (net.minecraft.server.dedicated.DedicatedServer@2393d819)
[01:54:24] [Server thread/INFO] [Minecraft/]: Server permissions file permissions.yml is empty, ignoring it
[01:54:24] [Server thread/INFO] [/]: Hey, you don't have a server icon! Try out one of Thermos' Icon Generators at https://github.com/CyberdyneCC/ThermosIconGenerators !
[01:54:54] [Server thread/INFO] [/]: CONSOLE: Stopping the server..
[01:54:54] [Server thread/INFO] [FML/]: Unloading dimension 0
[01:54:54] [Server thread/INFO] [FML/]: Unloading dimension -1
[01:54:54] [Server thread/INFO] [FML/]: Unloading dimension 1
[01:54:54] [Server thread/INFO] [FML/]: Applying holder lookups
[01:54:54] [Server thread/INFO] [FML/]: Holder lookups applied`

**Comment by lucko** [comment]
Related to CyberdyneCC/Thermos#498

The fix is detailed in this comment: https://github.com/CyberdyneCC/Thermos/issues/498#issuecomment-247083549
