### ISSUE TITLE
Failed to init Storage dao (Requested to be added)

### ISSUE THREAD

**Issue by triggmysta** [lucko/LuckPerms#1536]
I have already had a discussion with the Staff Member on the Luckperms discord server. I spoke with ImmortalShard and he/she wasn't able to assist with this issue as they have not noticed it before. 

I have reset the config and there are no errors in console. However as soon as I add my details for my database, the below error starts to occur. 

This error is being produced within my Proxy server console. My other servers (game servers) use the spigot version of luckperms and are connected to the database details that I tried putting into the proxy config file. 

On my proxy server I am using the Bungeecord version of luckperms.

Here is the error that I am receiving: 

Either preview it below or look @ this link: https://hastebin.com/sucefesoji.cs

```19.05 00:26:57 [Server] INFO __    
19.05 00:26:57 [Server] INFO |    |__)   LuckPerms v4.4.22
19.05 00:26:57 [Server] INFO |___ |      Running on Bungee - BungeeCord
19.05 00:26:57 [Server] INFO Loading configuration...
19.05 00:26:57 [Server] INFO Loading storage provider... [MYSQL]
19.05 00:26:57 [Server] SEVERE Failed to init storage dao
19.05 00:26:57 [Server] SEVERE java.lang.NullPointerException: database
19.05 00:26:57 [Server] SEVERE at java.util.Objects.requireNonNull(Objects.java:228)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.common.storage.misc.StorageCredentials.getDatabase(StorageCredentials.java:60)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.appendConfigurationInfo(HikariConnectionFactory.java:69)
19.05 00:26:57 [Server] INFO Loading messaging service... [SQL]
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:79)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:167)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.common.storage.Storage.init(Storage.java:110)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:136)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.bungee.LPBungeeBootstrap.onEnable(LPBungeeBootstrap.java:124)
19.05 00:26:57 [Server] SEVERE at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
19.05 00:26:57 [Server] SEVERE at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
19.05 00:26:57 [Server] SEVERE at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
19.05 00:26:57 [Server] SEVERE at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
19.05 00:26:57 [Server] SEVERE java.lang.RuntimeException: java.sql.SQLException: Unable to get a connection from the pool. (hikari is null)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:56)
19.05 00:26:57 [Server] WARNING Messaging service 'sql' not recognised.
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.common.messaging.MessagingFactory$SqlMessengerProvider.obtain(MessagingFactory.java:132)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.common.messaging.LuckPermsMessagingService.<init>(LuckPermsMessagingService.java:72)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.common.messaging.MessagingFactory.getServiceFor(MessagingFactory.java:95)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.bungee.messaging.BungeeMessagingFactory.getServiceFor(BungeeMessagingFactory.java:63)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.common.messaging.MessagingFactory.getInstance(MessagingFactory.java:73)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:137)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.bungee.LPBungeeBootstrap.onEnable(LPBungeeBootstrap.java:124)
19.05 00:26:57 [Server] SEVERE at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
19.05 00:26:57 [Server] SEVERE at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
19.05 00:26:57 [Server] SEVERE at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
19.05 00:26:57 [Server] SEVERE at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
19.05 00:26:57 [Server] SEVERE Caused by: java.sql.SQLException: Unable to get a connection from the pool. (hikari is null)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:129)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.common.messaging.sql.SqlMessenger.getConnection(SqlMessenger.java:84)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.init(AbstractSqlMessenger.java:55)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:54)
19.05 00:26:57 [Server] SEVERE ... 11 more
19.05 00:26:57 [Server] INFO Loading internal permission managers...
19.05 00:26:57 [Server] INFO Performing initial data load...
19.05 00:26:57 [Server] SEVERE java.util.concurrent.CompletionException: java.sql.SQLException: Unable to get a connection from the pool. (hikari is null)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:99)
19.05 00:26:57 [Server] SEVERE at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
19.05 00:26:57 [Server] SEVERE at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
19.05 00:26:57 [Server] SEVERE at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
19.05 00:26:57 [Server] SEVERE at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
19.05 00:26:57 [Server] SEVERE at java.lang.Thread.run(Thread.java:748)
19.05 00:26:57 [Server] SEVERE Caused by: java.sql.SQLException: Unable to get a connection from the pool. (hikari is null)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:129)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:648)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$10(Storage.java:190)
19.05 00:26:57 [Server] SEVERE at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:94)
19.05 00:26:57 [Server] SEVERE ... 5 more
19.05 00:26:57 [Server] INFO Successfully enabled. (took 259ms)
19.05 00:26:57 [Server] INFO Enabled plugin LuckPerms version 4.4.22 by Luck
```

**Comment by BrainStone** [comment]
First of all, please wrap the error log in \`\`\`.

So:
\`\`\`
Error
Error
\`\`\`
Turns into
```
Error
Error
```

In case you haven't tried that yet, try deleting the `libs` (or `lib` 🤔) folder inside the `luckperms` folder.

**Comment by lucko** [comment]
Seems like your configuration file is missing the `database` property.

Make sure the YAML is indented properly.

https://github.com/lucko/LuckPerms/blob/7f4f9bb9174ebd3d2225a814a86f9b717843207f/bukkit/src/main/resources/config.yml#L100-L102
