### ISSUE TITLE
Could not pass FMLPreInitializationEvent

### ISSUE THREAD

**Issue by M3TTA** [lucko/LuckPerms#1545]
i just started my server and this happened

    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-366290f8
    Sponge: 1.12.2-7.1.5
    SpongeForge: 1.12.2-2768-7.1.5
    Minecraft Forge: 14.23.5.2768
    LuckPerms: 4.3.75
`[14:44:58] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]:         __    
[14:44:58] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]:   |    |__)   LuckPerms v4.3.75
[14:44:58] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]:   |___ |      Running on Sponge - SpongeForge
[14:44:58] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: 
[14:44:58] [Server thread/INFO] [luckperms]: Loading configuration...
[14:44:58] [Server thread/ERROR] [Sponge]: Could not pass FMLPreInitializationEvent to Plugin{id=luckperms, name=LuckPerms, version=4.3.75, description=A permissions plugin, url=https://luckperms.github.io, authors=[Luck], source=C:\Users\Alisia\Desktop\mega\minecrap\pixelmon\.\mods\plugins\LuckPerms-Sponge-4.3.75.jar}
java.lang.RuntimeException: java.io.IOException: me.lucko.luckperms.lib.hocon.ConfigException$Parse: Reader: 561: Expecting a value but got wrong token: '}' (if you intended '}' to be part of a key or string value, try enclosing the key or value in double quotes)
	at me.lucko.luckperms.common.config.adapter.ConfigurateConfigAdapter.reload(ConfigurateConfigAdapter.java:61) ~[ConfigurateConfigAdapter.class:?]
	at me.lucko.luckperms.common.config.adapter.ConfigurateConfigAdapter.<init>(ConfigurateConfigAdapter.java:50) ~[ConfigurateConfigAdapter.class:?]
	at me.lucko.luckperms.sponge.SpongeConfigAdapter.<init>(SpongeConfigAdapter.java:40) ~[SpongeConfigAdapter.class:?]
	at me.lucko.luckperms.sponge.LPSpongePlugin.provideConfigurationAdapter(LPSpongePlugin.java:122) ~[LPSpongePlugin.class:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:107) ~[AbstractLuckPermsPlugin.class:?]
	at me.lucko.luckperms.sponge.LPSpongeBootstrap.onEnable(LPSpongeBootstrap.java:174) ~[LPSpongeBootstrap.class:?]
	at org.spongepowered.common.event.listener.GamePreInitializationEventListener_LPSpongeBootstrap_onEnable3.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2768-7.1.5]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:248) [SpongeImpl.class:1.12.2-2768-7.1.5]
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:283) [SpongeMod.class:1.12.2-2768-7.1.5]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.io.IOException: me.lucko.luckperms.lib.hocon.ConfigException$Parse: Reader: 561: Expecting a value but got wrong token: '}' (if you intended '}' to be part of a key or string value, try enclosing the key or value in double quotes)
	at me.lucko.luckperms.lib.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:145) ~[AbstractConfigurationLoader.class:?]
	at me.lucko.luckperms.lib.configurate.loader.ConfigurationLoader.load(ConfigurationLoader.java:58) ~[ConfigurationLoader.class:?]
	at me.lucko.luckperms.common.config.adapter.ConfigurateConfigAdapter.reload(ConfigurateConfigAdapter.java:59) ~[ConfigurateConfigAdapter.class:?]
	... 44 more
Caused by: me.lucko.luckperms.lib.hocon.ConfigException$Parse: Reader: 561: Expecting a value but got wrong token: '}' (if you intended '}' to be part of a key or string value, try enclosing the key or value in double quotes)
	at me.lucko.luckperms.lib.hocon.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201) ~[ConfigDocumentParser$ParseContext.class:1.3.3]
	at me.lucko.luckperms.lib.hocon.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197) ~[ConfigDocumentParser$ParseContext.class:1.3.3]
	at me.lucko.luckperms.lib.hocon.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:251) ~[ConfigDocumentParser$ParseContext.class:1.3.3]
	at me.lucko.luckperms.lib.hocon.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:475) ~[ConfigDocumentParser$ParseContext.class:1.3.3]
	at me.lucko.luckperms.lib.hocon.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:247) ~[ConfigDocumentParser$ParseContext.class:1.3.3]
	at me.lucko.luckperms.lib.hocon.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:458) ~[ConfigDocumentParser$ParseContext.class:1.3.3]
	at me.lucko.luckperms.lib.hocon.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:648) ~[ConfigDocumentParser$ParseContext.class:1.3.3]
	at me.lucko.luckperms.lib.hocon.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14) ~[ConfigDocumentParser.class:1.3.3]
	at me.lucko.luckperms.lib.hocon.impl.Parseable.rawParseValue(Parseable.java:260) ~[Parseable.class:1.3.3]
	at me.lucko.luckperms.lib.hocon.impl.Parseable.rawParseValue(Parseable.java:248) ~[Parseable.class:1.3.3]
	at me.lucko.luckperms.lib.hocon.impl.Parseable.parseValue(Parseable.java:180) ~[Parseable.class:1.3.3]
	at me.lucko.luckperms.lib.hocon.impl.Parseable.parseValue(Parseable.java:174) ~[Parseable.class:1.3.3]
	at me.lucko.luckperms.lib.hocon.impl.Parseable.parse(Parseable.java:299) ~[Parseable.class:1.3.3]
	at me.lucko.luckperms.lib.hocon.ConfigFactory.parseReader(ConfigFactory.java:623) ~[ConfigFactory.class:1.3.3]
	at me.lucko.luckperms.lib.configurate.hocon.HoconConfigurationLoader.loadInternal(HoconConfigurationLoader.java:174) ~[HoconConfigurationLoader.class:?]
	at me.lucko.luckperms.lib.configurate.hocon.HoconConfigurationLoader.loadInternal(HoconConfigurationLoader.java:55) ~[HoconConfigurationLoader.class:?]
	at me.lucko.luckperms.lib.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:136) ~[AbstractConfigurationLoader.class:?]
	at me.lucko.luckperms.lib.configurate.loader.ConfigurationLoader.load(ConfigurationLoader.java:58) ~[ConfigurationLoader.class:?]
	at me.lucko.luckperms.common.config.adapter.ConfigurateConfigAdapter.reload(ConfigurateConfigAdapter.java:59) ~[ConfigurateConfigAdapter.class:?]
	... 44 more`

**Comment by Turbotailz** [comment]
Try updating your version of LuckPerms, your version is very old.

**Comment by M3TTA** [comment]
> Try updating your version of LuckPerms, your version is very old.

updated to 4.4.24 still doesnt work

**Comment by BrainStone** [comment]
Your config is broken. Says so clearly in the error.
