### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by ludvdber** [lucko/LuckPerms#1586]
Hello, I have this in my console:
```
[11:27:55] [Server thread/INFO]: gilles666 issued server command: /lp editor
[11:29:28] [Server thread/INFO]: gilles666 issued server command: /lp applyedits Z464bGSydH
[11:29:28] [luckperms-worker-0/INFO]: [LuckPerms] [Messaging] Sending log with id: 7661b018-c52b-4311-921d-b3310b5bb53d
[11:29:28] [pool-13-thread-1/INFO]: [LP] LOG > (gilles666@survie) [G] (admin)
[11:29:28] [pool-13-thread-1/INFO]: [LP] LOG > webeditor remove suffix.91.☆ true
[11:29:28] [luckperms-worker-0/WARN]: java.sql.SQLException: Incorrect string value: '\xE2\x98\x86 tr...' for column 'msg' at row 1
[11:29:28] [luckperms-worker-0/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[11:29:28] [luckperms-worker-0/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[11:29:28] [luckperms-worker-0/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[11:29:28] [luckperms-worker-0/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[11:29:28] [luckperms-worker-0/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1288)
[11:29:28] [luckperms-worker-0/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:788)
[11:29:28] [luckperms-worker-0/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1242)
[11:29:28] [luckperms-worker-0/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[11:29:28] [luckperms-worker-0/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[11:29:28] [luckperms-worker-0/WARN]: 	at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.sendOutgoingMessage(AbstractSqlMessenger.java:76)
[11:29:28] [luckperms-worker-0/WARN]: 	at me.lucko.luckperms.common.messaging.LuckPermsMessagingService.lambda$pushLog$2(LuckPermsMessagingService.java:138)
[11:29:28] [luckperms-worker-0/WARN]: 	at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$ErrorReportingRunnable.run(AbstractJavaScheduler.java:106)
[11:29:28] [luckperms-worker-0/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[11:29:28] [luckperms-worker-0/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[11:29:28] [luckperms-worker-0/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:835)
[11:29:30] [luckperms-worker-0/INFO]: [LuckPerms] [Messaging] Sending ping with id: 1951cd76-f904-4576-84a7-c2526c527d28
```

Paper version git-Paper-94 (MC: 1.14.2) 
LuckPerms-Bukkit-4.4.26

**Comment by lucko** [comment]
Seems like your MySQL server isn't accepting UTF-8 characters.

Might need to change the encoding on the table to `utf8mb4`.

The error isn't being caused by LP, so not much more I can do - sorry!
