### ISSUE TITLE
AsyncPlayerPreLoginEvent error with legacy version and online-mode=true

### ISSUE THREAD

**Issue by uiytt** [lucko/LuckPerms#1612]
So yeah, i'm in 1.7.10 with thermos (not the best for luckperm :/) 
My server is premium only (online-mode=true)
I have LuckPerms-Bukkit-Legacy-4.4.26
Following the LuckPerm wiki I have modified the librairies 

But when I try to log in, I have this error : 
```
[06:51:25 ERROR]: [LuckPerms] Exception occurred whilst loading data for 75810fec-d049-4fb2-ab95-8a485a73ba94 - uiytt
[06:51:25 WARN]: java.util.concurrent.CompletionException: java.lang.NullPointerException
[06:51:25 WARN]:        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
[06:51:25 WARN]:        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
[06:51:25 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
[06:51:25 WARN]:        at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$ErrorReportingRunnable.run(AbstractJavaScheduler.java:106)
[06:51:25 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[06:51:25 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[06:51:25 WARN]:        at java.lang.Thread.run(Thread.java:748)
[06:51:25 WARN]: Caused by: java.lang.NullPointerException
[06:51:25 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$savePlayerData$20(Storage.java:256)
[06:51:25 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:81)
[06:51:25 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[06:51:25 WARN]:        ... 4 more
[06:51:25 ERROR]: Could not pass event AsyncPlayerPreLoginEvent to LuckPerms v4.4.26
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.57]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.57]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:489) [SimplePluginManager.class:1.7.10-1614.57]
        at net.minecraft.server.network.ThreadPlayerLookupUUID.fireLoginEvents(ThreadPlayerLookupUUID.java:99) [ThreadPlayerLookupUUID.class:?]
        at net.minecraft.server.network.ThreadPlayerLookupUUID.run(ThreadPlayerLookupUUID.java:48) [ThreadPlayerLookupUUID.class:?]
Caused by: java.lang.NullPointerException
        at me.lucko.luckperms.bukkit.listeners.BukkitConnectionListener.onPlayerPreLogin(BukkitConnectionListener.java:118) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
        ... 5 more
[06:51:25 INFO]: Disconnecting com.mojang.authlib.GameProfile@70980026[id=75810fec-d049-4fb2-ab95-8a485a73ba94,name=uiytt,properties={textures=[com.mojang.authlib.properties.Property@874c396]},legacy=false] (/82.224.188.32:10739): §7§l[§b§lL§3§lP§7§l] §cA database error occurred whilst loading permissions data. Please try again later
```

Can you help me please ?

**Comment by Imortalshard** [comment]
Hi Uiytt,

Please have a read of this link, it may help with resolving the issue.

https://github.com/lucko/LuckPerms/wiki/Installation#cauldron-thermos-etc

Thanks,
Imortalshard

**Comment by uiytt** [comment]
@Imortalshard already done before ^^ : 

> Following the LuckPerm wiki I have modified the librairies
By that I mean that I change the file  libraries/net/md-5/SpecialSource/1.7-SNAPSHOT

**Comment by lucko** [comment]
Can you send your full server startup log please.

**Comment by uiytt** [comment]
[latest.log](https://github.com/lucko/LuckPerms/files/3398332/latest.log)

**Comment by uiytt** [comment]
Any idea ?

**Comment by lucko** [comment]
```
[19:24:04] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[19:24:04] [Server thread/ERROR]: Error occurred while enabling LuckPerms v4.4.26 (Is it up to date?)
java.lang.NoSuchMethodError: guava10.com.google.common.cache.CacheBuilder.build(Lguava10/com/google/common/cache/CacheLoader;)Lguava10/com/google/common/cache/LoadingCache;
	at me.lucko.luckperms.lib.eventbus.SubscriberRegistry.<clinit>(SubscriberRegistry.java:52) ~[?:?]
	at me.lucko.luckperms.lib.eventbus.SimpleEventBus.<init>(SimpleEventBus.java:43) ~[?:?]
	at me.lucko.luckperms.common.event.AbstractEventBus$Bus.<init>(AbstractEventBus.java:150) ~[?:?]
	at me.lucko.luckperms.common.event.AbstractEventBus.<init>(AbstractEventBus.java:59) ~[?:?]
	at me.lucko.luckperms.bukkit.BukkitEventBus.<init>(BukkitEventBus.java:38) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitPlugin.provideEventBus(LPBukkitPlugin.java:211) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:164) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:153) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.57]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.57]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.57]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.57]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.57]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:463) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:374) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

Seems like you server is doing some sort of legacy remapping.

This is an issue with the server software and not LuckPerms. Sorry, not much I can do. :(
