### ISSUE TITLE
lang.yml parsing error

### ISSUE THREAD

**Issue by RalphORama** [lucko/LuckPerms#1629]
I'm trying to add a `lang.yml` to my server according to [this wiki post](https://github.com/lucko/LuckPerms/wiki/Locale-and-Translations), but when I download and save the [en-US.yaml](https://github.com/LuckPerms/locale/blob/master/en_US.yml) locale file as `lang.yml` on my server, I get the following error:

```
[17:30:50 INFO]: [LuckPerms] Loading configuration...
[17:30:50 INFO]: [LuckPerms] Found lang.yml - loading messages...
[17:30:50 WARN]: while parsing a block mapping
[17:30:50 WARN]:  in 'reader', line 5, column 1:
[17:30:50 WARN]:     prefix: "&7&l[&b&lL&3&lP&7&l] "
[17:30:50 WARN]:     ^
[17:30:50 WARN]: expected <block end>, but found '<scalar>'
[17:30:50 WARN]:  in 'reader', line 33, column 48:
[17:30:50 WARN]:      ... ission: "Unknown command. Type ""/help"" for help."
[17:30:50 WARN]:                                          ^
[17:30:50 WARN]:
[17:30:50 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:572)
[17:30:50 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
[17:30:50 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
[17:30:50 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:214)
[17:30:50 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
[17:30:50 WARN]:        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85)
[17:30:50 WARN]:        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108)
[17:30:50 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139)
[17:30:50 WARN]:        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
[17:30:50 WARN]:        at org.yaml.snakeyaml.Yaml.load(Yaml.java:467)
[17:30:50 WARN]:        at me.lucko.luckperms.common.locale.LocaleManager.loadFromFile(LocaleManager.java:78)
[17:30:50 WARN]:        at me.lucko.luckperms.common.locale.LocaleManager.tryLoad(LocaleManager.java:59)
[17:30:50 WARN]:        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:112)
[17:30:50 WARN]:        at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:153)
[17:30:50 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[17:30:50 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
[17:30:50 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[17:30:50 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
[17:30:50 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
[17:30:50 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:236)
[17:30:50 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
[17:30:50 WARN]:        at java.lang.Thread.run(Unknown Source)
[17:30:51 INFO]: [LuckPerms] Loading storage provider... [H2]
[17:30:51 INFO]: [LuckPerms] Loading internal permission managers...
```

Server info:

- OS: Windows 10 Pro x64
- Java: `java version "1.8.0_211"`
- Paper: `git-Paper-639 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)`

`/lp info` output:

```
> lp info
[17:37:26 INFO]: [LP] Running LuckPerms v4.4.27 by Luck.
[17:37:26 INFO]:  [LP] -  Platform: Bukkit
[17:37:26 INFO]:  [LP] -  Server Brand: Paper
[17:37:26 INFO]:  [LP] -  Server Version:
[17:37:26 INFO]:  [LP] -  git-Paper-639 (MC: 1.13.2) - 1.13.2-R0.1-SNAPSHOT

[17:37:26 INFO]: [LP] -  Storage:
[17:37:26 INFO]:  [LP] -     Type: H2

[17:37:26 INFO]: [LP] -     File Size: 0.03MB
[17:37:26 INFO]: [LP] -  Messaging: None
[17:37:26 INFO]:  [LP] -  Instance:
[17:37:26 INFO]:  [LP] -     Static contexts: None
[17:37:26 INFO]:  [LP] -     Online Players: 0 (0 unique)
[17:37:26 INFO]:  [LP] -     Uptime: 4m 6s
[17:37:26 INFO]:  [LP] -     Local Data: 0 users, 1 groups, 0 tracks
```

**Comment by RalphORama** [comment]
Whoops, didn't realize I didn't read far enough into the error to see it was an issue with one of my customized messages.
