### ISSUE TITLE
Error in set suffix with MariaDB

### ISSUE THREAD

**Issue by JavituRec** [lucko/LuckPerms#1662]
Hi,

I get a error in console with I set a suffix:

`[10:52:46] [pool-14-thread-1/INFO]: [LP] LOG > meta setsuffix 2 ✔ 
[10:52:46] [luckperms-worker-37/WARN]: java.sql.SQLDataException: (conn=61126) Incorrect string value: '\xE2\x9C\x94 "}...' for column `DatabaseServer`.`luckperms_messenger`.`msg` at row 1
[10:52:46] [luckperms-worker-37/WARN]: 	at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:225)
[10:52:46] [luckperms-worker-37/WARN]: 	at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)
[10:52:46] [luckperms-worker-37/WARN]: 	at me.lucko.luckperms.lib.mariadb.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)
[10:52:46] [luckperms-worker-37/WARN]: 	at me.lucko.luckperms.lib.mariadb.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:230)
[10:52:46] [luckperms-worker-37/WARN]: 	at me.lucko.luckperms.lib.mariadb.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:157)
[10:52:46] [luckperms-worker-37/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[10:52:46] [luckperms-worker-37/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[10:52:46] [luckperms-worker-37/WARN]: 	at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.sendOutgoingMessage(AbstractSqlMessenger.java:76)
[10:52:46] [luckperms-worker-37/WARN]: 	at me.lucko.luckperms.common.messaging.LuckPermsMessagingService.lambda$pushLog$2(LuckPermsMessagingService.java:138)
[10:52:46] [luckperms-worker-37/WARN]: 	at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$ErrorReportingRunnable.run(AbstractJavaScheduler.java:106)
[10:52:46] [luckperms-worker-37/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[10:52:46] [luckperms-worker-37/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[10:52:46] [luckperms-worker-37/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[10:52:46] [luckperms-worker-37/WARN]: Caused by: java.sql.SQLException: Incorrect string value: '\xE2\x9C\x94 "}...' for column `DatabaseServer`.`luckperms_messenger`.`msg` at row 1
[10:52:46] [luckperms-worker-37/WARN]: 	at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1594)
[10:52:46] [luckperms-worker-37/WARN]: 	at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1453)
[10:52:46] [luckperms-worker-37/WARN]: 	at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1415)
[10:52:46] [luckperms-worker-37/WARN]: 	at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:288)
[10:52:46] [luckperms-worker-37/WARN]: 	at me.lucko.luckperms.lib.mariadb.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:221)
[10:52:46] [luckperms-worker-37/WARN]: 	... 9 more`

**Comment by Tobi406** [comment]
See #1586
