### ISSUE TITLE
Unable to pass event UserDataRecalculateEvent to handler (Plugin attempted to register task while disabled)

### ISSUE THREAD

**Issue by LoganDark** [lucko/LuckPerms#1691]
```
[15:29:53 WARN]: [LuckPerms] Unable to pass event UserDataRecalculateEvent to handler me.lucko.luckperms.bukkit.LPBukkitPlugin$$Lambda$8229/1460435473
[15:29:53 WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[15:29:53 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:413)
[15:29:53 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:130)
[15:29:53 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:126)
[15:29:53 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:109)
[15:29:53 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:92)
[15:29:53 WARN]: 	at me.lucko.luckperms.bukkit.BukkitSchedulerAdapter.lambda$new$0(BukkitSchedulerAdapter.java:37)
[15:29:53 WARN]: 	at me.lucko.luckperms.common.plugin.scheduler.SchedulerAdapter.executeSync(SchedulerAdapter.java:65)
[15:29:53 WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitPlugin.refreshAutoOp(LPBukkitPlugin.java:345)
[15:29:53 WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitPlugin.lambda$null$1(LPBukkitPlugin.java:269)
[15:29:53 WARN]: 	at java.util.Optional.ifPresent(Optional.java:159)
[15:29:53 WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitPlugin.lambda$performFinalSetup$2(LPBukkitPlugin.java:269)
[15:29:53 WARN]: 	at me.lucko.luckperms.common.event.LuckPermsEventHandler.invoke(LuckPermsEventHandler.java:108)
[15:29:53 WARN]: 	at me.lucko.luckperms.common.event.LuckPermsEventHandler.invoke(LuckPermsEventHandler.java:45)
[15:29:53 WARN]: 	at me.lucko.luckperms.lib.eventbus.SimpleEventBus.post(SimpleEventBus.java:107)
[15:29:53 WARN]: 	at me.lucko.luckperms.common.event.AbstractEventBus.post(AbstractEventBus.java:84)
[15:29:53 WARN]: 	at me.lucko.luckperms.common.event.EventFactory.post(EventFactory.java:112)
[15:29:53 WARN]: 	at me.lucko.luckperms.common.event.EventFactory.lambda$post$0(EventFactory.java:125)
[15:29:53 WARN]: 	at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$ErrorReportingRunnable.run(AbstractJavaScheduler.java:106)
[15:29:53 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[15:29:53 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[15:29:53 WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

after running `stop`. There have been tons and tons of `reload`s while the server was running, if that's relevant, approximately 32 of them... (plugin development, I know)

```
Plugins (18): LuckPerms, FastAsyncWorldEdit, NoRain, PlaceholderAPI, PlugMan, Vault, ItemPort, LaggRemover, ProtocolLib, WorldEdit, Orebfuscator4, FancyMOTD, VaultChatFormatter, SuperVanish, WorldGuard, WorldEditSelectionVisualizer, EditableSign, ExtraContexts
```

The part of the log the error shows up in is here (EditableSign is not my plugin, but it generates another message for every single reload, so that's how I approximated the number of reloads):

```
>stop
[15:29:53 INFO]: Stopping the server
[15:29:53 INFO]: Stopping server
[15:29:53 INFO]: [ExtraContexts] Disabling ExtraContexts v1.0-SNAPSHOT
[15:29:53 INFO]: [EditableSign] Disabling EditableSign v7.0.3
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [EditableSign] EditableSign version 7.0.3 is Disabled
[15:29:53 INFO]: [WESV] Disabling WorldEditSelectionVisualizer v2.0.2
[15:29:53 INFO]: [WorldGuard] Disabling WorldGuard v6.2.2-SNAPSHOT;8eeab68
[15:29:53 INFO]: [WorldGuard] Shutting down executor and waiting for any pending tasks...
[15:29:53 INFO]: [SuperVanish] Disabling SuperVanish v6.1.3
[15:29:53 INFO]: [VaultChatFormatter] Disabling VaultChatFormatter v1.0-SNAPSHOT
[15:29:53 INFO]: [FancyMOTD] Disabling FancyMOTD v1.0
[15:29:53 INFO]: [Orebfuscator4] Disabling Orebfuscator4 v4.4.4
[15:29:53 INFO]: [WorldEdit] Disabling WorldEdit v6.1.9;caf0ad9
[15:29:53 INFO]: [ProtocolLib] Disabling ProtocolLib v4.4.0
[15:29:53 INFO]: [LaggRemover] Disabling LaggRemover v2.0.6
[15:29:53 INFO]: [LaggRemover] LaggRemover has been disabled!
[15:29:53 INFO]: [ItemPort] Disabling ItemPort v1.0
[15:29:53 INFO]: [Vault] Disabling Vault v1.5.6-b49
[15:29:53 INFO]: [PlugMan] Disabling PlugMan v2.1.5
[15:29:53 INFO]: [PlaceholderAPI] Disabling PlaceholderAPI v2.10.3
[15:29:53 INFO]: [NoRain] Disabling NoRain v0.2
[15:29:53 INFO]: [FastAsyncWorldEdit] Disabling FastAsyncWorldEdit v19.07.25-58243b6-1278-22.3.1
[15:29:53 INFO]: [LuckPerms] Disabling LuckPerms v4.4.1
[15:29:53 INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[15:29:53 INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[15:29:53 INFO]: [WorldGuard] (world) Lava fire is blocked.
[15:29:53 INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[15:29:53 INFO]: [WorldGuard] Loaded configuration for world 'world'
[15:29:53 WARN]: [LuckPerms] Unable to pass event UserDataRecalculateEvent to handler me.lucko.luckperms.bukkit.LPBukkitPlugin$$Lambda$8229/1460435473
[15:29:53 WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[15:29:53 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:413)
[15:29:53 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:130)
[15:29:53 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:126)
[15:29:53 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:109)
[15:29:53 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:92)
[15:29:53 WARN]: 	at me.lucko.luckperms.bukkit.BukkitSchedulerAdapter.lambda$new$0(BukkitSchedulerAdapter.java:37)
[15:29:53 WARN]: 	at me.lucko.luckperms.common.plugin.scheduler.SchedulerAdapter.executeSync(SchedulerAdapter.java:65)
[15:29:53 WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitPlugin.refreshAutoOp(LPBukkitPlugin.java:345)
[15:29:53 WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitPlugin.lambda$null$1(LPBukkitPlugin.java:269)
[15:29:53 WARN]: 	at java.util.Optional.ifPresent(Optional.java:159)
[15:29:53 WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitPlugin.lambda$performFinalSetup$2(LPBukkitPlugin.java:269)
[15:29:53 WARN]: 	at me.lucko.luckperms.common.event.LuckPermsEventHandler.invoke(LuckPermsEventHandler.java:108)
[15:29:53 WARN]: 	at me.lucko.luckperms.common.event.LuckPermsEventHandler.invoke(LuckPermsEventHandler.java:45)
[15:29:53 WARN]: 	at me.lucko.luckperms.lib.eventbus.SimpleEventBus.post(SimpleEventBus.java:107)
[15:29:53 WARN]: 	at me.lucko.luckperms.common.event.AbstractEventBus.post(AbstractEventBus.java:84)
[15:29:53 WARN]: 	at me.lucko.luckperms.common.event.EventFactory.post(EventFactory.java:112)
[15:29:53 WARN]: 	at me.lucko.luckperms.common.event.EventFactory.lambda$post$0(EventFactory.java:125)
[15:29:53 WARN]: 	at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$ErrorReportingRunnable.run(AbstractJavaScheduler.java:106)
[15:29:53 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[15:29:53 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[15:29:53 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[15:29:53 INFO]: [LuckPerms] Closing storage...
[15:29:53 INFO]: [LuckPerms] Shutting down internal scheduler...
[15:29:53 INFO]: [LuckPerms] Goodbye!
[15:29:53 INFO]: Saving players
[15:29:53 INFO]: LoganDark lost connection: Server closed
[15:29:54 INFO]: LoganDark left the game
[15:29:54 INFO]: Saving worlds
[15:29:54 INFO]: Saving chunks for level 'world'/overworld
[15:29:54 INFO]: Saving chunks for level 'world_nether'/the_nether
[15:29:54 INFO]: Saving chunks for level 'world_the_end'/the_end
```

The server is in offline mode.

**Comment by Andre601** [comment]
`org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled`

LuckPerms is obviously not enabled. Check console for any errors on startup.
Also **NEVER** reload your server! NEVER!
Always restart it, as errors can happen due to not having plugins disable properly. Spigot even warns about that when you reload and PaperMC requires you to confirm the reload in the first place.

Also, this is everything I can and will help you with since I don't support offline-mode (cracked) servers.

**Comment by LoganDark** [comment]
> LuckPerms is obviously not enabled. Check console for any errors on startup.

LuckPerms tried to run something _after it got disabled by `/stop`._ There was no error on startup. If LP had been disabled the whole time then it wouldn't have done anything, and I wouldn't have been able to set groups and permissions like I had been doing the whole time.

> Also NEVER reload your server! NEVER!
> Always restart it, as errors can happen due to not having plugins disable properly.

Last time I checked, it was the plugin author's job to make sure their plugin unloads properly. LuckPerms is not unloading properly when you run the **stop** command. That's not a reload, it should be supported.

If LuckPerms starts to error if you reload it, then the bug should be fixed so it reloads properly. I understand not supporting LP getting messed up by _other_ plugins reloading improperly, but LP itself should.

I'm aware that /reload is not supported. I'm also aware that restarting the fucking server takes five times longer. Hot swap can only go so far and I don't want to wait that long to see a typo fixed in the help command. That's where reload comes in. Shame on you if you think I care whether or not it's supported, by you or anyone.

> Also, this is everything I can and will help you with since I don't support offline-mode (cracked) servers.

It's a server running on localhost, it isn't even exposed to the Internet. It's for plugin development, not for playing on. I don't really care if you don't want to help, I didn't ask for your help in the first place.

**Comment by Andre601** [comment]
No need to react this rude.
LP in general does work with server reloads just fine.
Also it would be helpful if you could provide more information like LP and server version aswell as server type.

**Comment by LoganDark** [comment]
> No need to react this rude.

You just told me:

- LuckPerms was "obviously not enabled"
- "NEVER reload your server"
- "I don't support offline-mode (cracked) servers."

I think the way you replied to my issue warranted a rude response.

> Also it would be helpful if you could provide more information like LP and server version aswell as server type.

![image](https://user-images.githubusercontent.com/4723091/63207953-4f962700-c083-11e9-8a45-0a0dea854e14.png)

```
>version
[00:09:46 INFO]: This server is running CraftBukkit version git-Spigot-79a30d7-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[00:09:46 INFO]: This is a final build for 1.12.2. Please see https://www.spigotmc.org/ for details about upgrading.
>version luckperms
[00:09:47 INFO]: LuckPerms version 4.4.1
[00:09:47 INFO]: A permissions plugin
[00:09:47 INFO]: Website: https://luckperms.github.io
[00:09:47 INFO]: Author: Luck
```

LP was installed from Spigot Resources.

**Comment by Turbotailz** [comment]
> I think the way you replied to my issue warranted a somewhat rude response

This is just immature behaviour and doesn't get anyone anywhere. 

> `LuckPerms version 4.4.1`

You should probably update to the latest version available from [here](https://luckperms.github.io/) and see if that resolves anything before seeking further support.

**Comment by LoganDark** [comment]
> This is just immature behaviour and doesn't get anyone anywhere.

Well don't be a dick from the start and you won't waste anyone's time.

> You should probably update to the latest version available from here and see if that resolves anything before seeking further support.

I upgraded to the latest version and the issue seems to be solved, thanks!
