### ISSUE TITLE
An error about MYSQL

### ISSUE THREAD

**Issue by TheAberto** [lucko/LuckPerms#1698]
i getting that error:

```[22:43:19] [Thread-474/ERROR]: [LuckPerms] Exception occurred whilst loading data for 3394b57d-e73f-3165-9227-d5977aba6c49 - RUHCU
[22:43:19] [Thread-474/WARN]: java.util.concurrent.CompletionException: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '3394b57d-e73f-3165-9227-d5977aba6c49' for key 'PRIMARY'
[22:43:19] [Thread-474/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:86)
[22:43:19] [Thread-474/WARN]: 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
[22:43:19] [Thread-474/WARN]: 	at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$ErrorReportingRunnable.run(AbstractJavaScheduler.java:106)
[22:43:19] [Thread-474/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[22:43:19] [Thread-474/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[22:43:19] [Thread-474/WARN]: 	at java.lang.Thread.run(Unknown Source)
[22:43:19] [Thread-474/WARN]: Caused by: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '3394b57d-e73f-3165-9227-d5977aba6c49' for key 'PRIMARY'
[22:43:19] [Thread-474/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[22:43:19] [Thread-474/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[22:43:19] [Thread-474/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[22:43:19] [Thread-474/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[22:43:19] [Thread-474/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[22:43:19] [Thread-474/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.Util.getInstance(Util.java:408)
[22:43:19] [Thread-474/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
[22:43:19] [Thread-474/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[22:43:19] [Thread-474/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[22:43:19] [Thread-474/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[22:43:19] [Thread-474/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1288)
[22:43:19] [Thread-474/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:788)
[22:43:19] [Thread-474/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1242)
[22:43:19] [Thread-474/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[22:43:19] [Thread-474/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[22:43:19] [Thread-474/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.savePlayerData(SqlStorage.java:938)
[22:43:19] [Thread-474/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$savePlayerData$20(Storage.java:254)
[22:43:19] [Thread-474/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:81)
[22:43:19] [Thread-474/WARN]: 	... 5 more
```

 i guess resource of error is my MYSQL connection. but i want sure.

**Comment by Andre601** [comment]
I'm (sadly) no mysql expert but from what I can understand does `3394b57d-e73f-3165-9227-d5977aba6c49` have a duplicate entry in the database...
You should try to find this duplicate and delete it.

**Comment by TheAberto** [comment]
how i can? tell basically. i can understand i'm sure

**Comment by DrOreo002** [comment]
> how i can? tell basically. i can understand i'm sure

You can use [DBBrowser](https://sqlitebrowser.org) it has a really good gui. You can basically understand how to by just looking at it

**Comment by TheAberto** [comment]
> > how i can? tell basically. i can understand i'm sure
> 
> You can use [DBBrowser](https://sqlitebrowser.org) it has a really good gui. You can basically understand how to by just looking at it

but i using pool MYSQL

**Comment by lucko** [comment]
Just try reconnecting? That should resolve the issue.
