### ISSUE TITLE
LP Startup Issue - Thermos

### ISSUE THREAD

**Issue by TheNeoTV** [lucko/LuckPerms#1701]
Hey,
i got an issue if i start my Thermos Server with LuckPerms, the issue is :

```quote
java.lang.NoSuchMethodError: guava10.com.google.common.collect.Range.closed(Ljava/lang/Comparable;Ljava/lang/Comparable;)Lguava10/com/google/common/collect/Range;
```

The Log is :

```code
[06:52:45 INFO]: [LuckPerms] Enabling LuckPerms v4.4.1
[06:52:45 INFO]:         __
[06:52:45 INFO]:   |    |__)   LuckPerms v4.4.1
[06:52:45 INFO]:   |___ |      Running on Bukkit - Cauldron
[06:52:45 INFO]:
[06:52:45 INFO]: [LuckPerms] Loading configuration...
[06:52:46 INFO]: [LuckPerms] Successfully downloaded 'mysql_driver-5.1.47.jar' with matching checksum: 5PhASPOSsrN7r0ao1QjkuN2uKG0gnvmVueEYhSAcGSM=
[06:52:46 INFO]: [LuckPerms] Successfully downloaded 'hikari-3.3.1.jar' with matching checksum: SIaA1yzGHOZNpZNoIt903f5ScJrIB3u8CT2cNkaLcy0=
[06:52:46 INFO]: [LuckPerms] Attempting to apply relocations to mysql_driver-5.1.47.jar...
[06:52:46 INFO]: [LuckPerms] Attempting to apply relocations to hikari-3.3.1.jar...
[06:52:46 INFO]: [LuckPerms] Loading storage provider... [MYSQL]
[06:52:48 INFO]: [LuckPerms] Loading messaging service... [SQL]
[06:52:49 ERROR]: Error occurred while enabling LuckPerms v4.4.1 (Is it up to date?)
java.lang.NoSuchMethodError: guava10.com.google.common.collect.Range.closed(Ljava/lang/Comparable;Ljava/lang/Comparable;)Lguava10/com/google/common/collect/Range;
        at me.lucko.luckperms.common.util.Predicates.notInRange(Predicates.java:62) ~[?:?]
        at me.lucko.luckperms.common.commands.generic.permission.PermissionInfo.<init>(PermissionInfo.java:66) ~[?:?]
        at me.lucko.luckperms.common.commands.generic.permission.CommandPermission.<init>(CommandPermission.java:38) ~[?:?]
        at me.lucko.luckperms.common.commands.user.UserMainCommand.<init>(UserMainCommand.java:69) ~[?:?]
        at me.lucko.luckperms.common.command.CommandManager.<init>(CommandManager.java:105) ~[?:?]
        at me.lucko.luckperms.bukkit.BukkitCommandExecutor.<init>(BukkitCommandExecutor.java:49) ~[?:?]
        at me.lucko.luckperms.bukkit.LPBukkitPlugin.registerCommands(LPBukkitPlugin.java:152) ~[?:?]
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:142) ~[?:?]
        at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:153) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.56]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.56]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.56]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.56]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.56]
        at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:463) [ayq.class:?]
        at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
        at net.minecraft.world.World.<init>(World.java:371) [ahb.class:?]
        at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

I changed the SpecialSource because it uses ASM4 so wondering what happend.. Some ideas?

[Server Log File](https://github.com/lucko/LuckPerms/files/3528717/latest.log)

**Comment by RJHaytree** [comment]
Hello, thermos ships with an outdated version of guava, and you need to manually update that library in order to get LP to work. 

```This is how to fix luckperms-legacy not loading with thermos (1.7.10):

1) Navigate to libraries\net\md-5\SpecialSource\1.7-SNAPSHOT folder

2) Delete the SpecialSource-1.7-SNAPSHOT.jar jar file

3) Download SpecialSource v1.7.4 from:
 http://central.maven.org/maven2/net/md-5/SpecialSource/1.7.4/SpecialSource-1.7.4.jar 

4) Copy the jar file to the libraries\net\md-5\SpecialSource\1.7-SNAPSHOT folder

5) Rename the jar file you just copied to SpecialSource-1.7-SNAPSHOT.jar

6) Start up server. If it stops immediately, you have renamed the SpecialSource wrong.
 ```

**Comment by TheNeoTV** [comment]
this not works ...

other solution?

**Comment by BrainStone** [comment]
You are the first person that would not have worked with. So it does work but you were doing it wrong.

You can find the instructions on the wiki too: https://github.com/lucko/LuckPerms/wiki/Installation#cauldron-thermos-etc

And btw, saying it doesn't work is saying precisley nothing.
If it in fact doesn't work you need to provide us with the error you're getting.

**Comment by TheNeoTV** [comment]
```quote
You are the first person that would not have worked with. So it does work but you were doing it wrong.
```
That is wrong please do not tell me what i am doing wrong. I can read and i say it does not work.

**Comment by Andre601** [comment]
Yes, but that fact (which BrainStone stated) that it worked for everyone else so far with Thermos and that you're the first one having issues is a pretty clear indicator that it must be a human error on your end.

**Comment by lucko** [comment]
Sorry, the only advice we have for Thermos users is above.

Thermos itself is super unsupported - you're on your own beyond that I'm afraid.
