### ISSUE TITLE
Problem with legacy verion

### ISSUE THREAD

**Issue by ErriourRU** [lucko/LuckPerms#1710]
When player trying to join on server:
```
[LuckPerms] Exception thrown when setting up permissions for 731e0f95-843a-11e9-8496-525400f0582d - Evge4ka6 - denying login.
[10:45:42] [INFO] [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.IllegalStateException: LPPermissible already injected into player CraftPlayer{name=Evge4ka6}
[10:45:42] [INFO] [java.lang.Throwable$WrappedPrintStream:println:748]:         at me.lucko.luckperms.bukkit.inject.permissible.PermissibleInjector.inject(PermissibleInjector.java:97)
[10:45:42] [INFO] [java.lang.Throwable$WrappedPrintStream:println:748]:         at me.lucko.luckperms.bukkit.listeners.BukkitConnectionListener.onPlayerLogin(BukkitConnectionListener.java:185)
[10:45:42] [INFO] [java.lang.Throwable$WrappedPrintStream:println:748]:         at org.bukkit.plugin.java.JavaPluginLoader_BukkitConnectionListener_onPlayerLogin_PlayerLoginEvent/869936957.invoke(.dynamic)
[10:45:42] [INFO] [java.lang.Throwable$WrappedPrintStream:println:748]:         at org.bukkit.plugin.java.JavaPluginLoader$2.execute(JavaPluginLoader.java:509)
[10:45:42] [INFO] [java.lang.Throwable$WrappedPrintStream:println:748]:         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:68)
[10:45:42] [INFO] [java.lang.Throwable$WrappedPrintStream:println:748]:         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:575)
[10:45:42] [INFO] [java.lang.Throwable$WrappedPrintStream:println:748]:         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:553)
[10:45:42] [INFO] [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.management.ServerConfigurationManager.attemptLogin(ServerConfigurationManager.java:1123)
[10:45:42] [INFO] [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:91)
[10:45:42] [INFO] [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.network.NetHandlerLoginServer.func_147233_a(NetHandlerLoginServer.java:65)
[10:45:42] [INFO] [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228)
[10:45:42] [INFO] [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:147)
[10:45:42] [INFO] [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:637)
[10:45:42] [INFO] [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:307)
[10:45:42] [INFO] [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:519)
[10:45:42] [INFO] [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:419)
[10:45:42] [INFO] [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:660)
```

LP version: v4.4.26

**Comment by lucko** [comment]
Possibly duplicate login events?

Does it happen for every login? What other plugins do you have installed - does it happen with just LuckPerms there?
