### ISSUE TITLE
Error while loading on bungeecord

### ISSUE THREAD

**Issue by Nosiows** [lucko/LuckPerms#1719]
21:21:26 [AVERTISSEMENT] Error enabling plugin LuckPerms
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$100(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:34)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:324)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:232)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:266)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 18 more

**Comment by Tobi406** [comment]
Use the BungeeCord version from https://luckperms.github.io

**Comment by Andre601** [comment]
You have to use the BungeeCord version of LuckPerms. Follow the link Tobi posted
