### ISSUE TITLE
Luck perms MYSQL Error

### ISSUE THREAD

**Issue by xWIXx** [lucko/LuckPerms#1728]
I git this error:
"[18:07:53 WARN]: java.lang.RuntimeException: Processor me.lucko.luckperms.common.cache.BufferedRequest$$Lambda$258/1161176014@44aec409 threw an exception whilst computing a result
[18:07:53 WARN]:        at me.lucko.luckperms.common.cache.BufferedRequest$Processor$BoundTask.run(BufferedRequest.java:172)
[18:07:53 WARN]:        at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$ErrorReportingRunnable.run(AbstractJavaScheduler.java:106)
[18:07:53 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[18:07:53 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[18:07:53 WARN]:        at java.lang.Thread.run(Unknown Source)
[18:07:53 WARN]: Caused by: java.util.concurrent.CompletionException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5001ms.
[18:07:53 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:99)
[18:07:53 WARN]:        at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
[18:07:53 WARN]:        ... 4 more
[18:07:53 WARN]: Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5001ms.
[18:07:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[18:07:53 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:131)
[18:07:53 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:646)
[18:07:53 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$10(Storage.java:190)
[18:07:53 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:94)
[18:07:53 WARN]:        ... 5 more
[18:07:53 WARN]: Caused by: me.lucko.luckperms.lib.hikari.pool.PoolBase$ConnectionSetupException: java.sql.SQLException: Access denied for user 'pizza'@'localhost' (using password: YES)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:501)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:727)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:713)
[18:07:53 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[18:07:53 WARN]:        ... 3 more
[18:07:53 WARN]: Caused by: java.sql.SQLException: Access denied for user 'pizza'@'localhost' (using password: YES)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2230)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2025)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[18:07:53 WARN]:        at sun.reflect.GeneratedConstructorAccessor71.newInstance(Unknown Source)
[18:07:53 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[18:07:53 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
[18:07:53 WARN]:        ... 7 more
[18:07:53 WARN]: java.util.concurrent.CompletionException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5001ms.
[18:07:53 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:99)
[18:07:53 WARN]:        at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
[18:07:53 WARN]:        at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$ErrorReportingRunnable.run(AbstractJavaScheduler.java:106)
[18:07:53 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[18:07:53 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[18:07:53 WARN]:        at java.lang.Thread.run(Unknown Source)
[18:07:53 WARN]: Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5001ms.
[18:07:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[18:07:53 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:131)
[18:07:53 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:646)
[18:07:53 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$10(Storage.java:190)
[18:07:53 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:94)
[18:07:53 WARN]:        ... 5 more
[18:07:53 WARN]: Caused by: me.lucko.luckperms.lib.hikari.pool.PoolBase$ConnectionSetupException: java.sql.SQLException: Access denied for user 'pizza'@'localhost' (using password: YES)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:501)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:727)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:713)
[18:07:53 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[18:07:53 WARN]:        ... 3 more
[18:07:53 WARN]: Caused by: java.sql.SQLException: Access denied for user 'pizza'@'localhost' (using password: YES)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2230)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2025)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[18:07:53 WARN]:        at sun.reflect.GeneratedConstructorAccessor71.newInstance(Unknown Source)
[18:07:53 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[18:07:53 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
[18:07:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
[18:07:53 WARN]:        ... 7 more"
Please help

**Comment by Tobi406** [comment]
```
[18:07:53 WARN]: Caused by: java.sql.SQLException: Access denied for user 'pizza'@'localhost' (using password: YES)
```
Make sure you used the right password and that the user has access rights to the database
