### ISSUE TITLE
MYSQL Error please help!!!

### ISSUE THREAD

**Issue by xWIXx** [lucko/LuckPerms#1729]
I got this error:
"[20:15:29 INFO]: [LuckPerms] Loading configuration...
[20:15:29 INFO]: [LuckPerms] Loading storage provider... [MYSQL]
[20:15:34 ERROR]: [LuckPerms] Failed to init storage dao
[20:15:34 WARN]: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5001ms.
[20:15:34 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[20:15:34 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:131)
[20:15:34 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.tableExists(SqlStorage.java:153)
[20:15:34 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:170)
[20:15:34 WARN]:        at me.lucko.luckperms.common.storage.Storage.init(Storage.java:110)
[20:15:34 WARN]:        at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88)
[20:15:34 WARN]:        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:136)
[20:15:34 WARN]:        at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:153)
[20:15:34 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[20:15:34 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[20:15:34 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[20:15:34 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[20:15:34 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[20:15:34 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199)
[20:15:34 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[20:15:34 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:15:34 WARN]: Caused by: me.lucko.luckperms.lib.hikari.pool.PoolBase$ConnectionSetupException: java.sql.SQLException: Access denied for user 'pizza'@'localhost' (using password: YES)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:501)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:727)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:713)
[20:15:34 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[20:15:34 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:15:34 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:15:34 WARN]:        ... 1 more
[20:15:34 WARN]: Caused by: java.sql.SQLException: Access denied for user 'pizza'@'localhost' (using password: YES)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2230)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2025)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[20:15:34 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:15:34 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[20:15:34 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[20:15:34 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
[20:15:34 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
[20:15:34 WARN]:        ... 7 more
[20:15:34 INFO]: [LuckPerms] Loading messaging service... [SQL]
[20:15:39 WARN]: java.lang.RuntimeException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5001ms."

PLEASE HELP ME!!!!!

**Comment by Andre601** [comment]
Check your [login cridentials](https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#luckperms-cannot-connect-to-my-mysql-server)
