### ISSUE TITLE
getting error after new update

### ISSUE THREAD

**Issue by Heroynas** [lucko/LuckPerms#1731]
spigot 1.14.4

[21:46:52] [Server thread/INFO]: Heroynas issued server command: /lp user Heroynas group set owner
[21:46:52] [luckperms-worker-4/WARN]: [LuckPerms] Unable to pass event NodeAddEvent to handler us.donut.skuniversal.luckperms.LuckPermsListener$$Lambda$3782/397887872
[21:46:52] [luckperms-worker-1/WARN]: [LuckPerms] Unable to pass event NodeClearEvent to handler us.donut.skuniversal.luckperms.LuckPermsListener$$Lambda$3782/397887872
[21:46:52] [luckperms-worker-1/WARN]: java.lang.IllegalStateException: BukkitGroupChangeEvent cannot be triggered asynchronously from another thread.
[21:46:52] [luckperms-worker-1/WARN]:   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:511)
[21:46:52] [luckperms-worker-1/WARN]:   at us.donut.skuniversal.luckperms.LuckPermsListener.onGroupChange(LuckPermsListener.java:50)
[21:46:52] [luckperms-worker-1/WARN]:   at me.lucko.luckperms.common.event.LuckPermsEventHandler.invoke(LuckPermsEventHandler.java:108)
[21:46:52] [luckperms-worker-1/WARN]:   at me.lucko.luckperms.common.event.LuckPermsEventHandler.invoke(LuckPermsEventHandler.java:45)
[21:46:52] [luckperms-worker-1/WARN]:   at me.lucko.luckperms.lib.eventbus.SimpleEventBus.post(SimpleEventBus.java:107)
[21:46:52] [luckperms-worker-1/WARN]:   at me.lucko.luckperms.common.event.AbstractEventBus.post(AbstractEventBus.java:84)
[21:46:52] [luckperms-worker-1/WARN]:   at me.lucko.luckperms.common.event.EventFactory.post(EventFactory.java:112)
[21:46:52] [luckperms-worker-1/WARN]:   at me.lucko.luckperms.common.event.EventFactory.lambda$post$0(EventFactory.java:125)
[21:46:52] [luckperms-worker-1/WARN]:   at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$ErrorReportingRunnable.run(AbstractJavaScheduler.java:106)
[21:46:52] [luckperms-worker-1/WARN]:   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[21:46:52] [luckperms-worker-1/WARN]:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[21:46:52] [luckperms-worker-1/WARN]:   at java.lang.Thread.run(Unknown Source)
[21:46:52] [pool-33-thread-1/INFO]: [LP] LOG > (Heroynas) [U] (Heroynas)
[21:46:52] [pool-33-thread-1/INFO]: [LP] LOG > parent set owner
[21:46:52] [luckperms-worker-4/WARN]: java.lang.IllegalStateException: BukkitGroupChangeEvent cannot be triggered asynchronously from another thread.
[21:46:52] [luckperms-worker-4/WARN]:   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:511)
[21:46:52] [luckperms-worker-4/WARN]:   at us.donut.skuniversal.luckperms.LuckPermsListener.onGroupChange(LuckPermsListener.java:50)
[21:46:52] [luckperms-worker-4/WARN]:   at me.lucko.luckperms.common.event.LuckPermsEventHandler.invoke(LuckPermsEventHandler.java:108)
[21:46:52] [luckperms-worker-4/WARN]:   at me.lucko.luckperms.common.event.LuckPermsEventHandler.invoke(LuckPermsEventHandler.java:45)
[21:46:52] [luckperms-worker-4/WARN]:   at me.lucko.luckperms.lib.eventbus.SimpleEventBus.post(SimpleEventBus.java:107)
[21:46:52] [luckperms-worker-4/WARN]:   at me.lucko.luckperms.common.event.AbstractEventBus.post(AbstractEventBus.java:84)
[21:46:52] [luckperms-worker-4/WARN]:   at me.lucko.luckperms.common.event.EventFactory.post(EventFactory.java:112)
[21:46:52] [luckperms-worker-4/WARN]:   at me.lucko.luckperms.common.event.EventFactory.lambda$post$0(EventFactory.java:125)
[21:46:52] [luckperms-worker-4/WARN]:   at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$ErrorReportingRunnable.run(AbstractJavaScheduler.java:106)
[21:46:52] [luckperms-worker-4/WARN]:   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[21:46:52] [luckperms-worker-4/WARN]:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[21:46:52] [luckperms-worker-4/WARN]:   at java.lang.Thread.run(Unknown Source)

**Comment by Andre601** [comment]
You don't provide enough information for us to actually help you.
Please make sure you provide the following information:
- What LuckPerms version are you running?
- What are your config settings? (Remove any potentially sensitive data like passwords before sharing the file)

Also, please use https://hasteb.in for sharing issues with us as it's much easier to read.

### Additional Links/Information
**Synchronizing groups, permissions, etc. accross servers**:
https://github.com/lucko/LuckPerms/wiki/Network-Installation

**Setup prefixes/suffixes and display them in chat, tablist, etc.**:
https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta

**Storage system errors (MySQL/MariaDB related errors)**:
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors

**Comment by lucko** [comment]
Issue is with the `skuniversal` plugin.
