### ISSUE TITLE
MongoDB Error

### ISSUE THREAD

**Issue by ramo10101** [lucko/LuckPerms#1740]
https://pastebin.com/Bqm7kNkP
It connects thenn authentication error, then if i try change host to 127.0.0.1:27017 or localhost it says sock exception error: Ramo
Ramo
Member
Premium
Messages:110
Reputation:6
Reactions:+6
erverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
[00:44:01 INFO]: Exception in monitor thread while connecting to server 127.0.0.1:27017
me.lucko.luckperms.lib.mongodb.MongoSocketOpenException: Exception opening socket
at me.lucko.luckperms.lib.mongodb.internal.connection.SocketStream.open(SocketStream.java:70) ~[remapped-mongodb_driver-3.10.1.jar:?]
at me.lucko.luckperms.lib.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:126) ~[remapped-mongodb_driver-3.10.1.jar:?]
at me.lucko.luckperms.lib.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117) [remapped-mongodb_driver-3.10.1.jar:?]
at java.lang.Thread.run(Thread.java:74:cool: [?:1.8.0_222]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_222]
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_222]
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_222]
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:18:cool: ~[?:1.8.0_222]
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_222]
at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_222]
at me.lucko.luckperms.lib.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:64) ~[remapped-mongodb_driver-3.10.1.jar:?]
at me.lucko.luckperms.lib.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:79) ~[remapped-mongodb_driver-3.10.1.jar:?]
at me.lucko.luckperms.lib.mongodb.internal.connection.SocketStream.open(SocketStream.java:65) ~[remapped-mongodb_driver-3.10.1.jar:?]
... 3 more

**Comment by lucko** [comment]
The error being passed on by your Mongo server is:

```
Command failed with error 18: 'auth failed' on server 180.92.194.177:27017. The full response is { "ok" : 0.0, "errmsg" : "auth failed", "code" : 18 }
```

Maybe incorrect password?
