### ISSUE TITLE
Migration Stack "error" (Permission Ex migration)

### ISSUE THREAD

**Issue by quorn23** [lucko/LuckPerms#1751]
```
[03:48:36] [Server thread/INFO]: quorn23 issued server command: /lp migration PermissionsEx
[03:48:36] [pool-14-thread-1/INFO]: [LP] MIGRATION [PermissionsEx] > Starting.
[03:48:36] [pool-14-thread-1/INFO]: [LP] MIGRATION [PermissionsEx] > Calculating group weightings.
[03:48:36] [pool-14-thread-1/INFO]: [LP] MIGRATION [PermissionsEx] > Starting group migration.
[03:48:37] [pool-14-thread-1/INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 1 groups so far.
[03:48:37] [pool-14-thread-1/INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 2 groups so far.
[03:48:37] [pool-14-thread-1/INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 3 groups so far.
[03:48:37] [pool-14-thread-1/INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 4 groups so far.
[03:48:37] [pool-14-thread-1/INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 5 groups so far.
[03:48:37] [pool-14-thread-1/INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 6 groups so far.
[03:48:37] [pool-14-thread-1/INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 7 groups so far.
[03:48:37] [pool-14-thread-1/INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 8 groups so far.
[03:48:37] [pool-14-thread-1/INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 9 groups so far.
[03:48:37] [pool-14-thread-1/INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 9 groups
[03:48:37] [pool-14-thread-1/INFO]: [LP] MIGRATION [PermissionsEx] > Starting tracks migration.
[03:48:37] [pool-14-thread-1/INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 0 tracks
[03:48:37] [pool-14-thread-1/INFO]: [LP] MIGRATION [PermissionsEx] > Starting user migration.
[03:48:37] [pool-14-thread-1/WARN]: java.lang.IllegalStateException: PermissionEntityEvent may only be triggered synchronously.
[03:48:37] [pool-14-thread-1/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533)
[03:48:37] [pool-14-thread-1/WARN]: 	at ru.tehkode.permissions.bukkit.PermissionsEx.callEvent(PermissionsEx.java:393)
[03:48:37] [pool-14-thread-1/WARN]: 	at ru.tehkode.permissions.PermissionManager.callEvent(PermissionManager.java:697)
[03:48:37] [pool-14-thread-1/WARN]: 	at ru.tehkode.permissions.PermissionEntity.callEvent(PermissionEntity.java:730)
[03:48:37] [pool-14-thread-1/WARN]: 	at ru.tehkode.permissions.PermissionEntity.callEvent(PermissionEntity.java:734)
[03:48:37] [pool-14-thread-1/WARN]: 	at ru.tehkode.permissions.PermissionEntity.setOption(PermissionEntity.java:499)
[03:48:37] [pool-14-thread-1/WARN]: 	at ru.tehkode.permissions.PermissionEntity.setOption(PermissionEntity.java:509)
[03:48:37] [pool-14-thread-1/WARN]: 	at ru.tehkode.permissions.PermissionUser.getName(PermissionUser.java:78)
[03:48:37] [pool-14-thread-1/WARN]: 	at me.lucko.luckperms.bukkit.migration.MigrationPermissionsEx.lambda$execute$2(MigrationPermissionsEx.java:172)
[03:48:37] [pool-14-thread-1/WARN]: 	at me.lucko.luckperms.bukkit.migration.MigrationPermissionsEx$$Lambda$3817.00000000C40AC900.accept(Unknown Source)
[03:48:37] [pool-14-thread-1/WARN]: 	at me.lucko.luckperms.common.util.Iterators.iterate(Iterators.java:40)
[03:48:37] [pool-14-thread-1/WARN]: 	at me.lucko.luckperms.bukkit.migration.MigrationPermissionsEx.execute(MigrationPermissionsEx.java:165)
[03:48:37] [pool-14-thread-1/WARN]: 	at me.lucko.luckperms.common.command.abstraction.MainCommand.execute(MainCommand.java:102)
[03:48:37] [pool-14-thread-1/WARN]: 	at me.lucko.luckperms.common.command.abstraction.MainCommand.execute(MainCommand.java:45)
[03:48:37] [pool-14-thread-1/WARN]: 	at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:215)
[03:48:37] [pool-14-thread-1/WARN]: 	at me.lucko.luckperms.common.command.CommandManager.lambda$onCommand$0(CommandManager.java:150)
[03:48:37] [pool-14-thread-1/WARN]: 	at me.lucko.luckperms.common.command.CommandManager$$Lambda$3804.00000000AF6AB460.get(Unknown Source)
[03:48:37] [pool-14-thread-1/WARN]: 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[03:48:37] [pool-14-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[03:48:37] [pool-14-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[03:48:37] [pool-14-thread-1/WARN]: 	at java.lang.Thread.run(Thread.java:819)
[03:48:37] [pool-14-thread-1/INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 1 users.
[03:48:37] [pool-14-thread-1/INFO]: [LP] MIGRATION [PermissionsEx] > Success! Migration complete.
```

Paper Spigot 1.14.4 
It looks like the permissions got imported fine.

**Comment by Andre601** [comment]
This seems to be an issue with spigots new rule of async methods to not be triggered sync and vice-versa.

Make sure to use latest dev build.
