### ISSUE TITLE
ERROR MySQL - Hakari

### ISSUE THREAD

**Issue by Ragbecca** [lucko/LuckPerms#1754]
I'm having problems with setting up my Luckyperms with MySQL, I've tried the common help guide for connections, but I've concluded that this problem is like no other.

`[Server thread] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Starting...
[18:56:17] [Server thread/WARN]: [Server thread] ERROR me.lucko.luckperms.lib.hikari.util.PropertyElf - Failed to set property port on target class me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource
[18:56:17] [Server thread/WARN]: java.lang.NumberFormatException: For input string: ""
[18:56:17] [Server thread/WARN]: 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[18:56:17] [Server thread/WARN]: 	at java.lang.Integer.parseInt(Integer.java:592)
[18:56:17] [Server thread/WARN]: 	at java.lang.Integer.parseInt(Integer.java:615)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.util.PropertyElf.setProperty(PropertyElf.java:141)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.util.PropertyElf.lambda$setTargetFromProperties$0(PropertyElf.java:59)
[18:56:17] [Server thread/WARN]: 	at java.util.Hashtable.forEach(Hashtable.java:879)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.util.PropertyElf.setTargetFromProperties(PropertyElf.java:54)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:317)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.PoolBase.<init>(PoolBase.java:109)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.<init>(HikariPool.java:108)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:91)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:167)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.Storage.init(Storage.java:110)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:136)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:153)
[18:56:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[18:56:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347)
[18:56:17] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[18:56:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436)
[18:56:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350)
[18:56:17] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:214)
[18:56:17] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
[18:56:17] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[18:56:17] [Server thread/ERROR]: [LuckPerms] Failed to init storage dao
[18:56:17] [Server thread/WARN]: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: ""
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.util.PropertyElf.setProperty(PropertyElf.java:165)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.util.PropertyElf.lambda$setTargetFromProperties$0(PropertyElf.java:59)
[18:56:17] [Server thread/WARN]: 	at java.util.Hashtable.forEach(Hashtable.java:879)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.util.PropertyElf.setTargetFromProperties(PropertyElf.java:54)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:317)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.PoolBase.<init>(PoolBase.java:109)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.<init>(HikariPool.java:108)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:91)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:167)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.Storage.init(Storage.java:110)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:136)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:153)
[18:56:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[18:56:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347)
[18:56:17] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[18:56:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436)
[18:56:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350)
[18:56:17] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:214)
[18:56:17] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
[18:56:17] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[18:56:17] [Server thread/WARN]: Caused by: java.lang.NumberFormatException: For input string: ""
[18:56:17] [Server thread/WARN]: 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[18:56:17] [Server thread/WARN]: 	at java.lang.Integer.parseInt(Integer.java:592)
[18:56:17] [Server thread/WARN]: 	at java.lang.Integer.parseInt(Integer.java:615)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.util.PropertyElf.setProperty(PropertyElf.java:141)
[18:56:17] [Server thread/WARN]: 	... 21 more
[18:56:17] [Server thread/INFO]: [LuckPerms] Loading messaging service... [SQL]
[18:56:17] [Server thread/WARN]: java.lang.RuntimeException: java.sql.SQLException: Unable to get a connection from the pool. (hikari is null)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:56)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.MessagingFactory$SqlMessengerProvider.obtain(MessagingFactory.java:132)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.LuckPermsMessagingService.<init>(LuckPermsMessagingService.java:72)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.MessagingFactory.getServiceFor(MessagingFactory.java:95)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.messaging.BukkitMessagingFactory.getServiceFor(BukkitMessagingFactory.java:63)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.MessagingFactory.getInstance(MessagingFactory.java:73)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:137)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:153)
[18:56:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[18:56:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347)
[18:56:17] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[18:56:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436)
[18:56:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350)
[18:56:17] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:214)
[18:56:17] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
[18:56:17] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[18:56:17] [Server thread/WARN]: Caused by: java.sql.SQLException: Unable to get a connection from the pool. (hikari is null)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:129)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.sql.SqlMessenger.getConnection(SqlMessenger.java:84)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.init(AbstractSqlMessenger.java:55)
[18:56:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:54)
[18:56:17] [Server thread/WARN]: 	... 15 more
[18:56:17] [Server thread/WARN]: [LuckPerms] Messaging service 'sql' not recognised.
[18:56:18] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[18:56:18] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[18:56:18] [Server thread/WARN]: java.util.concurrent.CompletionException: java.sql.SQLException: Unable to get a connection from the pool. (hikari is null)
[18:56:18] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:99)
[18:56:18] [Server thread/WARN]: 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
[18:56:18] [Server thread/WARN]: 	at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$ErrorReportingRunnable.run(AbstractJavaScheduler.java:106)
[18:56:18] [Server thread/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[18:56:18] [Server thread/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[18:56:18] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[18:56:18] [Server thread/WARN]: Caused by: java.sql.SQLException: Unable to get a connection from the pool. (hikari is null)
[18:56:18] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:129)
[18:56:18] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:646)
[18:56:18] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$10(Storage.java:190)
[18:56:18] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:94)
[18:56:18] [Server thread/WARN]: 	... 5 more
[18:56:18] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 1373ms)`

My config file:
storage-method: MySQL
  address: :::3306
  database: minecraft
  username: root
  password: '- '
  pool-settings:
    maximum-pool-size: 10
    minimum-idle: 10
    maximum-lifetime: 1800000 # 30 minutes
    connection-timeout: 5000 # 5 seconds
      useUnicode: true
      characterEncoding: utf8
  table_prefix: 'luckperms_'
  mongodb_collection_prefix: ''
  mongodb_connection_URI: ''
split-storage:
  enabled: false
  methods:
    user: h2
    group: h2
    track: h2
    uuid: h2
    log: h2
sync-minutes: 3
watch-files: true
messaging-service: none
auto-push-updates: true
push-log-entries: true
broadcast-received-log-entries: true
redis:
  enabled: false
  address: localhost
  password: ''

If somebody could help. I've been stuck with this problem for quite some time.

Extra info: MySQL runs on :::3306

**Comment by Tobi406** [comment]
Are you trying to connect to your localhost? Try `127.0.0.1` then

**Comment by Ragbecca** [comment]
Thank you, fixed it.

**Comment by killmasterMC** [comment]
> Gracias, lo arreglé.

Pues yo no
