### ISSUE TITLE
java.lang.RuntimeException: Script engine not present

### ISSUE THREAD

**Issue by BirkhoffLee** [lucko/LuckPerms#1775]
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
Eclipse OpenJ9 VM (build openj9-0.15.1, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190717_368 (JIT enabled, AOT enabled)
OpenJ9 - 0f66c6431
OMR - ec782f26
JCL - f147086df1e based on jdk8u222-b10)
:/home/container$ java -Xms2048M -Xmx2048M -Xmns1024M -Xmnx1638M -Xgc:concurrentScavenge -Xgc:dnssExpectedTimeRatioMaximum=3 -Xgc:scvNoAdaptiveTenure -Xdisableexplicitgc -jar server.jar
```

```
>lp info
> [07:29:26 INFO]: [LP] Running LuckPerms v4.4.31 by Luck.
> [07:29:26 INFO]: [LP] - Platform: Bukkit
> [07:29:26 INFO]: [LP] - Server Brand: CraftBukkit
> [07:29:26 INFO]: [LP] - Server Version:
> [07:29:26 INFO]: [LP] - git-PaperSpigot-"4c7641d" (MC: 1.8.8) - 1.8.8-R0.1-SNAPSHOT
> [07:29:26 INFO]: [LP] - Storage:
> [07:29:26 INFO]: [LP] - Type: MariaDB
> [07:29:26 INFO]: [LP] - Ping: 1ms
> [07:29:26 INFO]: [LP] - Connected: true
> [07:29:26 INFO]: [LP] - Messaging: Sql
> [07:29:26 INFO]: [LP] - Instance:
> [07:29:26 INFO]: [LP] - Static contexts: None
> [07:29:26 INFO]: [LP] - Online Players: 1 (3 unique)
> [07:29:26 INFO]: [LP] - Uptime: 37m 25s
> [07:29:26 INFO]: [LP] - Local Data: 1 users, 18 groups, 2 tracks
```

```
> [07:21:29 INFO]: birkhoff issued server command: /lp verbose on
> [07:21:29 WARN]: java.lang.RuntimeException: Script engine not present
> [07:21:29 WARN]: at me.lucko.luckperms.common.verbose.VerboseFilter.parse(VerboseFilter.java:69)
> [07:21:29 WARN]: at me.lucko.luckperms.common.commands.misc.VerboseCommand.execute(VerboseCommand.java:80)
> [07:21:29 WARN]: at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:50)
> [07:21:29 WARN]: at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:42)
> [07:21:29 WARN]: at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:214)
> [07:21:29 WARN]: at me.lucko.luckperms.common.command.CommandManager.lambda$onCommand$0(CommandManager.java:149)
> [07:21:29 WARN]: at me.lucko.luckperms.common.command.CommandManager$$Lambda$442.00000000B6D29760.get(Unknown Source)
> [07:21:29 WARN]: at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
> [07:21:29 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> [07:21:29 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> [07:21:29 WARN]: at java.lang.Thread.run(Unknown Source)
```

**Comment by Andre601** [comment]
Cold be an issue with having a headless Java version.
OpenJ9 is to my knowledge one of those and causes issues.

**Comment by BirkhoffLee** [comment]
@lucko Could you take a look on this? Is this “fixable” on LuckPerms side or it just simply won’t work in OpenJ9? Thanks.

**Comment by lucko** [comment]
Will be fixed in LP v5 - Nashorn dependency is being removed.
