### ISSUE TITLE
Exception during startup

### ISSUE THREAD

**Issue by CommanderTvis** [lucko/LuckPerms#1807]
I've tried to install LuckPerms 4.4.1 on Paper 1.8.8. Plugin has thrown an exception during enabling.
```
[12:55:34 INFO]: [LuckPerms] Enabling LuckPerms v4.4.1
[12:55:34 INFO]:         __    
[12:55:34 INFO]:   |    |__)   LuckPerms v4.4.1
[12:55:34 INFO]:   |___ |      Running on Bukkit - CraftBukkit
[12:55:34 INFO]: [LuckPerms] Loading configuration...
[12:55:34 INFO]: [LuckPerms] Loading storage provider... [H2]
[12:55:35 INFO]: [LuckPerms] Loading internal permission managers...
[12:55:35 ERROR]: Error occurred while enabling LuckPerms v4.4.1 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/eventbus/EventSubscriber
	at me.lucko.luckperms.bukkit.LPBukkitPlugin.provideEventBus(LPBukkitPlugin.java:209) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:163) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:153) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.eventbus.EventSubscriber
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_232]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
	... 11 more
```

**Comment by CommanderTvis** [comment]
Solved by removing `plugins/LuckPerms/lib` directory; then rebooting the server
