### ISSUE TITLE
Dynmap Luckperms under 1.14.4 

### ISSUE THREAD

**Issue by lastsamurai26** [lucko/LuckPerms#1819]
is this a Luckperms or dynmap issus ? 

[23:09:43] [Server thread/ERROR]: Error occurred while enabling dynmap v3.0-beta-5-218 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/api/LuckPermsApi
	at org.dynmap.bukkit.permissions.LuckPermsPermissions.create(LuckPermsPermissions.java:26) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:848) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.api.LuckPermsApi
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
	... 11 more

**Comment by blubberdiblub** [comment]
Dynmap is still referencing the old Class.

You can follow these instructions to work around it:
https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5#api-compatibility

**Comment by lastsamurai26** [comment]
Thx for the help :)
