### ISSUE TITLE
Conflict with DynMap

### ISSUE THREAD

**Issue by Amblyopia** [lucko/LuckPerms#1823]
Just updated from 4.4.31 to 5.0.8 and my DynMap (3.0 beta 5) would not load.  Had to revert back to 4.4.31.

`[14:53:45] [Server thread/ERROR]: Error occurred while enabling dynmap v3.0-beta-5-218 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/api/LuckPermsApi
	at org.dynmap.bukkit.permissions.LuckPermsPermissions.create(LuckPermsPermissions.java:26) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:848) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-230]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.api.LuckPermsApi
	at java.net.URLClassLoader.findClass(URLClassLoader.java:436) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-230]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 11 more
[14:53:45] [Server thread/INFO]: [dynmap] Disabling dynmap v3.0-beta-5-218
[14:53:45] [Server thread/ERROR]: Error occurred while disabling dynmap v3.0-beta-5-218 (Is it up to date?)
java.lang.NullPointerException: null
	at org.dynmap.bukkit.DynmapPlugin.onDisable(DynmapPlugin.java:946) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-230]
	at java.lang.Thread.run(Thread.java:835) [?:?]
`

**Comment by Turbotailz** [comment]
You probably need the legacy API extension:

https://github.com/lucko/LuckPerms/wiki/Extensions#extension-legacy-api

**Comment by illumeleet** [comment]
same here

**Comment by Amblyopia** [comment]
It's unable to load the legacy API.

`[17:52:44] [Server thread/ERROR]: Could not load 'plugins/extension-legacy-api-1.0.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:159) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:142) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-230]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more
`

**Comment by Turbotailz** [comment]
If you scroll further up that page, [it tells you where to correctly install the extensions](https://github.com/lucko/LuckPerms/wiki/Extensions#installing-extensions) - in a folder named `extensions` inside the `LuckPerms` folder.

**Comment by Amblyopia** [comment]
Ha!  For some reason I didn't scroll up.

After correctly installing the extension the issue has been resolved.

Thank you.

**Comment by Turbotailz** [comment]
@illumeleet make sure to follow the above to fix this issue on your server too.
