### ISSUE TITLE
Error removing or adding permission via vault? LuckPerms v5 

### ISSUE THREAD

**Issue by SrBedrock** [lucko/LuckPerms#1826]
After upgrading to V5 I started getting this error.

https://hasteb.in/ikabihuw.bash

```log
>.... [16:42:16 INFO]: ThiagoROX issued server command: /auto
>.... [16:42:16 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'auto' in plugin VKAutoPickup v9.6.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.4.jar:git-Paper-230]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-230]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-230]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
at me.lucko.luckperms.common.node.AbstractNodeBuilder.withContext(AbstractNodeBuilder.java:111) ~[?:?]
at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.holderRemovePermission(LuckPermsVaultPermission.java:455) ~[?:?]
at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.userRemovePermission(LuckPermsVaultPermission.java:226) ~[?:?]
at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.playerRemove(AbstractVaultPermission.java:203) ~[?:?]
at com.vk2gpz.autopickup.d.c(d.java:172) ~[?:?]
at com.vk2gpz.autopickup.d.onCommand(d.java:45) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.4.jar:git-Paper-230]
... 17 more
```

**Comment by SrBedrock** [comment]
Luck Perms Version 5.0.8
Paper Version 230
Vault Version 1.7.3

**Comment by BrainStone** [comment]
That might be an issue with the actual plugin. Does the same issue happen with LPv4?

**Comment by lucko** [comment]
Thanks for reporting, should be fixed in the latest commit.

**Comment by SrBedrock** [comment]
Thanks guys!
