### ISSUE TITLE
Error opening deluxe menu with permission as a requirement. LuckPerms v5

### ISSUE THREAD

**Issue by SrBedrock** [lucko/LuckPerms#1827]
After upgrading to V5 I started getting this error.
Error opening deluxe menu with permission as a requirement to open a menu.

https://hasteb.in/jimiyicu.rb

```log
>.... [18:29:42 WARN]: [DeluxeMenus] Plugin DeluxeMenus v1.12.0 generated an exception while executing task 295979
java.lang.UnsupportedOperationException: null
at me.lucko.luckperms.extension.legacyapi.impl.misc.FakeSortedSet.comparator(FakeSortedSet.java:30) ~[?:?]
at java.util.SortedSet$1.getComparator(SortedSet.java:260) ~[?:1.8.0_212]
at java.util.stream.StreamOpFlag.fromCharacteristics(StreamOpFlag.java:734) ~[?:1.8.0_212]
at java.util.stream.StreamSupport.stream(StreamSupport.java:70) ~[?:1.8.0_212]
at java.util.Collection.stream(Collection.java:581) ~[?:1.8.0_212]
at me.lucko.luckperms.placeholders.LPPlaceholderProvider.lambda$setup$42(LPPlaceholderProvider.java:224) ~[?:?]
at me.lucko.luckperms.placeholders.LPPlaceholderProvider.onPlaceholderRequest(LPPlaceholderProvider.java:283) ~[?:?]
at me.lucko.luckperms.placeholders.LuckPermsExpansion.onPlaceholderRequest(LuckPermsExpansion.java:69) ~[?:?]
at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38) ~[?:?]
at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:234) ~[?:?]
at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:375) ~[?:?]
at com.extendedclip.deluxemenus.menu.MenuItem.getItemStack(MenuItem.java:389) ~[?:?]
at com.extendedclip.deluxemenus.menu.Menu$2.run(Menu.java:279) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-230]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-230]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-230]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by SrBedrock** [comment]
Luck Perms Version 5.0.8
Deluxe Menu Version 1.12.0
Paper Version 230
Vault Version 1.7.3

**Comment by BrainStone** [comment]
That looks like deluxe menu is trying to perform an action that is not supported through the API bridge.  
The author of deluxe menu needs to update the plugin to support LPv5.

**Comment by lucko** [comment]
You just need to update to the latest placeholder expansion for LuckPerms - I've just uploaded it to the PlaceholderAPI eCloud, or you can download it from here.

https://ci.lucko.me/job/LuckPermsPlaceholders/

**Comment by SrBedrock** [comment]
Thanks!
