### ISSUE TITLE
Issue placeholder expansion

### ISSUE THREAD

**Issue by RAFAELESPADA** [lucko/LuckPerms#1833]
your expansion for luckperms does not enable and im using the lastest version of both plugin and expansion.
PlaceholderAPI lastest version too
Server version: spigot 1.13
Error:
Caused by: java.lang.NoClassDefFoundError: net/luckperms/api/LuckPerms
        at me.lucko.luckperms.placeholders.LuckPermsExpansion.canRegister(LuckPe
rmsExpansion.java:48) ~[?:?]
        at me.clip.placeholderapi.expansion.ExpansionManager.registerExpansion(E
xpansionManager.java:102) ~[?:?]
        at me.clip.placeholderapi.expansion.ExpansionManager.registerAllExpansio
ns(ExpansionManager.java:154) ~[?:?]
        at me.clip.placeholderapi.ServerLoadEventListener.onServerLoad(ServerLoa
dEventListener.java:52) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_221]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader
$1.execute(PerWorldPluginLoader.java:116) ~[?:?]
        ... 10 more
Caused by: java.lang.ClassNotFoundException: net.luckperms.api.LuckPerms
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at me.lucko.luckperms.placeholders.LuckPermsExpansion.canRegister(LuckPe
rmsExpansion.java:48) ~[?:?]
        at me.clip.placeholderapi.expansion.ExpansionManager.registerExpansion(E
xpansionManager.java:102) ~[?:?]
        at me.clip.placeholderapi.expansion.ExpansionManager.registerAllExpansio
ns(ExpansionManager.java:154) ~[?:?]
        at me.clip.placeholderapi.ServerLoadEventListener.onServerLoad(ServerLoa
dEventListener.java:52) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_221]

**Comment by Tobi406** [comment]
What is your exact LuckPerms version?

**Comment by RAFAELESPADA** [comment]
version: 4.4.1

**Comment by Tobi406** [comment]
That isn't the latest version and won't work with this version of the placeholder expansion.

You can find the newest build on https://luckperms.net

**Comment by RAFAELESPADA** [comment]
you should put the lastest on spigot too

**Comment by Tobi406** [comment]
Spigot isn't often updated commonly, as every commit creates a new build (and so a new version).

Luck wants to wait with updating the build on Spigot because the new web editor is still in beta and has some problems (although they should hopefully be not that great)

**Comment by RAFAELESPADA** [comment]
You can close this report now my issue has been resolved thanks

**Comment by Andre601** [comment]
You csn close it yourself since you created it
