### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by BrayaanPS** [lucko/LuckPerms#1838]
I get this following error with the Authme plugin
`[15:44:31] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.6.0-SNAPSHOT-b2334
[15:44:32] [Server thread/INFO]: [AuthMe] Created column 'regdate' and set the current timestamp, 1575312272096, to all 0 rows
[15:44:32] [Server thread/INFO]: [AuthMe] SQLite Setup finished
[15:44:32] [Server thread/WARN]: [AuthMe] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke method 'setup' for fr.xephi.authme.permission.PermissionsManager@7d416fc9
[15:44:32] [Server thread/WARN]: fr.xephi.authme.libs.ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke method 'setup' for fr.xephi.authme.permission.PermissionsManager@7d416fc9
[15:44:32] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.invokeMethod(ReflectionUtils.java:76)
[15:44:32] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.postProcess(PostConstructMethodInvoker.java:27)
[15:44:32] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.runPostConstructHandlers(InjectorImpl.java:271)
[15:44:32] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
[15:44:32] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
[15:44:32] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
[15:44:32] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
[15:44:32] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
[15:44:32] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
[15:44:32] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
[15:44:32] [Server thread/WARN]: 	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:253)
[15:44:32] [Server thread/WARN]: 	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:227)
[15:44:32] [Server thread/WARN]: 	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:146)
[15:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[15:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[15:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[15:44:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461)
[15:44:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375)
[15:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449)
[15:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266)
[15:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775)
[15:44:32] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:44:32] [Server thread/WARN]: Caused by: java.lang.reflect.InvocationTargetException
[15:44:32] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:44:32] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:44:32] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:44:32] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[15:44:32] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.invokeMethod(ReflectionUtils.java:73)
[15:44:32] [Server thread/WARN]: 	... 21 more
[15:44:32] [Server thread/WARN]: Caused by: java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms
[15:44:32] [Server thread/WARN]: 	at fr.xephi.authme.permission.handlers.LuckPermsHandler.<init>(LuckPermsHandler.java:40)
[15:44:32] [Server thread/WARN]: 	at fr.xephi.authme.permission.PermissionsManager.createPermissionHandler(PermissionsManager.java:135)
[15:44:32] [Server thread/WARN]: 	at fr.xephi.authme.permission.PermissionsManager.setup(PermissionsManager.java:92)
[15:44:32] [Server thread/WARN]: 	... 26 more
[15:44:32] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.LuckPerms
[15:44:32] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[15:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135)
[15:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81)
[15:44:32] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[15:44:32] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[15:44:32] [Server thread/WARN]: 	... 29 more
[15:44:32] [Server thread/WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[15:44:32] [Server thread/INFO]: [AuthMe] Waiting for 0 tasks to finish
[15:44:32] [Server thread/INFO]: [AuthMe] AuthMe 5.6.0-SNAPSHOT-b2334 disabled!`

**Comment by Andre601** [comment]
If you're using v5 of LP make sure to read the wiki page about migration from v4 to v5.
Your error is most likely caused by this.

**Comment by BrayaanPS** [comment]
Oh, thanks.
