### ISSUE TITLE
Incompatibility issues with Authme (and several others) on LP5+

### ISSUE THREAD

**Issue by Gazpa47** [lucko/LuckPerms#1841]
Getting this every time I load up the server. Forces it to shutdown. I don't know if this issue is on LP's end or Authme's end so....

[10:20:54] [Server thread/WARN]: [AuthMe] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke method 'setup' for fr.xephi.authme.permission.PermissionsManager@3a7b467
[10:20:54] [Server thread/WARN]: fr.xephi.authme.libs.ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke method 'setup' for fr.xephi.authme.permission.PermissionsManager@3a7b467
[10:20:54] [Server thread/WARN]:        at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.invokeMethod(ReflectionUtils.java:76)
[10:20:54] [Server thread/WARN]:        at fr.xephi.authme.libs.ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.postProcess(PostConstructMethodInvoker.java:27)
[10:20:54] [Server thread/WARN]:        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.runPostConstructHandlers(InjectorImpl.java:271)
[10:20:54] [Server thread/WARN]:        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
[10:20:54] [Server thread/WARN]:        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
[10:20:54] [Server thread/WARN]:        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
[10:20:54] [Server thread/WARN]:        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
[10:20:54] [Server thread/WARN]:        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
[10:20:54] [Server thread/WARN]:        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
[10:20:54] [Server thread/WARN]:        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
[10:20:54] [Server thread/WARN]:        at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:253)
[10:20:54] [Server thread/WARN]:        at fr.xephi.authme.AuthMe.initialize(AuthMe.java:227)
[10:20:54] [Server thread/WARN]:        at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:146)
[10:20:54] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[10:20:54] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[10:20:54] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[10:20:54] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[10:20:54] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[10:20:54] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[10:20:54] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
[10:20:54] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876)
[10:20:54] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[10:20:54] [Server thread/WARN]: Caused by: java.lang.reflect.InvocationTargetException
[10:20:54] [Server thread/WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:20:54] [Server thread/WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:20:54] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:20:54] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[10:20:54] [Server thread/WARN]:        at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.invokeMethod(ReflectionUtils.java:73)
[10:20:54] [Server thread/WARN]:        ... 21 more
[10:20:54] [Server thread/WARN]: Caused by: java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms
[10:20:54] [Server thread/WARN]:        at fr.xephi.authme.permission.handlers.LuckPermsHandler.<init>(LuckPermsHandler.java:40)
[10:20:54] [Server thread/WARN]:        at fr.xephi.authme.permission.PermissionsManager.createPermissionHandler(PermissionsManager.java:135)
[10:20:54] [Server thread/WARN]:        at fr.xephi.authme.permission.PermissionsManager.setup(PermissionsManager.java:92)
[10:20:54] [Server thread/WARN]:        ... 26 more
[10:20:54] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.LuckPerms
[10:20:54] [Server thread/WARN]:        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[10:20:54] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139)
[10:20:54] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85)
[10:20:54] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[10:20:54] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[10:20:54] [Server thread/WARN]:        ... 29 more

**Comment by BrainStone** [comment]
https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5#api-compatibility

**Comment by Maks1116** [comment]
I have the same problem but it makes another exception: 
[InjectorReflectorException]: Could not invoke constructor of class 'class fr.exphi.authme.command.CommandHandler'

**Comment by benwoo1110** [comment]
> I have the same problem but it makes another exception:
> [InjectorReflectorException]: Could not invoke constructor of class 'class fr.exphi.authme.command.CommandHandler'

Contact authme support. If for some reason you think is LP causing it (I doubt so), at least open a new issue.
