### ISSUE TITLE
LP Refuses to accept that my mongo host address exists.

### ISSUE THREAD

**Issue by BattleDash** [lucko/LuckPerms#1846]
Here's the full stack trace first of all:

```
[17:19:25 INFO]: [LuckPerms] Loading configuration...
[17:19:27 INFO]: [LuckPerms] Successfully downloaded 'mongodb_driver-3.10.1.jar' with matching checksum: IGjdjTH4VjqnqGUdVe8u+dKfzKkpCG1NR11TE8ieCdU=
[17:19:27 INFO]: [LuckPerms] Attempting to apply relocations to mongodb_driver-3.10.1.jar...
[17:19:28 INFO]: [LuckPerms] Loading storage provider... [MONGODB]
[17:19:28 INFO]: Cluster created with settings {hosts=[cluster0-nmrvd.mongodb.net:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
[17:19:28 INFO]: Exception in monitor thread while connecting to server cluster0-nmrvd.mongodb.net:27017
me.lucko.luckperms.lib.mongodb.MongoSocketException: cluster0-nmrvd.mongodb.net
        at me.lucko.luckperms.lib.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:211) ~[remapped-mongodb_driver-3.10.1.jar:?]
        at me.lucko.luckperms.lib.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:75) ~[remapped-mongodb_driver-3.10.1.jar:?]
        at me.lucko.luckperms.lib.mongodb.internal.connection.SocketStream.open(SocketStream.java:65) ~[remapped-mongodb_driver-3.10.1.jar:?]
        at me.lucko.luckperms.lib.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:126) ~[remapped-mongodb_driver-3.10.1.jar:?]
        at me.lucko.luckperms.lib.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117) [remapped-mongodb_driver-3.10.1.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.net.UnknownHostException: cluster0-nmrvd.mongodb.net
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:1.8.0_231]
        at java.net.InetAddress$2.lookupAllHostAddr(Unknown Source) ~[?:1.8.0_231]
        at java.net.InetAddress.getAddressesFromNameService(Unknown Source) ~[?:1.8.0_231]
        at java.net.InetAddress.getAllByName0(Unknown Source) ~[?:1.8.0_231]
        at java.net.InetAddress.getAllByName(Unknown Source) ~[?:1.8.0_231]
        at java.net.InetAddress.getAllByName(Unknown Source) ~[?:1.8.0_231]
        at me.lucko.luckperms.lib.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:203) ~[remapped-mongodb_driver-3.10.1.jar:?]
        ... 5 more
[17:19:28 INFO]: [LuckPerms] Loading internal permission managers...
[17:19:28 INFO]: [LuckPerms] Performing initial data load...
[17:19:28 INFO]: Cluster description not yet available. Waiting for 30000 ms before timing out
[17:19:58 WARN]: java.util.concurrent.CompletionException: me.lucko.luckperms.lib.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=cluster0-nmrvd.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={me.lucko.luckperms.lib.mongodb.MongoSocketException: cluster0-nmrvd.mongodb.net}, caused by {java.net.UnknownHostException: cluster0-nmrvd.mongodb.net}}]
[17:19:58 WARN]:        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
[17:19:58 WARN]:        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
[17:19:58 WARN]:        at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
[17:19:58 WARN]:        at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$ErrorReportingRunnable.run(AbstractJavaScheduler.java:106)
[17:19:58 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:19:58 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:19:58 WARN]:        at java.lang.Thread.run(Unknown Source)
[17:19:58 WARN]: Caused by: me.lucko.luckperms.lib.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=cluster0-nmrvd.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={me.lucko.luckperms.lib.mongodb.MongoSocketException: cluster0-nmrvd.mongodb.net}, caused by {java.net.UnknownHostException: cluster0-nmrvd.mongodb.net}}]
[17:19:58 WARN]:        at me.lucko.luckperms.lib.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:182)
[17:19:58 WARN]:        at me.lucko.luckperms.lib.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41)
[17:19:58 WARN]:        at me.lucko.luckperms.lib.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:136)
[17:19:58 WARN]:        at me.lucko.luckperms.lib.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:94)
[17:19:58 WARN]:        at me.lucko.luckperms.lib.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:249)
[17:19:58 WARN]:        at me.lucko.luckperms.lib.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:172)
[17:19:58 WARN]:        at me.lucko.luckperms.lib.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:132)
[17:19:58 WARN]:        at me.lucko.luckperms.lib.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:86)
[17:19:58 WARN]:        at me.lucko.luckperms.common.storage.implementation.mongodb.MongoStorage.loadAllGroups(MongoStorage.java:412)
[17:19:58 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$10(Storage.java:190)
[17:19:58 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:94)
[17:19:58 WARN]:        ... 5 more
[17:19:58 INFO]: [LuckPerms] Successfully enabled. (took 33087ms)
```
As you can see: `java.net.UnknownHostException: cluster0-nmrvd.mongodb.net`. I have no clue why this is happening as I can connect fine to my database on MongoDB Compass, as well as my various Web API backends and Discord Bots that I own. This is happening on both v4.4.1 and Latest. I really need this resolved ASAP as I need a new permissions solution for when we launch the bungee network later tonight and I prefer using Mongo over SQL.

Any contributions/ideas are appreciated. I've set LuckPerms up before with this exact same mongo server and it worked fine, it was on an old HDD so I don't have access to how I managed it is the problem, but I don't see why I would be doing anything differently than what I've tried already. Nothing works.

**Comment by BattleDash** [comment]
It also finds 0 of everything if I try to migrate permissions/users from PEX.

**Comment by electronicboy** [comment]
```
$ nslookup A cluster0-nmrvd.mongodb.net
nslookup: couldn't get address for 'cluster0-nmrvd.mongodb.net': not found
```
Not really anything related to LP, that domain doesn't resolve?

**Comment by Andre601** [comment]
> It also finds 0 of everything if I try to migrate permissions/users from PEX.

Make sure PEX is still installed for migration.

**Comment by BattleDash** [comment]
@Andre601 Yes, pex is installed for migration already.

And @electronicboy that makes no sense at all, how am I able to connect to it from MongoDB compass and my various programs?

**Comment by electronicboy** [comment]
Do they rely on srv records, I wonder; this might potentially be more
something for the mongodb drivers issue tracker

**Comment by electronicboy** [comment]
Oh, the driver uses a separate prefix for this, mongodb+srv://

**Comment by BattleDash** [comment]
Yes, it's a srv connection, I tried adding mongodb+srv:// to the start of the address in config and it threw another error I think it was related to parsing the text or something not home so not sure.

**Comment by electronicboy** [comment]
What error?

**Comment by BattleDash** [comment]
Not home and I never took any screenshots, but it was referencing the "//" in the address string so I don't think custom prefixes are supported by LP

**Comment by BattleDash** [comment]
I just don't get how I got this to work before, it's on an old HDD and when I tried to find it on it I couldn't but I distinctively remember having LP set up with this exact same database before

**Comment by lucko** [comment]
Sorry, but I don't think the issue is with LP here.
