### ISSUE TITLE
Errors with the legacy api extension

### ISSUE THREAD

**Issue by ApertureDevelopment** [lucko/LuckPerms#1850]
Two users reported errors involving that classes could not be found from the legacy api extension

```
> [23:36:23 INFO]: [NametagEdit] Found LuckPerms! Hooking in.
> [23:36:23 ERROR]: Error occurred while enabling NametagEdit v4.4.0 (Is it up to date?)
java.lang.NoClassDefFoundError: me.lucko.luckperms.LuckPerms
at com.nametagedit.plugin.hooks.HookLuckPerms.<init>(HookLuckPerms.java:19) ~[?:?]
at com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:54) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_222]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.LuckPerms
at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_222]
```
and:
```
[23:11:22 ERROR]: [LuckPerms] Exception whilst executing command: [help]
> [23:11:22 WARN]: java.lang.NoClassDefFoundError: Could not initialize class me.lucko.luckperms.lib.text.adapter.bukkit.TextAdapter0
> [23:11:22 WARN]: at me.lucko.luckperms.lib.text.adapter.bukkit.TextAdapter.sendComponent(TextAdapter.java:59)
> [23:11:22 WARN]: at me.lucko.luckperms.lib.text.adapter.bukkit.TextAdapter.sendComponent(TextAdapter.java:49)
> [23:11:22 WARN]: at me.lucko.luckperms.bukkit.BukkitSenderFactory.sendMessage(BukkitSenderFactory.java:82)
> [23:11:22 WARN]: at me.lucko.luckperms.bukkit.BukkitSenderFactory.sendMessage(BukkitSenderFactory.java:45)
> [23:11:22 WARN]: at me.lucko.luckperms.common.sender.AbstractSender.sendMessage(AbstractSender.java:102)
> [23:11:22 WARN]: at me.lucko.luckperms.common.command.CommandManager.lambda$sendCommandUsage$12(CommandManager.java:288)
> [23:11:22 WARN]: at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> [23:11:22 WARN]: at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
> [23:11:22 WARN]: at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
> [23:11:22 WARN]: at java.util.Iterator.forEachRemaining(Iterator.java:116)
> [23:11:22 WARN]: at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
> [23:11:22 WARN]: at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
> [23:11:22 WARN]: at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
> [23:11:22 WARN]: at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> [23:11:22 WARN]: at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> [23:11:22 WARN]: at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> [23:11:22 WARN]: at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> [23:11:22 WARN]: at me.lucko.luckperms.common.command.CommandManager.sendCommandUsage(CommandManager.java:273)
> [23:11:22 WARN]: at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:188)
> [23:11:22 WARN]: at me.lucko.luckperms.common.command.CommandManager.lambda$onCommand$0(CommandManager.java:145)
> [23:11:22 WARN]: at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
> [23:11:22 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [23:11:22 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [23:11:22 WARN]: at java.lang.Thread.run(Thread.java:748)
```

Both followed the manual from the wiki for the installation of the legacy API and yet this error still occured.

**Comment by Andre601** [comment]
`java.lang.NoClassDefFoundError: me.lucko.luckperms.LuckPerms`
This seems weird as I remember the path being `me.lucko.luckperms.LuckPermsApi` in v4...

**Comment by BrainStone** [comment]
In other words they didn’t install the extension correctly

**Comment by lucko** [comment]
Yeah, are you sure the extension is installed correctly? First error you posted suggests it didn't load correctly.

Second error is unrelated, can you try deleting the `/LuckPerms/libs` folder and restarting your server.

**Comment by ApertureDevelopment** [comment]
Those are not my errors, I was just redirecting the error here. The user for the first error provided a screenshot of a folder structure, showing that the legacy api extension was in the correct folder and installed. He used a Debian Docker container with paper spigot and the latest LP. I was unable to test it yet and wont be able to test it until tomorrow.

The second one, I will redirect the solution to him tomorrow when I have time again.
