### ISSUE TITLE
Table 'luckperms.luckperms_messenger' doesn't exist in engine

### ISSUE THREAD

**Issue by Jimmy-Painter** [lucko/LuckPerms#1872]
Hello, I'm wondering if someone could shine some light on this issue I'm having on my Bungeecord proxy. This is my first time venturing into the world of databases so I'm still trying to figure some of this stuff out. I have a local MariaDB database that is holding all the permissions for the server. The proxy, survival world, and creative world are all linked to it. All servers are running the latest versions of 1.15 from Spigot and this is also the newest version of Bungee. The Bungeecord proxy throws this error from Luckperms every time the proxy starts. Neither of the Spigot servers has issues on startup. I've looked around for solutions to the problem but I wasn't able to find anything, maybe I was looking in the wrong place. How would I go about fixing this? Thanks!

```
21:51:43 [INFO] Using standard Java JCE cipher.
21:51:43 [INFO] Using standard Java compressor.
21:51:43 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.15-SNAPSHOT:4cccf53:1426
21:51:45 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
21:51:45 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
21:51:45 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
21:51:45 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
21:51:45 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
21:51:45 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
21:51:45 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.15-SNAPSHOT:4cccf53:1426 by SpigotMC
21:51:45 [INFO] Loaded plugin LuckPerms version 5.0.16 by Luck
21:51:45 [INFO] Loaded plugin cmd_find version git:cmd_find:1.15-SNAPSHOT:4cccf53:1426 by SpigotMC
21:51:45 [INFO] Loaded plugin cmd_server version git:cmd_server:1.15-SNAPSHOT:4cccf53:1426 by SpigotMC
21:51:45 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.15-SNAPSHOT:4cccf53:1426 by SpigotMC
21:51:45 [INFO] Loaded plugin cmd_send version git:cmd_send:1.15-SNAPSHOT:4cccf53:1426 by SpigotMC
21:51:45 [INFO] Loaded plugin cmd_list version git:cmd_list:1.15-SNAPSHOT:4cccf53:1426 by SpigotMC
21:51:45 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.15-SNAPSHOT:4cccf53:1426 by SpigotMC
21:51:45 [INFO]         __
21:51:45 [INFO]   |    |__)   LuckPerms v5.0.16
21:51:45 [INFO]   |___ |      Running on BungeeCord - BungeeCord
21:51:45 [INFO]
21:51:45 [INFO] [LuckPerms] Loading configuration...
21:51:47 [INFO] [LuckPerms] Loading storage provider... [MARIADB]
21:51:47 [SEVERE] [main] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Starting...
21:51:47 [SEVERE] [main] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Start completed.
21:51:47 [INFO] [LuckPerms] Loading messaging service... [SQL]
21:51:48 [WARNING] [LuckPerms] Messaging service 'sql' not recognised.
21:51:48 [SEVERE] java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: (conn=9204) Table 'luckperms.luckperms_messenger' doesn't exist in engine
21:51:48 [SEVERE]     at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:57)
21:51:48 [SEVERE]     at me.lucko.luckperms.common.messaging.MessagingFactory$SqlMessengerProvider.obtain(MessagingFactory.java:144)
21:51:48 [SEVERE]     at me.lucko.luckperms.common.messaging.LuckPermsMessagingService.<init>(LuckPermsMessagingService.java:73)
21:51:48 [SEVERE]     at me.lucko.luckperms.common.messaging.MessagingFactory.getServiceFor(MessagingFactory.java:105)
21:51:48 [SEVERE]     at me.lucko.luckperms.bungee.messaging.BungeeMessagingFactory.getServiceFor(BungeeMessagingFactory.java:64)
21:51:48 [SEVERE]     at me.lucko.luckperms.common.messaging.MessagingFactory.getInstance(MessagingFactory.java:83)
21:51:48 [SEVERE]     at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:146)
21:51:48 [SEVERE]     at me.lucko.luckperms.bungee.LPBungeeBootstrap.onEnable(LPBungeeBootstrap.java:124)
21:51:48 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:247)
21:51:48 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:279)
21:51:48 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
21:51:48 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
21:51:48 [SEVERE] Caused by: java.sql.SQLSyntaxErrorException: (conn=9204) Table 'luckperms.luckperms_messenger' doesn't exist in engine
21:51:48 [SEVERE]     at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:243)
21:51:48 [SEVERE]     at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
21:51:48 [SEVERE]     at me.lucko.luckperms.lib.mariadb.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:258)
21:51:48 [SEVERE]     at me.lucko.luckperms.lib.mariadb.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:225)
21:51:48 [SEVERE]     at me.lucko.luckperms.lib.mariadb.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:145)
21:51:48 [SEVERE]     at me.lucko.luckperms.lib.mariadb.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:159)
21:51:48 [SEVERE]     at me.lucko.luckperms.lib.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
21:51:48 [SEVERE]     at me.lucko.luckperms.lib.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
21:51:48 [SEVERE]     at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.init(AbstractSqlMessenger.java:62)
21:51:48 [SEVERE]     at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:55)
21:51:48 [SEVERE]     ... 11 more
21:51:48 [SEVERE] Caused by: java.sql.SQLException: Table 'luckperms.luckperms_messenger' doesn't exist in engine
21:51:48 [SEVERE]     at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1599)
21:51:48 [SEVERE]     at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1461)
21:51:48 [SEVERE]     at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1424)
21:51:48 [SEVERE]     at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:240)
21:51:48 [SEVERE]     at me.lucko.luckperms.lib.mariadb.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:216)
21:51:48 [SEVERE]     ... 17 more
21:51:48 [INFO] [LuckPerms] Loading internal permission managers...
21:51:48 [INFO] [LuckPerms] Performing initial data load...
21:51:49 [INFO] [LuckPerms] Successfully enabled. (took 3760ms)
21:51:49 [INFO] Enabled plugin LuckPerms version 5.0.16 by Luck
21:51:49 [INFO] Enabled plugin cmd_find version git:cmd_find:1.15-SNAPSHOT:4cccf53:1426 by SpigotMC
21:51:49 [INFO] Enabled plugin cmd_server version git:cmd_server:1.15-SNAPSHOT:4cccf53:1426 by SpigotMC
21:51:49 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.15-SNAPSHOT:4cccf53:1426 by SpigotMC
21:51:49 [INFO] Enabled plugin cmd_send version git:cmd_send:1.15-SNAPSHOT:4cccf53:1426 by SpigotMC
21:51:49 [INFO] Enabled plugin cmd_list version git:cmd_list:1.15-SNAPSHOT:4cccf53:1426 by SpigotMC
21:51:50 [INFO] Listening on /0.0.0.0:25565
```

**Comment by lucko** [comment]
Strange, the table should exist as it is created just before the error occurs.

https://github.com/lucko/LuckPerms/blob/7474842b45729e7c5dea8313dcd6b70bdf402725/common/src/main/java/me/lucko/luckperms/common/messaging/sql/AbstractSqlMessenger.java#L57-L62

error is from line 62 ^^

I wonder whether this is related to 86a15b9a66f2ce1d8436f3285d6432eea34065b2

Any ideas @electron93 ?

**Comment by electron93** [comment]
@lucko Probably the cause here is a damaged table. @Jimmy-Painter Are you sure that sql is selected as a message service on all your servers? Because it is strange that the error only occurs with Bungee.

And try to execute this sql query manually. If this error occurs, then you should probably think about ways to restore the table.
```sql
SELECT MAX(`id`) as `latest` FROM `luckperms_messenger`;
```

**Comment by lucko** [comment]
Well, it can be "restored" by just deleting it, the plugin should recreate it automatically.

It doesn't contain critically important data.

**Comment by Jimmy-Painter** [comment]
Fixed the issue, the messaging service in the bungee config was set to 'SQL' while the messaging service for the servers was set to 'bungee'. I switched 'SQL' out for 'bungee' in the Luckperms bungee config and everything is working fine now. Thanks for the help guys!
