### ISSUE TITLE
Nukkit API Problem

### ISSUE THREAD

**Issue by NTY666233** [lucko/LuckPerms#1898]
I used the nukkit version of luckperms(newest),but I had some problems on placeholderapi.I can't distinguish that on luckperms or placeholderapi even if nukkit.Plz help me.
Here is the Error:
Throwing
java.lang.RuntimeException: java.lang.IllegalStateException: API is not loaded.
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:443) [server.jar:?]
at cn.nukkit.Server.enablePlugin(Server.java:733) [server.jar:?]
at cn.nukkit.Server.enablePlugins(Server.java:722) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:558) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:112) [server.jar:?]
Caused by: java.lang.IllegalStateException: API is not loaded.
at me.lucko.luckperms.LuckPerms.getApi(LuckPerms.java:55) ~[?:?]
at com.creeperface.nukkitx.placeholders.providers.LuckPermsProvider.registerPlaceholders(LuckPermsProvider.kt:19) ~[?:?]
at com.creeperface.nukkitx.placeholders.Placeholders.onEnable(Placeholders.kt:24) ~[?:?]
at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[server.jar:?]
at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[server.jar:?]
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) ~[server.jar:?]
... 4 more

**Comment by BrainStone** [comment]
That’s an issue with the Placeholder plugin.
