### ISSUE TITLE
Invalid plugin.yml error with Legacy Api Extentsion 1.0.0

### ISSUE THREAD

**Issue by quorn23** [lucko/LuckPerms#1899]
`[06:37:00 ERROR]: Could not load 'plugins\extension-legacy-api-1.0.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:159) ~[patched_1.15.1.jar:git-Paper-29]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:142) ~[patched_1.15.1.jar:git-Paper-29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:356) ~[patched_1.15.1.jar:git-Paper-29]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.15.1.jar:git-Paper-29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-29]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more`

LP 5.0 starts fine, one plugin crashed so i downloaded the extentsion until it gets updated, sadly the api extention won't start, just throws this error.

**Comment by BrainStone** [comment]
https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5#installing-the-extension

**Comment by quorn23** [comment]
Oh wow, looks like i need sleep, thanks!
