### ISSUE TITLE
extension-default-assignments Not work

### ISSUE THREAD

**Issue by successed** [lucko/LuckPerms#1904]
```
[17:46:17] [Server thread/INFO]: [LuckPerms] Loading extension: me.lucko.luckperms.extension.defaultassignments.DefaultAssignmentsExtension (extension-default-assignments-1.0.0.jar)
[17:46:17] [Server thread/ERROR]: Error occurred while enabling LuckPerms v5.0.39 (Is it up to date?)
java.lang.RuntimeException: java.lang.IllegalAccessException: Class me.lucko.luckperms.extension.defaultassignments.DefaultAssignmentsExtension can not access a member of class me.lucko.luckperms.common.api.LuckPermsApiProvider with modifiers "private final"
	at me.lucko.luckperms.extension.defaultassignments.DefaultAssignmentsExtension.load(DefaultAssignmentsExtension.java:43) ~[?:?]
	at me.lucko.luckperms.common.extension.SimpleExtensionManager.loadExtension(SimpleExtensionManager.java:173) ~[?:?]
	at me.lucko.luckperms.common.extension.SimpleExtensionManager.lambda$loadExtensions$1(SimpleExtensionManager.java:97) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_232]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_232]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647) ~[?:1.8.0_232]
	at me.lucko.luckperms.common.extension.SimpleExtensionManager.loadExtensions(SimpleExtensionManager.java:94) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:181) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:155) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-237]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-237]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-237]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-237]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-237]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:227) ~[patched_1.14.4.jar:git-Paper-237]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-237]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.IllegalAccessException: Class me.lucko.luckperms.extension.defaultassignments.DefaultAssignmentsExtension can not access a member of class me.lucko.luckperms.common.api.LuckPermsApiProvider with modifiers "private final"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102) ~[?:1.8.0_232]
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296) ~[?:1.8.0_232]
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288) ~[?:1.8.0_232]
	at java.lang.reflect.Field.get(Field.java:390) ~[?:1.8.0_232]
	at me.lucko.luckperms.extension.defaultassignments.DefaultAssignmentsExtension.getConfigurationAdapter(DefaultAssignmentsExtension.java:94) ~[?:?]
	at me.lucko.luckperms.extension.defaultassignments.DefaultAssignmentsExtension.load(DefaultAssignmentsExtension.java:41) ~[?:?]
	... 16 more
```

Extension version : extension-default-assignments-1.0.0
Luckperm version : 5.0.39
Server version Paper-237 - 1.14.4

Luckperm Config:

[config.txt](https://github.com/lucko/LuckPerms/files/4008173/config.txt)

**Comment by Andre601** [comment]
You don't provide enough information for us to actually help you.
Please make sure you provide the following information:
- Any error you encountered (Upload the content of your logs on https://hasteb.in or similar and not directly to the GitHub issue)
- What Server or Proxy type are you running?
  - What is the version of it?
- What LuckPerms version are you running?
- What are your config settings? (Remove any potentially sensitive data like passwords before sharing the file)

### Additional Links/Information
**Synchronizing groups, permissions, etc. accross servers**:
https://github.com/lucko/LuckPerms/wiki/Network-Installation

**Setup prefixes/suffixes and display them in chat, tablist, etc.**:
https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta

**Storage system errors (MySQL/MariaDB related errors)**:
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors

**Comment by lucko** [comment]
Should be fixed by https://github.com/LuckPerms/extension-default-assignments/commit/7ef88fda63c3deaddbf999fc5275f56197c682c6

https://ci.lucko.me/job/extension-default-assignments/2/

**Comment by successed** [comment]
> Should be fixed by [LuckPerms/extension-default-assignments@7ef88fd](https://github.com/LuckPerms/extension-default-assignments/commit/7ef88fda63c3deaddbf999fc5275f56197c682c6)
> 
> https://ci.lucko.me/job/extension-default-assignments/2/

Is there anything I can do?

**Comment by lucko** [comment]
Sorry, my bad - try this one.

https://ci.lucko.me/job/extension-default-assignments/3/
