### ISSUE TITLE
Can't open web editor with /lp editor

### ISSUE THREAD

**Issue by totoshogun** [lucko/LuckPerms#1912]
Hi i seem to be getting an error when i try to open the web editor, this the error i get:

[13:00:35] [Server thread/INFO]: Oran1_ issued server command: /lp editor
[13:00:35] [pool-9-thread-1/WARN]: java.lang.RuntimeException: Request was unsuccessful: 403 - Forbidden
[13:00:35] [pool-9-thread-1/WARN]: at me.lucko.luckperms.common.web.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:49)
[13:00:35] [pool-9-thread-1/WARN]: at me.lucko.luckperms.common.web.BytebinClient.makeHttpRequest(BytebinClient.java:69)
[13:00:35] [pool-9-thread-1/WARN]: at me.lucko.luckperms.common.web.BytebinClient.postContent(BytebinClient.java:94)
[13:00:35] [pool-9-thread-1/WARN]: at me.lucko.luckperms.common.web.WebEditor.post(WebEditor.java:138)
[13:00:35] [pool-9-thread-1/WARN]: at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:132)
[13:00:35] [pool-9-thread-1/WARN]: at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:50)
[13:00:35] [pool-9-thread-1/WARN]: at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:42)
[13:00:35] [pool-9-thread-1/WARN]: at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:210)
[13:00:35] [pool-9-thread-1/WARN]: at me.lucko.luckperms.common.command.CommandManager.lambda$onCommand$0(CommandManager.java:145)
[13:00:35] [pool-9-thread-1/WARN]: at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[13:00:35] [pool-9-thread-1/WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[13:00:35] [pool-9-thread-1/WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[13:00:35] [pool-9-thread-1/WARN]: at java.lang.Thread.run(Thread.java:745)

-And once i log off the game i get this error:
[13:05:35] [OkHttp ConnectionPool/WARN]: [me.lucko.luckperms.lib.okhttp3.OkHttpClient] A connection to https://bytebin.lucko.me/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);

**Comment by BrainStone** [comment]
Are you behind a proxy by any chance?

Also what LP version?

**Comment by totoshogun** [comment]
no i am not using any proxy and its the newest version LuckPerms-Bukkit-5.0.50

**Comment by TauCubed** [comment]
On your server, does your Firewall block (outgoing) HTTP? ports: (80 & 443)
Are you running any software like nginx? (reverse proxy)

**Comment by totoshogun** [comment]
no it allows https like urls, i have a plugin that has links on signs and that works fine so not sure but this only happened recently and it was working two or three days ago

**Comment by electronicboy** [comment]
"links on signs" is irrelevant if you mean that people open them in their clients, your issue is that the connection to the bytebin is blocked somewhere, either down to something on your end or something with the web-servers setup (Which is why "how" are you hosting the server is somewhat important to know)

**Comment by totoshogun** [comment]
No idea how the server is hosted as i just paid for the server host lol and again it wouldn't make much sense that it was working two or three days ago but now isn't...  i did also try going back a version and still nothing so not sure.

**Comment by TGaming9872** [comment]
i aslo have a error 403 - Forbidden . was working the other week now its not

**Comment by totoshogun** [comment]
Ok for some unknown reason it now works fine again... o_O  i didn't do anything lol

**Comment by lucko** [comment]
Most likely Cloudflare blocking your requests. Not much I can do about that though..
