### ISSUE TITLE
Rebuilding my servers from scratch keep getting this error on both bungee and spigot

### ISSUE THREAD

**Issue by thephatcrew** [lucko/LuckPerms#1948]
Bungee Error

08:43:54 [INFO] Enabled plugin HubBasics version 6.9.5 by Fabricio20
--
08:43:54 [INFO] §b §3 __
08:43:54 [INFO] §b \| §3\|__) §2LuckPerms §bv5.0.63
08:43:54 [INFO] §b \|___ §3\| §8Running on BungeeCord - BungeeCord
08:43:54 [INFO]
08:43:54 [INFO] [LuckPerms] Loading configuration...
08:43:54 [WARNING] Exception encountered when loading plugin: LuckPerms
java.lang.UnsatisfiedLinkError: sun.nio.fs.LinuxWatchService.inotifyInit()I
at sun.nio.fs.LinuxWatchService.inotifyInit(Native Method)
at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:59)
at sun.nio.fs.BsdFileSystem.newWatchService(BsdFileSystem.java:51)
at me.lucko.luckperms.common.storage.implementation.file.FileWatcher.<init>(FileWatcher.java:65)
at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:140)
at me.lucko.luckperms.bungee.LPBungeeBootstrap.onEnable(LPBungeeBootstrap.java:125)
at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:280)
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
08:43:54 [INFO] Enabled plugin cmd_find version git:cmd_find:1.15-SNAPSHOT:129884f:1451 by SpigotMC
08:43:54 [INFO] Enabled plugin cmd_server version git:cmd_server:1.15-SNAPSHOT:129884f:1451 by SpigotMC
08:43:54 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.15-SNAPSHOT:129884f:1451 by SpigotMC
08:43:54 [INFO] Enabled plugin cmd_send version git:cmd_send:1.15-SNAPSHOT:129884f:1451 by SpigotMC
08:43:54 [INFO] Enabled plugin cmd_list version git:cmd_list:1.15-SNAPSHOT:129884f:1451 by SpigotMC
08:43:54 [INFO] Listening on /0.0.0.0:25565

Spigot Error
[08:51:36] [Server thread/INFO]: Starting minecraft server version 1.15.1
--
[08:51:36] [Server thread/INFO]: Loading properties
[08:51:37] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-037559e-5c6b0dc (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
[08:51:37] [Server thread/INFO]: Debug logging is disabled
[08:51:37] [Server thread/INFO]: Server Ping Player Sample Count: 12
[08:51:37] [Server thread/INFO]: Using 4 threads for Netty based IO
[08:51:37] [Server thread/INFO]: Default game type: SURVIVAL
[08:51:37] [Server thread/INFO]: Generating keypair
[08:51:38] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:25566
[08:51:39] [Server thread/INFO]: Using default channel type
[08:51:47] [Server thread/INFO]: [HubBasics] Loading HubBasics v6.9.5
[08:51:47] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.0.63
[08:51:49] [Server thread/INFO]: [Vault] Loading Vault v1.7.2-b107
[08:51:49] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.0.63
[08:51:49] [Server thread/INFO]: __
[08:51:49] [Server thread/INFO]: \| \|__) LuckPerms v5.0.63
[08:51:49] [Server thread/INFO]: \|___ \| Running on Bukkit - CraftBukkit
[08:51:49] [Server thread/INFO]:
[08:51:49] [Server thread/INFO]: [LuckPerms] Loading configuration...
[08:51:50] [Server thread/ERROR]: Error occurred while enabling LuckPerms v5.0.63 (Is it up to date?)
java.lang.UnsatisfiedLinkError: sun.nio.fs.LinuxWatchService.inotifyInit()I
at sun.nio.fs.LinuxWatchService.inotifyInit(Native Method) ~[?:1.8.0_242]
at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:59) ~[?:1.8.0_242]
at sun.nio.fs.BsdFileSystem.newWatchService(BsdFileSystem.java:51) ~[?:1.8.0_242]
at me.lucko.luckperms.common.storage.implementation.file.FileWatcher.<init>(FileWatcher.java:65) ~[?:?]
at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:140) ~[?:?]
at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:155) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:783) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[08:51:50] [Server thread/INFO]: [Vault] Enabling Vault v1.7.2-b107
[08:51:50] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[08:51:50] [Server thread/INFO]: [Vault] Enabled Version 1.7.2-b107

**Comment by thephatcrew** [comment]
[latest.log](https://github.com/lucko/LuckPerms/files/4097939/latest.log)

**Comment by Andre601** [comment]
What Java version do you use?
Do you make sure that LP can download files? It downloads specific dependencies on first startup.

**Comment by thephatcrew** [comment]
I am currently using mineos in freenas ill post more information soon

**Comment by thephatcrew** [comment]
this is the java information that came up.

https://hasteb.in/efadijam.md

**Comment by Andre601** [comment]
Are you using CraftBukkit?
Try to update to Spigot or [Paper](https://papermc.io) (second one is recommendet)

**Comment by thephatcrew** [comment]
one sec I thought I was using spigot

**Comment by thephatcrew** [comment]
I was using spigot but switch to paper to see if it would fix it and still got the same error. https://hasteb.in/eraqazeg.md

**Comment by Andre601** [comment]
From my understanding is the `UnsatisfiedLinkError` that LP throws caused by a library missing.
This library could either be one from Java (most likely in this case) or from a dependency that LP downloads.

Make sure that LP is able to download the files.
Stop the server, delete the `lib` folder in the LuckPerms folder (if present) and start the server again.

But like I said is this most likely a missing library from Java itself.
What system is the server running? Linux? Ubuntu?

**Comment by thephatcrew** [comment]
Freenas runs on Freebsd

**Comment by Andre601** [comment]
Then it's probably an issue with either FreeBsd or Java.

**Comment by thephatcrew** [comment]
im going to backup all my files delete this jail and start all over and see if that works.
