### ISSUE TITLE
LuckPerms breaking other plugins

### ISSUE THREAD

**Issue by PatBoi** [lucko/LuckPerms#1954]
So when restarting my server I get this error printed on my console:

```
[21:22:31 ERROR]: Error occurred while enabling Prison v3.2.0 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms
at tech.mcprison.prison.spigot.permissions.LuckPermissions.<init>(LuckPermissions.java:20) ~[?:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212]
at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_212]
at tech.mcprison.prison.spigot.SpigotPrison.registerIntegration(SpigotPrison.java:235) ~[?:?]
at tech.mcprison.prison.spigot.SpigotPrison.initIntegrations(SpigotPrison.java:224) ~[?:?]
at tech.mcprison.prison.spigot.SpigotPrison.onEnable(SpigotPrison.java:113) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.1.jar:git-Paper-45]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.1.jar:git-Paper-45]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-45]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-45]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-45]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.1.jar:git-Paper-45]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.1.jar:git-Paper-45]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-45]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.LuckPerms
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.15.1.jar:git-Paper-45]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.15.1.jar:git-Paper-45]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
... 18 more
[21:22:31 INFO]: [Prison] Disabling Prison v3.2.0
```

here is the full console log https://gist.github.com/PatBoi/dc614f0fcefcdc56ac2a3cc8a1f4531e

So all plugins including LuckPerms works but the Prison plugin is breaking and I am assuming it is because of LuckPerms.. according to the logs.. I used PermissionEx before I discovered LuckPerms and now when started using LuckPerms, Prison broke.

**Comment by Andre601** [comment]
Are you using LP v5?
Then take a look at the migration guide on the wiki about moving from v4 to v5.

**Comment by PatBoi** [comment]
Seems like it has fixed my issue. Thank you.
