### ISSUE TITLE
When I stop my server this Error just appear.How to fix this@@?

### ISSUE THREAD

**Issue by TaiwanKHJHGTea** [lucko/LuckPerms#1970]
```
[23:16:38 INFO]: [LuckPerms] Disabling LuckPerms v5.0.39
[23:16:38 INFO]: [LuckPerms] Closing storage...
[23:16:39 INFO]: [LuckPerms] Shutting down internal scheduler...
[23:16:39 INFO]: [LuckPerms] Goodbye!
[23:16:39 WARN]: java.util.ConcurrentModificationException
[23:16:39 WARN]:        at java.util.HashMap$ValueSpliterator.tryAdvance(Unknown Source)
[23:16:39 WARN]:        at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
[23:16:39 WARN]:        at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
[23:16:39 WARN]:        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[23:16:39 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[23:16:39 WARN]:        at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
[23:16:39 WARN]:        at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
[23:16:39 WARN]:        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[23:16:39 WARN]:        at java.util.stream.ReferencePipeline.anyMatch(Unknown Source)
[23:16:39 WARN]:        at io.izzel.taboolib.module.packet.channel.ChannelExecutor$ChannelHandler.write(ChannelExecutor.java:54)
[23:16:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[23:16:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[23:16:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[23:16:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[23:16:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[23:16:39 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[23:16:39 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[23:16:39 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[23:16:39 WARN]:        at net.minecraft.server.v1_15_R1.NetworkManager.lambda$b$4(NetworkManager.java:205)
[23:16:39 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[23:16:39 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[23:16:39 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[23:16:39 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[23:16:39 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[23:16:39 WARN]:        at java.lang.Thread.run(Unknown Source)
[23:16:39 WARN]: java.util.ConcurrentModificationException
[23:16:39 WARN]:        at java.util.HashMap$ValueSpliterator.tryAdvance(Unknown Source)
[23:16:39 WARN]:        at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
[23:16:39 WARN]:        at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
[23:16:39 WARN]:        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[23:16:39 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[23:16:39 WARN]:        at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
[23:16:39 WARN]:        at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
[23:16:39 WARN]:        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[23:16:39 WARN]:        at java.util.stream.ReferencePipeline.anyMatch(Unknown Source)
[23:16:39 WARN]:        at io.izzel.taboolib.module.packet.channel.ChannelExecutor$ChannelHandler.write(ChannelExecutor.java:54)
[23:16:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[23:16:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[23:16:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[23:16:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[23:16:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[23:16:39 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[23:16:39 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[23:16:39 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[23:16:39 WARN]:        at net.minecraft.server.v1_15_R1.NetworkManager.lambda$b$4(NetworkManager.java:205)
[23:16:39 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[23:16:39 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[23:16:39 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[23:16:39 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[23:16:39 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[23:16:39 WARN]:        at java.lang.Thread.run(Unknown Source)
[23:16:39 INFO]: Saving players
```

**Comment by lucko** [comment]
Issue is with `io.izzel.taboolib`, not LuckPerms.
