### ISSUE TITLE
[LP] A database error occurred whilst loading permissions data. Please try again later.

### ISSUE THREAD

**Issue by Maorct** [lucko/LuckPerms#1988]
```
[LuckPerms] Failed to init storage implementation
[11:52:59] [Server thread/WARN]: org.h2.jdbc.JdbcSQLNonTransientException: IO Exception: null [90028-199]
[11:52:59] [Server thread/WARN]: 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
[11:52:59] [Server thread/WARN]: 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
[11:52:59] [Server thread/WARN]: 	at org.h2.message.DbException.get(DbException.java:194)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:197)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:173)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
[11:52:59] [Server thread/WARN]: 	at org.h2.engine.Database.getPageStore(Database.java:2739)
[11:52:59] [Server thread/WARN]: 	at org.h2.engine.Database.open(Database.java:769)
[11:52:59] [Server thread/WARN]: 	at org.h2.engine.Database.openDatabase(Database.java:319)
[11:52:59] [Server thread/WARN]: 	at org.h2.engine.Database.<init>(Database.java:313)
[11:52:59] [Server thread/WARN]: 	at org.h2.engine.Engine.openSession(Engine.java:69)
[11:52:59] [Server thread/WARN]: 	at org.h2.engine.Engine.openSession(Engine.java:201)
[11:52:59] [Server thread/WARN]: 	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
[11:52:59] [Server thread/WARN]: 	at org.h2.engine.Engine.createSession(Engine.java:161)
[11:52:59] [Server thread/WARN]: 	at org.h2.engine.Engine.createSession(Engine.java:31)
[11:52:59] [Server thread/WARN]: 	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
[11:52:59] [Server thread/WARN]: 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
[11:52:59] [Server thread/WARN]: 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
[11:52:59] [Server thread/WARN]: 	at org.h2.Driver.connect(Driver.java:69)
[11:52:59] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory.getConnection(H2ConnectionFactory.java:83)
[11:52:59] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:154)
[11:52:59] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.Storage.init(Storage.java:114)
[11:52:59] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88)
[11:52:59] [Server thread/WARN]: 	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:147)
[11:52:59] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:155)
[11:52:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[11:52:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[11:52:59] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[11:52:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[11:52:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[11:52:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:223)
[11:52:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[11:52:59] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:52:59] [Server thread/WARN]: Caused by: java.lang.IllegalStateException: Reading from nio:/home/myrs/sc/plugins/LuckPerms/luckperms-h2.mv.db failed; file length 9093120 read length 3072 at 11993014 [1.4.199/1]
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:420)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.FileStore.readFully(FileStore.java:98)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1048)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.MVStore.readPage(MVStore.java:2186)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.MVMap.readPage(MVMap.java:554)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1086)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.Cursor.hasNext(Cursor.java:53)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:793)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.MVStore.<init>(MVStore.java:401)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
[11:52:59] [Server thread/WARN]: 	... 28 more
[11:52:59] [Server thread/WARN]: Caused by: java.io.EOFException
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:408)
[11:52:59] [Server thread/WARN]: 	... 38 more
[11:52:59] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[11:52:59] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[11:52:59] [Server thread/WARN]: java.util.concurrent.CompletionException: org.h2.jdbc.JdbcSQLNonTransientException: IO Exception: null [90028-199]
[11:52:59] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:103)
[11:52:59] [Server thread/WARN]: 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
[11:52:59] [Server thread/WARN]: 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
[11:52:59] [Server thread/WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[11:52:59] [Server thread/WARN]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[11:52:59] [Server thread/WARN]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[11:52:59] [Server thread/WARN]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[11:52:59] [Server thread/WARN]: Caused by: org.h2.jdbc.JdbcSQLNonTransientException: IO Exception: null [90028-199]
[11:52:59] [Server thread/WARN]: 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
[11:52:59] [Server thread/WARN]: 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
[11:52:59] [Server thread/WARN]: 	at org.h2.message.DbException.get(DbException.java:194)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:197)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:173)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
[11:52:59] [Server thread/WARN]: 	at org.h2.engine.Database.getPageStore(Database.java:2739)
[11:52:59] [Server thread/WARN]: 	at org.h2.engine.Database.open(Database.java:769)
[11:52:59] [Server thread/WARN]: 	at org.h2.engine.Database.openDatabase(Database.java:319)
[11:52:59] [Server thread/WARN]: 	at org.h2.engine.Database.<init>(Database.java:313)
[11:52:59] [Server thread/WARN]: 	at org.h2.engine.Engine.openSession(Engine.java:69)
[11:52:59] [Server thread/WARN]: 	at org.h2.engine.Engine.openSession(Engine.java:201)
[11:52:59] [Server thread/WARN]: 	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
[11:52:59] [Server thread/WARN]: 	at org.h2.engine.Engine.createSession(Engine.java:161)
[11:52:59] [Server thread/WARN]: 	at org.h2.engine.Engine.createSession(Engine.java:31)
[11:52:59] [Server thread/WARN]: 	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
[11:52:59] [Server thread/WARN]: 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
[11:52:59] [Server thread/WARN]: 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
[11:52:59] [Server thread/WARN]: 	at org.h2.Driver.connect(Driver.java:69)
[11:52:59] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory.getConnection(H2ConnectionFactory.java:83)
[11:52:59] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:432)
[11:52:59] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$10(Storage.java:194)
[11:52:59] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:98)
[11:52:59] [Server thread/WARN]: 	... 6 more
[11:52:59] [Server thread/WARN]: Caused by: java.lang.IllegalStateException: Reading from nio:/home/myrs/sc/plugins/LuckPerms/luckperms-h2.mv.db failed; file length 9093120 read length 3072 at 11993014 [1.4.199/1]
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:420)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.FileStore.readFully(FileStore.java:98)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1048)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.MVStore.readPage(MVStore.java:2186)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.MVMap.readPage(MVMap.java:554)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1086)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.Cursor.hasNext(Cursor.java:53)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:793)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.MVStore.<init>(MVStore.java:401)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
[11:52:59] [Server thread/WARN]: 	... 24 more
[11:52:59] [Server thread/WARN]: Caused by: java.io.EOFException
[11:52:59] [Server thread/WARN]: 	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:408)
[11:52:59] [Server thread/WARN]: 	... 34 more
[11:53:00] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 4358ms)`

`Disconnecting com.mojang.authlib.GameProfile@4b8c98fc[id=fe28b1fb-c3a6-4b2b-b6fa-b6eebc9548da,name=yang阳哈哈,properties={},legacy=false] (/119.191.87.128:54607): [LP] A database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors.
[12:12:55] [Server thread/INFO]: com.mojang.authlib.GameProfile@4b8c98fc[id=fe28b1fb-c3a6-4b2b-b6fa-b6eebc9548da,name=yang阳哈哈,properties={},legacy=false] (/119.191.87.128:54607) lost connection: [LP] A database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors.
[12:12:57] [User Authenticator #5/ERROR]: [LuckPerms] Exception occurred whilst loading data for fe28b1fb-c3a6-4b2b-b6fa-b6eebc9548da - yang阳哈哈
[12:12:57] [User Authenticator #5/WARN]: java.util.concurrent.CompletionException: org.h2.jdbc.JdbcSQLNonTransientException: IO Exception: null [90028-199]
[12:12:57] [User Authenticator #5/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:90)
[12:12:57] [User Authenticator #5/WARN]: 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[12:12:57] [User Authenticator #5/WARN]: 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
[12:12:57] [User Authenticator #5/WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[12:12:57] [User Authenticator #5/WARN]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[12:12:57] [User Authenticator #5/WARN]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[12:12:57] [User Authenticator #5/WARN]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[12:12:57] [User Authenticator #5/WARN]: Caused by: org.h2.jdbc.JdbcSQLNonTransientException: IO Exception: null [90028-199]
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.message.DbException.get(DbException.java:194)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:197)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:173)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.engine.Database.getPageStore(Database.java:2739)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.engine.Database.open(Database.java:769)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.engine.Database.openDatabase(Database.java:319)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.engine.Database.<init>(Database.java:313)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.engine.Engine.openSession(Engine.java:69)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.engine.Engine.openSession(Engine.java:201)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.engine.Engine.createSession(Engine.java:161)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.engine.Engine.createSession(Engine.java:31)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.Driver.connect(Driver.java:69)
[12:12:57] [User Authenticator #5/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory.getConnection(H2ConnectionFactory.java:83)
[12:12:57] [User Authenticator #5/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.getPlayerName(SqlStorage.java:679)
[12:12:57] [User Authenticator #5/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.savePlayerData(SqlStorage.java:609)
[12:12:57] [User Authenticator #5/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$savePlayerData$20(Storage.java:258)
[12:12:57] [User Authenticator #5/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:85)
[12:12:57] [User Authenticator #5/WARN]: 	... 6 more
[12:12:57] [User Authenticator #5/WARN]: Caused by: java.lang.IllegalStateException: Reading from nio:/home/myrs/sc/plugins/LuckPerms/luckperms-h2.mv.db failed; file length 9093120 read length 3072 at 11993014 [1.4.199/1]
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:420)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.mvstore.FileStore.readFully(FileStore.java:98)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1048)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.mvstore.MVStore.readPage(MVStore.java:2186)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.mvstore.MVMap.readPage(MVMap.java:554)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1086)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.mvstore.Cursor.hasNext(Cursor.java:53)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:793)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.mvstore.MVStore.<init>(MVStore.java:401)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
[12:12:57] [User Authenticator #5/WARN]: 	... 25 more
[12:12:57] [User Authenticator #5/WARN]: Caused by: java.io.EOFException
[12:12:57] [User Authenticator #5/WARN]: 	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:408)
[12:12:57] [User Authenticator #5/WARN]: 	... 35 more
[12:12:57] [User Authenticator #5/INFO]: Disconnecting com.mojang.authlib.GameProfile@600fccc8[id=fe28b1fb-c3a6-4b2b-b6fa-b6eebc9548da,name=yang阳哈哈,properties={},legacy=false] (/119.191.87.128:43301): [LP] A database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors.
[12:12:57] [Server thread/INFO]: com.mojang.authlib.GameProfile@600fccc8[id=fe28b1fb-c3a6-4b2b-b6fa-b6eebc9548da,name=yang阳哈哈,properties={},legacy=false] (/119.191.87.128:43301) lost connection: [LP] A database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors.
[12:12:58] [User Authenticator #5/ERROR]: [LuckPerms] Exception occurred whilst loading data for fe28b1fb-c3a6-4b2b-b6fa-b6eebc9548da - yang阳哈哈
[12:12:58] [User Authenticator #5/WARN]: java.util.concurrent.CompletionException: org.h2.jdbc.JdbcSQLNonTransientException: IO Exception: null [90028-199]
[12:12:58] [User Authenticator #5/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:90)
[12:12:58] [User Authenticator #5/WARN]: 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[12:12:58] [User Authenticator #5/WARN]: 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
[12:12:58] [User Authenticator #5/WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[12:12:58] [User Authenticator #5/WARN]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[12:12:58] [User Authenticator #5/WARN]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[12:12:58] [User Authenticator #5/WARN]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[12:12:58] [User Authenticator #5/WARN]: Caused by: org.h2.jdbc.JdbcSQLNonTransientException: IO Exception: null [90028-199]
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.message.DbException.get(DbException.java:194)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:197)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:173)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.engine.Database.getPageStore(Database.java:2739)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.engine.Database.open(Database.java:769)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.engine.Database.openDatabase(Database.java:319)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.engine.Database.<init>(Database.java:313)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.engine.Engine.openSession(Engine.java:69)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.engine.Engine.openSession(Engine.java:201)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.engine.Engine.createSession(Engine.java:161)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.engine.Engine.createSession(Engine.java:31)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.Driver.connect(Driver.java:69)
[12:12:58] [User Authenticator #5/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory.getConnection(H2ConnectionFactory.java:83)
[12:12:58] [User Authenticator #5/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.getPlayerName(SqlStorage.java:679)
[12:12:58] [User Authenticator #5/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.savePlayerData(SqlStorage.java:609)
[12:12:58] [User Authenticator #5/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$savePlayerData$20(Storage.java:258)
[12:12:58] [User Authenticator #5/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:85)
[12:12:58] [User Authenticator #5/WARN]: 	... 6 more
[12:12:58] [User Authenticator #5/WARN]: Caused by: java.lang.IllegalStateException: Reading from nio:/home/myrs/sc/plugins/LuckPerms/luckperms-h2.mv.db failed; file length 9093120 read length 3072 at 11993014 [1.4.199/1]
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:420)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.mvstore.FileStore.readFully(FileStore.java:98)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1048)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.mvstore.MVStore.readPage(MVStore.java:2186)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.mvstore.MVMap.readPage(MVMap.java:554)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1086)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.mvstore.Cursor.hasNext(Cursor.java:53)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:793)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.mvstore.MVStore.<init>(MVStore.java:401)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
[12:12:58] [User Authenticator #5/WARN]: 	... 25 more
[12:12:58] [User Authenticator #5/WARN]: Caused by: java.io.EOFException
[12:12:58] [User Authenticator #5/WARN]: 	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:408)
[12:12:58] [User Authenticator #5/WARN]: 	... 35 more
[12:12:58] [User Authenticator #5/INFO]: Disconnecting com.mojang.authlib.GameProfile@56aee42c[id=fe28b1fb-c3a6-4b2b-b6fa-b6eebc9548da,name=yang阳哈哈,properties={},legacy=false] (/119.191.87.128:38721): [LP] A database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors.
[12:12:58] [Server thread/INFO]: com.mojang.authlib.GameProfile@56aee42c[id=fe28b1fb-c3a6-4b2b-b6fa-b6eebc9548da,name=yang阳哈哈,properties={},legacy=false] (/119.191.87.128:38721) lost connection: [LP] A database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors.
```
This problem occurred after today's server restart.
Is there a way to fix it?
My server already has thousands of registrations and an average of 100-130 people per day. If this error cannot be fixed, it will be fatal to my server.
plugin 4.4.1 - 5.0.78
server paper1.12.2

**Comment by Feniksovich** [comment]
Paste your error on pastebin.com pls

**Comment by BrainStone** [comment]
Much rather use 3 back ticks to create a code block instead of just one.

**Comment by Maorct** [comment]
https://pastebin.com/xRJdqfTX

**Comment by Maorct** [comment]
The server was up and running for several months before this error occurred.

**Comment by Maorct** [comment]
Is there a way to fix this error or export data?

**Comment by Maorct** [comment]
@Feniksovich

**Comment by BrainStone** [comment]
Looks like the database file somehow got corrupted.  
Do you have a backup of the file? Else it's looking really bad.

**Comment by Maorct** [comment]
There are no backup files because the plug-in is always running well. This error occurred after the server automatically rebooted in the early hours of this morning.

**Comment by Maorct** [comment]
> Looks like the database file somehow got corrupted.
> Do you have a backup of the file? Else it's looking really bad.

I only expected that there would be a problem with MySQL database and gave MySQL backup, but I didn't think that LP's local data would be damaged.
So, if I don't have a fix or I can export the data then I might have to see god in advance.

**Comment by BrainStone** [comment]
The file got corrupted while it was being written to or at least open. So my guess would be that the server either crashed or was forcefully shutdown.  
And recovering corrupted data is really nothing we can help you with. You might have luck reaching out people more invested with the h2 database format.  
And as a note: If LP can't read the data while starting it also can't export anything from it, because that would require being able to read the data.

**Comment by Maorct** [comment]
The plug-in has a file named luckperms-h2.trace.db. Is this useful?

**Comment by BrainStone** [comment]
I don't think so. But I'm not very knowledgeable about the topic.

**Comment by lucko** [comment]
> Looks like the database file somehow got corrupted

Basically this - it's not a LuckPerms issue/bug, unfortunately therefore not something I can help with / fix.

You might be able to fix your database file using the H2 recovery tool.
http://www.h2database.com/html/advanced.html#using_recover_tool
