### ISSUE TITLE
[Question] Warning message on BungeeTabListPlus

### ISSUE THREAD

**Issue by Baktus79** [lucko/LuckPerms#2018]
I know this isnt your problem but I want to ask anyways. Im using BungeeTabListPlus on my BungeeCord but Im getting this warning message. Do you guys know what this means?

```
[WARNING] Exception encountered when loading plugin: BungeeTabListPlus
java.lang.LinkageError: loader (instance of  net/md_5/bungee/api/plugin/PluginClassloader): attempted duplicate class definition for name: "net/luckperms/api/LuckPerms"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass0(PluginClassloader.java:44)
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass0(PluginClassloader.java:56)
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:37)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at de.codecrafter47.data.bungee.PlayerDataAccess.isClassPresent(PlayerDataAccess.java:175)
	at de.codecrafter47.data.bungee.PlayerDataAccess.<init>(PlayerDataAccess.java:107)
	at codecrafter47.bungeetablistplus.managers.DataManager.<init>(DataManager.java:85)
	at codecrafter47.bungeetablistplus.BungeeTabListPlus.onEnable(BungeeTabListPlus.java:255)
	at codecrafter47.bungeetablistplus.BungeePlugin.onEnable(BungeePlugin.java:40)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:280)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

**Comment by Andre601** [comment]
You should ask the dev of BTLP about this as it is an issue with their plugin.

**Comment by Baktus79** [comment]
Yes I know and I did. I noticed that this happens on more than one plugin. Maybe I really should be asking if there was any changes to the API on new releases of LuckPerms?

**Comment by Andre601** [comment]
The only big changes where when v5 was release which was breaking in terms of the API.
But other than that shouldn't there be any (major) changes that would affect the developers of other plugins.
Otherwise Luck would've mentioned this in an announcement or made a release on Spigot, Sponge, etc.

**Comment by Baktus79** [comment]
Yeah, you are right. But thanks for your help :D
