### ISSUE TITLE
Storage keeps disconnecting

### ISSUE THREAD

**Issue by Sotlol1** [lucko/LuckPerms#2037]
Several times a day Luckperms loses connection to my MariaDB storage. I have changed databases several times but it still happens.  None of the other plugins I use have had a connection problem only luck perms do. I have even tried using one of the databases one of my other plugins is on which works correctly but luck perms still lose connection to it. It keeps spamming this every second in my console for hours when it starts.

```
23:04:09] [luckperms-scheduler-worker-21/WARN]: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
> [23:04:09] [luckperms-scheduler-worker-21/WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)
> [23:04:09] [luckperms-scheduler-worker-21/WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
> [23:04:09] [luckperms-scheduler-worker-21/WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
> [23:04:09] [luckperms-scheduler-worker-21/WARN]: at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
> [23:04:09] [luckperms-scheduler-worker-21/WARN]: at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:131)
> [23:04:09] [luckperms-scheduler-worker-21/WARN]: at me.lucko.luckperms.common.messaging.sql.SqlMessenger.getConnection(SqlMessenger.java:85)
> [23:04:09] [luckperms-scheduler-worker-21/WARN]: at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.pollMessages(AbstractSqlMessenger.java:96)
> [23:04:09] [luckperms-scheduler-worker-21/WARN]: at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$ErrorReportingRunnable.run(AbstractJavaScheduler.java:118)
> [23:04:09] [luckperms-scheduler-worker-21/WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [23:04:09] [luckperms-scheduler-worker-21/WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [23:04:09] [luckperms-scheduler-worker-21/WARN]: at java.lang.Thread.run(Thread.java:748)
> [23:04:09] [luckperms-scheduler-worker-21/WARN]: Caused by: java.sql.SQLException: Connection.setNetworkTimeout cannot be called on a closed connection
> [23:04:09] [luckperms-scheduler-worker-21/WARN]: at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionMapper.getSqlException(ExceptionMapper.java:278)
> [23:04:09] [luckperms-scheduler-worker-21/WARN]: at me.lucko.luckperms.lib.mariadb.MariaDbConnection.setNetworkTimeout(MariaDbConnection.java:1624)
> [23:04:09] [luckperms-scheduler-worker-21/WARN]: at me.lucko.luckperms.lib.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:552)
> [23:04:09] [luckperms-scheduler-worker-21/WARN]: at me.lucko.luckperms.lib.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:168)
> [23:04:09] [luckperms-scheduler-worker-21/WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:185)
```

**Comment by lucko** [comment]
Please see here for more info: https://github.com/lucko/LuckPerms/wiki/Storage-system-errors
