### ISSUE TITLE
InterruptedException on shutdown on Velocity proxy

### ISSUE THREAD

**Issue by Techdaan** [lucko/LuckPerms#2044]
I am getting an InterruptedException on Velocity after running the `shutdown` command. 

This can be reproduced on a fresh installation of Velocity v1.0.5 and LuckPerms v5.0.88 by simply installing LuckPerms and running Velocity.

```
java.lang.InterruptedException
      at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
      at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
      at java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:492)
      at java.util.concurrent.LinkedBlockingDeque.take(LinkedBlockingDeque.java:680)
      at sun.nio.fs.AbstractWatchService.take(AbstractWatchService.java:118)
      at me.lucko.luckperms.common.storage.implementation.file.watcher.AbstractFileWatcher.runEventProcessingLoop(AbstractFileWatcher.java:128)
      at me.lucko.luckperms.common.storage.implementation.file.watcher.FileWatcher.lambda$new$0(FileWatcher.java:61)
      at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:186)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      at java.lang.Thread.run(Thread.java:748)
```

**Comment by lucko** [comment]
Safe to ignore the error -- the above commit stops it from being printed to the console.
