### ISSUE TITLE
Error occurred while enabling LuckPerms v5.0.94 (Is it up to date?)

### ISSUE THREAD

**Issue by yonatannebenzhal** [lucko/LuckPerms#2066]
I own a Spigot server, and I get this error in the log every time I try and run the server with LuckPerms in the plugins folder. In game I get "[LP] error occurred whilst loading permissions data. Please
try again later. If you are a server admin. please check the console for any errors". 

My server is running on 1.15.2 and MY LuckPerms version is LuckPerms-Bukkit-5.0.94.

thanks!

**Comment by Andre601** [comment]
There should be an actual error like a stacktrace.
Please provide your logs through https://hasteb.in as we can't see your Server setup, nor read minds.

**Comment by yonatannebenzhal** [comment]
https://hasteb.in/rihotihi.md

**Comment by lucko** [comment]
The noteworthy bit is here:

```
[12:36:05] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.0.94
[12:36:05] [Server thread/INFO]: __
[12:36:05] [Server thread/INFO]: | |__) LuckPerms v5.0.94
[12:36:05] [Server thread/INFO]: |___ | Running on Bukkit - CraftBukkit
[12:36:05] [Server thread/INFO]:
[12:36:05] [Server thread/INFO]: [LuckPerms] Loading configuration...
[12:36:05] [Server thread/ERROR]: Error occurred while enabling LuckPerms v5.0.94 (Is it up to date?)
java.lang.UnsatisfiedLinkError: sun.nio.fs.LinuxWatchService.inotifyInit()I
at sun.nio.fs.LinuxWatchService.inotifyInit(Native Method) ~[?:1.8.0_242]
at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:59) ~[?:1.8.0_242]
at sun.nio.fs.BsdFileSystem.newWatchService(BsdFileSystem.java:51) ~[?:1.8.0_242]
at me.lucko.luckperms.common.storage.implementation.file.watcher.AbstractFileWatcher.<init>(AbstractFileWatcher.java:76) ~[?:?]
at me.lucko.luckperms.common.storage.implementation.file.watcher.FileWatcher.<init>(FileWatcher.java:56) ~[?:?]
at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:136) ~[?:?]
at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:158) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:432) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

It's a JVM error which might be fixed by updating to a newer Java version.

In the meantime I'll add a workaround in LP so the error doesn't stall the whole enable process.

**Comment by BrainStone** [comment]
Not quite. That means that the Java installation is missing some native bindings.  
Purely a java installation issue. Disable auto-updates or report it to your hoster.
