### ISSUE TITLE
Can't work in velocity

### ISSUE THREAD

**Issue by zsn741656478** [lucko/LuckPerms#2069]
> [22:19:25] [main/INFO]: Booting up Velocity 1.0.6-SNAPSHOT (git-5c6163d8-b195)...
[22:19:25] [main/INFO]: Connections will use NIO channels, Java compression, Java ciphers
[22:19:25] [main/INFO]: Proxy is running in offline mode!
[22:19:25] [main/INFO]: Loading plugins...
[22:19:26] [main/ERROR]: Exception in thread "main" com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Lme/lucko/luckperms/api/LuckPermsApi;
[22:19:26] [main/ERROR]: 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2048)
[22:19:26] [main/ERROR]: 	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
[22:19:26] [main/ERROR]: 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3973)
[22:19:26] [main/ERROR]: 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
[22:19:26] [main/ERROR]: 	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4963)
[22:19:26] [main/ERROR]: 	at com.google.inject.internal.FailableCache.get(FailableCache.java:51)
[22:19:26] [main/ERROR]: 	at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:48)
[22:19:26] [main/ERROR]: 	at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:155)
[22:19:26] [main/ERROR]: 	at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:581)
[22:19:26] [main/ERROR]: 	at com.google.inject.internal.AbstractBindingProcessor$Processor$1.run(AbstractBindingProcessor.java:176)
[22:19:26] [main/ERROR]: 	at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:49)
[22:19:26] [main/ERROR]: 	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:122)
[22:19:26] [main/ERROR]: 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
[22:19:26] [main/ERROR]: 	at com.google.inject.Guice.createInjector(Guice.java:87)
[22:19:26] [main/ERROR]: 	at com.google.inject.Guice.createInjector(Guice.java:69)
[22:19:26] [main/ERROR]: 	at com.google.inject.Guice.createInjector(Guice.java:59)
[22:19:26] [main/ERROR]: 	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:77)
[22:19:26] [main/ERROR]: 	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:98)
[22:19:26] [main/ERROR]: 	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:245)
[22:19:26] [main/ERROR]: 	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:205)
[22:19:26] [main/ERROR]: 	at com.velocitypowered.proxy.Velocity.main(Velocity.java:47)
[22:19:26] [main/ERROR]: Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Lme/lucko/luckperms/api/LuckPermsApi;
[22:19:26] [main/ERROR]: 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2048)
[22:19:26] [main/ERROR]: 	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
[22:19:26] [main/ERROR]: 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3973)
[22:19:26] [main/ERROR]: 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
[22:19:26] [main/ERROR]: 	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4963)
[22:19:26] [main/ERROR]: 	at com.google.inject.internal.FailableCache.get(FailableCache.java:51)
[22:19:26] [main/ERROR]: 	at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:65)
[22:19:26] [main/ERROR]: 	at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:74)
[22:19:26] [main/ERROR]: 	at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:29)
[22:19:26] [main/ERROR]: 	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:37)
[22:19:26] [main/ERROR]: 	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:33)
[22:19:26] [main/ERROR]: 	at com.google.inject.internal.FailableCache$1.load(FailableCache.java:40)
[22:19:26] [main/ERROR]: 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
[22:19:26] [main/ERROR]: 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2276)
[22:19:26] [main/ERROR]: 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
[22:19:26] [main/ERROR]: 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
[22:19:26] [main/ERROR]: 	... 20 more
[22:19:26] [main/ERROR]: Caused by: java.lang.NoClassDefFoundError: Lme/lucko/luckperms/api/LuckPermsApi;
[22:19:26] [main/ERROR]: 	at java.lang.Class.getDeclaredFields0(Native Method)
[22:19:26] [main/ERROR]: 	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
[22:19:26] [main/ERROR]: 	at java.lang.Class.getDeclaredFields(Class.java:1916)
[22:19:26] [main/ERROR]: 	at com.google.inject.spi.InjectionPoint.getDeclaredFields(InjectionPoint.java:760)
[22:19:26] [main/ERROR]: 	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:670)
[22:19:26] [main/ERROR]: 	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:378)
[22:19:26] [main/ERROR]: 	at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:88)
[22:19:26] [main/ERROR]: 	at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:36)
[22:19:26] [main/ERROR]: 	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:45)
[22:19:26] [main/ERROR]: 	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:41)
[22:19:26] [main/ERROR]: 	at com.google.inject.internal.FailableCache$1.load(FailableCache.java:40)
[22:19:26] [main/ERROR]: 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
[22:19:26] [main/ERROR]: 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2276)
[22:19:26] [main/ERROR]: 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
[22:19:26] [main/ERROR]: 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
[22:19:26] [main/ERROR]: 	... 35 more
[22:19:26] [main/ERROR]: Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.api.LuckPermsApi
[22:19:26] [main/ERROR]: 	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:66)
[22:19:26] [main/ERROR]: 	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:43)
[22:19:26] [main/ERROR]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[22:19:26] [main/ERROR]: 	... 50 more

**Comment by BrainStone** [comment]
https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5#api-compatibility

**Comment by zsn741656478** [comment]
> https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5#api-compatibility

Thanks.
