### ISSUE TITLE
Problem with Nametagedit

### ISSUE THREAD

**Issue by aleesheyk** [lucko/LuckPerms#2098]
hi, it's been 1 month since I have a problem with another plugin, which is nametagedit, it throws me an error that I can't fix by updating the same plugin, since the updates higher than 4.4.1, they close the server, and check that it is not the plugin nametagedit, even so when I use 4.4.1 of luckperms I get an error with the other plugin and that does not let me use the commands within the game, create the error problem that both plugins have.

[19:04:23 INFO]: [NametagEdit] Found LuckPerms! Hooking in.
[19:04:23 ERROR]: Error occurred while enabling NametagEdit v4.4.6 (Is it up to date?)
 java.lang.NoClassDefFoundError: net/luckperms/api/LuckPermsProvider
        at com.nametagedit.plugin.hooks.HookLuckPerms.<init>(HookLuckPerms.java:19) ~[?:?]
        at com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:54) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) ~[JavaPlugin.class:9d300c6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [JavaPluginLoader.class:9d300c6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399) [SimplePluginManager.class:9d300c6]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:489) [CraftServer.class:9d300c6]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:418) [CraftServer.class:9d300c6]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:384) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:319) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:588) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.ClassNotFoundException: net.luckperms.api.LuckPermsProvider
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:106) ~[PluginClassLoader.class:9d300c6]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:75) ~[PluginClassLoader.class:9d300c6]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        ... 11 more

**Comment by Andre601** [comment]
Please only open one issue (#2097) and consider editing it instead of opening a second one

**Comment by RJHaytree** [comment]
That version of NameTagEdit requires at least LuckPerms 5.0.0. You either need to downgrade NameTagEdit to a version which uses LuckPerms 4.4.1, or you upgrade your LuckPerms to the latest.

If you have plugins that only allow LuckPerms 4.4.1, you can upgrade and try use the legacy expansion. https://github.com/lucko/LuckPerms/wiki/Extensions#extension-legacy-api

**Comment by aleesheyk** [comment]
muchas gracias se me resolvio el problema 

> Please only open one issue (#2097) and consider editing it instead of opening a second one.
> 
> About your issue:
> Use the [lates LuckPerms version](https://luckperms.net) and make sure to read [this page](https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5)
