### ISSUE TITLE
User migration error with PermissionsEx

### ISSUE THREAD

**Issue by iLemon** [lucko/LuckPerms#2102]
```
[11:46:13 INFO]: iLemon issued server command: /lp migration permissionsex
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Starting.
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Calculating group weightings.
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Starting group migration.
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 1 groups so far.
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 2 groups so far.
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 3 groups so far.
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 4 groups so far.
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 5 groups so far.
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 6 groups so far.
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 7 groups so far.
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 8 groups so far.
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 9 groups so far.
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 10 groups so far.
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 11 groups so far.
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 12 groups so far.
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 13 groups so far.
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 14 groups so far.
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 15 groups so far.
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 16 groups so far.
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 17 groups so far.
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 17 groups
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Starting tracks migration.
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Migrated 0 tracks
[11:46:13 INFO]: [LP] MIGRATION [PermissionsEx] > Starting user migration.
[11:46:13 WARN]: java.lang.IllegalStateException: PermissionEntityEvent may only be triggered synchronously.
[11:46:13 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:547)
[11:46:13 WARN]:        at ru.tehkode.permissions.bukkit.PermissionsEx.callEvent(PermissionsEx.java:393)
[11:46:13 WARN]:        at ru.tehkode.permissions.PermissionManager.callEvent(PermissionManager.java:697)
[11:46:13 WARN]:        at ru.tehkode.permissions.PermissionEntity.callEvent(PermissionEntity.java:730)
[11:46:13 WARN]:        at ru.tehkode.permissions.PermissionEntity.callEvent(PermissionEntity.java:734)
[11:46:13 WARN]:        at ru.tehkode.permissions.PermissionEntity.setOption(PermissionEntity.java:499)
[11:46:13 WARN]:        at ru.tehkode.permissions.PermissionUser.updateTimedGroups(PermissionUser.java:603)
[11:46:13 WARN]:        at ru.tehkode.permissions.PermissionUser.initialize(PermissionUser.java:64)
[11:46:13 WARN]:        at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:239)
[11:46:13 WARN]:        at ru.tehkode.permissions.PermissionManager.getUsers(PermissionManager.java:264)
[11:46:13 WARN]:        at me.lucko.luckperms.bukkit.migration.MigrationPermissionsEx.execute(MigrationPermissionsEx.java:171)
[11:46:13 WARN]:        at me.lucko.luckperms.common.command.abstraction.ParentCommand.execute(ParentCommand.java:108)
[11:46:13 WARN]:        at me.lucko.luckperms.common.command.abstraction.ParentCommand.execute(ParentCommand.java:44)
[11:46:13 WARN]:        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:207)
[11:46:13 WARN]:        at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:148)
[11:46:13 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
[11:46:13 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[11:46:13 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[11:46:13 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
```

This is with the latest version of LuckPerms and PermissionsEx 1.23.4

Running on a fork of paper 1.15.2

PEX file backend

**Comment by BrainStone** [comment]
What LuckPerms version?

**Comment by iLemon** [comment]
Latest on spigot, 5.0.72

**Comment by larryb11** [comment]
Try the latest from here, no idea if it will work but maybe: https://luckperms.net/

**Comment by iLemon** [comment]
Tried the latest dev build, 5.0.104. The same error happens.

**Comment by BrainStone** [comment]
Could you try to log off the server? And run the migration from the console?

**Comment by lucko** [comment]
Should be fixed in the above commit.

**Comment by iLemon** [comment]
Tried the latest commit (ver 5.0.106). This time there was no error but LuckPerms stopped responding to any commands and doesn't complete the migration.

https://gist.github.com/iLemon/81e8a2ed501c3a63ad24e09eec5a9d00

**Comment by lucko** [comment]
How big is your PEX file?
