### ISSUE TITLE
LuckPermsBungee and PlaceholderAPI

### ISSUE THREAD

**Issue by AustinR12** [lucko/LuckPerms#2117]
I looked up help on my issue and saw many others had this issue but couldn't find a working solution. I have LuckPermsBungee Version 5.0.108 and PlaceHolderAPI Version 2.10.5. Everytime I try to load in PAPI placeholders I get this error.
I have tried using the extension-legacy-api extension and still getting error.

[14:17:11 WARN]: [PlaceholderAPI] Task #15 for PlaceholderAPI v2.10.5 generated an exception
java.lang.NoClassDefFoundError: net/luckperms/api/LuckPerms
        at me.lucko.luckperms.placeholders.LuckPermsExpansion.canRegister(LuckPermsExpansion.java:48) ~[?:?]
        at me.clip.placeholderapi.expansion.ExpansionManager.registerExpansion(ExpansionManager.java:110) ~[?:?]
        at me.clip.placeholderapi.expansion.ExpansionManager.registerAllExpansions(ExpansionManager.java:173) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPIPlugin.lambda$onEnable$0(PlaceholderAPIPlugin.java:151) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.ClassNotFoundException: net.luckperms.api.LuckPerms
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        ... 11 more

**Comment by BrainStone** [comment]
What LP version do you have on your backend servers?

PAPI and Bungee don't care for eachother.

**Comment by lucko** [comment]
Update LuckPerms on your Spigot server to the latest.
