### ISSUE TITLE
Year 2038 problem

### ISSUE THREAD

**Issue by ozraru** [lucko/LuckPerms#2126]
https://en.wikipedia.org/wiki/Year_2038_problem
I think the data type should be `long` because of the Year 2038 problem
![image](https://user-images.githubusercontent.com/34647405/78017613-7b9eb800-7387-11ea-82c1-03dd1d52b110.png)

Used Google Translate

**Comment by lucko** [comment]
Hah interesting - what error did you get in the console?

**Comment by ozraru** [comment]
![image](https://user-images.githubusercontent.com/34647405/78018056-2c0cbc00-7388-11ea-98c6-86279bf0ffc1.png)

**Comment by ozraru** [comment]
[19:35:43 INFO]: ozraru issued server command: /lp user ozraru parent addtemp owner 2147483648 replace
[19:35:43 INFO]: [LP] LOG > (ozraru) [U] (ozraru)
[19:35:43 INFO]: [LP] LOG > parent addtemp owner PT156064H38M25S
[19:35:43 WARN]: java.util.concurrent.ExecutionException: org.h2.jdbc.JdbcBatchUpdateException: Numeric value out of range: "2147483648" in column "EXPIRY"; SQL statement:
INSERT INTO `luckperms_user_permissions` (uuid, permission, value, server, world, expiry, contexts) VALUES(?, ?, ?, ?, ?, ?, ?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7) [22004-199]
[19:35:43 WARN]:        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
[19:35:43 WARN]:        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
[19:35:43 WARN]:        at me.lucko.luckperms.common.command.utils.StorageAssistant.save(StorageAssistant.java:82)
[19:35:43 WARN]:        at me.lucko.luckperms.common.command.utils.StorageAssistant.save(StorageAssistant.java:134)
[19:35:43 WARN]:        at me.lucko.luckperms.common.commands.generic.parent.ParentAddTemp.execute(ParentAddTemp.java:104)
[19:35:43 WARN]:        at me.lucko.luckperms.common.command.abstraction.GenericParentCommand.execute(GenericParentCommand.java:89)
[19:35:43 WARN]:        at me.lucko.luckperms.common.command.abstraction.GenericParentCommand.execute(GenericParentCommand.java:48)
[19:35:43 WARN]:        at me.lucko.luckperms.common.command.abstraction.ParentCommand.execute(ParentCommand.java:108)
[19:35:43 WARN]:        at me.lucko.luckperms.common.command.abstraction.ParentCommand.execute(ParentCommand.java:44)
[19:35:43 WARN]:        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:202)
[19:35:43 WARN]:        at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:143)
[19:35:43 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
[19:35:43 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[19:35:43 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[19:35:43 WARN]:        at java.lang.Thread.run(Thread.java:748)
[19:35:43 WARN]: Caused by: org.h2.jdbc.JdbcBatchUpdateException: Numeric value out of range: "2147483648" in column "EXPIRY"; SQL statement:
INSERT INTO `luckperms_user_permissions` (uuid, permission, value, server, world, expiry, contexts) VALUES(?, ?, ?, ?, ?, ?, ?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7) [22004-199]
[19:35:43 WARN]:        at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1298)
[19:35:43 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.updateUserPermissions(SqlStorage.java:803)
[19:35:43 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.saveUser(SqlStorage.java:338)
[19:35:43 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$saveUser$5(Storage.java:157)
[19:35:43 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:98)
[19:35:43 WARN]:        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
[19:35:43 WARN]:        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)
[19:35:43 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[19:35:43 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[19:35:43 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[19:35:43 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[19:35:46 INFO]: ozraru issued server command: /lp user ozraru parent addtemp owner 2147483647 replace
[19:35:46 INFO]: [LP] LOG > (ozraru) [U] (ozraru)
[19:35:46 INFO]: [LP] LOG > parent addtemp owner PT156064H38M21S

**Comment by lucko** [comment]
Thanks, will look into fixing this :)

**Comment by ozraru** [comment]
Thanks!

**Comment by lucko** [comment]
Fixed in the above commit.

I haven't added schema migrations for this - but can do so in the future if it becomes a problem.
