### ISSUE TITLE
Internal Error when i do "/papi ecloud download LuckPerms"

### ISSUE THREAD

**Issue by cheesymyst** [lucko/LuckPerms#2128]
Placeholder says it loads the extension, the in red text says "an internal error occurred while attempting to perform this command"
![image](https://user-images.githubusercontent.com/57509631/78081568-7422e300-7376-11ea-9388-0395d8d74a79.png)

**Comment by Andre601** [comment]
Please give us the actual error which is located in the console.
If the error contains something like net.java.ClassDefNotFoundException (or something like that) then try updating to lates version of LuckPerms as you're most likely using an outdated version.

**Comment by cheesymyst** [comment]
Sorry, (btw idk how to understand logs)
this is what i got 
[23:46:01] [Server thread/INFO]: LeEpicCheese issued server command: /papi ecloud download luckperms
[23:46:01] [Server thread/INFO]: [PlaceholderAPI] Attempting download of expansion: LuckPerms by user: LeEpicCheese from url: http://api.extendedclip.com/media/Expansion-LuckPerms_IaULsEO.jar
[23:46:01] [Server thread/INFO]: [PlaceholderAPI] Fetching available expansion information...
[23:46:01] [Craft Scheduler Thread - 251/INFO]: [PlaceholderAPI] Download of expansion: LuckPerms complete!
[23:46:02] [Craft Scheduler Thread - 250/INFO]: [PlaceholderAPI] 169 placeholder expansions are available on the cloud.
[23:46:06] [Server thread/INFO]: LeEpicCheese issued server command: /papi reload
[23:46:06] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: statistic
[23:46:06] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: player
[23:46:06] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'papi' in plugin PlaceholderAPI v2.10.5
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot.jar:git-Paper-155]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[spigot.jar:git-Paper-155]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[spigot.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825) ~[spigot.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633) ~[spigot.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[spigot.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[spigot.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[spigot.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[spigot.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[spigot.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[spigot.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[spigot.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[spigot.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[spigot.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[spigot.jar:git-Paper-155]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoClassDefFoundError: net/luckperms/api/LuckPerms
	at me.lucko.luckperms.placeholders.LuckPermsExpansion.canRegister(LuckPermsExpansion.java:48) ~[?:?]
	at me.clip.placeholderapi.expansion.ExpansionManager.registerExpansion(ExpansionManager.java:110) ~[?:?]
	at me.clip.placeholderapi.expansion.ExpansionManager.registerAllExpansions(ExpansionManager.java:173) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPIPlugin.reloadConf(PlaceholderAPIPlugin.java:186) ~[?:?]
	at me.clip.placeholderapi.commands.PlaceholderAPICommands.onCommand(PlaceholderAPICommands.java:263) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:git-Paper-155]
	... 17 more
Caused by: java.lang.ClassNotFoundException: net.luckperms.api.LuckPerms
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	at me.lucko.luckperms.placeholders.LuckPermsExpansion.canRegister(LuckPermsExpansion.java:48) ~[?:?]
	at me.clip.placeholderapi.expansion.ExpansionManager.registerExpansion(ExpansionManager.java:110) ~[?:?]
	at me.clip.placeholderapi.expansion.ExpansionManager.registerAllExpansions(ExpansionManager.java:173) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPIPlugin.reloadConf(PlaceholderAPIPlugin.java:186) ~[?:?]
	at me.clip.placeholderapi.commands.PlaceholderAPICommands.onCommand(PlaceholderAPICommands.java:263) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:git-Paper-155]
	... 17 more

**Comment by Andre601** [comment]
> If the error contains something like net.java.ClassDefNotFoundException (or something like that) then try updating to lates version of LuckPerms as you're most likely using an outdated version.

> Caused by: java.lang.NoClassDefFoundError: net/luckperms/api/LuckPerms

**Comment by cheesymyst** [comment]
Sorry and thanks!
