### ISSUE TITLE
Exception thrown during asynchronous load

### ISSUE THREAD

**Issue by EnergyNick** [lucko/LuckPerms#2132]
Minecraft 1.12.2 with forge
Sponge Forge 1.12.2-2838-7.2.0
LuckPerms-Sponge-5.0.113
Config: default

Other plugins: Nucleus-1.14.3-S7.1-MC1.12.2-plugin, Pieconomy-0.6.2, worldedit-sponge-api7.1.0-6.1.10-SNAPSHOT-dist

Exception: (send when player connect to server and with interval)

me.lucko.luckperms.lib.caffeine.cache.LocalAsyncCache lambda$handleCompletion$7
WARNING: Exception thrown during asynchronous load
java.util.concurrent.CompletionException: java.lang.IllegalStateException: State must be COMPLETE, but is actually ACCUMULATING
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: State must be COMPLETE, but is actually ACCUMULATING
        at me.lucko.luckperms.common.cacheddata.type.MetaAccumulator.ensureState(MetaAccumulator.java:98)
        at me.lucko.luckperms.common.cacheddata.type.MetaAccumulator.getMeta(MetaAccumulator.java:165)
        at me.lucko.luckperms.common.cacheddata.type.SimpleMetaCache.loadMeta(SimpleMetaCache.java:70)
        at me.lucko.luckperms.common.cacheddata.AbstractCachedDataManager.calculateMeta(AbstractCachedDataManager.java:161)
        at me.lucko.luckperms.common.cacheddata.AbstractCachedDataManager.access$800(AbstractCachedDataManager.java:60)
        at me.lucko.luckperms.common.cacheddata.AbstractCachedDataManager$MetaCacheLoader.load(AbstractCachedDataManager.java:372)
        at me.lucko.luckperms.common.cacheddata.AbstractCachedDataManager$MetaCacheLoader.load(AbstractCachedDataManager.java:369)
        at me.lucko.luckperms.lib.caffeine.cache.CacheLoader.lambda$asyncLoad$0(CacheLoader.java:104)
        ... 6 more

**Comment by lucko** [comment]
Update: https://luckperms.net/
