### ISSUE TITLE
LuckPerms not working with MySQL/ MariaDB

### ISSUE THREAD

**Issue by laGameTV** [lucko/LuckPerms#2140]
I don't know why but LuckPerms is not working very well...

```
[15:45:05 INFO]: [LuckPerms] Enabling LuckPerms v5.0.117
> [15:45:05 INFO]: __
> [15:45:05 INFO]: | |__) LuckPerms v5.0.117
> [15:45:05 INFO]: |___ | Running on Bukkit - CraftBukkit
> [15:45:05 INFO]:
> [15:45:05 INFO]: [LuckPerms] Loading configuration...
> [15:45:06 INFO]: [LuckPerms] Loading storage provider... [MARIADB]
> [15:45:06 WARN]: [Server thread] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Starting...
> [15:45:06 WARN]: [Server thread] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Start completed.
> [15:45:11 ERROR]: [LuckPerms] Failed to init storage implementation
> [15:45:11 WARN]: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
> [15:45:11 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
> [15:45:11 WARN]: at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:131)
> [15:45:11 WARN]: at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:154)
> [15:45:11 WARN]: at me.lucko.luckperms.common.storage.Storage.init(Storage.java:114)
> [15:45:11 WARN]: at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88)
> [15:45:11 WARN]: at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:145)
> [15:45:11 WARN]: at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:158)
> [15:45:11 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
> [15:45:11 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
> [15:45:11 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
> [15:45:11 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
> [15:45:11 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
> [15:45:11 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
> [15:45:11 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
> [15:45:11 WARN]: at java.lang.Thread.run(Thread.java:748)
> [15:45:11 WARN]: Caused by: me.lucko.luckperms.lib.hikari.pool.PoolBase$ConnectionSetupException: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=164.68.100.192)(port=3306)(type=master) : Socket fail to connect to host:164.68.100.192, port:3306. Connection refused (Connection refused)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:501)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:727)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:713)
> [15:45:11 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [15:45:11 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [15:45:11 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [15:45:11 WARN]: ... 1 more
> [15:45:11 WARN]: Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=164.68.100.192)(port=3306)(type=master) : Socket fail to connect to host:164.68.100.192, port:3306. Connection refused (Connection refused)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:241)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.mariadb.MariaDbDataSource.getConnection(MariaDbDataSource.java:305)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
> [15:45:11 WARN]: ... 7 more
> [15:45:11 WARN]: Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=164.68.100.192)(port=3306)(type=master) : Socket fail to connect to host:164.68.100.192, port:3306. Connection refused (Connection refused)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:241)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1241)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.mariadb.internal.util.Utils.retrieveProxy(Utils.java:610)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.mariadb.MariaDbConnection.newConnection(MariaDbConnection.java:142)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.mariadb.MariaDbDataSource.getConnection(MariaDbDataSource.java:302)
> [15:45:11 WARN]: ... 10 more
> [15:45:11 WARN]: Caused by: java.sql.SQLNonTransientConnectionException: Socket fail to connect to host:164.68.100.192, port:3306. Connection refused (Connection refused)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:241)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:87)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.createSocket(AbstractConnectProtocol.java:218)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:474)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1236)
> [15:45:11 WARN]: ... 13 more
> [15:45:11 WARN]: Caused by: java.net.ConnectException: Connection refused (Connection refused)
> [15:45:11 WARN]: at java.net.PlainSocketImpl.socketConnect(Native Method)
> [15:45:11 WARN]: at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> [15:45:11 WARN]: at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> [15:45:11 WARN]: at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> [15:45:11 WARN]: at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> [15:45:11 WARN]: at java.net.Socket.connect(Socket.java:607)
> [15:45:11 WARN]: at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.createSocket(AbstractConnectProtocol.java:213)
> [15:45:11 WARN]: ... 15 more
> [15:45:11 INFO]: [LuckPerms] Loading messaging service... [SQL]
> [15:45:16 WARN]: java.lang.RuntimeException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
> [15:45:16 WARN]: at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:57)
> [15:45:16 WARN]: at me.lucko.luckperms.common.messaging.MessagingFactory$SqlMessengerProvider.obtain(MessagingFactory.java:144)
> [15:45:16 WARN]: at me.lucko.luckperms.common.messaging.LuckPermsMessagingService.<init>(LuckPermsMessagingService.java:73)
> [15:45:16 WARN]: at me.lucko.luckperms.common.messaging.MessagingFactory.getServiceFor(MessagingFactory.java:105)
> [15:45:16 WARN]: at me.lucko.luckperms.bukkit.messaging.BukkitMessagingFactory.getServiceFor(BukkitMessagingFactory.java:64)
> [15:45:16 WARN]: at me.lucko.luckperms.common.messaging.MessagingFactory.getInstance(MessagingFactory.java:83)
> [15:45:16 WARN]: at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:146)
> [15:45:16 WARN]: at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:158)
> [15:45:16 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
> [15:45:16 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
> [15:45:16 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
> [15:45:16 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
> [15:45:16 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
> [15:45:16 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
> [15:45:16 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
> [15:45:16 WARN]: at java.lang.Thread.run(Thread.java:748)
> [15:45:16 WARN]: Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
> [15:45:16 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
> [15:45:16 WARN]: at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:131)
> [15:45:16 WARN]: at me.lucko.luckperms.common.messaging.sql.SqlMessenger.getConnection(SqlMessenger.java:85)
> [15:45:16 WARN]: at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.init(AbstractSqlMessenger.java:56)
> [15:45:16 WARN]: at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:55)
> [15:45:16 WARN]: ... 15 more
> [15:45:16 WARN]: Caused by: me.lucko.luckperms.lib.hikari.pool.PoolBase$ConnectionSetupException: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=164.68.100.192)(port=3306)(type=master) : Socket fail to connect to host:164.68.100.192, port:3306. Connection refused (Connection refused)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:501)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:727)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:713)
> [15:45:16 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [15:45:16 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [15:45:16 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [15:45:16 WARN]: ... 1 more
> [15:45:16 WARN]: Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=164.68.100.192)(port=3306)(type=master) : Socket fail to connect to host:164.68.100.192, port:3306. Connection refused (Connection refused)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:241)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.mariadb.MariaDbDataSource.getConnection(MariaDbDataSource.java:305)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
> [15:45:16 WARN]: ... 7 more
> [15:45:16 WARN]: Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=164.68.100.192)(port=3306)(type=master) : Socket fail to connect to host:164.68.100.192, port:3306. Connection refused (Connection refused)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:241)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1241)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.mariadb.internal.util.Utils.retrieveProxy(Utils.java:610)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.mariadb.MariaDbConnection.newConnection(MariaDbConnection.java:142)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.mariadb.MariaDbDataSource.getConnection(MariaDbDataSource.java:302)
> [15:45:16 WARN]: ... 10 more
> [15:45:16 WARN]: Caused by: java.sql.SQLNonTransientConnectionException: Socket fail to connect to host:164.68.100.192, port:3306. Connection refused (Connection refused)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:241)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:87)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.createSocket(AbstractConnectProtocol.java:218)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:474)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1236)
> [15:45:16 WARN]: ... 13 more
> [15:45:16 WARN]: Caused by: java.net.ConnectException: Connection refused (Connection refused)
> [15:45:16 WARN]: at java.net.PlainSocketImpl.socketConnect(Native Method)
> [15:45:16 WARN]: at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> [15:45:16 WARN]: at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> [15:45:16 WARN]: at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> [15:45:16 WARN]: at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> [15:45:16 WARN]: at java.net.Socket.connect(Socket.java:607)
> [15:45:16 WARN]: at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.createSocket(AbstractConnectProtocol.java:213)
> [15:45:16 WARN]: ... 15 more
> [15:45:16 WARN]: [LuckPerms] Messaging service 'sql' not recognised.
> [15:45:16 INFO]: [LuckPerms] Loading internal permission managers...
> [15:45:16 INFO]: [LuckPerms] Performing initial data load...
> [15:45:21 WARN]: java.util.concurrent.CompletionException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
> [15:45:21 WARN]: at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:103)
> [15:45:21 WARN]: at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
> [15:45:21 WARN]: at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)
> [15:45:21 WARN]: at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> [15:45:21 WARN]: at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
> [15:45:21 WARN]: at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
> [15:45:21 WARN]: at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
> [15:45:21 WARN]: Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
> [15:45:21 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
> [15:45:21 WARN]: at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:131)
> [15:45:21 WARN]: at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:432)
> [15:45:21 WARN]: at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$10(Storage.java:194)
> [15:45:21 WARN]: at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:98)
> [15:45:21 WARN]: ... 6 more
> [15:45:21 WARN]: Caused by: me.lucko.luckperms.lib.hikari.pool.PoolBase$ConnectionSetupException: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=164.68.100.192)(port=3306)(type=master) : Socket fail to connect to host:164.68.100.192, port:3306. Connection refused (Connection refused)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:501)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:727)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:713)
> [15:45:21 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [15:45:21 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [15:45:21 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [15:45:21 WARN]: at java.lang.Thread.run(Thread.java:748)
> [15:45:21 WARN]: Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=164.68.100.192)(port=3306)(type=master) : Socket fail to connect to host:164.68.100.192, port:3306. Connection refused (Connection refused)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:241)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.mariadb.MariaDbDataSource.getConnection(MariaDbDataSource.java:305)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
> [15:45:21 WARN]: ... 7 more
> [15:45:21 WARN]: Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=164.68.100.192)(port=3306)(type=master) : Socket fail to connect to host:164.68.100.192, port:3306. Connection refused (Connection refused)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:241)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1241)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.mariadb.internal.util.Utils.retrieveProxy(Utils.java:610)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.mariadb.MariaDbConnection.newConnection(MariaDbConnection.java:142)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.mariadb.MariaDbDataSource.getConnection(MariaDbDataSource.java:302)
> [15:45:21 WARN]: ... 10 more
> [15:45:21 WARN]: Caused by: java.sql.SQLNonTransientConnectionException: Socket fail to connect to host:164.68.100.192, port:3306. Connection refused (Connection refused)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:241)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:87)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.createSocket(AbstractConnectProtocol.java:218)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:474)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1236)
> [15:45:21 WARN]: ... 13 more
> [15:45:21 WARN]: Caused by: java.net.ConnectException: Connection refused (Connection refused)
> [15:45:21 WARN]: at java.net.PlainSocketImpl.socketConnect(Native Method)
> [15:45:21 WARN]: at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> [15:45:21 WARN]: at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> [15:45:21 WARN]: at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> [15:45:21 WARN]: at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> [15:45:21 WARN]: at java.net.Socket.connect(Socket.java:607)
> [15:45:21 WARN]: at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.createSocket(AbstractConnectProtocol.java:213)
> [15:45:21 WARN]: ... 15 more
> [15:45:21 INFO]: [LuckPerms] Successfully enabled. (took 15943ms)
```

**Comment by lucko** [comment]
> Could not connect to address=(host=164.68.100.192)(port=3306)(type=master) : Socket fail to connect to host:164.68.100.192, port:3306. Connection refused (Connection refused)

Sure your database address is correct? Check your firewall? 

https://github.com/lucko/LuckPerms/wiki/Storage-system-errors
