### ISSUE TITLE
Bungeecord error

### ISSUE THREAD

**Issue by hwalker928** [lucko/LuckPerms#2145]
I get this error when a player joins by Bungeecord proxy.

```
11:50:13 [SEVERE] [LuckPerms] Exception occurred whilst loading data for 7bd8b230-680e-45e2-acff-5215f7f69688 - EnderTweaks
11:50:13 [SEVERE] [LuckPerms] Exception occurred whilst loading data for 8a9dacdf-8d99-4ad9-9b07-55728d547a17 - rupertrmstr
11:50:13 [SEVERE] java.lang.NullPointerException
11:50:13 [SEVERE]     at me.lucko.luckperms.common.plugin.util.AbstractConnectionListener.loadUser(AbstractConnectionListener.java:67)
11:50:13 [SEVERE]     at me.lucko.luckperms.bungee.listeners.BungeeConnectionListener.lambda$onPlayerLogin$0(BungeeConnectionListener.java:90)
11:50:13 [SEVERE]     at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
11:50:13 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
11:50:13 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
11:50:13 [SEVERE]     at java.lang.Thread.run(Thread.java:748)
11:50:13 [SEVERE] java.lang.NullPointerException
11:50:13 [SEVERE]     at me.lucko.luckperms.common.plugin.util.AbstractConnectionListener.loadUser(AbstractConnectionListener.java:67)
11:50:13 [SEVERE]     at me.lucko.luckperms.bungee.listeners.BungeeConnectionListener.lambda$onPlayerLogin$0(BungeeConnectionListener.java:90)
11:50:13 [SEVERE]     at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
11:50:13 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
11:50:13 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
11:50:13 [SEVERE]     at java.lang.Thread.run(Thread.java:748)
11:50:13 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@530d0a, id=3, owner=me.lucko.luckperms.bungee.LPBungeeBootstrap@191004a, task=me.lucko.luckperms.bungee.listeners.BungeeConnectionListener$$Lambda$119/16282668@1a2898a, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException
    at me.lucko.luckperms.bungee.listeners.BungeeConnectionListener.lambda$onPlayerLogin$0(BungeeConnectionListener.java:103)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
11:50:13 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@530d0a, id=4, owner=me.lucko.
```

**Comment by Andre601** [comment]
Could you please use a site like https://hasteb.in for sharing errors?

**Comment by hwalker928** [comment]
https://hasteb.in/dimekeke.rb

**Comment by Andre601** [comment]
Looks like the information for the users is null (not existant) somehow.
What LP version are you running and what server/proxy type and version are you using?

In worst case would the player data be corrupted.

**Comment by hwalker928** [comment]
It is version 5.0.125 of luckperms.
The server was made only hours ago so it would have been the latest version.

**Comment by Andre601** [comment]
Try the latest release from https://luckperms.net and also delete the lib/libs folder to let LP re-download the required dependencies.

**Comment by hwalker928** [comment]
How do I configure it? Do I put the bungeecord version on the bungee server and then the spigot version on the spigot servers? Or do I just need the BC version?

**Comment by Andre601** [comment]
https://github.com/lucko/LuckPerms/wiki/Network-Installation

**Comment by hwalker928** [comment]
Is there anywhere I can download an older version of luckperms?

**Comment by hwalker928** [comment]
I've now stopped the errors, but it is not syncing between servers.

**Comment by lucko** [comment]
Follow the instructions here: https://github.com/lucko/LuckPerms/wiki/Network-Installation

**Comment by hwalker928** [comment]
I've already followed that, it doesn't work..
