### ISSUE TITLE
Mysql connect

### ISSUE THREAD

**Issue by Crazed981** [lucko/LuckPerms#2150]
```
[05:48:23] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.0.72
[05:48:23] [Server thread/INFO]:         __    
[05:48:23] [Server thread/INFO]:   |    |__)   LuckPerms v5.0.72
[05:48:23] [Server thread/INFO]:   |___ |      Running on Bukkit - Paper
[05:48:23] [Server thread/INFO]: 
[05:48:23] [Server thread/INFO]: [LuckPerms] Loading configuration...
[05:48:23] [Server thread/INFO]: [LuckPerms] Loading storage provider... [MYSQL]
[05:48:23] [Server thread/INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Starting...
[05:48:23] [Server thread/INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Start completed.
[05:48:28] [Server thread/ERROR]: [LuckPerms] Failed to init storage implementation
[05:48:28] [Server thread/WARN]: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5001ms.
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:131)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:154)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.Storage.init(Storage.java:114)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:147)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:155)
[05:48:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[05:48:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[05:48:28] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[05:48:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[05:48:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[05:48:28] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:227)
[05:48:28] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876)
[05:48:28] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[05:48:28] [Server thread/WARN]: Caused by: me.lucko.luckperms.lib.hikari.pool.PoolBase$ConnectionSetupException: java.sql.SQLException: Connection setting too low for 'maxAllowedPacket'. When 'useServerPrepStmts=true', 'maxAllowedPacket' must be higher than 8203. Check also 'max_allowed_packet' in MySQL configuration files.
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:501)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:727)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:713)
[05:48:28] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[05:48:28] [Server thread/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[05:48:28] [Server thread/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[05:48:28] [Server thread/WARN]: 	... 1 more
[05:48:28] [Server thread/WARN]: Caused by: java.sql.SQLException: Connection setting too low for 'maxAllowedPacket'. When 'useServerPrepStmts=true', 'maxAllowedPacket' must be higher than 8203. Check also 'max_allowed_packet' in MySQL configuration files.
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:3250)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2233)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[05:48:28] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:48:28] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[05:48:28] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[05:48:28] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
[05:48:28] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
[05:48:28] [Server thread/WARN]: 	... 7 more
[05:48:28] [Server thread/INFO]: [LuckPerms] Loading messaging service... [SQL]
[05:48:33] [Server thread/WARN]: java.lang.RuntimeException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:57)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.MessagingFactory$SqlMessengerProvider.obtain(MessagingFactory.java:144)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.LuckPermsMessagingService.<init>(LuckPermsMessagingService.java:73)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.MessagingFactory.getServiceFor(MessagingFactory.java:105)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.messaging.BukkitMessagingFactory.getServiceFor(BukkitMessagingFactory.java:64)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.MessagingFactory.getInstance(MessagingFactory.java:83)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:148)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:155)
[05:48:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[05:48:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[05:48:33] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[05:48:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[05:48:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[05:48:33] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:227)
[05:48:33] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876)
[05:48:33] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[05:48:33] [Server thread/WARN]: Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:131)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.sql.SqlMessenger.getConnection(SqlMessenger.java:85)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.init(AbstractSqlMessenger.java:56)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:55)
[05:48:33] [Server thread/WARN]: 	... 15 more
[05:48:33] [Server thread/WARN]: Caused by: me.lucko.luckperms.lib.hikari.pool.PoolBase$ConnectionSetupException: java.sql.SQLException: Connection setting too low for 'maxAllowedPacket'. When 'useServerPrepStmts=true', 'maxAllowedPacket' must be higher than 8203. Check also 'max_allowed_packet' in MySQL configuration files.
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:501)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:727)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:713)
[05:48:33] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[05:48:33] [Server thread/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[05:48:33] [Server thread/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[05:48:33] [Server thread/WARN]: 	... 1 more
[05:48:33] [Server thread/WARN]: Caused by: java.sql.SQLException: Connection setting too low for 'maxAllowedPacket'. When 'useServerPrepStmts=true', 'maxAllowedPacket' must be higher than 8203. Check also 'max_allowed_packet' in MySQL configuration files.
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:3250)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2233)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[05:48:33] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:48:33] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[05:48:33] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[05:48:33] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
[05:48:33] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
[05:48:33] [Server thread/WARN]: 	... 7 more
[05:48:33] [Server thread/WARN]: [LuckPerms] Messaging service 'sql' not recognised.
[05:48:33] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[05:48:33] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[05:48:38] [Server thread/WARN]: java.util.concurrent.CompletionException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:103)
[05:48:38] [Server thread/WARN]: 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
[05:48:38] [Server thread/WARN]: 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source)
[05:48:38] [Server thread/WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[05:48:38] [Server thread/WARN]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
[05:48:38] [Server thread/WARN]: 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[05:48:38] [Server thread/WARN]: 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[05:48:38] [Server thread/WARN]: Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:131)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:432)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$10(Storage.java:194)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:98)
[05:48:38] [Server thread/WARN]: 	... 6 more
[05:48:38] [Server thread/WARN]: Caused by: me.lucko.luckperms.lib.hikari.pool.PoolBase$ConnectionSetupException: java.sql.SQLException: Connection setting too low for 'maxAllowedPacket'. When 'useServerPrepStmts=true', 'maxAllowedPacket' must be higher than 8203. Check also 'max_allowed_packet' in MySQL configuration files.
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:501)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:727)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:713)
[05:48:38] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[05:48:38] [Server thread/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[05:48:38] [Server thread/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[05:48:38] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[05:48:38] [Server thread/WARN]: Caused by: java.sql.SQLException: Connection setting too low for 'maxAllowedPacket'. When 'useServerPrepStmts=true', 'maxAllowedPacket' must be higher than 8203. Check also 'max_allowed_packet' in MySQL configuration files.
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:3250)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2233)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[05:48:38] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:48:38] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[05:48:38] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[05:48:38] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
[05:48:38] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
[05:48:38] [Server thread/WARN]: 	... 7 more
[05:48:38] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 15618ms)
```

**Comment by BrainStone** [comment]
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors

**Comment by lucko** [comment]
Important bit is here:

> Connection setting too low for 'maxAllowedPacket'. When 'useServerPrepStmts=true', 'maxAllowedPacket' must be higher than 8203. Check also 'max_allowed_packet' in MySQL configuration files
