### ISSUE TITLE
LuckPerms Database error [1.7.10]

### ISSUE THREAD

**Issue by Tomi0928** [lucko/LuckPerms#2166]
SO i use the legacy jar with a custom spigot:
https://mega.nz/#!gmRG1aAL!E-fz0oYWaVAl-mKd3yuPJm450FAXp15RCT0dhifG2Dc
(I need this because of the Lazurus core)
https://www.mc-market.org/resources/11362/field?field=dependencies
This plugin supports LuckPerms but if i try to connect LP to database it chrashes

I get This LOG:

```
[12:17:04] [INFO]: [LuckPerms] Enabling LuckPerms v5.0.130
[12:17:04] [INFO]:         __    
[12:17:04] [INFO]:   |    |__)   LuckPerms v5.0.130
[12:17:04] [INFO]:   |___ |      Running on Bukkit - PaperSpigot
[12:17:04] [INFO]: 
[12:17:04] [INFO]: [LuckPerms] Loading configuration...
[12:17:05] [INFO]: [LuckPerms] Loading storage provider... [MYSQL]
[12:17:05] [WARN]: SLF4J: Class path contains multiple SLF4J bindings.
[12:17:05] [WARN]: SLF4J: Found binding in [jar:file:/C:/Users/Tomi/Desktop/HÖCÖFÖ/plugins/Minecord/lib/slf4j-simple-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[12:17:05] [WARN]: SLF4J: Found binding in [jar:file:/C:/Users/Tomi/Desktop/HÖCÖFÖ/plugins/LuckPerms/libs/slf4j-simple-1.7.30-remapped.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[12:17:05] [WARN]: SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[12:17:05] [WARN]: Failed to instantiate SLF4J LoggerFactory
[12:17:05] [WARN]: Reported exception:
[12:17:05] [WARN]: java.lang.NoClassDefFoundError: org/slf4j/spi/LoggerFactoryBinder
[12:17:05] [WARN]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[12:17:05] [WARN]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[12:17:05] [WARN]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[12:17:05] [WARN]: 	at java.net.URLClassLoader.defineClass(Unknown Source)
[12:17:05] [WARN]: 	at java.net.URLClassLoader.access$100(Unknown Source)
[12:17:05] [WARN]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[12:17:05] [WARN]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[12:17:05] [WARN]: 	at java.security.AccessController.doPrivileged(Native Method)
[12:17:05] [WARN]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[12:17:05] [WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[12:17:05] [WARN]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[12:17:05] [WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[12:17:05] [WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[12:17:05] [WARN]: 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
[12:17:05] [WARN]: 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
[12:17:05] [WARN]: 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
[12:17:05] [WARN]: 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
[12:17:05] [WARN]: 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
[12:17:05] [WARN]: 	at me.lucko.luckperms.lib.hikari.HikariConfig.<clinit>(HikariConfig.java:51)
[12:17:05] [WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:76)
[12:17:05] [WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:151)
[12:17:05] [WARN]: 	at me.lucko.luckperms.common.storage.Storage.init(Storage.java:114)
[12:17:05] [WARN]: 	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88)
[12:17:05] [WARN]: 	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:145)
[12:17:05] [WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:158)
[12:17:05] [WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[12:17:05] [WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[12:17:05] [WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:411)
[12:17:05] [WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:466)
[12:17:05] [WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:385)
[12:17:05] [WARN]: 	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:173)
[12:17:05] [WARN]: 	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:485)
[12:17:05] [WARN]: 	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[12:17:05] [WARN]: Caused by: java.lang.ClassNotFoundException: org.slf4j.spi.LoggerFactoryBinder
[12:17:05] [WARN]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[12:17:05] [WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[12:17:05] [WARN]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[12:17:05] [WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[12:17:05] [WARN]: 	... 33 more
[12:17:05] [ERROR]: Error occurred while enabling LuckPerms v5.0.130 (Is it up to date?)
java.lang.NoClassDefFoundError: org/slf4j/spi/LoggerFactoryBinder
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_211]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_211]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_211]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_211]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_211]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150) ~[?:?]
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124) ~[?:?]
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417) ~[?:?]
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362) ~[?:?]
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388) ~[?:?]
	at me.lucko.luckperms.lib.hikari.HikariConfig.<clinit>(HikariConfig.java:51) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:76) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:151) ~[?:?]
	at me.lucko.luckperms.common.storage.Storage.init(Storage.java:114) ~[?:?]
	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:145) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:158) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[LazarusSpigot.jar:1.0]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [LazarusSpigot.jar:1.0]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:411) [LazarusSpigot.jar:1.0]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:466) [LazarusSpigot.jar:1.0]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:385) [LazarusSpigot.jar:1.0]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:173) [LazarusSpigot.jar:1.0]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:485) [LazarusSpigot.jar:1.0]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [LazarusSpigot.jar:1.0]
Caused by: java.lang.ClassNotFoundException: org.slf4j.spi.LoggerFactoryBinder
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	... 33 more
```

**Comment by Tobi406** [comment]
See #1540
