### ISSUE TITLE
Failed to load jar for dependency SLF4J_SIMPLE - SpongeVanilla 

### ISSUE THREAD

**Issue by Mahagon** [lucko/LuckPerms#217]
Cant use mysql with the spongeplugin. It fails to load slf4j simple:

i use this Version of LuckPerms: https://ci.lucko.me/job/LuckPerms/117/

The Server ist running on Ubuntu 16.04 with Oracles Java 1.8 Update 121 (64 bit)

Sponge Build: 1.11.2-6.0.0-BETA-234

```
Sponge - SpongeVanilla
[11:56:44 INFO]:   Running on server version SpongeAPI: 6.0.0-SNAPSHOT-43b286d - SpongeVanilla: 1.11.2-6.0.0-BETA-234
[11:56:44 INFO]:
[11:56:44 INFO]: [LP] Loading configuration...
[11:56:44 INFO]: [LP] Detecting storage method...
[11:56:44 INFO]: [LP] Loading dependencies...
[11:56:44 INFO]: [LP] Identified the following dependencies: [MYSQL_DRIVER, SLF4J_API, SLF4J_SIMPLE, HIKARI]
[11:56:44 INFO]: [LuckPerms] [ERROR] Failed to load jar for dependency SLF4J_SIMPLE
[11:56:44 ERROR] [STDERR]: java.lang.ClassNotFoundException: org.slf4j.impl.SimpleLoggerFactory
[11:56:44 ERROR] [STDERR]:        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[11:56:44 ERROR] [STDERR]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[11:56:44 ERROR] [STDERR]:        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[11:56:44 ERROR] [STDERR]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[11:56:44 ERROR] [STDERR]:        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
[11:56:44 ERROR] [STDERR]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[11:56:44 ERROR] [STDERR]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[11:56:44 ERROR] [STDERR]:        at me.lucko.luckperms.common.dependencies.DependencyManager.loadJar(DependencyManager.java:143)
[11:56:44 ERROR] [STDERR]:        at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependencies(DependencyManager.java:104)
[11:56:44 ERROR] [STDERR]:        at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependencies(DependencyManager.java:81)
[11:56:44 ERROR] [STDERR]:        at me.lucko.luckperms.sponge.LPSpongePlugin.onEnable(LPSpongePlugin.java:183)
[11:56:44 ERROR] [STDERR]:        at org.spongepowered.common.event.listener.GamePreInitializationEventListener_LPSpongePlugin_onEnable8.handle(Unknown Source)
[11:56:44 ERROR] [STDERR]:        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[11:56:44 ERROR] [STDERR]:        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:305)
[11:56:44 ERROR] [STDERR]:        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:320)
[11:56:44 ERROR] [STDERR]:        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:324)
[11:56:44 ERROR] [STDERR]:        at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:201)
[11:56:44 ERROR] [STDERR]:        at org.spongepowered.server.SpongeVanilla.preInitialize(SpongeVanilla.java:115)
[11:56:44 ERROR] [STDERR]:        at net.minecraft.server.dedicated.DedicatedServer.handler$onServerLoad$znp000(SourceFile:1223)
[11:56:44 ERROR] [STDERR]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:112)
[11:56:44 ERROR] [STDERR]:        at net.minecraft.server.MinecraftServer.run(SourceFile:436)
[11:56:44 ERROR] [STDERR]:        at java.lang.Thread.run(Thread.java:745)
```

i hope you can fix it :)
Thanks a lot

**Comment by lucko** [comment]
Can you delete the `/libs/` filter and try again.

**Comment by Mahagon** [comment]
Still running on an error:
https://gist.github.com/Mahagon/54ff266a03556279954d714c54295168

[12:05:50] [Server thread/INFO] [MinecraftServer]: [LP] Dependency 'slf4j_api-1.7.9.jar' could not be found. Attempting to download.
[12:05:50] [Server thread/INFO] [MinecraftServer]: [LP] Dependency 'slf4j_api-1.7.9.jar' successfully downloaded.
[12:05:50] [Server thread/INFO] [MinecraftServer]: [LP] Dependency 'slf4j_simple-1.7.9.jar' could not be found. Attempting to download.
[12:05:50] [Server thread/INFO] [MinecraftServer]: [LP] Dependency 'slf4j_simple-1.7.9.jar' successfully downloaded.

**Comment by lucko** [comment]
Huh, strange. I can reproduce this too, not sure why it's happening though.

Does the rest of the plugin enable correctly?

**Comment by Mahagon** [comment]
It created the mysqltables:

Tables_in_minecraft
luckperms_actions
luckperms_group_permissions
luckperms_groups
luckperms_players
luckperms_tracks
luckperms_user_permissions

so it seems to.

Also the plugins is written in green color in the pluginlist ingame

**Comment by lucko** [comment]
Ok, that commit should fix the error then. :)
