### ISSUE TITLE
Error, bungee, mysql

### ISSUE THREAD

**Issue by ExtremeGrief** [lucko/LuckPerms#2192]
When I type /lp networksync, I get this error: "error while pushing changes to other servers a messaging service has not been configured". But the mysql and messaging server have been configured.

**Comment by Laarryy** [comment]
Can you pastebin the startup log for your server? As well as a pastebin of your config, if possible (with seensitive info removed of course)

**Comment by ExtremeGrief** [comment]
Uhh I use screen command on linux. Do you know how can I see the logs?

**Comment by Laarryy** [comment]
I'm not too familiar with linux honestly, but basically whatever window you type `stop` into to stop the server is your log, and I'm pretty sure you've got that set up. I know on windows it's just a cmd window. [Here's a spigot page with some simple instructions](https://www.spigotmc.org/threads/help-me-for-linux-open-console-minecraft.284737/) and a link to a few more.. Literally just your console from startup is all that's needed.

**Comment by ExtremeGrief** [comment]
I got it, I am copying to pastebin

**Comment by ExtremeGrief** [comment]
@Laarryy 
Server log:https://pastebin.com/bmeP6FHB
nevermind the other plugins errors.

config file:https://pastebin.com/D3KPJyci

if it matters, I use clever cloud

**Comment by Laarryy** [comment]
```
[21:40:40] [Server thread/ERROR]: Cannot load plugins/LuckPerms/config.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 98, column 3:
      address: blmsk65e5b1c6qdpjukl-my ...
      ^
expected <block end>, but found BlockMappingStart
 in 'string', line 145, column 5:
        properties:
        ^
 
    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:178) ~[patched_1.12.2.jar:git-Paper-1618]
    at me.lucko.luckperms.bukkit.BukkitConfigAdapter.reload(BukkitConfigAdapter.java:54) ~[?:?]
    at me.lucko.luckperms.bukkit.BukkitConfigAdapter.<init>(BukkitConfigAdapter.java:49) ~[?:?]
    at me.lucko.luckperms.bukkit.LPBukkitPlugin.provideConfigurationAdapter(LPBukkitPlugin.java:127) ~[?:?]
    at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:114) ~[?:?]
    at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:158) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
    at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:223) ~[patched_1.12.2.jar:git-Paper-1618]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
    at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 98, column 3:
      address: blmsk65e5b1c6qdpjukl-my ...
      ^
expected <block end>, but found BlockMappingStart
 in 'string', line 145, column 5:
        properties:
        ^
 
    at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:571) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:227) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:249) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:240) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:140) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) ~[patched_1.12.2.jar:git-Paper-1618]
    ... 16 more
```

This explains exactly what's wrong, there's a syntax error in your config.

**Comment by ExtremeGrief** [comment]
But I do not see anything wrong. Can you check the config too?

**Comment by Laarryy** [comment]
There's a syntax error either before or at exactly where the little arrow in the error is pointing. You've likely either removed the `' '` where it needed to be or added an extra character (or space) where it shouldn't be. Easiest fix is to regenerate the config and fill everything in again, being careful not to add or remove anything except for adding your info.

**Comment by Laarryy** [comment]
```
 address: "censored"
 
  # The name of the database to store LuckPerms data in.
  # - This must be created already. Don't worry about this setting if you're using MongoDB.
  database: "censored"
 
  # Credentials for the database.
  username: "censored"
  password: "censored"
```
This section is what looks like has been done wrong, remember not to add `" "` or remove `' '` anywhere.

**Comment by ExtremeGrief** [comment]
I will try, but looks like I did not make any mistake. I will try nevertheless.

**Comment by ExtremeGrief** [comment]
@Laarryy I am new to this, can you tell me exactly what I need to modify? Now I get [LP] A database error occurred whilist loading permission data. Please try again later. If you are a server admin, please check the console for any errors.

**Comment by Laarryy** [comment]
Please send the console error that occurs when that happens or see [this page](https://github.com/lucko/LuckPerms/wiki/Storage-system-errors) for how to fix whatever is showing in console.

**Comment by ExtremeGrief** [comment]
I got new config file, and just modified the entries. Same error as before. I am lost.

**Comment by ExtremeGrief** [comment]
[latest.txt](https://github.com/lucko/LuckPerms/files/4494824/latest.txt)
Here is the new log.

**Comment by Laarryy** [comment]
Same thing, misconfiguration. Run the config through http://yaml-online-parser.appspot.com/ and try to find the error (the error will go away when you've removed the syntax error)

**Comment by ExtremeGrief** [comment]
How can I use that site?

**Comment by Laarryy** [comment]
you paste the config in there and go where it points you, then you try and remove whatever syntax error you've included. Without your full and actual config ( which you definitely shouldn't post here ) that's the best I can do. If you delete and regen the config, there will be no syntax errors, and if you just paste values where they belong, the thing'll work. It says there's a syntax error, so there's a syntax error, for sure.

**Comment by ExtremeGrief** [comment]
I do not understand. What do you mean where the site points me. It does not point me anywhere. I just regened the config, and replaced mysql values with mine.

**Comment by Laarryy** [comment]
When you paste your config into the box on the left side of that website, it will tell you where the syntax errors are and you can either try and fix them or try to redo the config without creating a syntax error, again. There's nothing more I can say because there's definitely a syntax error in the config, if that's the error you're getting.

**Comment by ExtremeGrief** [comment]
Can you try and put my config there? It does not show any errors.

**Comment by Laarryy** [comment]
I don't have your config, at least not one with the data. can you send a pastebin of your config but replace some of the characters in the address and password? don't remove or reformat anything though

**Comment by ExtremeGrief** [comment]
[config.txt](https://github.com/lucko/LuckPerms/files/4494873/config.txt)

**Comment by Laarryy** [comment]
That one looks good, try starting the server with it and if there are any different errors, *pastebin* them here please

**Comment by ExtremeGrief** [comment]
OK, I know it's weird, now it works. Just restarted my pc and it works now.

**Comment by Laarryy** [comment]
Awesome. Feel free to hop on to the [discord](https://discord.gg/luckperms) for further support if ya need it

**Comment by ExtremeGrief** [comment]
OK, now I have the same problem again. I just disabled SSL because there was a warning and I get the same syntax error. Now the site tells me the exact same thing that the console told me.

ERROR:

while parsing a block mapping
  in "<unicode string>", line 98, column 3:
      address: blmsk65e5b1c6qdpjukl-my ... 
      ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 145, column 5:
        properties:
        ^

**Comment by lucko** [comment]
Try wrapping it in quotes `" "`
