### ISSUE TITLE
Big error in console > Plugin not working

### ISSUE THREAD

**Issue by Orkamicky** [lucko/LuckPerms#2197]
**Problem**

Crash report in console when starting up and loading papi (PlaceholderAPI)
**Details**

Plugin version: Bungee-5.0.136

Software version: Latest Bungeecord (installed LuckPerms on)
Server Spigot: 1.8.8

Relevant plugins: Bungeecord: Luckperms
Spigot: Vault, Placeholderapi, essentials, essentialschat, advancedchattorch, tab
**Console error**
`[02:26:53 WARN]: [PlaceholderAPI] Task #4 for PlaceholderAPI v2.10.5 generated an exception
java.lang.NoClassDefFoundError: net/luckperms/api/LuckPerms
        at me.lucko.luckperms.placeholders.LuckPermsExpansion.canRegister(LuckPermsExpansion.java:48) ~[?:?]
        at me.clip.placeholderapi.expansion.ExpansionManager.registerExpansion(ExpansionManager.java:110) ~[?:?]
        at me.clip.placeholderapi.expansion.ExpansionManager.registerAllExpansions(ExpansionManager.java:173) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPIPlugin.lambda$onEnable$0(PlaceholderAPIPlugin.java:151) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.ClassNotFoundException: net.luckperms.api.LuckPerms
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        ... 11 more`

**Comment by BrainStone** [comment]
This is clearly on the Spigot.  
Why are you providing Bungee versions?
