### ISSUE TITLE
Web Editor not working (403 error)

### ISSUE THREAD

**Issue by lujo777** [lucko/LuckPerms#2234]
When I write /lp editor there is some warnings in console, editor not working.

[LP] Preparing a new editor session. Please wait...
[13:20:03 WARN]: java.lang.RuntimeException: Request was unsuccessful: 403 - 
[13:20:03 WARN]:        at me.lucko.luckperms.common.web.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java
:50)
[13:20:03 WARN]:        at me.lucko.luckperms.common.web.BytebinClient.makeHttpRequest(BytebinClient.java:69)
[13:20:03 WARN]:        at me.lucko.luckperms.common.web.BytebinClient.postContent(BytebinClient.java:94)
[13:20:03 WARN]:        at me.lucko.luckperms.common.web.WebEditor.post(WebEditor.java:138)
[13:20:03 WARN]:        at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:132)
[13:20:03 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:5
0)
[13:20:03 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:4
2)
[13:20:03 WARN]:        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:202)
[13:20:03 WARN]:        at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.
java:143)
[13:20:03 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:
1700)
[13:20:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135
)
[13:20:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635
)
[13:20:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by Turbotailz** [comment]
HTTP code 403 means access is forbidden which likely means your connection to the bytebin service has been blocked by Cloudflare for some reason. Have you been able to access the web editor from this server before?

**Comment by lujo777** [comment]
I just installed luckperms today

**Comment by Andre601** [comment]
What version of LP?

**Comment by lujo777** [comment]
v5.0.140
