### ISSUE TITLE
A error with UUID in Bungee

### ISSUE THREAD

**Issue by Elguerrero11** [lucko/LuckPerms#2241]
29.04 13:30:46 [Server] WARN [LuckPerms]: A permission check was made for player Elguerrero - 9c9dae1f-e116-3398-9ce1-205f5cb6c31d, but LuckPerms does not have any permissions data loaded for them. Perhaps their UUID has been altered since login?
29.04 13:30:46 [Server] ERROR java.lang.Exception
29.04 13:30:46 [Server] ERROR at me.lucko.luckperms.bungee.listeners.BungeePermissionCheckListener.onPlayerPermissionCheck(BungeePermissionCheckListener.java:67)
29.04 13:30:46 [Server] ERROR at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
29.04 13:30:46 [Server] ERROR at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
29.04 13:30:46 [Server] ERROR at java.lang.reflect.Method.invoke(Method.java:498)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:384)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:504)
29.04 13:30:46 [Server] ERROR at eu.kennytv.maintenance.bungee.util.BungeeSenderInfo.hasPermission(BungeeSenderInfo.java:49)
29.04 13:30:46 [Server] ERROR at eu.kennytv.maintenance.core.util.SenderInfo.hasMaintenancePermission(SenderInfo.java:32)
29.04 13:30:46 [Server] ERROR at eu.kennytv.maintenance.core.proxy.listener.ProxyJoinListenerBase.serverConnect(ProxyJoinListenerBase.java:51)
29.04 13:30:46 [Server] ERROR at eu.kennytv.maintenance.bungee.listener.ServerConnectListener.serverConnect(ServerConnectListener.java:75)
29.04 13:30:46 [Server] ERROR at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
29.04 13:30:46 [Server] ERROR at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
29.04 13:30:46 [Server] ERROR at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
29.04 13:30:46 [Server] ERROR at java.lang.reflect.Method.invoke(Method.java:498)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:384)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.UserConnection.connect(UserConnection.java:285)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.UserConnection.connect(UserConnection.java:276)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.UserConnection.connect(UserConnection.java:251)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.UserConnection.connect(UserConnection.java:214)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.UserConnection.connect(UserConnection.java:199)
29.04 13:30:46 [Server] ERROR at net.uraharanz.plugins.dynamicbungeeauth.methods.ServerMethods.lambda$sendLobbyServer$0(ServerMethods.java:108)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
29.04 13:30:46 [Server] ERROR at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
29.04 13:30:46 [Server] ERROR at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
29.04 13:30:46 [Server] ERROR at java.lang.Thread.run(Thread.java:748)29.04 13:30:46 [Server] WARN [LuckPerms]: A permission check was made for player Elguerrero - 9c9dae1f-e116-3398-9ce1-205f5cb6c31d, but LuckPerms does not have any permissions data loaded for them. Perhaps their UUID has been altered since login?
29.04 13:30:46 [Server] ERROR java.lang.Exception
29.04 13:30:46 [Server] ERROR at me.lucko.luckperms.bungee.listeners.BungeePermissionCheckListener.onPlayerPermissionCheck(BungeePermissionCheckListener.java:67)
29.04 13:30:46 [Server] ERROR at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
29.04 13:30:46 [Server] ERROR at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
29.04 13:30:46 [Server] ERROR at java.lang.reflect.Method.invoke(Method.java:498)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:384)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:504)
29.04 13:30:46 [Server] ERROR at eu.kennytv.maintenance.bungee.util.BungeeSenderInfo.hasPermission(BungeeSenderInfo.java:49)
29.04 13:30:46 [Server] ERROR at eu.kennytv.maintenance.core.util.SenderInfo.hasMaintenancePermission(SenderInfo.java:32)
29.04 13:30:46 [Server] ERROR at eu.kennytv.maintenance.core.proxy.listener.ProxyJoinListenerBase.serverConnect(ProxyJoinListenerBase.java:51)
29.04 13:30:46 [Server] ERROR at eu.kennytv.maintenance.bungee.listener.ServerConnectListener.serverConnect(ServerConnectListener.java:75)
29.04 13:30:46 [Server] ERROR at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
29.04 13:30:46 [Server] ERROR at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
29.04 13:30:46 [Server] ERROR at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
29.04 13:30:46 [Server] ERROR at java.lang.reflect.Method.invoke(Method.java:498)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:384)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.UserConnection.connect(UserConnection.java:285)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.UserConnection.connect(UserConnection.java:276)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.UserConnection.connect(UserConnection.java:251)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.UserConnection.connect(UserConnection.java:214)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.UserConnection.connect(UserConnection.java:199)
29.04 13:30:46 [Server] ERROR at net.uraharanz.plugins.dynamicbungeeauth.methods.ServerMethods.lambda$sendLobbyServer$0(ServerMethods.java:108)
29.04 13:30:46 [Server] ERROR at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
29.04 13:30:46 [Server] ERROR at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
29.04 13:30:46 [Server] ERROR at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
29.04 13:30:46 [Server] ERROR at java.lang.Thread.run(Thread.java:748)

**Comment by lucko** [comment]
Which version of LuckPerms are you using?

**Comment by Elguerrero11** [comment]
> Which version of LuckPerms are you using?

5.0.146

**Comment by lucko** [comment]
Please set this option to true

https://github.com/lucko/LuckPerms/blob/cd25681cd37ff1d8e77e46c2a9d682ca2f4f9a56/bungee/src/main/resources/config.yml#L507-L510

Then run `/lpb reloadconfig` - and wait for the issue to occur again.

Then send the log file from when the player connected to when the issue occurred.

**Comment by Elguerrero11** [comment]
I have do.

[14:35:38] [Netty Worker IO Thread #8/INFO] [LuckPerms]: Processing pre-login for 92193716-bcc2-4491-aaea-fa201391bfce - Elguerrero
[14:35:38] [LuckPerms Pool Thread #8/WARN] [LuckPerms]: LuckPerms already has data for player 'Elguerrero' - but this data is stored under a different UUID.
[14:35:38] [LuckPerms Pool Thread #8/WARN] [LuckPerms]: 'Elguerrero' has previously used the unique ids [9c9dae1f-e116-3398-9ce1-205f5cb6c31d] but is now connecting with '92193716-bcc2-4491-aaea-fa201391bfce'
[14:35:38] [LuckPerms Pool Thread #8/WARN] [LuckPerms]: The UUID the player is connecting with now is Mojang-assigned (type 4). This implies that BungeeCord's IP-Forwarding has not been setup correctly on one (or more) of the backend servers.
[14:35:38] [LuckPerms Pool Thread #8/WARN] [LuckPerms]: The UUID the player is connecting with now is Mojang-assigned (type 4). This implies that one of the other servers in your network is not authenticating correctly.
[14:35:38] [LuckPerms Pool Thread #8/WARN] [LuckPerms]: If you're using BungeeCord/Velocity, please ensure that IP-Forwarding is setup correctly on all of your backend servers!
[14:35:38] [LuckPerms Pool Thread #8/WARN] [LuckPerms]: See here for more info: https://github.com/lucko/LuckPerms/wiki/Network-Installation#pre-setup
[14:35:38] [Netty Worker IO Thread #8/WARN] [LuckPerms]: A permission check was made for player Elguerrero - 9c9dae1f-e116-3398-9ce1-205f5cb6c31d, but LuckPerms does not have any permissions data loaded for them. Perhaps their UUID has been altered since login?
[14:35:38] [Netty Worker IO Thread #8/ERROR]: java.lang.Exception
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at me.lucko.luckperms.bungee.listeners.BungeePermissionCheckListener.onPlayerPermissionCheck(BungeePermissionCheckListener.java:67)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:384)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:504)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at twolovers.antibot.bungee.listeners.PostLoginListener.onPostLogin(PostLoginListener.java:36)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:384)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:759)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[14:35:38] [Netty Worker IO Thread #8/ERROR]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by arenmarsden** [comment]
@Elguerrero11 The first two lines of the error:
```
[14:35:38] [Netty Worker IO Thread #8/INFO] [LuckPerms]: Processing pre-login for 92193716-bcc2-4491-aaea-fa201391bfce - Elguerrero
[14:35:38] [LuckPerms Pool Thread #8/WARN] [LuckPerms]: LuckPerms already has data for player 'Elguerrero' - but this data is stored under a different UUID.
```
This implies your BungeeCord configuration is not set up properly. Make sure your Spigot servers have `bungeecord: true` and ip-forwarding is set to `true`.

This would explain these errors too:

```
[14:35:38] [LuckPerms Pool Thread #8/WARN] [LuckPerms]: The UUID the player is connecting with now is Mojang-assigned (type 4). This implies that BungeeCord's IP-Forwarding has not been setup correctly on one (or more) of the backend servers.
[14:35:38] [LuckPerms Pool Thread #8/WARN] [LuckPerms]: The UUID the player is connecting with now is Mojang-assigned (type 4). This implies that one of the other servers in your network is not authenticating correctly.
```


Please read this document: https://github.com/lucko/LuckPerms/wiki/Network-Installation#pre-setup and make sure this is correctly configured.

**Comment by Elguerrero11** [comment]
> @Elguerrero11 The first two lines of the error:
> 
> ```
> [14:35:38] [Netty Worker IO Thread #8/INFO] [LuckPerms]: Processing pre-login for 92193716-bcc2-4491-aaea-fa201391bfce - Elguerrero
> [14:35:38] [LuckPerms Pool Thread #8/WARN] [LuckPerms]: LuckPerms already has data for player 'Elguerrero' - but this data is stored under a different UUID.
> ```
> 
> This implies your BungeeCord configuration is not set up properly. Make sure your Spigot servers have `bungeecord: true` and ip-forwarding is set to `true`.
> 
> This would explain these errors too:
> 
> ```
> [14:35:38] [LuckPerms Pool Thread #8/WARN] [LuckPerms]: The UUID the player is connecting with now is Mojang-assigned (type 4). This implies that BungeeCord's IP-Forwarding has not been setup correctly on one (or more) of the backend servers.
> [14:35:38] [LuckPerms Pool Thread #8/WARN] [LuckPerms]: The UUID the player is connecting with now is Mojang-assigned (type 4). This implies that one of the other servers in your network is not authenticating correctly.
> ```
> 
> Please read this document: https://github.com/lucko/LuckPerms/wiki/Network-Installation#pre-setup and make sure this is correctly configured.

Thanks but i have readed that, i have looked in all servers and is fine, i will test to delete the users tables.

**Comment by Elguerrero11** [comment]
I have deleted the database and is the same error, maybe i need to have the plugin updated in each server?

I have not updated in all servers.

**Comment by Elguerrero11** [comment]
Ok, i have updated the plugin in all servers and the error still...

**Comment by arenmarsden** [comment]
> Ok, i have updated the plugin in all servers and the error still...
> What can i do?
> 
> I dont know what do.

What version of Minecraft is your server running on? Please share the result of `/version`, and do you know what version of BungeeCord you are running?

**Comment by Elguerrero11** [comment]
> > Ok, i have updated the plugin in all servers and the error still...
> > What can i do?
> > I dont know what do.
> 
> What version of Minecraft is your server running on? Please share the result of `/version`, and do you know what version of BungeeCord you are running?

I am using Flamecord like proxy, is in mcmarket, is of a dev, that fix invulnerabilities and more, but i think that the error is a incompatibility with latest dynamicbungeeauth plugin because i updated that, put the option of offline uuid in true for that dont change the rank of the player when activate /premium and appear then the error, is say, that appear when i updated that plugin with that option in the config.

**Comment by lucko** [comment]
The issue is one of your plugins is altering player UUIDs between the time when LuckPerms loads data and when permission checks are made.

> [14:35:38] [Netty Worker IO Thread #8/INFO] [LuckPerms]: Processing pre-login for 92193716-bcc2-4491-aaea-fa201391bfce - Elguerrero

> [14:35:38] [Netty Worker IO Thread #8/WARN] [LuckPerms]: A permission check was made for player Elguerrero - 9c9dae1f-e116-3398-9ce1-205f5cb6c31d, but LuckPerms does not have any permissions data loaded for them. Perhaps their UUID has been altered since login?

Sounds like it could be DynamicBungeeAuth - if that's the case you need to ask them to fix the problem.

**Comment by Elguerrero11** [comment]
I will test with the dev, thanks :)
