### ISSUE TITLE
The LuckPerms API is not loaded.

### ISSUE THREAD

**Issue by LiinxTV** [lucko/LuckPerms#2247]
Hello, i recently read about how to use the api but i still get an error.

Error:

**
java.lang.ExceptionInInitializerError
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:328)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:235)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:272)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.IllegalStateException: The LuckPerms API is not loaded.
    at net.luckperms.api.LuckPermsProvider.get(LuckPermsProvider.java:50)
    at fr.me.coins.Coins.<clinit>(Coins.java:36)
    ... 9 more
**

here is the code for registering:

Coins.java:36: protected static LuckPerms luckperms = LuckPermsProvider.get();

I think the provider is not correctly set, buton wiki page, init is only for Spigot / Sponge but for bungeecord how to do ?

PS: it's not from bungee.yml cause i have put this:

depends: [LuckPerms]

so it load after luckperms

**Comment by Andre601** [comment]
Did you actually make sure that the right version of LP (BungeeCord version) is on BungeeCord and actually loaded?
If the plugin doesn't exist/isn't loaded then obviously will there be errors.

**Comment by LiinxTV** [comment]
I have solved, i had just put my initiator on the onLoad, but we must put initiator in onEnable if we put a depends on the bungee.yml

My fault, i close the thread
