### ISSUE TITLE
Error on Nukkit (player quit)

### ISSUE THREAD

**Issue by ToraToraNii** [lucko/LuckPerms#2269]
**Condition**: player without Xbox account tries to join server and gets kicked due to "not authenticated"
Plugin compiled from https://github.com/lucko/LuckPerms/commit/fe32aa2d33e0f18559d8e6e792cfd65aaf103d37
Logs:
```
[FATAL] Could not pass event "cn.nukkit.event.player.PlayerQuitEvent" to "LuckPerms v5.0.151": null on me.lucko.luckperms.nukkit.listeners.NukkitConnectionListener
[ERROR] Throwing
cn.nukkit.utils.EventException: null
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[nukkit.jar:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) ~[nukkit.jar:?]
	at cn.nukkit.Player.close(Player.java:3783) ~[nukkit.jar:?]
	at cn.nukkit.Player.close(Player.java:3730) ~[nukkit.jar:?]
	at cn.nukkit.Player.close(Player.java:3726) ~[nukkit.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:2200) ~[nukkit.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_242]
	at cn.nukkit.network.Network.processPackets(Network.java:202) [nukkit.jar:?]
	at cn.nukkit.network.Network.processBatch(Network.java:187) [nukkit.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:2151) [nukkit.jar:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:76) [nukkit.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:88) [nukkit.jar:?]
	at cn.nukkit.Server.tick(Server.java:1155) [nukkit.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:938) [nukkit.jar:?]
	at cn.nukkit.Server.start(Server.java:906) [nukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:581) [nukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:119) [nukkit.jar:?]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_242]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:1978) ~[?:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:1953) ~[?:?]
	at java.util.Collections$SetFromMap.add(Collections.java:5515) ~[?:1.8.0_242]
	at com.google.common.collect.ForwardingCollection.add(ForwardingCollection.java:89) ~[nukkit.jar:?]
	at me.lucko.luckperms.common.model.manager.user.UserHousekeeper.registerUsage(UserHousekeeper.java:57) ~[?:?]
	at me.lucko.luckperms.common.plugin.util.AbstractConnectionListener.handleDisconnect(AbstractConnectionListener.java:118) ~[?:?]
	at me.lucko.luckperms.nukkit.listeners.NukkitConnectionListener.onPlayerQuit(NukkitConnectionListener.java:191) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[nukkit.jar:?]
	... 17 more
```

**Comment by lucko** [comment]
Thanks, should be fixed by the above commit.
