### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by geronimomc** [lucko/LuckPerms#2283]
```
> [20:38:16 WARN]: Exception in thread "Thread-16"
> [20:38:16 WARN]: java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms
> [20:38:16 WARN]: at net.fatehub.plugin.handlers.permissions.implement.LuckPermsPermissionSystem.getName(LuckPermsPermissionSystem.java:20)
> [20:38:16 WARN]: at net.fatehub.plugin.scoreboard.ScorebardAdapter.lambda$getLines$0(ScorebardAdapter.java:32)
> [20:38:16 WARN]: at java.util.ArrayList.forEach(ArrayList.java:1257)
> [20:38:16 WARN]: at net.fatehub.plugin.scoreboard.ScorebardAdapter.getLines(ScorebardAdapter.java:30)
> [20:38:16 WARN]: at net.fatehub.plugin.utilities.assemble.AssembleThread.tick(AssembleThread.java:65)
> [20:38:16 WARN]: at net.fatehub.plugin.utilities.assemble.AssembleThread.run(AssembleThread.java:30)
> [20:38:16 WARN]: Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.LuckPerms
> [20:38:16 WARN]: at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> [20:38:16 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
> [20:38:16 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
> [20:38:16 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
> [20:38:16 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
> [20:38:16 WARN]: ... 6 more
```

Got this random error when a user joined the server

**Comment by Tobi406** [comment]
One of your plugins doesn't supports the v5 version of the API.

Best is to contact the author of FateHub that their plugin doesn't work with the new LP API anymore.
As a temporary solution see [api compatility on the wiki!](https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5#api-compatibility)
