### ISSUE TITLE
Server console flooding with warning

### ISSUE THREAD

**Issue by Ghoulcinder** [lucko/LuckPerms#2284]
Anyone who might have a clue what the issue could be? Tried removing other plugins to check for any compatibility issues and didn't seem to make a difference. Tried putting legacy API in the LuckPerms extensions folder also. Had no issues when on 1.14 but upgraded to 1.15 recently and problems have arisen since.

Server works just fine, console just gets spammed with the following messages as soon as someone joins, and whenever a person types in chat.

[21:08:06] [Server thread/WARN]: [LuckPerms] An exception was thrown by me.lucko.luckperms.bukkit.context.WorldCalculator whilst calculating the context of subject CraftPlayer-name=Ghoulcinder-
[21:08:06] [Server thread/WARN]: java.lang.IllegalArgumentException: value is (effectively) empty
[21:08:06] [Server thread/WARN]:    at me.lucko.luckperms.common.context.contextset.AbstractContextSet.sanitizeValue(AbstractContextSet.java:87)
[21:08:06] [Server thread/WARN]:    at me.lucko.luckperms.common.context.contextset.ImmutableContextSetImpl$BuilderImpl.add(ImmutableContextSetImpl.java:220)
[21:08:06] [Server thread/WARN]:    at me.lucko.luckperms.common.context.contextset.ImmutableContextSetImpl$BuilderImpl.add(ImmutableContextSetImpl.java:200)
[21:08:06] [Server thread/WARN]:    at me.lucko.luckperms.bukkit.context.WorldCalculator.calculate(WorldCalculator.java:57)
[21:08:06] [Server thread/WARN]:    at me.lucko.luckperms.bukkit.context.WorldCalculator.calculate(WorldCalculator.java:45)
[21:08:06] [Server thread/WARN]:    at me.lucko.luckperms.common.context.ContextManager.calculate(ContextManager.java:117)
[21:08:06] [Server thread/WARN]:    at me.lucko.luckperms.common.context.QueryOptionsCache.supply(QueryOptionsCache.java:54)
[21:08:06] [Server thread/WARN]:    at me.lucko.luckperms.common.context.QueryOptionsCache.supply(QueryOptionsCache.java:42)
[21:08:06] [Server thread/WARN]:    at me.lucko.luckperms.common.cache.ExpiringCache.get(ExpiringCache.java:64)
[21:08:06] [Server thread/WARN]:    at me.lucko.luckperms.common.context.QueryOptionsCache.getQueryOptions(QueryOptionsCache.java:59)
[21:08:06] [Server thread/WARN]:    at me.lucko.luckperms.bukkit.inject.permissible.LuckPermsPermissible.hasPermission(LuckPermsPermissible.java:174)
[21:08:06] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_15_R1.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:221)
[21:08:06] [Server thread/WARN]:    at com.earth2me.essentials.perm.impl.SuperpermsHandler.hasPermission(SuperpermsHandler.java:40)
[21:08:06] [Server thread/WARN]:    at com.earth2me.essentials.perm.PermissionsHandler.hasPermission(PermissionsHandler.java:62)
[21:08:06] [Server thread/WARN]:    at com.earth2me.essentials.User.isAuthorizedCheck(User.java:112)
[21:08:06] [Server thread/WARN]:    at com.earth2me.essentials.User.isAuthorized(User.java:93)
[21:08:06] [Server thread/WARN]:    at com.earth2me.essentials.EssentialsPlayerListener$1DelayJoinTask.run(EssentialsPlayerListener.java:315)
[21:08:06] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81)
[21:08:06] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394)
[21:08:06] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036)
[21:08:06] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406)
[21:08:06] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984)
[21:08:06] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824)
[21:08:06] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:748)

**Comment by lucko** [comment]
I believe this is fixed already in the latest version.

https://luckperms.net/

**Comment by Ghoulcinder** [comment]
Version 5.1.7 indeed fixed the problem! I thought I had the most recent one as I downloaded it from spigotmc, turns out it was outdated indeed.

Thank you very much for the assistance!
