### ISSUE TITLE
[Bungee] SQL No more working since add plugin PremiumVanish

### ISSUE THREAD

**Issue by tutur1004** [lucko/LuckPerms#2285]
Got this errors on bungee start
`22:46:10 [WARNING] Exception encountered when loading plugin: LuckPerms
java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:418)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
at me.lucko.luckperms.lib.hikari.HikariConfig.<clinit>(HikariConfig.java:51)
at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:77)
at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:150)
at me.lucko.luckperms.common.storage.Storage.init(Storage.java:115)
at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88)
at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:145)
at me.lucko.luckperms.bungee.LPBungeeBootstrap.onEnable(LPBungeeBootstrap.java:148)
at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:286)
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)`
Someone can help me ?
Work perfectly before, I'm using MariaDB an 5.1.1 bungee version !

**Comment by BrainStone** [comment]
See #2255

**Comment by tutur1004** [comment]
ik the plugin who make this error, it's premiumvanish.. But Premium work and Luck nop so the problem is from LuckPerm..

**Comment by BrainStone** [comment]
No it's not.

Like if you smash a window with a stone, is it the stone's fault for smashing the window or is it the windows's fault for breaking?  
(stone = PremiumVanish, window = LuckPerms)

**Comment by tutur1004** [comment]
Hm.. Same error for someone else this day ? Strange..

**Comment by BrainStone** [comment]
Reach out to the author if PremiumVanish. They should be able to fix this easily.
