### ISSUE TITLE
Unable to pass event UserDataRecalculateEvent to handler

### ISSUE THREAD

**Issue by mibby** [lucko/LuckPerms#2289]
Noticed this error on shutdown with LuckPerms dev 1082.

```
[12:38:30] [Server thread/INFO]: [LuckPerms] Disabling LuckPerms v5.1.3
[12:38:30] [Server thread/INFO]: [LuckPerms] Starting shutdown process...
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: [LuckPerms] Unable to pass event UserDataRecalculateEvent to handler me.lucko.luckperms.bukkit.LPBukkitPlugin$$Lambda$3018/0x0000000801803040
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@794d68b8[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@73b503c8[Wrapped task = me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$$Lambda$5220/0x00000008029f0440@7d72e3ce]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@3c4fe9f5[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 107964]
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2057)
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:827)
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: 	at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler.asyncLater(AbstractJavaScheduler.java:71)
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: 	at me.lucko.luckperms.common.cache.BufferedRequest$Processor.scheduleTask(BufferedRequest.java:142)
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: 	at me.lucko.luckperms.common.cache.BufferedRequest$Processor.<init>(BufferedRequest.java:125)
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: 	at me.lucko.luckperms.common.cache.BufferedRequest.request(BufferedRequest.java:83)
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: 	at me.lucko.luckperms.bukkit.listeners.BukkitCommandListUpdater.onUserDataRecalculate(BukkitCommandListUpdater.java:72)
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: 	at me.lucko.luckperms.common.event.LuckPermsEventSubscription.invoke(LuckPermsEventSubscription.java:95)
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: 	at me.lucko.luckperms.common.event.LuckPermsEventSubscription.invoke(LuckPermsEventSubscription.java:43)
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: 	at me.lucko.luckperms.lib.eventbus.SimpleEventBus.post(SimpleEventBus.java:107)
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: 	at me.lucko.luckperms.common.event.AbstractEventBus.post(AbstractEventBus.java:84)
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: 	at me.lucko.luckperms.common.event.EventDispatcher.post(EventDispatcher.java:115)
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: 	at me.lucko.luckperms.common.event.EventDispatcher.lambda$post$0(EventDispatcher.java:128)
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1429)
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[12:38:30] [ForkJoinPool-2-worker-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[12:38:30] [Server thread/INFO]: [LuckPerms] Closing storage...
[12:38:30] [Server thread/INFO]: [LuckPerms] Goodbye!
```

**Comment by lucko** [comment]
Thank you :)
