### ISSUE TITLE
Error pinging remote server thrown on bungee.

### ISSUE THREAD

**Issue by Joapple** [lucko/LuckPerms#230]
This happens on my bungee console, Luckperms is set to ping everytime a permission change. Most of tthe time the permission itself is lost, so if i was to set a permission through vault, like for example from my prefix plugin, the permission is lost. Using my plugin itself works, but sending as a console command from DeluxeMenus it won't work. Updated Luckperms to the latest one stable which is 3.0.78
<details><summary>Show stack trace</summary><pre><code>
16:35:53 [WARNING] Error pinging remote server
io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(...): localhost/127.0.0.1:20000
    at io.netty.channel.unix.Socket.finishConnect(...)(Unknown Source)
16:35:53 [SEVERE] Apr 04, 2017 4:35:53 PM net.md_5.bungee.event.EventBus post
WARNING: Error dispatching event ProxyPingEvent(connection=[/50.240.18.37:49386] <-> InitialHandler, response=ServerPing(version=null, players=null, description=                     Block Worlds: 1.10 , modinfo=ServerPing.ModInfo(type=FML, modList=[]))) to listener com.colt.JustOneMoreBungee.JustOneMore@7599720e
java.lang.NullPointerException
    at com.colt.JustOneMoreBungee.JustOneMore.onPing(JustOneMore.java:23)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:377)
    at net.md_5.bungee.connection.InitialHandler$3.done(InitialHandler.java:229)
    at net.md_5.bungee.connection.InitialHandler$3.done(InitialHandler.java:208)
    at net.md_5.bungee.BungeeServerInfo$1.operationComplete(BungeeServerInfo.java:139)
    at net.md_5.bungee.BungeeServerInfo$1.operationComplete(BungeeServerInfo.java:130)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
    at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
    at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.fulfillConnectPromise(AbstractEpollStreamChannel.java:910)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.finishConnect(AbstractEpollStreamChannel.java:929)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollOutReady(AbstractEpollStreamChannel.java:946)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:384)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Thread.java:745)
>
>
</code></pre></details>

**Comment by lucko** [comment]
The actual error has nothing to do with LuckPerms.

Report to the author of this plugin: `com.colt.JustOneMoreBungee.JustOneMore`

Pings are only sent automatically when you use LuckPerms commands.

**Comment by Joapple** [comment]
that plugin didn't get update since 2015 :( I will try without that plugin loaded hoping it fixed my permission lost issue. Thanks for your time! Really appreciate it.
