### ISSUE TITLE
LuckPerms doesn't work at latest Nukkit git-29007ba

### ISSUE THREAD

**Issue by nosooqua** [lucko/LuckPerms#2309]
Full startup log:
<details>
  <summary>Startup log</summary>
  
[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 35M / 0M
[Pterodactyl Daemon] Ensuring correct ownership of files.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
:/home/container$ java -Xms128M -Xmx1024M -jar server.jar
14:52:46 [INFO ] Loading nukkit.yml ...
14:52:46 [INFO ] Loading server.properties ...
14:52:46 [INFO ] Selected English (eng) as the base language
14:52:46 [INFO ] Starting Minecraft: BE server version v1.14.60
=> 14:52:46 [INFO ] Selected Zlib Provider: 2 (cn.nukkit.utils.ZlibThreadLocal)
14:52:46 [INFO ] Opening server on 0.0.0.0:19201
14:52:46 [INFO ] This server is running Nukkit version git-29007ba "" (API 1.0.9)
14:52:46 [INFO ] Nukkit is distributed under the LGPL License
14:52:47 [INFO ] Loading recipes...
14:52:47 [INFO ] Loaded 1320 recipes.
14:52:47 [INFO ] Successfully loaded 0 resource packs
14:52:47 [INFO ] Loading LuckPerms v5.1.16
14:52:47 [INFO ] Epoll Status is true
14:52:50 [INFO ] Loading DbLib v1.0.1
14:52:50 [INFO ] [DbLib] Establishing a connection withjdbc:sqlite:nukkit.db (user:nukkit)
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
14:52:51 [INFO ] [DbLib] DbLib 1.0.1 created by fromgate for nukkit.ru
14:52:51 [INFO ] Loading KotlinLib v1.3.72
14:52:51 [INFO ] Loading PlaceholderAPI v1.3.3
14:52:51 [INFO ] Loading CubedChat v1.0.0
14:52:51 [INFO ] Loading Holograms v3.2.0
14:52:51 [INFO ] Loading Placeholders v1.3
14:52:51 [INFO ] Enabling LuckPerms v5.1.16
14:52:51 [INFO ] __
14:52:51 [INFO ] | |__) LuckPerms v5.1.16
14:52:51 [INFO ] |___ | Running on Nukkit - Nukkit
14:52:51 [INFO ]
14:52:51 [INFO ] [LuckPerms] Loading configuration...
14:52:51 [INFO ] [LuckPerms] Loading storage provider... [MYSQL]
[main] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Starting...
[main] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Start completed.
14:52:52 [INFO ] [LuckPerms] Loading messaging service... [SQL]
14:52:52 [INFO ] [LuckPerms] Loading internal permission managers...
14:52:52 [ERROR] Throwing
java.lang.RuntimeException: java.lang.ExceptionInInitializerError
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:443) [server.jar:?]
at cn.nukkit.Server.enablePlugin(Server.java:741) [server.jar:?]
at cn.nukkit.Server.enablePlugins(Server.java:730) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:491) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:112) [server.jar:?]
Caused by: java.lang.ExceptionInInitializerError
at me.lucko.luckperms.nukkit.inject.permissible.MonitoredPermissibleBase.<init>(MonitoredPermissibleBase.java:62) ~[?:?]
at me.lucko.luckperms.nukkit.inject.permissible.PermissibleMonitoringInjector.transform(PermissibleMonitoringInjector.java:82) ~[?:?]
at me.lucko.luckperms.nukkit.inject.permissible.PermissibleMonitoringInjector.injectConsole(PermissibleMonitoringInjector.java:96) ~[?:?]
at me.lucko.luckperms.nukkit.inject.permissible.PermissibleMonitoringInjector.run(PermissibleMonitoringInjector.java:57) ~[?:?]
at me.lucko.luckperms.nukkit.LPNukkitPlugin.setupPlatformHooks(LPNukkitPlugin.java:162) ~[?:?]
at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:171) ~[?:?]
at me.lucko.luckperms.nukkit.LPNukkitBootstrap.onEnable(LPNukkitBootstrap.java:125) ~[?:?]
at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[server.jar:?]
at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[server.jar:?]
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) ~[server.jar:?]
... 4 more
Caused by: java.lang.IllegalArgumentException: Can not set final java.util.Set field cn.nukkit.permission.PermissibleBase.attachments to me.lucko.luckperms.common.util.EmptyCollections$EmptyList
at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:1.8.0_242]
at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:1.8.0_242]
at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:83) ~[?:1.8.0_242]
at java.lang.reflect.Field.set(Field.java:764) ~[?:1.8.0_242]
at me.lucko.luckperms.nukkit.inject.permissible.DummyPermissibleBase.<init>(DummyPermissibleBase.java:71) ~[?:?]
at me.lucko.luckperms.nukkit.inject.permissible.DummyPermissibleBase.<clinit>(DummyPermissibleBase.java:65) ~[?:?]
at me.lucko.luckperms.nukkit.inject.permissible.MonitoredPermissibleBase.<init>(MonitoredPermissibleBase.java:62) ~[?:?]
at me.lucko.luckperms.nukkit.inject.permissible.PermissibleMonitoringInjector.transform(PermissibleMonitoringInjector.java:82) ~[?:?]
at me.lucko.luckperms.nukkit.inject.permissible.PermissibleMonitoringInjector.injectConsole(PermissibleMonitoringInjector.java:96) ~[?:?]
at me.lucko.luckperms.nukkit.inject.permissible.PermissibleMonitoringInjector.run(PermissibleMonitoringInjector.java:57) ~[?:?]
at me.lucko.luckperms.nukkit.LPNukkitPlugin.setupPlatformHooks(LPNukkitPlugin.java:162) ~[?:?]
at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:171) ~[?:?]
at me.lucko.luckperms.nukkit.LPNukkitBootstrap.onEnable(LPNukkitBootstrap.java:125) ~[?:?]
at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[server.jar:?]
at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[server.jar:?]
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) ~[server.jar:?]
... 4 more
14:52:52 [INFO ] Disabling LuckPerms v5.1.16
14:52:52 [INFO ] [LuckPerms] Starting shutdown process...
14:52:52 [ERROR] Throwing
java.lang.NullPointerException: null
at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.disable(AbstractLuckPermsPlugin.java:218) ~[?:?]
at me.lucko.luckperms.nukkit.LPNukkitBootstrap.onDisable(LPNukkitBootstrap.java:133) ~[?:?]
at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:91) ~[server.jar:?]
at cn.nukkit.plugin.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:132) ~[server.jar:?]
at cn.nukkit.plugin.PluginManager.disablePlugin(PluginManager.java:513) [server.jar:?]
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:445) [server.jar:?]
at cn.nukkit.Server.enablePlugin(Server.java:741) [server.jar:?]
at cn.nukkit.Server.enablePlugins(Server.java:730) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:491) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:112) [server.jar:?]
14:52:52 [INFO ] Enabling Holograms v3.2.0
14:52:52 [INFO ] [Holograms] Loading characters...
14:52:52 [INFO ] [Holograms] Loading config...
14:52:52 [INFO ] [Holograms] Loading placeholders
14:52:52 [INFO ] [Holograms] Registering default grid sources
14:52:52 [INFO ] [Holograms] Loading grid config...
14:52:52 [INFO ] [Holograms] Loading holograms
14:52:52 [INFO ] Preparing level "world"
14:52:52 [ERROR] No level called "nether" found or nether is disabled in server properties! Nether functionality will be disabled.
14:52:52 [INFO ] Enabling DbLib v1.0.1
14:52:52 [INFO ] Enabling KotlinLib v1.3.72
14:52:52 [INFO ] Enabling PlaceholderAPI v1.3.3
14:52:52 [INFO ] Enabling CubedChat v1.0.0
14:52:52 [INFO ] Enabling Placeholders v1.3
14:52:52 [INFO ] [Placeholders] Nukkit placeholders loaded
14:52:52 [ERROR] Throwing
java.lang.RuntimeException: java.lang.IllegalStateException: The LuckPerms API is not loaded.
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:443) [server.jar:?]
at cn.nukkit.Server.enablePlugin(Server.java:741) [server.jar:?]
at cn.nukkit.Server.enablePlugins(Server.java:730) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:566) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:112) [server.jar:?]
Caused by: java.lang.IllegalStateException: The LuckPerms API is not loaded.
at net.luckperms.api.LuckPermsProvider.get(LuckPermsProvider.java:50) ~[?:?]
at com.creeperface.nukkitx.placeholders.providers.LuckPermsProvider.registerPlaceholders(LuckPermsProvider.kt:18) ~[?:?]
at com.creeperface.nukkitx.placeholders.Placeholders.onEnable(Placeholders.kt:24) ~[?:?]
at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[server.jar:?]
at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[server.jar:?]
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) ~[server.jar:?]
... 4 more
14:52:52 [INFO ] Disabling Placeholders v1.3
14:52:52 [INFO ] Starting GS4 status listener
14:52:52 [INFO ] Setting query port to 19201
14:52:52 [INFO ] Query is running on 0.0.0.0:19201
14:52:52 [INFO ] Default game type: Survival Mode
14:52:52 [INFO ] Done (6.487s)! For help, type "help" or "?"
[Pterodactyl Daemon] Server marked as ON
ver=> 14:54:53 [INFO ] This server is running Nukkit git-29007ba 「」 implementing API version 1.0.9 for Minecraft: BE v1.14.60 (protocol version 390)
15:03:10 [INFO ] nosooqua[/172.18.0.1:57796] logged in with entity id 1 at (world, -22.0501, 70.4469, 36.7521)
15:03:11 [INFO ] nosooqua joined the game
  
</details>

**Comment by nosooqua** [comment]
Sorry, did not notice a similar issue. Duplicate #2290
