### ISSUE TITLE
Null Pointer Error

### ISSUE THREAD

**Issue by good777LUCKY** [lucko/LuckPerms#2333]
When I use Luckperms and FuturePlots in Nukkit, it will make this error.

2020-05-25 21:51:54.213 [main] FATAL - plot에서 "plot claim" 명령어 실행 중 처리되지 않은 예외가 발생했습니다: java.lang.NullPointerException: permission
at java.util.Objects.requireNonNull(Objects.java:228)
at me.lucko.luckperms.nukkit.inject.permissible.LuckPermsPermissible.addAttachment(LuckPermsPermissible.java:247)
at cn.nukkit.Player.addAttachment(Player.java:535)
at cn.nukkit.Player.addAttachment(Player.java:530)
at cn.nukkit.Player.addAttachment(Player.java:525)
at tim03we.futureplots.FuturePlots.claimAvailable(FuturePlots.java:172)
at tim03we.futureplots.commands.ClaimCommand.execute(ClaimCommand.java:41)
at tim03we.futureplots.commands.MainCommand.execute(MainCommand.java:37)
at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257)
at cn.nukkit.Server.dispatchCommand(Server.java:767)
at cn.nukkit.Player.handleDataPacket(Player.java:2797)
at org.itxtech.synapseapi.SynapsePlayer.handleDataPacket(SynapsePlayer.java:395)
at org.itxtech.synapseapi.SynapseEntry$Ticker.run(SynapseEntry.java:263)
at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:296)
at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:277)
at cn.nukkit.Server.tick(Server.java:1148)
at cn.nukkit.Server.tickProcessor(Server.java:919)
at cn.nukkit.Server.start(Server.java:896)
at cn.nukkit.Server.(Server.java:578)
at cn.nukkit.Nukkit.main(Nukkit.java:112)

2020-05-25 21:51:54.214 [main] ERROR - Throwing
java.lang.NullPointerException: permission
at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_252]
at me.lucko.luckperms.nukkit.inject.permissible.LuckPermsPermissible.addAttachment(LuckPermsPermissible.java:247) ~[?:?]
at cn.nukkit.Player.addAttachment(Player.java:535) ~[nukkit-1.0-SNAPSHOT.jar:?]
at cn.nukkit.Player.addAttachment(Player.java:530) ~[nukkit-1.0-SNAPSHOT.jar:?]
at cn.nukkit.Player.addAttachment(Player.java:525) ~[nukkit-1.0-SNAPSHOT.jar:?]
at tim03we.futureplots.FuturePlots.claimAvailable(FuturePlots.java:172) ~[?:?]
at tim03we.futureplots.commands.ClaimCommand.execute(ClaimCommand.java:41) ~[?:?]
at tim03we.futureplots.commands.MainCommand.execute(MainCommand.java:37) ~[?:?]
at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257) [nukkit-1.0-SNAPSHOT.jar:?]
at cn.nukkit.Server.dispatchCommand(Server.java:767) [nukkit-1.0-SNAPSHOT.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:2797) [nukkit-1.0-SNAPSHOT.jar:?]
at org.itxtech.synapseapi.SynapsePlayer.handleDataPacket(SynapsePlayer.java:395) [synapse-api-1.0-SNAPSHOT.jar:?]
at org.itxtech.synapseapi.SynapseEntry$Ticker.run(SynapseEntry.java:263) [synapse-api-1.0-SNAPSHOT.jar:?]
at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99) [nukkit-1.0-SNAPSHOT.jar:?]
at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:296) [nukkit-1.0-SNAPSHOT.jar:?]
at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:277) [nukkit-1.0-SNAPSHOT.jar:?]
at cn.nukkit.Server.tick(Server.java:1148) [nukkit-1.0-SNAPSHOT.jar:?]
at cn.nukkit.Server.tickProcessor(Server.java:919) [nukkit-1.0-SNAPSHOT.jar:?]
at cn.nukkit.Server.start(Server.java:896) [nukkit-1.0-SNAPSHOT.jar:?]
at cn.nukkit.Server.(Server.java:578) [nukkit-1.0-SNAPSHOT.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]

**Comment by lucko** [comment]
Report to the author of `tim03we.futureplots.FuturePlots`, this isn't a LP error.
