### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by PszemoPL** [lucko/LuckPerms#2348]
21:07:46 [SEVERE] 	at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:86)
21:07:46 [SEVERE] 	... 5 more
21:07:46 [SEVERE] java.util.concurrent.CompletionException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
21:07:46 [SEVERE] 	at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:91)
21:07:46 [SEVERE] 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
21:07:46 [SEVERE] 	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
21:07:46 [SEVERE] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
21:07:46 [SEVERE] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
21:07:46 [SEVERE] 	at java.lang.Thread.run(Thread.java:748)
21:07:46 [SEVERE] Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
21:07:46 [SEVERE] 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:689)
21:07:46 [SEVERE] 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
21:07:46 [SEVERE] 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
21:07:46 [SEVERE] 	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
21:07:46 [SEVERE] 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:151)
21:07:46 [SEVERE] 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.getPlayerName(SqlStorage.java:709)
21:07:46 [SEVERE] 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.savePlayerData(SqlStorage.java:639)
21:07:46 [SEVERE] 	at me.lucko.luckperms.common.storage.Storage.lambda$savePlayerData$20(Storage.java:259)
21:07:46 [SEVERE] 	at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:86)
21:07:46 [SEVERE] 	... 5 more
21:07:46 [SEVERE] java.util.concurrent.CompletionException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
21:07:46 [SEVERE] 	at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:91)
21:07:46 [SEVERE] 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
21:07:46 [SEVERE] 	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
21:07:46 [SEVERE] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
21:07:46 [SEVERE] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
21:07:46 [SEVERE] 	at java.lang.Thread.run(Thread.java:748)
21:07:46 [SEVERE] Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
21:07:46 [SEVERE] 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:689)
21:07:46 [SEVERE] 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
21:07:46 [SEVERE] 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
21:07:46 [SEVERE] 	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
21:07:46 [SEVERE] 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:151)
21:07:46 [SEVERE] 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.getPlayerName(SqlStorage.java:709)
21:07:46 [SEVERE] 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.savePlayerData(SqlStorage.java:639)
21:07:46 [SEVERE] 	at me.lucko.luckperms.common.storage.Storage.lambda$savePlayerData$20(Storage.java:259)
21:07:46 [SEVERE] 	at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:86)
21:07:46 [SEVERE] 	... 5 more

**Comment by darbyjack** [comment]
Please refer to https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#common-errors
