### ISSUE TITLE
LuckPerms Failed To Start.

### ISSUE THREAD

**Issue by Kylerh15** [lucko/LuckPerms#2390]
Im having a issue with LuckPerms 5.1.26 not being able to start and throwing a error while booting server

`[21:21:05 INFO]: [LuckPerms] Loading configuration...
[21:21:06 ERROR]: Error occurred while enabling LuckPerms v5.1.26 (Is it up to date?)
java.lang.NoSuchMethodError: guava10.com.google.common.collect.Multimaps.asMap(Lguava10/com/google/common/collect/SetMultimap;)Ljava/util/Map;
        at me.lucko.luckperms.common.context.contextset.ImmutableContextSetImpl.toMap(ImmutableContextSetImpl.java:104) ~[?:?]
        at me.lucko.luckperms.common.context.ContextSetJsonSerializer.serializeContextSet(ContextSetJsonSerializer.java:52) ~[?:?]
        at me.lucko.luckperms.common.config.ContextsFile.save(ContextsFile.java:88) ~[?:?]
        at me.lucko.luckperms.common.config.ContextsFile.load(ContextsFile.java:60) ~[?:?]
        at me.lucko.luckperms.common.config.AbstractConfiguration.load(AbstractConfiguration.java:88) ~[?:?]
        at me.lucko.luckperms.common.config.AbstractConfiguration.<init>(AbstractConfiguration.java:56) ~[?:?]
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:116) ~[?:?]
        at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:161) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.57]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.57]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.57]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.57]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.57]
        at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:463) [ayq.class:?]
        at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
        at net.minecraft.world.World.<init>(World.java:374) [ahb.class:?]
        at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]`

Server Version: Thermos-1.7.10-1614-57

**Comment by benwoo1110** [comment]
Bukkit-Forge hack may have bugs with cause lp to not work, you can try a workaround: https://github.com/lucko/LuckPerms/wiki/Installation#cauldron-thermos-etc
