### ISSUE TITLE
cannot use temp group parents

### ISSUE THREAD

**Issue by corwinbass** [lucko/LuckPerms#2422]
Using LP version 5.1.64 on Paper 1.16.1 (ver 26 currently but don't think it's relevant)

When i try to execute command like
`/lp user playername parent addtemp vip 31d`
i get exception in console and nothing happens
```
[16:43:48 WARN]: java.lang.NoSuchMethodError: net.luckperms.api.node.Node.getExpiryDuration()Ljava/time/Duration;
[16:43:48 WARN]: at me.lucko.luckperms.common.commands.generic.parent.ParentAddTemp.execute(ParentAddTemp.java:98)
[16:43:48 WARN]: at me.lucko.luckperms.common.command.abstraction.GenericParentCommand.execute(GenericParentCommand.java:90)
[16:43:48 WARN]: at me.lucko.luckperms.common.command.abstraction.GenericParentCommand.execute(GenericParentCommand.java:49)
[16:43:48 WARN]: at me.lucko.luckperms.common.command.abstraction.ParentCommand.execute(ParentCommand.java:109)
[16:43:48 WARN]: at me.lucko.luckperms.common.command.abstraction.ParentCommand.execute(ParentCommand.java:45)
[16:43:48 WARN]: at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:204)
[16:43:48 WARN]: at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:145)
[16:43:48 WARN]: at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
[16:43:48 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[16:43:48 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[16:43:48 WARN]: at java.lang.Thread.run(Thread.java:748)
```

**Comment by lucko** [comment]
One of your other plugins is shading an older version of the LuckPerms API - try removing anything with a dependency on LuckPerms, that should resolve the issue. When (if) you find the plugin which is causing the issue, then report it to the author. :)
