### ISSUE TITLE
Error!! i need help 

### ISSUE THREAD

**Issue by GoldOuOb** [lucko/LuckPerms#2438]
```
[Tue, 7. Jul 2020 07:55:20 SGT WARN] [LuckPerms] An exception was thrown by me.lucko.luckperms.common.context.LPStaticContextsCalculator whilst calculating the context of subject CraftPlayer{name=gold_OuO}
[Tue, 7. Jul 2020 07:55:20 SGT WARN] java.lang.IllegalArgumentException: value is (effectively) empty
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at me.lucko.luckperms.common.context.contextset.AbstractContextSet.sanitizeValue(AbstractContextSet.java:120)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at me.lucko.luckperms.common.context.contextset.ImmutableContextSetImpl$BuilderImpl.add(ImmutableContextSetImpl.java:235)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at me.lucko.luckperms.common.context.contextset.ImmutableContextSetImpl$BuilderImpl.add(ImmutableContextSetImpl.java:211)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at me.lucko.luckperms.common.context.LPStaticContextsCalculator.calculate(LPStaticContextsCalculator.java:51)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at net.luckperms.api.context.StaticContextCalculator.calculate(StaticContextCalculator.java:73)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at me.lucko.luckperms.common.context.ContextManager.calculate(ContextManager.java:138)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at me.lucko.luckperms.common.context.QueryOptionsCache.supply(QueryOptionsCache.java:54)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at me.lucko.luckperms.common.context.QueryOptionsCache.supply(QueryOptionsCache.java:42)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at me.lucko.luckperms.common.cache.ExpiringCache.get(ExpiringCache.java:64)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at me.lucko.luckperms.common.context.QueryOptionsCache.getQueryOptions(QueryOptionsCache.java:59)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at me.lucko.luckperms.bukkit.inject.permissible.LuckPermsPermissible.hasPermission(LuckPermsPermissible.java:175)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:112)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at com.earth2me.essentials.perm.impl.SuperpermsHandler.hasPermission(SuperpermsHandler.java:79)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at com.earth2me.essentials.perm.PermissionsHandler.hasPermission(PermissionsHandler.java:65)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at com.earth2me.essentials.User.isAuthorizedCheck(User.java:121)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at com.earth2me.essentials.User.isAuthorized(User.java:102)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at com.earth2me.essentials.User.checkActivity(User.java:685)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at com.earth2me.essentials.EssentialsTimer.run(EssentialsTimer.java:58)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[Tue, 7. Jul 2020 07:55:20 SGT WARN]     at java.lang.Thread.run(Thread.java:748)

```

WHO CAN HELP ME

**Comment by codingJWilliams** [comment]
Could you please help with some debugging info such as a plugin list, and if possible, steps to reproduce this, for example:

"Install Luckperms version a.b.c. Install EssentialsX v1.2.3. Run `lp user <> ... <>`. Run `/vanish` and you'll see the error" 

Or something. Just an out of context error will not help us debug the issue.

**Comment by lucko** [comment]
Check the value of `server` in your LP configuration file. It shouldn't be empty.

**Comment by GoldOuOb** [comment]
> Could you please help with some debugging info such as a plugin list, and if possible, steps to reproduce this, for example:

> "Install Luckperms version a.b.c. Install EssentialsX v1.2.3. Run lp user <> ... <>. Run /vanish and you'll see the error"

> Or something. Just an out of context error will not help us debug the issue.

EssentialsX 2.18.0.0
Luckperms 5.1.75

**Comment by Laarryy** [comment]
@GoldOuOb the error is caused because the `server` field (the first option in the LP config) is empty. Please ensure something is there. Also, stating the versions of which plugins are being used does not count as steps to reproduce

**Comment by jefflima1** [comment]
I'm having this same problem, my configuration is default containing "global" on the server

#
# - When set to "global" this setting is effectively ignored.
# - In all other cases, the value here is added to all players in a "server" context.
# - See: https://luckperms.net/wiki/Context
server: global

**Comment by codingJWilliams** [comment]
Please don't resurrect years-old posts with different issues.

For help configuring LuckPerms it's best to join the Discord - https://discord.com/invite/luckperms
