### ISSUE TITLE
Help Error LuckPerms with MySQL

### ISSUE THREAD

**Issue by AmbiDeck** [lucko/LuckPerms#2444]
```
 [22:58:05] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.1.75

[22:58:05] [Server thread/INFO]: [0;36;1m       [0;36;22m __    [m
[22:58:05] [Server thread/INFO]: [0;36;1m  |    [0;36;22m|__)   [0;32;22mLuckPerms [0;36;1mv5.1.75[m
[22:58:05] [Server thread/INFO]: [0;36;1m  |___ [0;36;22m|      [0;30;1mRunning on Bukkit - CraftBukkit[m
[22:58:05] [Server thread/INFO]: [m
[22:58:05] [Server thread/INFO]: [LuckPerms] Loading configuration...
[22:58:08] [Server thread/INFO]: [LuckPerms] Loading storage provider... [MYSQL]
[22:58:08] [Server thread/WARN]: [LuckPerms] A NoSuchMethodError has occurred whilst initialising Hikari. This is likely due to classloading conflicts between other plugins.
[22:58:08] [Server thread/WARN]: [LuckPerms] Please check for other plugins below (and try loading LuckPerms without them installed) before reporting the issue.
[22:58:08] [Server thread/ERROR]: Error occurred while enabling LuckPerms v5.1.75 (Is it up to date?)
java.lang.IllegalAccessError: tried to access class org.bukkit.plugin.java.PluginClassLoader from class me.lucko.luckperms.bukkit.LPBukkitBootstrap
	at me.luck.bukkit.LPBukkitBootstrap.identifyClassLoader(LPBukkitBootstrap.java:286) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.handleLinkageError(HikariConnectionFactory.java:183) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:87) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:152) ~[?:?]
	at me.lucko.luckperms.common.storage.Storage.init(Storage.java:115) ~[?:?]
	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:146) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:161) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
```

**Comment by benwoo1110** [comment]
Try starting your server with only luckperms plugin installed.
