### ISSUE TITLE
ERROR AL ENTRAR AL SERVIDOR

### ISSUE THREAD

**Issue by LucaPeluka** [lucko/LuckPerms#2445]
hola tengo un servidor spigot 1.16.1 que al principio no tenia plugins luego puse EssentialsX y EssentialsChatX lo siguiente fue instalar Luckperms bueno iba todo bien en la consola y de la nada empieza a dar estos errores y no se mucho de codigo busque por google y muchos lugares y no encontre nada tengo la ultima version de EssentialsX y de LuckPermissions, Al no encontrar nada decidi ver que pasaba en verdad y cuando intento entrar al servidor me dice A database error ocurred whilst loading permissions data. If you are server admin, please check the console for any errors.

pd: no sabia como adjuntarles la consola perdon.

```
[10:56:42 INFO]: [LuckPerms] Loading LuckPerms v5.1.75
[11:01:32 ERROR]: [LuckPerms] Unable to load dependency BYTEBUDDY.
[11:01:32 WARN]: me.lucko.luckperms.common.dependencies.DependencyDownloadException: java.net.SocketException: Software caused connection abort: recv failed
[11:01:32 WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyRepository.downloadRaw(DependencyRepository.java:109)
[11:01:32 WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyRepository.download(DependencyRepository.java:122)
[11:01:32 WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyRepository.download(DependencyRepository.java:147)
[11:01:32 WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManager.downloadDependency(DependencyManager.java:171)
[11:01:32 WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependency(DependencyManager.java:149)
[11:01:32 WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManager.lambda$loadDependencies$2(DependencyManager.java:127)
[11:01:32 WARN]: 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
[11:01:32 WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[11:01:32 WARN]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
[11:01:32 WARN]: 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[11:01:32 WARN]: 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[11:01:32 WARN]: Caused by: java.net.SocketException: Software caused connection abort: recv failed
[11:01:32 WARN]: 	at java.net.SocketInputStream.socketRead0(Native Method)
[11:01:32 WARN]: 	at java.net.SocketInputStream.socketRead(Unknown Source)
[11:01:32 WARN]: 	at java.net.SocketInputStream.read(Unknown Source)
[11:01:32 WARN]: 	at java.net.SocketInputStream.read(Unknown Source)
[11:01:32 WARN]: 	at sun.security.ssl.InputRecord.readFully(Unknown Source)
[11:01:32 WARN]: 	at sun.security.ssl.InputRecord.readV3Record(Unknown Source)
[11:01:32 WARN]: 	at sun.security.ssl.InputRecord.read(Unknown Source)
[11:01:32 WARN]: 	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
[11:01:32 WARN]: 	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
[11:01:32 WARN]: 	at sun.security.ssl.AppInputStream.read(Unknown Source)
[11:01:32 WARN]: 	at java.io.BufferedInputStream.read1(Unknown Source)
[11:01:32 WARN]: 	at java.io.BufferedInputStream.read(Unknown Source)
[11:01:32 WARN]: 	at sun.net.www.MeteredStream.read(Unknown Source)
[11:01:32 WARN]: 	at java.io.FilterInputStream.read(Unknown Source)
[11:01:32 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
[11:01:32 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
[11:01:32 WARN]: 	at com.google.common.io.ByteStreams.copy(ByteStreams.java:106)
[11:01:32 WARN]: 	at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:166)
[11:01:32 WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyRepository.downloadRaw(DependencyRepository.java:102)
[11:01:32 WARN]: 	... 10 more
[11:01:32 WARN]: 	Suppressed: javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketException: Software caused connection abort: recv failed
[11:01:32 WARN]: 		at sun.security.ssl.SSLSocketImpl.checkEOF(Unknown Source)
[11:01:32 WARN]: 		at sun.security.ssl.AppInputStream.available(Unknown Source)
[11:01:32 WARN]: 		at java.io.BufferedInputStream.available(Unknown Source)
[11:01:32 WARN]: 		at sun.net.www.MeteredStream.available(Unknown Source)
[11:01:32 WARN]: 		at sun.net.www.http.KeepAliveStream.close(Unknown Source)
[11:01:32 WARN]: 		at java.io.FilterInputStream.close(Unknown Source)
[11:01:32 WARN]: 		at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.close(Unknown Source)
[11:01:32 WARN]: 		at me.lucko.luckperms.common.dependencies.DependencyRepository.downloadRaw(DependencyRepository.java:107)
[11:01:32 WARN]: 		... 10 more
[11:01:32 WARN]: 	Caused by: javax.net.ssl.SSLException: java.net.SocketException: Software caused connection abort: recv failed
[11:01:32 WARN]: 		at sun.security.ssl.Alerts.getSSLException(Unknown Source)
[11:01:32 WARN]: 		at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
[11:01:32 WARN]: 		at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
[11:01:32 WARN]: 		at sun.security.ssl.SSLSocketImpl.handleException(Unknown Source)
[11:01:32 WARN]: 		at sun.security.ssl.SSLSocketImpl.handleException(Unknown Source)
[11:01:32 WARN]: 		at sun.security.ssl.AppInputStream.read(Unknown Source)
[11:01:32 WARN]: 		at java.io.BufferedInputStream.read1(Unknown Source)
[11:01:32 WARN]: 		at java.io.BufferedInputStream.read(Unknown Source)
[11:01:32 WARN]: 		at sun.net.www.MeteredStream.read(Unknown Source)
[11:01:32 WARN]: 		at java.io.FilterInputStream.read(Unknown Source)
[11:01:32 WARN]: 		at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
[11:01:32 WARN]: 		at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
[11:01:32 WARN]: 		at com.google.common.io.ByteStreams.copy(ByteStreams.java:106)
[11:01:32 WARN]: 		at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:166)
[11:01:32 WARN]: 		at me.lucko.luckperms.common.dependencies.DependencyRepository.downloadRaw(DependencyRepository.java:102)
[11:01:32 WARN]: 		... 10 more
[11:01:32 WARN]: 	[CIRCULAR REFERENCE:java.net.SocketException: Software caused connection abort: recv failed]
[11:01:32 INFO]: [LuckPerms] Enabling LuckPerms v5.1.75
[11:01:32 INFO]:         __    
[11:01:32 INFO]:   |    |__)   LuckPerms v5.1.75
[11:01:32 INFO]:   |___ |      Running on Bukkit - CraftBukkit
[11:01:32 INFO]: 
[11:01:32 INFO]: [LuckPerms] Loading configuration...
[11:01:34 ERROR]: [LuckPerms] Unable to load dependency H2_DRIVER.
[11:01:34 WARN]: me.lucko.luckperms.common.dependencies.DependencyDownloadException: java.net.UnknownHostException: repo1.maven.org
[11:01:34 WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyRepository.downloadRaw(DependencyRepository.java:109)
[11:01:34 WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyRepository.download(DependencyRepository.java:122)
[11:01:34 WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyRepository.download(DependencyRepository.java:147)
[11:01:34 WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManager.downloadDependency(DependencyManager.java:171)
[11:01:34 WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependency(DependencyManager.java:149)
[11:01:34 WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManager.lambda$loadDependencies$2(DependencyManager.java:127)
[11:01:34 WARN]: 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
[11:01:34 WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[11:01:34 WARN]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
[11:01:34 WARN]: 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[11:01:34 WARN]: 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[11:01:34 WARN]: Caused by: java.net.UnknownHostException: repo1.maven.org
[11:01:34 WARN]: 	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
[11:01:34 WARN]: 	at java.net.PlainSocketImpl.connect(Unknown Source)
[11:01:34 WARN]: 	at java.net.SocksSocketImpl.connect(Unknown Source)
[11:01:34 WARN]: 	at java.net.Socket.connect(Unknown Source)
[11:01:34 WARN]: 	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
[11:01:34 WARN]: 	at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
[11:01:34 WARN]: 	at sun.net.NetworkClient.doConnect(Unknown Source)
[11:01:34 WARN]: 	at sun.net.www.http.HttpClient.openServer(Unknown Source)
[11:01:34 WARN]: 	at sun.net.www.http.HttpClient.openServer(Unknown Source)
[11:01:34 WARN]: 	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
[11:01:34 WARN]: 	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
[11:01:34 WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
[11:01:34 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
[11:01:34 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
[11:01:34 WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
[11:01:34 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[11:01:34 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[11:01:34 WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[11:01:34 WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyRepository.downloadRaw(DependencyRepository.java:101)
[11:01:34 WARN]: 	... 10 more
[11:01:34 INFO]: [LuckPerms] Loading storage provider... [H2]
[11:01:35 ERROR]: Error occurred while enabling LuckPerms v5.1.75 (Is it up to date?)
java.lang.IllegalStateException: Dependency H2_DRIVER is not loaded.
	at me.lucko.luckperms.common.dependencies.DependencyManager.obtainClassLoaderWith(DependencyManager.java:90) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory.<init>(H2ConnectionFactory.java:65) ~[?:?]
	at me.lucko.luckperms.common.storage.StorageFactory.createNewImplementation(StorageFactory.java:117) ~[?:?]
	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:85) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:146) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:161) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:491) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:405) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:187) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[11:01:35 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[11:01:35 WARN]: The server will make no attempt to authenticate usernames. Beware.
[11:01:35 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[11:01:35 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[11:01:35 INFO]: Preparing level "world"
[11:01:35 INFO]: -------- World Settings For [world] --------
[11:01:35 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[11:01:35 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[11:01:35 INFO]: Item Despawn Rate: 6000
[11:01:35 INFO]: Item Merge Radius: 2.5
[11:01:35 INFO]: View Distance: 7
[11:01:35 INFO]: Zombie Aggressive Towards Villager: true
[11:01:35 INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[11:01:35 INFO]: Nerfing mobs spawned from spawners: false
[11:01:35 INFO]: Mob Spawn Range: 6
[11:01:35 INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[11:01:35 INFO]: Cactus Growth Modifier: 100%
[11:01:35 INFO]: Cane Growth Modifier: 100%
[11:01:35 INFO]: Melon Growth Modifier: 100%
[11:01:35 INFO]: Mushroom Growth Modifier: 100%
[11:01:35 INFO]: Pumpkin Growth Modifier: 100%
[11:01:35 INFO]: Sapling Growth Modifier: 100%
[11:01:35 INFO]: Beetroot Growth Modifier: 100%
[11:01:35 INFO]: Carrot Growth Modifier: 100%
[11:01:35 INFO]: Potato Growth Modifier: 100%
[11:01:35 INFO]: Wheat Growth Modifier: 100%
[11:01:35 INFO]: NetherWart Growth Modifier: 100%
[11:01:35 INFO]: Vine Growth Modifier: 100%
[11:01:35 INFO]: Cocoa Growth Modifier: 100%
[11:01:35 INFO]: Bamboo Growth Modifier: 100%
[11:01:35 INFO]: SweetBerry Growth Modifier: 100%
[11:01:35 INFO]: Kelp Growth Modifier: 100%
[11:01:35 INFO]: Max TNT Explosions: 100
[11:01:35 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[11:01:35 INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[11:01:35 INFO]: Experience Merge Radius: 3.0
[11:01:35 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[11:01:36 INFO]: -------- World Settings For [world_nether] --------
[11:01:36 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[11:01:36 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[11:01:36 INFO]: Item Despawn Rate: 6000
[11:01:36 INFO]: Item Merge Radius: 2.5
[11:01:36 INFO]: View Distance: 7
[11:01:36 INFO]: Zombie Aggressive Towards Villager: true
[11:01:36 INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[11:01:36 INFO]: Nerfing mobs spawned from spawners: false
[11:01:36 INFO]: Mob Spawn Range: 6
[11:01:36 INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[11:01:36 INFO]: Cactus Growth Modifier: 100%
[11:01:36 INFO]: Cane Growth Modifier: 100%
[11:01:36 INFO]: Melon Growth Modifier: 100%
[11:01:36 INFO]: Mushroom Growth Modifier: 100%
[11:01:36 INFO]: Pumpkin Growth Modifier: 100%
[11:01:36 INFO]: Sapling Growth Modifier: 100%
[11:01:36 INFO]: Beetroot Growth Modifier: 100%
[11:01:36 INFO]: Carrot Growth Modifier: 100%
[11:01:36 INFO]: Potato Growth Modifier: 100%
[11:01:36 INFO]: Wheat Growth Modifier: 100%
[11:01:36 INFO]: NetherWart Growth Modifier: 100%
[11:01:36 INFO]: Vine Growth Modifier: 100%
[11:01:36 INFO]: Cocoa Growth Modifier: 100%
[11:01:36 INFO]: Bamboo Growth Modifier: 100%
[11:01:36 INFO]: SweetBerry Growth Modifier: 100%
[11:01:36 INFO]: Kelp Growth Modifier: 100%
[11:01:36 INFO]: Max TNT Explosions: 100
[11:01:36 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[11:01:36 INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[11:01:36 INFO]: Experience Merge Radius: 3.0
[11:01:36 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[11:01:36 INFO]: -------- World Settings For [world_the_end] --------
[11:01:36 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[11:01:36 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[11:01:36 INFO]: Item Despawn Rate: 6000
[11:01:36 INFO]: Item Merge Radius: 2.5
[11:01:36 INFO]: View Distance: 7
[11:01:36 INFO]: Zombie Aggressive Towards Villager: true
[11:01:36 INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[11:01:36 INFO]: Nerfing mobs spawned from spawners: false
[11:01:36 INFO]: Mob Spawn Range: 6
[11:01:36 INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[11:01:36 INFO]: Cactus Growth Modifier: 100%
[11:01:36 INFO]: Cane Growth Modifier: 100%
[11:01:36 INFO]: Melon Growth Modifier: 100%
[11:01:36 INFO]: Mushroom Growth Modifier: 100%
[11:01:36 INFO]: Pumpkin Growth Modifier: 100%
[11:01:36 INFO]: Sapling Growth Modifier: 100%
[11:01:36 INFO]: Beetroot Growth Modifier: 100%
[11:01:36 INFO]: Carrot Growth Modifier: 100%
[11:01:36 INFO]: Potato Growth Modifier: 100%
[11:01:36 INFO]: Wheat Growth Modifier: 100%
[11:01:36 INFO]: NetherWart Growth Modifier: 100%
[11:01:36 INFO]: Vine Growth Modifier: 100%
[11:01:36 INFO]: Cocoa Growth Modifier: 100%
[11:01:36 INFO]: Bamboo Growth Modifier: 100%
[11:01:36 INFO]: SweetBerry Growth Modifier: 100%
[11:01:36 INFO]: Kelp Growth Modifier: 100%
[11:01:36 INFO]: Max TNT Explosions: 100
[11:01:36 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[11:01:36 INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[11:01:36 INFO]: Experience Merge Radius: 3.0
[11:01:36 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[11:01:36 INFO]: Preparing start region for dimension minecraft:overworld
[11:01:40 INFO]: Preparing spawn area: 0%
[11:01:40 INFO]: Preparing spawn area: 0%
[11:01:40 INFO]: Preparing spawn area: 0%
[11:01:40 INFO]: Preparing spawn area: 0%
[11:01:40 INFO]: Preparing spawn area: 0%
[11:01:40 INFO]: Preparing spawn area: 0%
[11:01:40 INFO]: Preparing spawn area: 0%
[11:01:40 INFO]: Preparing spawn area: 0%
[11:01:40 INFO]: Preparing spawn area: 0%
[11:01:41 INFO]: Preparing spawn area: 0%
[11:01:41 INFO]: Preparing spawn area: 53%
[11:01:42 INFO]: Time elapsed: 5497 ms
[11:01:42 INFO]: Preparing start region for dimension minecraft:the_nether
[11:01:46 INFO]: Preparing spawn area: 0%
[11:01:46 INFO]: Preparing spawn area: 0%
[11:01:46 INFO]: Preparing spawn area: 0%
[11:01:46 INFO]: Preparing spawn area: 0%
[11:01:46 INFO]: Preparing spawn area: 0%
[11:01:46 INFO]: Preparing spawn area: 0%
[11:01:46 INFO]: Preparing spawn area: 0%
[11:01:46 INFO]: Preparing spawn area: 0%
[11:01:46 INFO]: Preparing spawn area: 0%
[11:01:46 INFO]: Preparing spawn area: 59%
[11:01:47 INFO]: Preparing spawn area: 83%
[11:01:47 INFO]: Preparing spawn area: 83%
[11:01:48 INFO]: Preparing spawn area: 83%
[11:01:48 INFO]: Preparing spawn area: 83%
[11:01:49 INFO]: Preparing spawn area: 83%
[11:01:49 INFO]: Preparing spawn area: 83%
[11:01:50 INFO]: Preparing spawn area: 83%
[11:01:50 INFO]: Preparing spawn area: 83%
[11:01:51 INFO]: Preparing spawn area: 83%
[11:01:51 INFO]: Preparing spawn area: 83%
[11:01:52 INFO]: Preparing spawn area: 83%
[11:01:52 INFO]: Preparing spawn area: 83%
[11:01:53 INFO]: Preparing spawn area: 83%
[11:01:53 INFO]: Preparing spawn area: 84%
[11:01:54 INFO]: Preparing spawn area: 86%
[11:01:54 INFO]: Preparing spawn area: 87%
[11:01:55 INFO]: Preparing spawn area: 88%
[11:01:55 INFO]: Preparing spawn area: 90%
[11:01:56 INFO]: Preparing spawn area: 91%
[11:01:56 INFO]: Preparing spawn area: 92%
[11:01:57 INFO]: Preparing spawn area: 94%
[11:01:57 INFO]: Preparing spawn area: 95%
[11:01:58 INFO]: Preparing spawn area: 97%
[11:01:58 INFO]: Preparing spawn area: 99%
[11:01:58 INFO]: Time elapsed: 16704 ms
[11:01:58 INFO]: Preparing start region for dimension minecraft:the_end
[11:02:00 INFO]: Preparing spawn area: 0%
[11:02:00 INFO]: Preparing spawn area: 0%
[11:02:00 INFO]: Preparing spawn area: 0%
[11:02:00 INFO]: Preparing spawn area: 0%
[11:02:00 INFO]: Preparing spawn area: 83%
[11:02:01 INFO]: Preparing spawn area: 83%
[11:02:01 INFO]: Preparing spawn area: 86%
[11:02:02 INFO]: Preparing spawn area: 96%
[11:02:02 INFO]: Time elapsed: 3705 ms
[11:02:02 INFO]: Server permissions file permissions.yml is empty, ignoring it
[11:02:02 INFO]: Done (27.496s)! For help, type "help"
[11:04:48 ERROR]: [LuckPerms] Exception occurred whilst loading data for 8d520190-5ce7-3e6f-bfe0-379993e04ee6 - LucaPeluka
[11:04:48 WARN]: java.lang.NullPointerException
[11:04:48 WARN]: 	at me.lucko.luckperms.common.plugin.util.AbstractConnectionListener.loadUser(AbstractConnectionListener.java:67)
[11:04:48 WARN]: 	at me.lucko.luckperms.bukkit.listeners.BukkitConnectionListener.onPlayerPreLogin(BukkitConnectionListener.java:116)
[11:04:48 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:04:48 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[11:04:48 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[11:04:48 WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[11:04:48 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315)
[11:04:48 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:04:48 WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[11:04:48 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[11:04:48 WARN]: 	at net.minecraft.server.v1_16_R1.LoginListener$LoginHandler.fireEvents(LoginListener.java:270)
[11:04:48 WARN]: 	at net.minecraft.server.v1_16_R1.LoginListener$1.run(LoginListener.java:183)
[11:04:48 ERROR]: Could not pass event AsyncPlayerPreLoginEvent to LuckPerms v5.1.75
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) [spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) [spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.LoginListener$LoginHandler.fireEvents(LoginListener.java:270) [spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.LoginListener$1.run(LoginListener.java:183) [spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
Caused by: java.lang.NullPointerException
	at me.lucko.luckperms.bukkit.listeners.BukkitConnectionListener.onPlayerPreLogin(BukkitConnectionListener.java:126) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	... 5 more
```

**Comment by codingJWilliams** [comment]
Whoa dude, that's a big unreadable error. For cleanliness can you edit it out of the original message, and put it in somewhere like https://pastebin.com so that we can read it properly.

**Comment by lucko** [comment]
Your server needs to be connected to the internet when LuckPerms starts for the first time.
