### ISSUE TITLE
Luck perms error. Please help!!

### ISSUE THREAD

**Issue by ImTomOriginal** [lucko/LuckPerms#2450]
```
java.lang.RuntimeException: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'LuckPerms.luckperms_messenger' doesn't exist in engine
[13:40:36 ERROR]:       at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:57)
[13:40:36 ERROR]:       at me.lucko.luckperms.common.messaging.MessagingFactory$SqlMessengerProvider.obtain(MessagingFactory.java:154)
[13:40:36 ERROR]:       at me.lucko.luckperms.common.messaging.LuckPermsMessagingService.<init>(LuckPermsMessagingService.java:73)
[13:40:36 ERROR]:       at me.lucko.luckperms.common.messaging.MessagingFactory.getServiceFor(MessagingFactory.java:106)
[13:40:36 ERROR]:       at me.lucko.luckperms.bungee.messaging.BungeeMessagingFactory.getServiceFor(BungeeMessagingFactory.java:64)
[13:40:36 ERROR]:       at me.lucko.luckperms.common.messaging.MessagingFactory.getInstance(MessagingFactory.java:84)
[13:40:36 ERROR]:       at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:147)
[13:40:36 ERROR]:       at me.lucko.luckperms.bungee.LPBungeeBootstrap.onEnable(LPBungeeBootstrap.java:153)
[13:40:36 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:300)
[13:40:36 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290)
[13:40:36 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
[13:40:36 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[13:40:36 ERROR]: Caused by: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'LuckPerms.luckperms_messenger' doesn't exist in engine
[13:40:36 ERROR]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:40:36 ERROR]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[13:40:36 ERROR]:       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[13:40:36 ERROR]:       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[13:40:36 ERROR]:       at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[13:40:36 ERROR]:       at me.lucko.luckperms.lib.mysql.jdbc.Util.getInstance(Util.java:408)
[13:40:36 ERROR]:       at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[13:40:36 ERROR]:       at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
[13:40:36 ERROR]:       at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
[13:40:36 ERROR]:       at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[13:40:36 ERROR]:       at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[13:40:36 ERROR]:       at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[13:40:36 ERROR]:       at me.lucko.luckperms.lib.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
[13:40:36 ERROR]:       at me.lucko.luckperms.lib.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2020)
[13:40:36 ERROR]:       at me.lucko.luckperms.lib.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[13:40:36 ERROR]:       at me.lucko.luckperms.lib.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[13:40:36 ERROR]:       at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.init(AbstractSqlMessenger.java:74)
[13:40:36 ERROR]:       at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:55)
[13:40:36 ERROR]:       ... 11 more
```

**Comment by lucko** [comment]
Any other exceptions during on enable?

Seems like the messenger table wasn't able to be created - you could try deleting the table manually or setting `messaging-service` to `notsql`.
