### ISSUE TITLE
LuckPerms doesn't load (Caused by Zip exception)

### ISSUE THREAD

**Issue by ERASFWGD00** [lucko/LuckPerms#2452]
PaperSpigot 1.16.1, LuckPerms 5.1.75

I tried updating LP after moving my server from 1.15.2. The old version of LP worked fine even after I updated the server to 1.16.1, but I decided to get the latest version from the LuckPerms website anyways.
On server startup, this message consistently appears in the logs:
```
11.07 15:59:39 [Server] ERROR Could not load 'plugins/LuckPerms-Bukkit-5.1.75.jar' in folder 'plugins'
11.07 15:59:39 [Server] INFO org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
11.07 15:59:39 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:170) ~[patched_1.16.1.jar:git-Paper-19]
11.07 15:59:39 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.16.1.jar:git-Paper-19]
11.07 15:59:39 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:386) ~[patched_1.16.1.jar:git-Paper-19]
11.07 15:59:39 [Server] INFO at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.1.jar:git-Paper-19]
11.07 15:59:39 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-19]
11.07 15:59:39 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-19]
11.07 15:59:39 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
11.07 15:59:39 [Server] INFO Caused by: java.util.zip.ZipException: error in opening zip file
11.07 15:59:39 [Server] INFO at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_242]
11.07 15:59:39 [Server] INFO at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_242]
11.07 15:59:39 [Server] INFO at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_242]
11.07 15:59:39 [Server] INFO at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_242]
11.07 15:59:39 [Server] INFO at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_242]
11.07 15:59:39 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:158) ~[patched_1.16.1.jar:git-Paper-19]
11.07 15:59:39 [Server] INFO ... 6 more
``` 

I've tried installing a previous version of LP but that brings the error of 'version not up to date?' so paper/bukkit disables the plugin.
I've tried redownloading the plugin, clearing out the old files from the previous setup, but to no avail.
I'm sure it's probably some minor installation issue but I don't know what it is exactly so any help would be appreciated.

**Comment by benwoo1110** [comment]
Looks like the jar file is corrupted. If you are using a server hosting side to upload the .jar file, I'd suggest using FTP instead.

**Comment by benwoo1110** [comment]
To add on, ensure you don't have any software that alter .jar file (idk maybe like so zipping software or anti virus)

**Comment by ERASFWGD00** [comment]
Thank you. I found out the process of uploading the jar file onto the server trimmed some 200KB off of the file.
This isn't a LP issue so I'm closing the issue.
