### ISSUE TITLE
LuckPerms not working on 1.16.1

### ISSUE THREAD

**Issue by spiker5032** [lucko/LuckPerms#2453]
```
>.... [16:45:29 INFO]: [LuckPerms] Enabling LuckPerms v5.1.26
>.... [16:45:29 INFO]: __
>.... [16:45:29 INFO]: | |__) LuckPerms v5.1.26
>.... [16:45:29 INFO]: |___ | Running on Bukkit - Paper
>.... [16:45:29 INFO]:
>.... [16:45:29 INFO]: [LuckPerms] Loading configuration...
>.... [16:45:29 INFO]: [LuckPerms] Loading storage provider... [H2]
>.... [16:45:30 ERROR]: Error occurred while enabling LuckPerms v5.1.26 (Is it up to date?)
java.lang.IllegalStateException: me.lucko.luckperms.lib.caffeine.cache.SSA
at me.lucko.luckperms.lib.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:101) ~[?:?]
at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3393) ~[?:?]
at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.<init>(BoundedLocalCache.java:3721) ~[?:?]
at me.lucko.luckperms.lib.caffeine.cache.Caffeine.build(Caffeine.java:1021) ~[?:?]
at me.lucko.luckperms.common.commands.user.UserParentCommand.<init>(UserParentCommand.java:66) ~[?:?]
at me.lucko.luckperms.common.command.CommandManager.<init>(CommandManager.java:102) ~[?:?]
at me.lucko.luckperms.bukkit.BukkitCommandExecutor.<init>(BukkitCommandExecutor.java:69) ~[?:?]
at me.lucko.luckperms.bukkit.BukkitAsyncCommandExecutor.<init>(BukkitAsyncCommandExecutor.java:42) ~[?:?]
at me.lucko.luckperms.bukkit.LPBukkitPlugin.registerCommands(LPBukkitPlugin.java:152) ~[?:?]
at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:154) ~[?:?]
at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:161) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-87]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-87]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-87]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-87]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-87]
at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:209) ~[patched_1.16.1.jar:git-Paper-87]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-87]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-87]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_242]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_242]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_242]
at me.lucko.luckperms.lib.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:98) ~[?:?]
... 19 more
Caused by: java.lang.IllegalStateException: me.lucko.luckperms.lib.caffeine.cache.PSA
at me.lucko.luckperms.lib.caffeine.cache.NodeFactory.newFactory(NodeFactory.java:121) ~[?:?]
at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.<init>(BoundedLocalCache.java:240) ~[?:?]
at me.lucko.luckperms.lib.caffeine.cache.SS.<init>(SS.java:32) ~[?:?]
at me.lucko.luckperms.lib.caffeine.cache.SSA.<init>(SSA.java:48) ~[?:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_242]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_242]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_242]
at me.lucko.luckperms.lib.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:98) ~[?:?]
... 19 more
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.caffeine.cache.PSA
at java.net.URLClassLoader$1.run(URLClassLoader.java:371) ~[?:1.8.0_242]
at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_242]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_242]
at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_242]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.1.jar:git-Paper-87]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.1.jar:git-Paper-87]
at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
at me.lucko.luckperms.lib.caffeine.cache.NodeFactory.newFactory(NodeFactory.java:116) ~[?:?]
at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.<init>(BoundedLocalCache.java:240) ~[?:?]
at me.lucko.luckperms.lib.caffeine.cache.SS.<init>(SS.java:32) ~[?:?]
at me.lucko.luckperms.lib.caffeine.cache.SSA.<init>(SSA.java:48) ~[?:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_242]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_242]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_242]
at me.lucko.luckperms.lib.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:98) ~[?:?]
... 19 more
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
at java.util.zip.ZipFile.read(Native Method) ~[?:1.8.0_242]
at java.util.zip.ZipFile.access$1400(ZipFile.java:60) ~[?:1.8.0_242]
at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:734) ~[?:1.8.0_242]
at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:434) ~[?:1.8.0_242]
at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:1.8.0_242]
at sun.misc.Resource.getBytes(Resource.java:124) ~[?:1.8.0_242]
at java.net.URLClassLoader.defineClass(URLClassLoader.java:463) ~[?:1.8.0_242]
at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_242]
at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_242]
at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_242]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_242]
at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_242]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.1.jar:git-Paper-87]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.1.jar:git-Paper-87]
at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
at me.lucko.luckperms.lib.caffeine.cache.NodeFactory.newFactory(NodeFactory.java:116) ~[?:?]
at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.<init>(BoundedLocalCache.java:240) ~[?:?]
at me.lucko.luckperms.lib.caffeine.cache.SS.<init>(SS.java:32) ~[?:?]
at me.lucko.luckperms.lib.caffeine.cache.SSA.<init>(SSA.java:48) ~[?:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_242]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_242]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_242]
at me.lucko.luckperms.lib.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:98) ~[?:?]
... 19 more
>.... [16:45:30 INFO]: [LuckPerms] Disabling LuckPerms v5.1.26
>.... [16:45:30 INFO]: [LuckPerms] Starting shutdown process...
>.... [16:45:30 ERROR]: Error occurred while disabling LuckPerms v5.1.26 (Is it up to date?)
java.lang.NullPointerException: null
at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.disable(AbstractLuckPermsPlugin.java:218) ~[?:?]
at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onDisable(LPBukkitBootstrap.java:177) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.1.jar:git-Paper-87]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.1.jar:git-Paper-87]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.1.jar:git-Paper-87]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.1.jar:git-Paper-87]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-87]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-87]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-87]
at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:209) ~[patched_1.16.1.jar:git-Paper-87]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-87]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-87]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

After /lp
```
>.... [16:46:57 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'lp' in plugin LuckPerms v5.1.26 - plugin is disabled.
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.1.jar:git-Paper-87]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-87]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-87]
at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[patched_1.16.1.jar:git-Paper-87]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1719) ~[patched_1.16.1.jar:git-Paper-87]
at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-87]
at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-87]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-87]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-87]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-87]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-87]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-87]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-87]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-87]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-87]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-87]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-87]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-87]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

[https://i.gyazo.com/d519ccbe00c9592f2c2f65e3c6b246dc.png](url)

**Comment by benwoo1110** [comment]
Try delete the libs folder in luckperms folder?

**Comment by DoNotSpamPls** [comment]
You should probably also update to the latest version of LP

**Comment by lucko** [comment]
Deleting the libs folder should fix this.
