### ISSUE TITLE
Nukkit 1.16 Needs some fixes

### ISSUE THREAD

**Issue by marvinej** [lucko/LuckPerms#2464]
Server Build: https://ci.nukkitx.com/job/NukkitX/job/Server/job/feature%252F1.16/4/

```
[03:40:42] [INFO ]: Loading LuckPerms v5.1.55
[03:40:42] [FATAL]: Nukkit crashed
java.lang.NoClassDefFoundError: cn/nukkit/utils/Logger
	at me.lucko.luckperms.nukkit.LPNukkitBootstrap.onLoad(LPNukkitBootstrap.java:112) ~[?:?]
	at cn.nukkit.plugin.JavaPluginLoader.initPlugin(JavaPluginLoader.java:112) ~[Nukkit.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:60) ~[Nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:95) ~[Nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:259) ~[Nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:127) ~[Nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:119) ~[Nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:115) ~[Nukkit.jar:?]
	at cn.nukkit.Server.boot(Server.java:498) ~[Nukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:141) ~[Nukkit.jar:?]
Caused by: java.lang.ClassNotFoundException: cn.nukkit.utils.Logger
	at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:34) ~[Nukkit.jar:?]
	at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28) ~[Nukkit.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_252]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
	... 10 more

**Comment by lucko** [comment]
LuckPerms doesn't support this version of Nukkit just yet.
