### ISSUE TITLE
I can't join to server

### ISSUE THREAD

**Issue by minecraftixPL** [lucko/LuckPerms#2465]
I have in minecraft
A database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors. and in logs
```[19:56:12] [User Authenticator #2/ERROR]: [LuckPerms] Exception occurred whilst loading data for 56aa0ba4-4f36-3fa5-a32f-53ec31246161 - minecraftixPL
[19:56:12] [User Authenticator #2/WARN]: java.util.concurrent.CompletionException: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-199]
[19:56:12] [User Authenticator #2/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:91)
[19:56:12] [User Authenticator #2/WARN]: 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[19:56:12] [User Authenticator #2/WARN]: 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
[19:56:12] [User Authenticator #2/WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[19:56:12] [User Authenticator #2/WARN]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[19:56:12] [User Authenticator #2/WARN]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[19:56:12] [User Authenticator #2/WARN]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[19:56:12] [User Authenticator #2/WARN]: Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-199]
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.message.DbException.get(DbException.java:194)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:193)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:173)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.engine.Database.getPageStore(Database.java:2739)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.engine.Database.open(Database.java:769)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.engine.Database.openDatabase(Database.java:319)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.engine.Database.<init>(Database.java:313)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.engine.Engine.openSession(Engine.java:69)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.engine.Engine.openSession(Engine.java:201)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.engine.Engine.createSession(Engine.java:161)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.engine.Engine.createSession(Engine.java:31)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.Driver.connect(Driver.java:69)
[19:56:12] [User Authenticator #2/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory.getConnection(H2ConnectionFactory.java:83)
[19:56:12] [User Authenticator #2/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.getPlayerName(SqlStorage.java:706)
[19:56:12] [User Authenticator #2/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.savePlayerData(SqlStorage.java:636)
[19:56:12] [User Authenticator #2/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$savePlayerData$20(Storage.java:259)
[19:56:12] [User Authenticator #2/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:86)
[19:56:12] [User Authenticator #2/WARN]: 	... 6 more
[19:56:12] [User Authenticator #2/WARN]: Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/crafthost_serwery/svr74162/plugins/LuckPerms/luckperms-h2.mv.db [1.4.199/7]
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.mvstore.FileStore.open(FileStore.java:166)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
[19:56:12] [User Authenticator #2/WARN]: 	... 25 more
[19:56:12] [User Authenticator #2/WARN]: Caused by: java.nio.channels.OverlappingFileLockException
[19:56:12] [User Authenticator #2/WARN]: 	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
[19:56:12] [User Authenticator #2/WARN]: 	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
[19:56:12] [User Authenticator #2/WARN]: 	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1108)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
[19:56:12] [User Authenticator #2/WARN]: 	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
[19:56:12] [User Authenticator #2/WARN]: 	at org.h2.mvstore.FileStore.open(FileStore.java:163)
[19:56:12] [User Authenticator #2/WARN]: 	... 28 more
[19:56:12] [User Authenticator #2/INFO]: Disconnecting com.mojang.authlib.GameProfile@ad91561[id=56aa0ba4-4f36-3fa5-a32f-53ec31246161,name=minecraftixPL,properties={},legacy=false] (/188.137.65.55:57425): ?7[?b?lL?3?lP?7] ?cA database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors.
[19:56:12] [Server thread/INFO]: com.mojang.authlib.GameProfile@ad91561[id=56aa0ba4-4f36-3fa5-a32f-53ec31246161,name=minecraftixPL,properties={},legacy=false] (/127.0.0.1) lost connection: ?7[?b?lL?3?lP?7] ?cA database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors.```

**Comment by Laarryy** [comment]
`Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-199]`
`Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/crafthost_serwery/svr74162/plugins/LuckPerms/luckperms-h2.mv.db [1.4.199/7]`

These two lines describe the issue; the permissions file has somehow been locked and LP cannot access it

**Comment by lucko** [comment]
You most likely have another server instance still running in the background from the same folder.
