### ISSUE TITLE
stop server error

### ISSUE THREAD

**Issue by Cuki1998** [lucko/LuckPerms#2468]
[03:35:43 WARN]: Exception in thread "ForkJoinPool.commonPool-worker-18" java.util.concurrent.CompletionException: java.sql.SQLException: HikariDataSo
urce HikariDataSource (luckperms-hikari) has been closed.
[03:35:43 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:91)
[03:35:43 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
[03:35:43 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
[03:35:43 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[03:35:43 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
[03:35:43 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[03:35:43 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[03:35:43 WARN]: Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (luckperms-hikari) has been closed.
[03:35:43 WARN]:        at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
[03:35:43 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnecti
onFactory.java:151)
[03:35:43 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadUser(SqlStorage.java:276)
[03:35:43 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$loadUser$4(Storage.java:149)
[03:35:43 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:86)
[03:35:43 WARN]:        ... 6 more

**Comment by Laarryy** [comment]
Looks like the connection to the database is closed *just* before the rest of the plugin. Doesn't seem to be anything to worry about!
