### ISSUE TITLE
SSL-Certificate invalid for bytebin.lucko.me

### ISSUE THREAD

**Issue by Minecraftschurli** [lucko/LuckPerms#2510]
When I try to open an editor with `/lp editor` or look at the tree view with `/lp tree` it gives me this output in the console:
```log
[18:26:44 WARN]: java.lang.RuntimeException: Error uploading data to bytebin
[18:26:44 WARN]:        at me.lucko.luckperms.common.web.WebEditor.post(WebEditor.java:151)
[18:26:44 WARN]:        at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:175)
[18:26:44 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:50)
[18:26:44 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:42)
[18:26:44 WARN]:        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:204)
[18:26:44 WARN]:        at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:145)
[18:26:44 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
[18:26:44 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[18:26:44 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[18:26:44 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
[18:26:44 WARN]: Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname bytebin.lucko.me not verified:
[18:26:44 WARN]:     certificate: sha256/wFlRiNhq/i08PSvadw0ph+B1MyPMkQVYGXeN9gC/9Hg=
[18:26:44 WARN]:     DN: CN=search.dnsadvantage.com
[18:26:44 WARN]:     subjectAltNames: [search.dnsadvantage.com]
[18:26:44 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:350)
[18:26:44 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:300)
[18:26:44 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:185)
[18:26:44 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
[18:26:44 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
[18:26:44 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
[18:26:44 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
[18:26:44 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
[18:26:44 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[18:26:44 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[18:26:44 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
[18:26:44 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[18:26:44 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[18:26:44 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[18:26:44 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[18:26:44 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
[18:26:44 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[18:26:44 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[18:26:44 WARN]:        at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
[18:26:44 WARN]:        at me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
[18:26:44 WARN]:        at me.lucko.luckperms.common.web.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
[18:26:44 WARN]:        at me.lucko.luckperms.common.web.BytebinClient.makeHttpRequest(BytebinClient.java:69)
[18:26:44 WARN]:        at me.lucko.luckperms.common.web.BytebinClient.postContent(BytebinClient.java:94)
[18:26:44 WARN]:        at me.lucko.luckperms.common.web.WebEditor.post(WebEditor.java:146)
[18:26:44 WARN]:        ... 9 more```

Which makes me not able to even look at the current permission setup of my server

**Comment by lucko** [comment]
This is likely an issue at your end, not mine.

Maybe a firewall or filter policy is blocking the connection?

**Comment by Minecraftschurli** [comment]
It can't be on my end since i have no firewall policy that could block it and it says the ssl is invalid and not that the connection was blocked (or something like that)

**Comment by Minecraftschurli** [comment]
this issue also occurs for me when trying to download the latest version then i get redirected to some other website which says that the domain is malicious

**Comment by Turbotailz** [comment]
Are you hosting this on your own computer?

You probably have something blocking the connection, like an anti virus.

**Comment by Minecraftschurli** [comment]
No i'm hosting it on a rpi4b-8gb with Ubuntu server 20.04 for rpi

**Comment by benwoo1110** [comment]
on your raspberry pi, can you access https://bytebin.lucko.me ?

**Comment by Minecraftschurli** [comment]
I think I tried with wget and it didn't work

**Comment by benwoo1110** [comment]
ah if you can't connect to https://bytebin.lucko.me means there is definitely some issue with your network or network config on your raspberry pi.

**Comment by Minecraftschurli** [comment]
With `wget https://bytebin.lucko.me` I get this output
```
https://bytebin.lucko.me/
Resolving bytebin.lucko.me (bytebin.lucko.me)... 156.154.175.241, 156.154.176.241, 2606:4700:3036::ac43:c82e, ...
Connecting to bytebin.lucko.me (bytebin.lucko.me)|156.154.175.241|:443... connected.
ERROR: no certificate subject alternative name matches
        requested host name ‘bytebin.lucko.me’.
To connect to bytebin.lucko.me insecurely, use `--no-check-certificate'.```

**Comment by BrainStone** [comment]
Can you do `wget -v <URL>` and show the output?

**Comment by Minecraftschurli** [comment]
`wget -v https://bytebin.lucko.me`
```
https://bytebin.lucko.me/
Resolving bytebin.lucko.me (bytebin.lucko.me)... 156.154.175.241, 156.154.176.241, 2606:4700:3037::681b:966a, ...
Connecting to bytebin.lucko.me (bytebin.lucko.me)|156.154.175.241|:443... connected.
ERROR: no certificate subject alternative name matches
        requested host name ‘bytebin.lucko.me’.
To connect to bytebin.lucko.me insecurely, use `--no-check-certificate'.
```

**Comment by BrainStone** [comment]
My apologies I meant ``wget -dv https://bytebin.lucko.me``

**Comment by Minecraftschurli** [comment]
`wget -dv https://bytebin.lucko.me`
```
Setting --verbose (verbose) to 1
Setting --verbose (verbose) to 1
DEBUG output created by Wget 1.20.3 on linux-gnu.

Reading HSTS entries from /home/<user>/.wget-hsts
URI encoding = ‘UTF-8’
Converted file name 'index.html' (UTF-8) -> 'index.html' (UTF-8)
https://bytebin.lucko.me/
Resolving bytebin.lucko.me (bytebin.lucko.me)... 156.154.175.241, 156.154.176.241, 2606:4700:3037::681b:966a, ...
Caching bytebin.lucko.me => 156.154.175.241 156.154.176.241 2606:4700:3037::681b:966a 2606:4700:3030::681b:976a 2606:4700:3036::ac43:c82e
Connecting to bytebin.lucko.me (bytebin.lucko.me)|156.154.175.241|:443... connected.
Created socket 3.
Releasing 0x0000aaaad4524740 (new refcount 1).
Initiating SSL handshake.
Handshake successful; connected socket 3 to SSL handle 0x0000aaaad45258d0
certificate:
  subject: CN=search.dnsadvantage.com
  issuer:  CN=RapidSSL RSA CA 2018,OU=www.digicert.com,O=DigiCert Inc,C=US
ERROR: no certificate subject alternative name matches
        requested host name ‘bytebin.lucko.me’.
To connect to bytebin.lucko.me insecurely, use `--no-check-certificate'.
Closed 3/SSL 0x0000aaaad45258d0
```

**Comment by BrainStone** [comment]
Ok. Somehow you're being connected to a weird host.  
Does the name "search.dnsadvantage.com" or "dnsadvantage.com" say anything to you?
