### ISSUE TITLE
Luckperms Error when add plugin on BungeeCord 

### ISSUE THREAD

**Issue by SharkblackFr** [lucko/LuckPerms#2518]
```
06:23:16 [SEVERE] [LuckPerms] Exception occurred whilst loading data for de45bdc2-2bf3-487b-b497-4924787c97c7 - SharkblackFr
06:23:16 [SEVERE] java.lang.NullPointerException
06:23:16 [SEVERE]     at me.lucko.luckperms.common.plugin.util.AbstractConnectionListener.loadUser(AbstractConnectionListener.java:67)
06:23:16 [SEVERE]     at me.lucko.luckperms.bungee.listeners.BungeeConnectionListener.lambda$onPlayerLogin$0(BungeeConnectionListener.java:90)
06:23:16 [SEVERE]     at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
06:23:16 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
06:23:16 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
06:23:16 [SEVERE]     at java.lang.Thread.run(Thread.java:748)
06:23:16 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@609db43b, id=21, owner=me.lucko.luckperms.bungee.LPBungeeBootstrap@3943a2be, task=me.lucko.luckperms.bungee.listeners.BungeeConnectionListener$$Lambda$190/123817119@7194b156, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException
    at me.lucko.luckperms.bungee.listeners.BungeeConnectionListener.lambda$onPlayerLogin$0(BungeeConnectionListener.java:103)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```
the server version and in 1.14.4 and the bungeecord utilidé is the latest version.
Concerning luckperms we use the version Bungee (LuckPerms-Bungee-5.1.84.jar) and spigot (LuckPerms-Bukkit-5.1.84.jar)
please help me as soon as possible because I can no longer add bungeecord plugins using luckperms currently

thanks in advance for your help

**Comment by lucko** [comment]
The BungeeCord `LoginEvent` is being called with a null connection, this is likely a bug with your version of BungeeCord. Ensure you are using the latest build, or perhaps try using Waterfall instead. (https://papermc.io/downloads#Waterfall)
