### ISSUE TITLE
Exception on join/quit

### ISSUE THREAD

**Issue by i3ym** [lucko/LuckPerms#2522]
Paper-379 1.15.2
When player joins or quits server, this comes out

```
> [17:23:55 WARN]: java.lang.RuntimeException: Exception occurred whilst generating event instance
> [17:23:55 WARN]:        at me.lucko.luckperms.common.event.EventDispatcher.generate(EventDispatcher.java:137)
> [17:23:55 WARN]:        at me.lucko.luckperms.common.event.EventDispatcher.lambda$dispatchDataRecalculate$21(EventDispatcher.java:284)
> [17:23:55 WARN]:        at me.lucko.luckperms.common.event.EventDispatcher.lambda$post$0(EventDispatcher.java:127)
> [17:23:55 WARN]:        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1429)
> [17:23:55 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
> [17:23:55 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
> [17:23:55 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
> [17:23:55 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
> [17:23:55 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
> [17:23:55 WARN]: Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: no such constructor: me.lucko.luckperms.common.event.gen.user.UserDataRecalculateEvent.<init>(LuckPerms)void/invokeSpecial
> [17:23:55 WARN]:        at me.lucko.luckperms.common.event.gen.GeneratedEventClass.lambda$static$0(GeneratedEventClass.java:69)
> [17:23:55 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
> [17:23:55 WARN]:        at me.lucko.luckperms.common.cache.LoadingMap.get(LoadingMap.java:67)
> [17:23:55 WARN]:        at me.lucko.luckperms.common.event.gen.GeneratedEventClass.generate(GeneratedEventClass.java:80)
> [17:23:55 WARN]:        at me.lucko.luckperms.common.event.EventDispatcher.generate(EventDispatcher.java:135)
> [17:23:55 WARN]:        ... 8 more
> [17:23:55 WARN]: Caused by: java.lang.IllegalAccessException: no such constructor: me.lucko.luckperms.common.event.gen.user.UserDataRecalculateEvent.<init>(LuckPerms)void/invokeSpecial
> [17:23:55 WARN]:        at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:971)
> [17:23:55 WARN]:        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114)
> [17:23:55 WARN]:        at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2785)
> [17:23:55 WARN]:        at java.base/java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:1953)
> [17:23:55 WARN]:        at me.lucko.luckperms.common.event.gen.GeneratedEventClass.<init>(GeneratedEventClass.java:134)
> [17:23:55 WARN]:        at me.lucko.luckperms.common.event.gen.GeneratedEventClass.lambda$static$0(GeneratedEventClass.java:67)
> [17:23:55 WARN]:        ... 12 more
> [17:23:55 WARN]: Caused by: java.lang.LinkageError: bad method type alias: (LuckPerms)void not visible from class me.lucko.luckperms.common.event.gen.user.UserDataRecalculateEvent
> [17:23:55 WARN]:        at java.base/java.lang.invoke.MemberName.checkForTypeAlias(MemberName.java:876)
> [17:23:55 WARN]:        at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1088)
> [17:23:55 WARN]:        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1111)
> [17:23:55 WARN]:        ... 16 more
```
Plugin still works after that

**Comment by lucko** [comment]
Try updating to the latest version. https://luckperms.net/download
