### ISSUE TITLE
Error with SQL

### ISSUE THREAD

**Issue by Azuuno** [lucko/LuckPerms#2524]
Hi I've got an error about my database. Earlier I didn't have any of these, it started today.

Error:
`[14:55:59 WARN]: [me.lucko.luckperms.lib.hikari.pool.ProxyConnection] luckperms-hikari - Connection me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection@52b7c280 marked as broken because of SQLSTATE(08S01), ErrorCode(0)
me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_252]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_252]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_252]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_252]
at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[?:?]
at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990) ~[?:?]
at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3517) ~[?:?]
at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3417) ~[?:?]
at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3860) ~[?:?]
at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[?:?]
at me.lucko.luckperms.lib.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1281) ~[?:?]
at me.lucko.luckperms.lib.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:787) ~[?:?]
at me.lucko.luckperms.lib.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1251) ~[?:?]
at me.lucko.luckperms.lib.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[?:?]
at me.lucko.luckperms.lib.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[?:?]
at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.runHousekeeping(AbstractSqlMessenger.java:117) ~[?:?]
at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$ErrorReportingRunnable.run(AbstractJavaScheduler.java:124) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.net.SocketTimeoutException: Read timed out
at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_252]
at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_252]
at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_252]
at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_252]
at me.lucko.luckperms.lib.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:101) ~[?:?]
at me.lucko.luckperms.lib.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:144) ~[?:?]
at me.lucko.luckperms.lib.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174) ~[?:?]
at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2966) ~[?:?]
at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3427) ~[?:?]
... 13 more
>.... [14:55:59 WARN]: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
>.... [14:55:59 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>.... [14:55:59 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>.... [14:55:59 WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>.... [14:55:59 WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>.... [14:55:59 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
>.... [14:55:59 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
>.... [14:55:59 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3517)
>.... [14:55:59 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3417)
>.... [14:55:59 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3860)
>.... [14:55:59 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
>.... [14:55:59 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1281)
>.... [14:55:59 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:787)
>.... [14:55:59 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1251)
>.... [14:55:59 WARN]: at me.lucko.luckperms.lib.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
>.... [14:55:59 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
>.... [14:55:59 WARN]: at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.runHousekeeping(AbstractSqlMessenger.java:117)
>.... [14:55:59 WARN]: at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$ErrorReportingRunnable.run(AbstractJavaScheduler.java:124)
>.... [14:55:59 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>.... [14:55:59 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>.... [14:55:59 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [14:55:59 WARN]: Caused by: java.net.SocketTimeoutException: Read timed out
>.... [14:55:59 WARN]: at java.net.SocketInputStream.socketRead0(Native Method)
>.... [14:55:59 WARN]: at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
>.... [14:55:59 WARN]: at java.net.SocketInputStream.read(SocketInputStream.java:171)
>.... [14:55:59 WARN]: at java.net.SocketInputStream.read(SocketInputStream.java:141)
>.... [14:55:59 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:101)
>.... [14:55:59 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:144)
>.... [14:55:59 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174)
>.... [14:55:59 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2966)
>.... [14:55:59 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3427)
>.... [14:55:59 WARN]: ... 13 more`

Thanks for your help :)

**Comment by Laarryy** [comment]
Can you please pastebin an entire log from server startup to that error? If it occurs during server startup, even better just pastebin the startup log, in full, pls.

**Comment by Bobbbe** [comment]
https://pastebin.com/NGzf2B45

**Comment by Azuuno** [comment]
Who are you @Bobbbe ?

Here is my startup log @Laarryy  : https://pastebin.com/QrWAtSVc

**Comment by lucko** [comment]
Should be fixed by 6f90e545fc42afc9d9a2c06ef446b198c62a2ef6
