### ISSUE TITLE
Plugin attempted to register task while disabled

### ISSUE THREAD

**Issue by dudematthew** [lucko/LuckPerms#2528]
```
[18:06:54] [ForkJoinPool-2-worker-26/WARN]: [LuckPerms] Unable to pass event NodeClearEvent to handler us.donut.skuniversal.luckperms.LuckPermsListener$$Lambda$4743/950544473
[18:06:54] [ForkJoinPool-2-worker-26/WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[18:06:54] [ForkJoinPool-2-worker-26/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:527)
[18:06:54] [ForkJoinPool-2-worker-26/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:205)
[18:06:54] [ForkJoinPool-2-worker-26/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:196)
[18:06:54] [ForkJoinPool-2-worker-26/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:160)
[18:06:54] [ForkJoinPool-2-worker-26/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:129)
[18:06:54] [ForkJoinPool-2-worker-26/WARN]: 	at us.donut.skuniversal.luckperms.LuckPermsListener.onGroupChange(LuckPermsListener.java:57)
[18:06:54] [ForkJoinPool-2-worker-26/WARN]: 	at me.lucko.luckperms.common.event.LuckPermsEventSubscription.invoke(LuckPermsEventSubscription.java:95)
[18:06:54] [ForkJoinPool-2-worker-26/WARN]: 	at me.lucko.luckperms.common.event.LuckPermsEventSubscription.invoke(LuckPermsEventSubscription.java:43)
[18:06:54] [ForkJoinPool-2-worker-26/WARN]: 	at me.lucko.luckperms.lib.eventbus.SimpleEventBus.post(SimpleEventBus.java:107)
[18:06:54] [ForkJoinPool-2-worker-26/WARN]: 	at me.lucko.luckperms.common.event.AbstractEventBus.post(AbstractEventBus.java:84)
[18:06:54] [ForkJoinPool-2-worker-26/WARN]: 	at me.lucko.luckperms.common.event.EventDispatcher.post(EventDispatcher.java:115)
[18:06:54] [ForkJoinPool-2-worker-26/WARN]: 	at me.lucko.luckperms.common.event.EventDispatcher.lambda$post$0(EventDispatcher.java:128)
[18:06:54] [ForkJoinPool-2-worker-26/WARN]: 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[18:06:54] [ForkJoinPool-2-worker-26/WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[18:06:54] [ForkJoinPool-2-worker-26/WARN]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[18:06:54] [ForkJoinPool-2-worker-26/WARN]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[18:06:54] [ForkJoinPool-2-worker-26/WARN]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Hi!
How do I fix this issue? :)

**Comment by lucko** [comment]
`us.donut.skuniversal.luckperms.LuckPermsListener.onGroupChange` - seems to have registered a listener without closing it when the corresponding plugin disables.
