### ISSUE TITLE
LuckPerms Issue causing crash

### ISSUE THREAD

**Issue by jpoblocki77** [lucko/LuckPerms#2529]
java.util.WeakHashMap cannot be cast to me.lucko.luckperms.bukkit.inject.server.LuckPermsSubscriptionMap$LPSubscriptionValueMap loading Jobs v4.7.4 (Is it up to date?)
 java.lang.ClassCastException: java.util.WeakHashMap cannot be cast to me.lucko.luckperms.bukkit.inject.server.LuckPermsSubscriptionMap$LPSubscriptionValueMap
        at me.lucko.luckperms.bukkit.inject.server.LuckPermsSubscriptionMap.get(LuckPermsSubscriptionMap.java:101) ~[?:?]
        at me.lucko.luckperms.bukkit.inject.server.LuckPermsSubscriptionMap.get(LuckPermsSubscriptionMap.java:71) ~[?:?]
        at org.bukkit.plugin.SimplePluginManager.unsubscribeFromPermission(SimplePluginManager.java:650) ~[SimplePluginManager.class:1.12.2-3a04c46]
        at org.bukkit.permissions.PermissibleBase.clearPermissions(PermissibleBase.java:175) ~[PermissibleBase.class:1.12.2-3a04c46]
        at org.bukkit.permissions.PermissibleBase.recalculatePermissions(PermissibleBase.java:155) ~[PermissibleBase.class:1.12.2-3a04c46]
        at org.bukkit.craftbukkit.v1_12_R1.command.ServerCommandSender.recalculatePermissions(ServerCommandSender.java:77) ~[ServerCommandSender.class:1.12.2-3a04c46]
        at org.bukkit.plugin.SimplePluginManager.dirtyPermissibles(SimplePluginManager.java:637) ~[SimplePluginManager.class:1.12.2-3a04c46]
        at org.bukkit.plugin.SimplePluginManager.dirtyPermissibles(SimplePluginManager.java:629) ~[SimplePluginManager.class:1.12.2-3a04c46]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:472) [CraftServer.class:1.12.2-3a04c46]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:415) [CraftServer.class:1.12.2-3a04c46]
        at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:384) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:316) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

Using Mohoist 1.12.2 latest build with Luckperms 1.12  version.

**Comment by jpoblocki77** [comment]
[18:38:12 ERROR]: Encountered an unexpected exception
[18:38:12 WARN]: Failed to identify me.lucko.luckperms.bukkit.inject.server.LuckPermsSubscriptionMap (untransformed name: me.lucko.luckperms.bukkit.inject.server.LuckPermsSubscriptionMap)
[18:38:12 ERROR]: This crash report has been saved to: D:\the-1122-pack_1.2.0\.\crash-reports\crash-2020-08-03_18.38.12-server.txt

**Comment by jpoblocki77** [comment]
[crash-2020-08-03_18.38.12-server.txt](https://github.com/lucko/LuckPerms/files/5019568/crash-2020-08-03_18.38.12-server.txt)

**Comment by lucko** [comment]
Update to the latest version, this was fixed already: https://luckperms.net/download
