### ISSUE TITLE
Bungeecord having problem with Luckeperms.

### ISSUE THREAD

**Issue by M0n3yng** [lucko/LuckPerms#2554]
I have been trying the set up Luckperms globally on my Bungeecord server but whenever I start Bungeecord I get a long string of [SEVERE] errors. How do I fix this?

Here is the log.

```
21:46:15 [INFO] Using standard Java JCE cipher.
21:46:15 [INFO] Using standard Java compressor.
21:46:15 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:15b5141:1529
21:46:15 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
21:46:15 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
21:46:15 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
21:46:15 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
21:46:15 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
21:46:15 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
21:46:15 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.16-R0.4-SNAPSHOT:15b5141:1529 by SpigotMC
21:46:15 [INFO] Loaded plugin LuckPerms version 5.1.87 by Luck
21:46:15 [INFO] Loaded plugin cmd_find version git:cmd_find:1.16-R0.4-SNAPSHOT:15b5141:1529 by SpigotMC
21:46:15 [INFO] Loaded plugin AdvancedBan version 2.2.1 by Leoko
21:46:15 [INFO] Loaded plugin BungeeHub version 0.3 by iFedeFC
21:46:15 [INFO] Loaded plugin cmd_server version git:cmd_server:1.16-R0.4-SNAPSHOT:15b5141:1529 by SpigotMC
21:46:15 [INFO] Loaded plugin LobbyLeave version 1.0 by BukkitTNT
21:46:15 [INFO] Loaded plugin UltraStaffChat version 4.0.1 by JoshuaSing
21:46:15 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.16-R0.4-SNAPSHOT:15b5141:1529 by SpigotMC
21:46:15 [INFO] Loaded plugin cmd_send version git:cmd_send:1.16-R0.4-SNAPSHOT:15b5141:1529 by SpigotMC
21:46:15 [INFO] Loaded plugin cmd_list version git:cmd_list:1.16-R0.4-SNAPSHOT:15b5141:1529 by SpigotMC
21:46:15 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.16-R0.4-SNAPSHOT:15b5141:1529 by SpigotMC
21:46:15 [INFO] __
21:46:15 [INFO] | |) LuckPerms v5.1.87
21:46:15 [INFO] |_ | Running on BungeeCord - BungeeCord
21:46:15 [INFO]
21:46:15 [INFO] [LuckPerms] Loading configuration...
21:46:15 [INFO] [LuckPerms] Loading storage provider... [MYSQL]
21:46:16 [SEVERE] [main] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Starting...
21:46:16 [SEVERE] [main] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Start completed.
21:46:21 [SEVERE] [LuckPerms] Failed to init storage implementation
21:46:21 [SEVERE] java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
21:46:21 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
21:46:21 [INFO] [LuckPerms] Loading messaging service... [SQL]
21:46:21 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
21:46:21 [SEVERE] at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:151)
21:46:21 [SEVERE] at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:155)
21:46:21 [SEVERE] at me.lucko.luckperms.common.storage.Storage.init(Storage.java:115)
21:46:21 [SEVERE] at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88)
21:46:21 [SEVERE] at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:151)
21:46:21 [SEVERE] at me.lucko.luckperms.bungee.LPBungeeBootstrap.onEnable(LPBungeeBootstrap.java:153)
21:46:21 [SEVERE] at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
21:46:21 [SEVERE] at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
21:46:21 [SEVERE] at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
21:46:21 [SEVERE] at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
21:46:21 [SEVERE] Caused by: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'minecraft'
21:46:21 [SEVERE] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
21:46:21 [SEVERE] at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
21:46:21 [SEVERE] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
21:46:21 [SEVERE] at java.lang.reflect.Constructor.newInstance(Unknown Source)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.Util.getInstance(Util.java:408)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:864)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1707)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1217)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.(ConnectionImpl.java:768)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection.(JDBC4Connection.java:47)
21:46:21 [SEVERE] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
21:46:21 [SEVERE] at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
21:46:21 [SEVERE] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
21:46:21 [SEVERE] at java.lang.reflect.Constructor.newInstance(Unknown Source)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:725)
21:46:21 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:711)
21:46:21 [SEVERE] at java.util.concurrent.FutureTask.run(Unknown Source)
21:46:21 [SEVERE] at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
21:46:21 [SEVERE] at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
21:46:21 [SEVERE] at java.lang.Thread.run(Unknown Source)
21:46:26 [SEVERE] java.lang.RuntimeException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5001ms.
21:46:26 [WARNING] [LuckPerms] Messaging service 'sql' not recognised.
21:46:26 [SEVERE] at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:57)
21:46:26 [SEVERE] at me.lucko.luckperms.common.messaging.MessagingFactory$SqlMessengerProvider.obtain(MessagingFactory.java:154)
21:46:26 [SEVERE] at me.lucko.luckperms.common.messaging.LuckPermsMessagingService.(LuckPermsMessagingService.java:73)
21:46:26 [SEVERE] at me.lucko.luckperms.common.messaging.MessagingFactory.getServiceFor(MessagingFactory.java:106)
21:46:26 [SEVERE] at me.lucko.luckperms.bungee.messaging.BungeeMessagingFactory.getServiceFor(BungeeMessagingFactory.java:64)
21:46:26 [SEVERE] at me.lucko.luckperms.common.messaging.MessagingFactory.getInstance(MessagingFactory.java:84)
21:46:26 [SEVERE] at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:152)
21:46:26 [SEVERE] at me.lucko.luckperms.bungee.LPBungeeBootstrap.onEnable(LPBungeeBootstrap.java:153)
21:46:26 [SEVERE] at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
21:46:26 [SEVERE] at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
21:46:26 [SEVERE] at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
21:46:26 [SEVERE] at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
21:46:26 [SEVERE] Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5001ms.
21:46:26 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
21:46:26 [SEVERE] at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:151)
21:46:26 [SEVERE] at me.lucko.luckperms.common.messaging.sql.SqlMessenger.getConnection(SqlMessenger.java:85)
21:46:26 [SEVERE] at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.init(AbstractSqlMessenger.java:56)
21:46:26 [SEVERE] at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:55)
21:46:26 [SEVERE] ... 11 more
21:46:26 [SEVERE] Caused by: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'minecraft'
21:46:26 [SEVERE] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
21:46:26 [SEVERE] at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
21:46:26 [SEVERE] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
21:46:26 [SEVERE] at java.lang.reflect.Constructor.newInstance(Unknown Source)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.Util.getInstance(Util.java:408)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:864)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1707)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1217)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.(ConnectionImpl.java:768)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection.(JDBC4Connection.java:47)
21:46:26 [SEVERE] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
21:46:26 [SEVERE] at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
21:46:26 [SEVERE] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
21:46:26 [SEVERE] at java.lang.reflect.Constructor.newInstance(Unknown Source)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:725)
21:46:26 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:711)
21:46:26 [SEVERE] at java.util.concurrent.FutureTask.run(Unknown Source)
21:46:26 [SEVERE] at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
21:46:26 [SEVERE] at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
21:46:26 [SEVERE] at java.lang.Thread.run(Unknown Source)
21:47:49 [INFO] [LuckPerms] Loading internal permission managers...
21:47:49 [INFO] [LuckPerms] Performing initial data load...
21:47:54 [SEVERE] java.util.concurrent.CompletionException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
21:47:54 [INFO] [LuckPerms] Successfully enabled. (took 99047ms)
21:47:54 [SEVERE] at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:104)
21:47:54 [SEVERE] at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
21:47:54 [SEVERE] at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
21:47:54 [SEVERE] at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
21:47:54 [SEVERE] at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
21:47:54 [SEVERE] at java.lang.Thread.run(Unknown Source)
21:47:54 [SEVERE] Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
21:47:54 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
21:47:54 [SEVERE] at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:151)
21:47:54 [SEVERE] at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:439)
21:47:54 [SEVERE] at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$10(Storage.java:195)
21:47:54 [SEVERE] at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:99)
21:47:54 [SEVERE] ... 5 more
21:47:54 [SEVERE] Caused by: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'minecraft'
21:47:54 [SEVERE] at sun.reflect.GeneratedConstructorAccessor16.newInstance(Unknown Source)
21:47:54 [SEVERE] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
21:47:54 [SEVERE] at java.lang.reflect.Constructor.newInstance(Unknown Source)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.Util.getInstance(Util.java:408)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:864)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1707)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1217)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.(ConnectionImpl.java:768)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection.(JDBC4Connection.java:47)
21:47:54 [SEVERE] at sun.reflect.GeneratedConstructorAccessor12.newInstance(Unknown Source)
21:47:54 [SEVERE] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
21:47:54 [SEVERE] at java.lang.reflect.Constructor.newInstance(Unknown Source)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:725)
21:47:54 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:711)
21:47:54 [SEVERE] at java.util.concurrent.FutureTask.run(Unknown Source)
21:47:54 [SEVERE] ... 3 more
21:47:54 [INFO] Enabled plugin LuckPerms version 5.1.87 by Luck
21:47:54 [INFO] Enabled plugin cmd_find version git:cmd_find:1.16-R0.4-SNAPSHOT:15b5141:1529 by SpigotMC
21:47:54 [SEVERE] Aug 11, 2020 9:47:54 PM me.leoko.advancedban.shaded.com.zaxxer.hikari.HikariDataSource
INFO: HikariPool-1 - Starting...

21:47:55 [INFO]

[]=====[Enabling AdvancedBan]=====[]
| Information:
| Name: AdvancedBan
| Developer: Leoko
| Version: 2.2.1
| Storage: HSQLDB (local)
| Support:
| Github: https://github.com/DevLeoko/AdvancedBan/issues
| Discord: https://discord.gg/ycDG6rS
| Twitter: @LeokoGar
| Update:
| You have the newest version
[]================================[]

21:47:55 [INFO] Enabled plugin AdvancedBan version 2.2.1 by Leoko
21:47:55 [INFO] [BungeeHub] ----------------------------
21:47:55 [INFO] [BungeeHub] BungeeCord Hub
21:47:55 [INFO] [BungeeHub]
21:47:55 [INFO] [BungeeHub] You are using the latest version
21:47:55 [INFO] [BungeeHub]
21:47:55 [INFO] [BungeeHub] ----------------------------
21:47:55 [INFO] Enabled plugin BungeeHub version 0.3 by iFedeFC
21:47:55 [INFO] Enabled plugin cmd_server version git:cmd_server:1.16-R0.4-SNAPSHOT:15b5141:1529 by SpigotMC
21:47:55 [INFO] LobbyLeave by BukkitTNT
21:47:55 [INFO] Enabled plugin LobbyLeave version 1.0 by BukkitTNT
21:47:55 [INFO] [UltraStaffChat] Starting...
21:47:55 [INFO]
21:47:55 [INFO] __ ___________
21:47:55 [INFO] / / / / / / UltraStaffChat Bungeecord
21:47:55 [INFO] / // /\ / / Running Version 4.0.1
21:47:55 [INFO] _//_/
21:47:55 [INFO]
21:47:55 [INFO] [UltraStaffChat] Started! Took 12ms.
21:47:55 [INFO] Enabled plugin UltraStaffChat version 4.0.1 by JoshuaSing
21:47:55 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.16-R0.4-SNAPSHOT:15b5141:1529 by SpigotMC
21:47:55 [INFO] Enabled plugin cmd_send version git:cmd_send:1.16-R0.4-SNAPSHOT:15b5141:1529 by SpigotMC
21:47:55 [INFO] Enabled plugin cmd_list version git:cmd_list:1.16-R0.4-SNAPSHOT:15b5141:1529 by SpigotMC
21:47:55 [INFO] Listening on /0.0.0.0:25565
```

**Comment by benwoo1110** [comment]
`Caused by: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'minecraft'`

it does look like your database information is wrong in luckperms config.yml

This page have a good checklist of common sql database errors: https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#common-errors
