### ISSUE TITLE
Server crash with DiscordSRV enabled on Mohist servers

### ISSUE THREAD

**Issue by Scarsz** [lucko/LuckPerms#2562]
Multiple users have this issue, all running Mohist. The issue only happens when DiscordSRV is enabled, but I'm confident that this is an issue somewhere between LuckPerms and Mohist.

```java
Description: Exception in server tick loop

java.lang.ClassCastException: java.util.WeakHashMap cannot be cast to me.lucko.luckperms.bukkit.inject.server.LuckPermsSubscriptionMap$LPSubscriptionValueMap
	at me.lucko.luckperms.bukkit.inject.server.LuckPermsSubscriptionMap.get(LuckPermsSubscriptionMap.java:101)
	at me.lucko.luckperms.bukkit.inject.server.LuckPermsSubscriptionMap.get(LuckPermsSubscriptionMap.java:71)
	at org.bukkit.plugin.SimplePluginManager.unsubscribeFromPermission(SimplePluginManager.java:651)
	at org.bukkit.permissions.PermissibleBase.clearPermissions(PermissibleBase.java:175)
	at org.bukkit.permissions.PermissibleBase.recalculatePermissions(PermissibleBase.java:155)
	at org.bukkit.plugin.SimplePluginManager.dirtyPermissibles(SimplePluginManager.java:638)
	at org.bukkit.plugin.SimplePluginManager.calculatePermissionDefault(SimplePluginManager.java:617)
	at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:589)
	at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:578)
	at org.bukkit.util.permissions.DefaultPermissions.registerPermission(DefaultPermissions.java:23)
	at org.bukkit.util.permissions.DefaultPermissions.registerPermission(DefaultPermissions.java:16)
	at org.bukkit.util.permissions.DefaultPermissions.registerPermission(DefaultPermissions.java:43)
	at org.bukkit.util.permissions.DefaultPermissions.registerCorePermissions(DefaultPermissions.java:76)
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:427)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:384)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:316)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by lucko** [comment]
Thanks for the report, but this has already been fixed :)

They just need to update to the latest version

**Comment by Scarsz** [comment]
Gotcha, thanks for the info.
