### ISSUE TITLE
Minecraft Server Icon Error

### ISSUE THREAD

**Issue by JensGamerYT** [lucko/LuckPerms#2573]
hy...
when i upload an image 64x64 with the name Server-Icon i get an error:

Couldn't load server icon
java.lang.IllegalArgumentException: Must be 64 pixels wide
at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.15.2.jar:git-Paper-379]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadServerIcon0(CraftServer.java:1877) ~[patched_1.15.2.jar:git-Paper-379]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadServerIcon0(CraftServer.java:1865) ~[patched_1.15.2.jar:git-Paper-379]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadIcon(CraftServer.java:937) ~[patched_1.15.2.jar:git-Paper-379]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.<init>(CraftServer.java:323) ~[patched_1.15.2.jar:git-Paper-379]
at net.minecraft.server.v1_15_R1.PlayerList.<init>(PlayerList.java:80) ~[patched_1.15.2.jar:git-Paper-379]
at net.minecraft.server.v1_15_R1.DedicatedPlayerList.<init>(SourceFile:14) ~[patched_1.15.2.jar:git-Paper-379]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:183) ~[patched_1.15.2.jar:git-Paper-379]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-379]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

can anyone say why its doing that?

**Comment by Laarryy** [comment]
This is not related even in the slightest to luckperms

**Comment by JensGamerYT** [comment]
What is the problem??

**Comment by BrainStone** [comment]
This is not the right place for this issue. 

I mean you’re also not asking your dentist for help with a broken leg, are you?

**Comment by JensGamerYT** [comment]
But were i must to ask it

there is no one that will help me

**Comment by BrainStone** [comment]
Well if you keep asking in the wrong places this is to be expected. 

I’d recommend asking on the SpigotMC forum.

**Comment by JensGamerYT** [comment]
how i can make a forum on spigot?

**Comment by Tobi406** [comment]
Ask that the people from Spigot, not us.

**Comment by BrainStone** [comment]
You’re not supposed to make a forum on Spigot. You’re supposed to ask on the SpigotMC forum. 

https://lmgtfy.com/?q=spigotmc+forum
