### ISSUE TITLE
Bungeeecord Issue on Cancelling LoginEvent (In my plugin)

### ISSUE THREAD

**Issue by Splitrox** [lucko/LuckPerms#2581]
Error:
[16:35:12 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@332729ad, id=157, owner=me.lucko.luckperms.bungee.LPBungeeBootstrap@10f7f7de, task=me.lucko.luckperms.bungee.listeners.BungeeConnectionListener$$Lambda$464/1656008606@734af2c5, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException: null
        at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:58) ~[bungeecord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at net.md_5.bungee.connection.InitialHandler.disconnect(InitialHandler.java:735) ~[bungeecord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at net.md_5.bungee.connection.InitialHandler$6.done(InitialHandler.java:659) ~[bungeecord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at net.md_5.bungee.connection.InitialHandler$6.done(InitialHandler.java:653) ~[bungeecord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at bungeepluginmanager.AsyncEventsListener$WrappedCallback.done(AsyncEventsListener.java:67) ~[?:?]
        at bungeepluginmanager.AsyncEventsListener$WrappedCallback.done(AsyncEventsListener.java:1) ~[?:?]
        at net.md_5.bungee.api.event.AsyncEvent.completeIntent(AsyncEvent.java:86) ~[bungeecord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at me.lucko.luckperms.bungee.listeners.BungeeConnectionListener.lambda$onPlayerLogin$0(BungeeConnectionListener.java:107) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[bungeecord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by lucko** [comment]
Doesn't seem to be being caused by LP, sorry not much I can do to help.

**Comment by Splitrox** [comment]
"task=me.lucko.luckperms.bungee.listeners.BungeeConnectionListener"
