### ISSUE TITLE
[bug]crash on 1.16.2

### ISSUE THREAD

**Issue by DEADLYDEVIL-SPIGOT** [lucko/LuckPerms#2587]
```
[03:20:47] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[03:20:48] [Server thread/ERROR]: Error occurred while enabling LuckPerms v5.1.93 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/guava/graph/MutableGraph
	at me.lucko.luckperms.bukkit.util.PluginManagerUtil.injectDependency(PluginManagerUtil.java:64) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitPlugin.setupPlatformHooks(LPBukkitPlugin.java:223) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:175) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:162) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:209) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-148]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.guava.graph.MutableGraph
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_265]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.2.jar:git-Paper-148]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_265]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_265]
	... 13 more
[03:20:48] [Server thread/INFO]: [LuckPerms] Disabling LuckPerms v5.1.93
[03:20:48] [Server thread/INFO]: [LuckPerms] Starting shutdown process...
[03:20:48] [Server thread/ERROR]: Error occurred while disabling LuckPerms v5.1.93 (Is it up to date?)
java.lang.NullPointerException: null
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.disable(AbstractLuckPermsPlugin.java:223) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onDisable(LPBukkitBootstrap.java:178) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:209) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-148]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

**Comment by Fefo6644** [comment]
Try deleting the `/libs/` directory inside the `/LuckPerms/` directory and give it a restart.

**Comment by DEADLYDEVIL-SPIGOT** [comment]
> 
> 
> Try deleting the `/libs/` directory inside the `/LuckPerms/` directory and give it a restart.

i tried but it didn't work

**Comment by Fefo6644** [comment]
Can you paste the entire startup log in [here](https://bytebin.lucko.me/) please?
You may need to download the libraries manually but just making sure it's not something else.

**Comment by DEADLYDEVIL-SPIGOT** [comment]
> 
> 
> Can you paste the entire startup log in [here](https://bytebin.lucko.me/) and send the link please?
> You may need to download the libraries manually but just making sure it's not something else.

ok wait

**Comment by DEADLYDEVIL-SPIGOT** [comment]
> 
> 
> Can you paste the entire startup log in [here](https://bytebin.lucko.me/) and send the link please?
> You may need to download the libraries manually but just making sure it's not something else.

`[16:56:51] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[16:56:51] [main/INFO]: Reloading ResourceManager: Default, bukkit
[16:56:52] [Server-Worker-5/INFO]: Loaded 7 recipes
[16:56:53] [Server thread/INFO]: Starting minecraft server version 1.16.2
[16:56:53] [Server thread/INFO]: Loading properties
[16:56:53] [Server thread/INFO]: This server is running Paper version git-Paper-148 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
[16:56:53] [Server thread/INFO]: Debug logging is disabled
[16:56:53] [Server thread/INFO]: Using 4 threads for Netty based IO
[16:56:53] [Server thread/INFO]: Server Ping Player Sample Count: 12
[16:56:53] [Server thread/INFO]: Default game type: SURVIVAL
[16:56:53] [Server thread/INFO]: Generating keypair
[16:56:53] [Server thread/INFO]: Starting Minecraft server on *:25565
[16:56:53] [Server thread/INFO]: Using default channel type
[16:56:53] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.1.93
[16:57:03] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[16:57:03] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.1.93
[16:57:03] [Server thread/INFO]:         __    
[16:57:03] [Server thread/INFO]:   |    |__)   LuckPerms v5.1.93
[16:57:03] [Server thread/INFO]:   |___ |      Running on Bukkit - Paper
[16:57:03] [Server thread/INFO]: 
[16:57:03] [Server thread/INFO]: [LuckPerms] Loading configuration...
[16:57:06] [Server thread/INFO]: [LuckPerms] Loading storage provider... [H2]
[16:57:07] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[16:57:07] [Server thread/ERROR]: Error occurred while enabling LuckPerms v5.1.93 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/guava/graph/MutableGraph
	at me.lucko.luckperms.bukkit.util.PluginManagerUtil.injectDependency(PluginManagerUtil.java:64) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitPlugin.setupPlatformHooks(LPBukkitPlugin.java:223) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:175) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:162) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:209) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-148]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.guava.graph.MutableGraph
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_261]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.2.jar:git-Paper-148]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
	... 13 more
[16:57:07] [Server thread/INFO]: [LuckPerms] Disabling LuckPerms v5.1.93
[16:57:07] [Server thread/INFO]: [LuckPerms] Starting shutdown process...
[16:57:07] [Server thread/ERROR]: Error occurred while disabling LuckPerms v5.1.93 (Is it up to date?)
java.lang.NullPointerException: null
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.disable(AbstractLuckPermsPlugin.java:223) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onDisable(LPBukkitBootstrap.java:178) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:209) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-148]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[16:57:07] [Server thread/INFO]: Preparing level "world"
[16:57:07] [Server thread/INFO]: -------- World Settings For [world] --------
[16:57:07] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[16:57:07] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[16:57:07] [Server thread/INFO]: Item Despawn Rate: 6000
[16:57:07] [Server thread/INFO]: Item Merge Radius: 2.5
[16:57:07] [Server thread/INFO]: View Distance: 10
[16:57:07] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[16:57:07] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[16:57:07] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[16:57:07] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[16:57:07] [Server thread/INFO]: Max TNT Explosions: 100
[16:57:07] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[16:57:07] [Server thread/INFO]: Experience Merge Radius: 3.0
[16:57:07] [Server thread/INFO]: Cactus Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Cane Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Melon Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Sapling Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Carrot Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Potato Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Wheat Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Vine Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Kelp Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[16:57:07] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[16:57:07] [Server thread/INFO]: Mob Spawn Range: 8
[16:57:07] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[16:57:07] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[16:57:07] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[16:57:07] [Server thread/INFO]: Item Despawn Rate: 6000
[16:57:07] [Server thread/INFO]: Item Merge Radius: 2.5
[16:57:07] [Server thread/INFO]: View Distance: 10
[16:57:07] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[16:57:07] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[16:57:07] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[16:57:07] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[16:57:07] [Server thread/INFO]: Max TNT Explosions: 100
[16:57:07] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[16:57:07] [Server thread/INFO]: Experience Merge Radius: 3.0
[16:57:07] [Server thread/INFO]: Cactus Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Cane Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Melon Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Sapling Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Carrot Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Potato Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Wheat Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Vine Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Kelp Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[16:57:07] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[16:57:07] [Server thread/INFO]: Mob Spawn Range: 8
[16:57:07] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[16:57:07] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[16:57:07] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[16:57:07] [Server thread/INFO]: Item Despawn Rate: 6000
[16:57:07] [Server thread/INFO]: Item Merge Radius: 2.5
[16:57:07] [Server thread/INFO]: View Distance: 10
[16:57:07] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[16:57:07] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[16:57:07] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[16:57:07] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[16:57:07] [Server thread/INFO]: Max TNT Explosions: 100
[16:57:07] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[16:57:07] [Server thread/INFO]: Experience Merge Radius: 3.0
[16:57:07] [Server thread/INFO]: Cactus Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Cane Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Melon Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Sapling Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Carrot Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Potato Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Wheat Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Vine Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Kelp Growth Modifier: 100%
[16:57:07] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[16:57:07] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[16:57:07] [Server thread/INFO]: Mob Spawn Range: 8
[16:57:07] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[16:57:07] [Server thread/INFO]: Loaded 0 spawn chunks for world world
[16:57:07] [Server thread/INFO]: Preparing spawn area: 0%
[16:57:07] [Server thread/INFO]: Time elapsed: 378 ms
[16:57:07] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[16:57:07] [Server thread/INFO]: Loaded 0 spawn chunks for world world_nether
[16:57:07] [Server thread/INFO]: Preparing spawn area: 0%
[16:57:08] [Server thread/INFO]: Time elapsed: 127 ms
[16:57:08] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[16:57:08] [Server thread/INFO]: Loaded 0 spawn chunks for world world_the_end
[16:57:08] [Server thread/INFO]: Time elapsed: 98 ms
[16:57:08] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(Unknown Source) ~[?:1.8.0_261]
	at java.util.zip.ZipFile.getEntry(Unknown Source) ~[?:1.8.0_261]
	at java.util.jar.JarFile.getEntry(Unknown Source) ~[?:1.8.0_261]
	at java.util.jar.JarFile.getJarEntry(Unknown Source) ~[?:1.8.0_261]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:133) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.2.jar:git-Paper-148]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
	at me.lucko.luckperms.bukkit.inject.server.LuckPermsSubscriptionMap.get(LuckPermsSubscriptionMap.java:103) ~[?:?]
	at me.lucko.luckperms.bukkit.inject.server.LuckPermsSubscriptionMap.get(LuckPermsSubscriptionMap.java:70) ~[?:?]
	at org.bukkit.plugin.SimplePluginManager.getPermissionSubscriptions(SimplePluginManager.java:817) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.permissions.Permission.getPermissibles(Permission.java:159) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.permissions.Permission.recalculatePermissibles(Permission.java:169) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.permissions.Permission.<init>(Permission.java:68) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.permissions.Permission.<init>(Permission.java:32) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.util.permissions.DefaultPermissions.registerPermission(DefaultPermissions.java:49) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.util.permissions.DefaultPermissions.registerCorePermissions(DefaultPermissions.java:87) ~[patched_1.16.2.jar:git-Paper-148]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:424) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-148]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-148]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[16:57:08] [Server thread/ERROR]: This crash report has been saved to: C:\Users\My-PC\Desktop\mcserver\1.16\.\crash-reports\crash-2020-08-27_16.57.08-server.txt
[16:57:08] [Server thread/INFO]: Stopping server
[16:57:08] [Server thread/INFO]: Saving players
[16:57:08] [Server thread/INFO]: Saving worlds
[16:57:08] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[16:57:12] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[16:57:12] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[16:57:14] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[16:57:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[16:57:14] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[16:57:14] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[16:57:14] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[16:57:14] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[16:57:14] [Server thread/INFO]: Flushing Chunk IO
[16:57:14] [Server thread/INFO]: Closing Thread Pool
[16:57:14] [Server thread/INFO]: Closing Server
`

**Comment by DEADLYDEVIL-SPIGOT** [comment]
> 
> 
> Can you paste the entire startup log in [here](https://bytebin.lucko.me/) and send the link please?
> You may need to download the libraries manually but just making sure it's not something else.

https://ctxt.io/2/AAAgaDxXFw

**Comment by Fefo6644** [comment]
Yeah, by the look of things, you'll have to download the libraries manually. Stop the server, remove everything inside the `/LuckPerms/libs/` directory and uploading the lib jars directly in there. You can get them by searching them by name in here (https://nexus.lucko.me/#browse/search) and here (https://search.maven.org/).
Here is the list: https://github.com/lucko/LuckPerms/wiki/Credits#open-source
Once you upload all of them, start the server and report back.

**Comment by DEADLYDEVIL-SPIGOT** [comment]
> 
> 
> Yeah, by the look of things, you'll have to download the libraries manually. Stop the server, remove everything inside the `/LuckPerms/libs/` directory and uploading the lib jars directly in there. You can get them by searching them by name in here (https://nexus.lucko.me/#browse/search) and here (https://search.maven.org/).
> Here is the list: https://github.com/lucko/LuckPerms/wiki/Credits#open-source
> Once you upload all of them, start the server and report back.

oh ok i'll try

**Comment by DEADLYDEVIL-SPIGOT** [comment]
> 
> 
> Yeah, by the look of things, you'll have to download the libraries manually. Stop the server, remove everything inside the `/LuckPerms/libs/` directory and uploading the lib jars directly in there. You can get them by searching them by name in here (https://nexus.lucko.me/#browse/search) and here (https://search.maven.org/).
> Here is the list: https://github.com/lucko/LuckPerms/wiki/Credits#open-source
> Once you upload all of them, start the server and report back.

i downloaded them but luckperms has downloaded those old apis again

**Comment by lucko** [comment]
You seem to be using the `Bukkit-Legacy` build, but this is not necessary, as you are running a modern version.

Try again using the normal bukkit jar download.
https://luckperms.net/download
