### ISSUE TITLE
[bug] crash on 1.16.2 Paper 

### ISSUE THREAD

**Issue by Gaming1111** [lucko/LuckPerms#2589]
Hi! Server crashes by Luckperms.

```
[13:14:22 INFO]: [LuckPerms] Enabling LuckPerms v5.1.93
[13:14:22 INFO]: __
[13:14:22 INFO]: | |__) LuckPerms v5.1.93
[13:14:22 INFO]: |___ | Running on Bukkit - Paper
[13:14:22 INFO]:
[13:14:22 INFO]: [LuckPerms] Loading configuration...
[13:14:23 INFO]: [LuckPerms] Loading storage provider... [MYSQL]
[13:14:23 INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Starting...
[13:14:23 INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Start completed.
[13:14:23 INFO]: [LuckPerms] Loading messaging service... [SQL]
[13:14:24 INFO]: [LuckPerms] Loading internal permission managers...
[13:14:24 ERROR]: Error occurred while enabling LuckPerms v5.1.93 (Is it up to date?)
java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such method: me.lucko.luckperms.common.event.gen.GeneratedEventClass.preGenerate()void/invokeStatic
at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:180) ~[?:?]
at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:162) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-152]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-152]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-152]
at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:209) ~[patched_1.16.2.jar:git-Paper-152]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-152]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-152]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.IllegalAccessError: no such method: me.lucko.luckperms.common.event.gen.GeneratedEventClass.preGenerate()void/invokeStatic
at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:483) ~[?:1.8.0_262]
... 11 more
Caused by: java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/bytebuddy/dynamic/scaffold/subclass/ConstructorStrategy
at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_262]
at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_262]
at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_262]
at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_262]
at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_262]
at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_262]
... 11 more
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.bytebuddy.dynamic.scaffold.subclass.ConstructorStrategy
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_262]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.2.jar:git-Paper-152]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.2.jar:git-Paper-152]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_262]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_262]
at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_262]
at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_262]
at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_262]
at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_262]
at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_262]
at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_262]
... 11 more
[13:14:24 INFO]: [LuckPerms] Disabling LuckPerms v5.1.93
[13:14:24 INFO]: [LuckPerms] Starting shutdown process...
[13:14:24 ERROR]: Error occurred while disabling LuckPerms v5.1.93 (Is it up to date?)
java.lang.NullPointerException: null
at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.disable(AbstractLuckPermsPlugin.java:223) ~[?:?]
at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onDisable(LPBukkitBootstrap.java:178) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.2.jar:git-Paper-152]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.2.jar:git-Paper-152]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.2.jar:git-Paper-152]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.2.jar:git-Paper-152]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-152]
at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:209) ~[patched_1.16.2.jar:git-Paper-152]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-152]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-152]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
```

```
'[13:14:59 ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: zip file closed
at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_262]
at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_262]
at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_262]
at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_262]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:133) ~[patched_1.16.2.jar:git-Paper-152]
at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.2.jar:git-Paper-152]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.2.jar:git-Paper-152]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.2.jar:git-Paper-152]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_262]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_262]
**at me.lucko.luckperms.bukkit.inject.permissible.MonitoredPermissibleBase.hasPermission(MonitoredPermissibleBase.java:109) ~[?:?]**
at org.bukkit.craftbukkit.v1_16_R2.command.ServerCommandSender.hasPermission(ServerCommandSender.java:40) ~[patched_1.16.2.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_16_R2.command.CraftConsoleCommandSender.hasPermission(CraftConsoleCommandSender.java:81) ~[patched_1.16.2.jar:git-Paper-152]
at tech.panoply.leaderheads.libs.co.aikar.acf.BukkitCommandIssuer.hasPermission(BukkitCommandIssuer.java:80) ~[?:?]
at tech.panoply.leaderheads.libs.co.aikar.acf.CommandManager.hasPermission(CommandManager.java:319) ~[?:?]
at tech.panoply.leaderheads.libs.co.aikar.acf.CommandManager.hasPermission(CommandManager.java:307) ~[?:?]
at tech.panoply.leaderheads.libs.co.aikar.acf.RegisteredCommand.hasPermission(RegisteredCommand.java:308) ~[?:?]
at tech.panoply.leaderheads.libs.co.aikar.acf.CommandHelp.lambda$new$0(CommandHelp.java:79) ~[?:?]
at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_262]
at tech.panoply.leaderheads.libs.co.aikar.acf.CommandHelp.<init>(CommandHelp.java:71) ~[?:?]
at tech.panoply.leaderheads.libs.co.aikar.acf.CommandManager.generateCommandHelp(CommandManager.java:197) ~[?:?]
at tech.panoply.leaderheads.libs.co.aikar.acf.ACFBukkitHelpTopic.<init>(ACFBukkitHelpTopic.java:44) ~[?:?]
at tech.panoply.leaderheads.libs.co.aikar.acf.BukkitCommandManager.lambda$new$0(BukkitCommandManager.java:114) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.help.SimpleHelpMap.initializeCommands(SimpleHelpMap.java:135) ~[patched_1.16.2.jar:git-Paper-152]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:427) ~[patched_1.16.2.jar:git-Paper-152]
at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-152]
at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-152]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-152]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-152]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
[13:14:59 ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2020-08-28_13.14.59-server.txt
```

**Comment by lucko** [comment]
Please try deleting the `/plugins/LuckPerms/libs` folder and restarting your server.
