### ISSUE TITLE
Luckperms Placeholder Expiry Time not working correct

### ISSUE THREAD

**Issue by blakedj012** [lucko/LuckPerms#2591]
First i have this problem:

[10:40:18 WARN]: [PlaceholderAPI] Task #71248 for PlaceholderAPI v2.10.9 generated an exception
java.lang.NullPointerException: null
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.createExpansionInstance(LocalExpansionManager.java:343) ~[?:?]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:138) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_231]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_231]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_231]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_231]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_231]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_231]
        at java.util.stream.LongPipeline.reduce(Unknown Source) ~[?:1.8.0_231]
        at java.util.stream.LongPipeline.sum(Unknown Source) ~[?:1.8.0_231]
        at java.util.stream.ReferencePipeline.count(Unknown Source) ~[?:1.8.0_231]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$2(LocalExpansionManager.java:288) ~[?:?]
        at me.clip.placeholderapi.util.Futures.lambda$null$0(Futures.java:46) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.2.jar:git-Paper-159]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.2.jar:git-Paper-159]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.2.jar:git-Paper-159]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:375) ~[patched_1.16.2.jar:git-Paper-159]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.2.jar:git-Paper-159]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Paper-159]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-159]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

Latest Luckperms and Paper 1.16.2

And in lp editor it shows 1 month expiry time what is correct but the placeholder shows only 7 days. I think it has to do with the error ?

**Comment by Fefo6644** [comment]
As for the first error, I would say update PAPI but I'm unsure what causes it as it's also not an LP error.
As for the expiry time placeholder, update PAPI to the latest dev build, it was a bug in it and it's been fixed (see PlaceholderAPI/PlaceholderAPI#423 )
https://ci.extendedclip.com/job/PlaceholderAPI/

**Comment by blakedj012** [comment]
Thanks it worked now!
