### ISSUE TITLE
Luckperms fails to load on Nukkit

### ISSUE THREAD

**Issue by mhiaxo** [lucko/LuckPerms#2597]
### Description

Luckperms fails to load on nukkit 1.0.

```
java.lang.RuntimeException: java.lang.NoSuchMethodError: 'int com.google.gson.JsonObject.size()'
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:440) [nukkit.jar:?]
at cn.nukkit.Server.enablePlugin(Server.java:746) [nukkit.jar:?]
at cn.nukkit.Server.enablePlugins(Server.java:735) [nukkit.jar:?]
at cn.nukkit.Server.<init>(Server.java:496) [nukkit.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit.jar:?]
Caused by: java.lang.NoSuchMethodError: 'int com.google.gson.JsonObject.size()'
at me.lucko.luckperms.common.context.ContextSetJsonSerializer.deserialize(ContextSetJsonSerializer.java:104) ~[?:?]
at me.lucko.luckperms.common.config.ContextsFile.load(ContextsFile.java:71) ~[?:?]
at me.lucko.luckperms.common.config.LuckPermsConfiguration.load(LuckPermsConfiguration.java:47) ~[?:?]
at me.lucko.luckperms.common.config.generic.KeyedConfiguration.init(KeyedConfiguration.java:49) ~[?:?]
at me.lucko.luckperms.common.config.LuckPermsConfiguration.<init>(LuckPermsConfiguration.java:41) ~[?:?]
at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:116) ~[?:?]
at me.lucko.luckperms.nukkit.LPNukkitBootstrap.onEnable(LPNukkitBootstrap.java:125) ~[?:?]
at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[nukkit.jar:?]
at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[nukkit.jar:?]
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[nukkit.jar:?]
```

* LuckPerms version: `v5.1.98`

**Comment by Fefo6644** [comment]
Stick with this version for now :) https://ci.lucko.me/view/LuckPerms/job/LuckPerms/1152/

**Comment by GiaNTizmO** [comment]
I have a not very nice way to fix the error:
Try downloading the latest version of gson and putting it in the folder with mods (preferably) or plugins, or in the library folder.
https://search.maven.org/artifact/com.google.code.gson/gson/2.8.6/jar
Try :)

**Comment by lucko** [comment]
2adaea2dac6c390028e28f69e2cbdbf7ce49878f
