### ISSUE TITLE
LuckPerms-2.11.21 (CI Build) <-- "Thank's captain obvious"

### ISSUE THREAD

**Issue by ChibbyHD** [lucko/LuckPerms#26]
So obviously considering this is a development build there is gonna be issues, but reporting issues is the only way you will know about the issue, right? (Just trying to be helpful, no harm done)

```
[01:54:59 WARN]: me.lucko.luckperms.exceptions.ObjectAlreadyHasException
[01:54:59 WARN]:        at me.lucko.luckperms.core.PermissionHolder.setPermission(PermissionHolder.java:558)
[01:54:59 WARN]:        at me.lucko.luckperms.core.PermissionHolder.setPermission(PermissionHolder.java:588)
[01:54:59 WARN]:        at me.lucko.luckperms.users.UserManager.giveDefaultIfNeeded(UserManager.java:80)
[01:54:59 WARN]:        at me.lucko.luckperms.storage.methods.SQLDatastore.lambda$loadUser$5(SQLDatastore.java:180)
[01:54:59 WARN]:        at me.lucko.luckperms.storage.methods.H2Datastore.runQuery(H2Datastore.java:91)
[01:54:59 WARN]:        at me.lucko.luckperms.storage.methods.SQLDatastore.loadUser(SQLDatastore.java:149)
[01:54:59 WARN]:        at me.lucko.luckperms.storage.methods.H2Datastore.loadUser(H2Datastore.java:31)
[01:54:59 WARN]:        at me.lucko.luckperms.utils.AbstractListener.onAsyncLogin(AbstractListener.java:62)
[01:54:59 WARN]:        at me.lucko.luckperms.BukkitListener.onPlayerPreLogin(BukkitListener.java:59)
[01:54:59 WARN]:        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35)
[01:54:59 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[01:54:59 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[01:54:59 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[01:54:59 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499)
[01:54:59 WARN]:        at net.minecraft.server.v1_10_R1.LoginListener$LoginHandler.fireEvents(LoginListener.java:248)
[01:54:59 WARN]:        at net.minecraft.server.v1_10_R1.LoginListener$3.run(LoginListener.java:209)
[01:54:59 INFO]: UUID of player OlafsFurryBalls is 75fc8638-0150-40e0-aab6-6d036fbcd35c
[01:55:00 INFO]: OlafsFurryBalls[/127.0.0.1:56994] logged in with entity id 154 at ([world]0.5578618169270192, 83.74885831273774, 1.7605709863437045)
>version
[01:56:09 INFO]: This server is running Paper version git-Paper-887 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
[01:56:09 INFO]: Checking version, please wait...
[01:56:10 INFO]: You are running the latest version
>plugins
[01:56:11 INFO]: Plugins (14): AsyncWorldEditInjector, AsyncWorldEdit, Vault, ProtocolLib, LuckPerms, WorldEdit, Essentials, EssentialsChat, EssentialsAntiBuild, EssentialsSpawn, WorldGuard, WorldGuardExtraFlags, ConditionalPerms, WorldGuardFishing
```

**Comment by lucko** [comment]
Thanks for reporting 👍 

Currently going through a few big changes, I'll get around to sorting this before the next release.
