### ISSUE TITLE
I can't enable luckperms

### ISSUE THREAD

**Issue by andrew070124** [lucko/LuckPerms#2622]
spigot 1.16.2
luckperms don't work with this error
Error occurred while enabling LuckPerms v5.1.93 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/lu
ckperms/lib/okhttp3/OkHttpClient$Builder
at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:123) ~[?:?]
at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:162) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:git-Spigot-379750e-43c7ff9]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[server.jar:git-Spigot-379750e-43c7ff9]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:git-Spigot-379750e-43c7ff9]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:492) ~[server.jar:git-Spigot-379750e-43c7ff9]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:406) ~[server.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:187) ~[server.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[server.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-379750e-43c7ff9]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.okhttp3.OkHttpClient$Builder
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_262]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[server.jar:git-Spigot-379750e-43c7ff9]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[server.jar:git-Spigot-379750e-43c7ff9]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_262]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_262]
![캡처](https://user-images.githubusercontent.com/68140979/93042293-a0fb5600-f689-11ea-9d20-164da1a45b14.PNG)
it is my plugin list
help me plz

**Comment by benwoo1110** [comment]
Try delete the `libs` in **LuckPerms* folder.
(please at least get the plugin name correct lol)

**Comment by andrew070124** [comment]
> Try delete the `libs` in *_LuckPerms_ folder.
> (please at least get the plugin name correct lol)

thanks! it fixed
