### ISSUE TITLE
Bug on LucKPerm

### ISSUE THREAD

**Issue by DjeyMute** [lucko/LuckPerms#2630]
Hi,

Yestarday this bug make crash some player to my server....

[18:36:35] [luckperms-scheduler-worker-46/WARN]: [me.lucko.luckperms.lib.hikari.pool.PoolBase] luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mariadb.MariaDbConnection@23a8780b ((conn=1298871) Connection.setNetworkTimeout cannot be called on a closed connection). Possibly consider using a shorter maxLifetime value.
[18:36:35] [luckperms-scheduler-worker-46/WARN]: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5003ms.
[18:36:35] [luckperms-scheduler-worker-46/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
[18:36:35] [luckperms-scheduler-worker-46/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
[18:36:35] [luckperms-scheduler-worker-46/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
[18:36:35] [luckperms-scheduler-worker-46/WARN]: 	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[18:36:35] [luckperms-scheduler-worker-46/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:151)
[18:36:35] [luckperms-scheduler-worker-46/WARN]: 	at me.lucko.luckperms.common.messaging.sql.SqlMessenger.getConnection(SqlMessenger.java:85)
[18:36:35] [luckperms-scheduler-worker-46/WARN]: 	at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.runHousekeeping(AbstractSqlMessenger.java:115)
[18:36:35] [luckperms-scheduler-worker-46/WARN]: 	at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$ErrorReportingRunnable.run(AbstractJavaScheduler.java:124)
[18:36:35] [luckperms-scheduler-worker-46/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[18:36:35] [luckperms-scheduler-worker-46/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[18:36:35] [luckperms-scheduler-worker-46/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[18:36:35] [luckperms-scheduler-worker-46/WARN]: Caused by: java.sql.SQLSyntaxErrorException: (conn=1298871) Connection.setNetworkTimeout cannot be called on a closed connection
[18:36:35] [luckperms-scheduler-worker-46/WARN]: 	at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
[18:36:35] [luckperms-scheduler-worker-46/WARN]: 	at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:171)
[18:36:35] [luckperms-scheduler-worker-46/WARN]: 	at me.lucko.luckperms.lib.mariadb.MariaDbConnection.setNetworkTimeout(MariaDbConnection.java:1655)
[18:36:35] [luckperms-scheduler-worker-46/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:560)
[18:36:35] [luckperms-scheduler-worker-46/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:173)
[18:36:35] [luckperms-scheduler-worker-46/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:186)

BungeeCord serveur 1.16.3 with the last version off LuckPerm.

**Comment by Laarryy** [comment]
Please follow the issue format

**Comment by DjeyMute** [comment]
I don't know what to say more this error occured without doing anything on my server so I don't know what to say more

**Comment by Thrasilias** [comment]
`- luckperms-hikari - Failed to validate connection
- cannot be called on a closed connection). Possibly consider using a shorter maxLifetime value.
- Connection is not available, request timed out after 5003ms.`
Fix your database,

**Comment by DjeyMute** [comment]
My database of... ? :/

**Comment by Thrasilias** [comment]
from where the error came from. check ur config

**Comment by underscore11code** [comment]
https://luckperms.net/wiki/Storage-system-errors

**Comment by DjeyMute** [comment]
To counter this error I make this : 

    maximum-lifetime: 300000 # 5 minutes

    connection-timeout: 10000 # 10 seconds

Since I did this there has been no more crash.
Do you think it's because of what I did?
