### ISSUE TITLE
Error with online editor, cannot upload data with bytebin LUCKPERMS

### ISSUE THREAD

**Issue by vilper** [lucko/LuckPerms#2673]
I installed luckperms on my bungeecord network server in question which has the errors, is spigot 1.12.2,  getting errors in console:

[19:03:46] [pool-9-thread-1/WARN]: java.lang.RuntimeException: Error uploading data to bytebin
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.common.web.WebEditor.post(WebEditor.java:151)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:175)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:50)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:42)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:204)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:145)
[19:03:46] [pool-9-thread-1/WARN]: at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
[19:03:46] [pool-9-thread-1/WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:03:46] [pool-9-thread-1/WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:03:46] [pool-9-thread-1/WARN]: at java.lang.Thread.run(Unknown Source)
[19:03:46] [pool-9-thread-1/WARN]: Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
[19:03:46] [pool-9-thread-1/WARN]: at sun.security.ssl.Alerts.getSSLException(Unknown Source)
[19:03:46] [pool-9-thread-1/WARN]: at sun.security.ssl.Alerts.getSSLException(Unknown Source)
[19:03:46] [pool-9-thread-1/WARN]: at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
[19:03:46] [pool-9-thread-1/WARN]: at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
[19:03:46] [pool-9-thread-1/WARN]: at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
[19:03:46] [pool-9-thread-1/WARN]: at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[19:03:46] [pool-9-thread-1/WARN]: at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:336)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:300)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:185)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.common.web.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.common.web.BytebinClient.makeHttpRequest(BytebinClient.java:69)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.common.web.BytebinClient.postContent(BytebinClient.java:94)
[19:03:46] [pool-9-thread-1/WARN]: at me.lucko.luckperms.common.web.WebEditor.post(WebEditor.java:146)
[19:03:46] [pool-9-thread-1/WARN]: ... 9 more`

What can i do?

**Comment by benwoo1110** [comment]
Can you check that the computer running the Minecraft server can access https://bytebin.lucko.me/ ?

Also it will be great if you follow the **issue template.**

**Comment by vilper** [comment]
It says me this:  bytebin bytebin.lucko.me
   [about bytebin] [upload]
   [10:43:10] [main/INFO]: Environment: authHost='https://authserver ... bytebin.lucko.me › ...
   ... illegal reflective access operation has occurred, Illegal reflective access by me. lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader'.
   lucko/bytebin: stupidly simple "pastebin" service - GitHub github.com › lucko › bytebin
   I host a public instance at https://bytebin.lucko.me; you can use it in your application as long as: you're not malicious; you don't needlessly spam it; your usage ...
   bytebin/Bytebin.java at master · lucko/bytebin · GitHub github.com › lucko › bytebin › blob › master › src › main › java › me › B...
   Content;. import me.lucko.bytebin.content.ContentCache;. import me.lucko. bytebin.content.ContentStorageHandler;. import me.lucko.bytebin.http. BytebinServer;.
   Self hosting the web interfaces | Wiki | LuckPerms luckperms.net › wiki › Self-hosting-the-web-interfaces
   mkdir bytebin cd bytebin curl -O https://ci.lucko.me/job/bytebin/ lastSuccessfulBuild/artifact/target/bytebin.jar touch config.json. Then open the newly created ...
   lucko ( Luck ) - gitMemory www.gitmemory.com › lucko
   ... https://gist.github.com/ to upload, then include the link below. --> Crash Log: https://bytebin.lucko.me/7TQjRqgzVK Config: https://bytebin.lucko.me/ wzuvCgjwjA ...
   HTTP POST to bytebin.lucko.me responds differently to python's ... stackoverflow.com › questions › http-post-to-bytebin-lucko-me-responds-d...
   You are getting a Response object back. Perhaps you want to print the response. json() instead? > ...
   lucko/LuckPerms - Bountysource www.bountysource.com › trackers › 37833660-lucko-luckperms
   Reproduction Steps: Make a new rank with Luckperms MySQL and try to add a default member to it. Console Log: https://bytebin.lucko.me/COh899pVag.
   LuckPerms помощь - Sponge - свой сервер Minecraft c модами и ... spongeapi.com › 617-luckperms-pomoshch
   ... загрузить данные на сайт редактора. Напиши им, что веб-редактор плагина LuckPerms не работает. Адрес веб-редактора: https://bytebin.lucko. me/.
   Spigot/LuckPerms ... - Gogs - Lipovcan.cz git.lipovcan.cz › java › me › lucko › luckperms › common › web › Bytebin
   JsonObject;; import me.lucko.luckperms.common.util.gson. ... BufferedReader;; public class Bytebin extends AbstractPastebin {; private final String url;; private ...

**Comment by lucko** [comment]
This is a connection/firewall issue at your end - sorry, nothing I can do.
