### ISSUE TITLE
Player Disconnected From Server

### ISSUE THREAD

**Issue by locpx92** [lucko/LuckPerms#2678]
### Description

Player will disconnected from server for the first time they join after the server is start or restart

### Reproduction steps

1. Start / Restart NukkitX Server
2. Player join the server -> Player Disconnected
3. There is error log in console: Caused by: java.lang.NullPointerException: locale
4. But if player join the server again, they can join as normal

### Expected behaviour

Player can join the server normally

### Environment details

* Server type/version: `Nukkit` running version `1.0.11` build `git-602b234`
* LuckPerms version: `v5.2.12`

Log file: https://gist.github.com/locpx92/2fa4f42e7d9a8044dfb8726b01e49db4

### Any other relevant details

Thanks.

**Comment by lucko** [comment]
Thanks for reporting, should be fixed by the above commit.

**Comment by locpx92** [comment]
**Sometime, I got disconnected from server with below error log,  the step is the same with above issue**

[LuckPerms] Exception thrown when setting up permissions for 00000000-0000-0000-0009-01f2342be9c7 - TuritLX - denying login.
> java.lang.IllegalStateException: LPPermissible already injected into player Player(name='TuritLX', location=Location (level=hub, x=242.57899475097656, y=60.0, z=1331.6788330078125, yaw=10.1416015625, pitch=-1.594879150390625))
        at me.lucko.luckperms.nukkit.inject.permissible.PermissibleInjector.inject(PermissibleInjector.java:85)
        at me.lucko.luckperms.nukkit.listeners.NukkitConnectionListener.onPlayerLogin(NukkitConnectionListener.java:164)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:543)
        at cn.nukkit.Player.completeLoginSequence(Player.java:1994)
        at cn.nukkit.Player$1.onCompletion(Player.java:2200)
        at cn.nukkit.scheduler.AsyncTask.collectTask(AsyncTask.java:83)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:281)
        at cn.nukkit.Server.tick(Server.java:1159)
        at cn.nukkit.Server.tickProcessor(Server.java:931)
        at cn.nukkit.Server.start(Server.java:899)
        at cn.nukkit.Server.<init>(Server.java:580)
        at cn.nukkit.Nukkit.main(Nukkit.java:120)
06:26:09 [INFO ] TuritLX[/127.0.0.1:45230] logged out due to [LP] An unexpected error occurred whilst setting up your permissions data. Please try again later.

**Comment by lucko** [comment]
Hmm, this may be more a Nukkit bug - it seems the player login event is being called more than once.
