### ISSUE TITLE
Console spam, I used griefpreventions for 2 years and its the first time that i get this problem:

### ISSUE THREAD

**Issue by vilper** [lucko/LuckPerms#2680]
```
[18:23:35] [pool-3-thread-14/WARN] [luckperms]: An exception was thrown by me.ryanhamshire.griefprevention.claim.ClaimContextCalculator whilst calculating the context of subject luckperms.api7.SubjectProxy(ref=luckperms.SubjectReference(collection=user, subject=e36216f3-5b7c-3f3b-9804-f3b29d5b2a89))
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]: java.lang.NullPointerException
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at me.ryanhamshire.griefprevention.claim.ClaimContextCalculator.accumulateContexts(ClaimContextCalculator.java:43)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at me.ryanhamshire.griefprevention.claim.ClaimContextCalculator.accumulateContexts(ClaimContextCalculator.java:37)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at me.lucko.luckperms.sponge.context.SpongeProxiedContextCalculator.calculate(SpongeProxiedContextCalculator.java:50)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at me.lucko.luckperms.sponge.context.SpongeProxiedContextCalculator.calculate(SpongeProxiedContextCalculator.java:41)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at me.lucko.luckperms.common.context.ContextManager.calculate(ContextManager.java:125)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at me.lucko.luckperms.common.context.QueryOptionsCache.supply(QueryOptionsCache.java:54)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at me.lucko.luckperms.common.context.QueryOptionsCache.supply(QueryOptionsCache.java:42)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at me.lucko.luckperms.common.cache.ExpiringCache.get(ExpiringCache.java:64)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at me.lucko.luckperms.common.context.QueryOptionsCache.getContextSet(QueryOptionsCache.java:64)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at me.lucko.luckperms.sponge.service.proxy.api7.SubjectProxy.getActiveContexts(SubjectProxy.java:163)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at java.util.Optional.map(Optional.java:215)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at net.minecraft.entity.player.EntityPlayerMP.getActiveContexts(EntityPlayerMP.java:3807)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at io.github.nucleuspowered.nucleus.services.impl.permission.NucleusPermissionService.hasPermissionTristate(NucleusPermissionService.java:264)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at io.github.nucleuspowered.nucleus.services.impl.permission.NucleusPermissionService.hasPermission(NucleusPermissionService.java:254)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at io.github.nucleuspowered.nucleus.services.impl.permission.NucleusPermissionService.hasPermission(NucleusPermissionService.java:121)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at io.github.nucleuspowered.nucleus.modules.afk.services.AFKHandler$AFKData.lambda$updateFromPermissions$2(AFKHandler.java:394)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at java.util.Optional.ifPresent(Optional.java:159)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at io.github.nucleuspowered.nucleus.modules.afk.services.AFKHandler$AFKData.updateFromPermissions(AFKHandler.java:393)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at io.github.nucleuspowered.nucleus.modules.afk.services.AFKHandler.lambda$onTick$4(AFKHandler.java:108)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at java.util.concurrent.ConcurrentHashMap$EntrySpliterator.forEachRemaining(ConcurrentHashMap.java:3606)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at io.github.nucleuspowered.nucleus.modules.afk.services.AFKHandler.onTick(AFKHandler.java:108)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at io.github.nucleuspowered.nucleus.modules.afk.runnables.AFKTask.accept(AFKTask.java:30)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at io.github.nucleuspowered.nucleus.modules.afk.runnables.AFKTask.accept(AFKTask.java:18)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197)
[18:23:35] [pool-3-thread-14/INFO] [STDERR]: [me.lucko.luckperms.common.context.ContextManager:calculate:128]:  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
```

What can I do? We cant even build and is a terrible spam

**Comment by lucko** [comment]
This is a GriefPrevention issue, not LP related.
