### ISSUE TITLE
Having different dialects of the same language completely breaks messages for said language.

### ISSUE THREAD

**Issue by Fefo6644** [lucko/LuckPerms#2682]
### Description

With the introduction of Pirate English, now there are two different English dialects; when LP tries to register it, it goes no no (stack trace at the bottom).

### Reproduction steps

1. Run `/lp translations install`
2. Observe, it throws.

It also happens on plugin load after installing the other dialect.

#### Not this
![image](https://user-images.githubusercontent.com/35617540/96817131-0ebb4000-13f5-11eb-8d34-ce7b1c643e97.png)

### Environment details

* Server type/version: `Paper` running version `1.16.3` build `244`
* LuckPerms version: `v5.2.14`

### Any other relevant details

```
java.lang.IllegalArgumentException: Invalid key (and 514 more)
       at me.lucko.luckperms.lib.adventure.translation.TranslationRegistry.registerAll(TranslationRegistry.java:194)
       at me.lucko.luckperms.lib.adventure.translation.TranslationRegistry.registerAll(TranslationRegistry.java:157)
       at me.lucko.luckperms.common.locale.TranslationManager.loadBase(TranslationManager.java:104)
       at me.lucko.luckperms.common.locale.TranslationManager.reload(TranslationManager.java:93)
       at me.lucko.luckperms.common.commands.misc.TranslationsCommand.execute(TranslationsCommand.java:91)
       at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:56)
       at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:48)
       at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:209)
       at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:142)
       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
       at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Translation already exists: luckperms.usage.editor.description for en
       at me.lucko.luckperms.lib.adventure.translation.TranslationRegistryImpl$Translation.register(TranslationRegistryImpl.java:110)
       at me.lucko.luckperms.lib.adventure.translation.TranslationRegistryImpl.register(TranslationRegistryImpl.java:48)
       at me.lucko.luckperms.lib.adventure.translation.TranslationRegistry.registerAll(TranslationRegistry.java:181)
       ... 12 more
```

**Comment by lucko** [comment]
ab0e25a56d60790d8e23f780ae9d3255a9b3f0fb
