### ISSUE TITLE
"mysql" setting no longer working with MariaDB databases

### ISSUE THREAD

**Issue by Turbotailz** [lucko/LuckPerms#2701]
I do not know much about the details of this however it seems to be a new error popping up due to a recent release of MariaDB (10.5.7) which causes this error if the config is set to `mysql` for the storage method:

```
04.11 20:13:36 [Server] WARN java.util.concurrent.CompletionException: java.sql.SQLException: Malformed communication packet
04.11 20:13:36 [Server] WARN at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:105)
04.11 20:13:36 [Server] WARN at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
04.11 20:13:36 [Server] WARN at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
04.11 20:13:36 [Server] WARN at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
04.11 20:13:36 [Server] WARN at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
04.11 20:13:36 [Server] WARN at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
04.11 20:13:36 [Server] WARN at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
04.11 20:13:36 [Server] WARN Caused by: java.sql.SQLException: Malformed communication packet
04.11 20:13:36 [Server] WARN at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
04.11 20:13:36 [Server] WARN at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
04.11 20:13:36 [Server] WARN at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
04.11 20:13:36 [Server] WARN at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
04.11 20:13:36 [Server] WARN at me.lucko.luckperms.lib.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1281)
04.11 20:13:36 [Server] WARN at me.lucko.luckperms.lib.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:787)
04.11 20:13:36 [Server] WARN at me.lucko.luckperms.lib.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2020)
04.11 20:13:36 [Server] WARN at me.lucko.luckperms.lib.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
04.11 20:13:36 [Server] WARN at me.lucko.luckperms.lib.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
04.11 20:13:36 [Server] WARN at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.selectGroups(SqlStorage.java:923)
04.11 20:13:36 [Server] WARN at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:485)
04.11 20:13:36 [Server] WARN at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$10(Storage.java:194)
04.11 20:13:36 [Server] WARN at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:100)
04.11 20:13:36 [Server] WARN ... 6 more
```

Users have reported that simply changing their storage method to `mariadb` has fixed this issue.

[Quote from Patrick<3#0001 on Discord](https://discordapp.com/channels/241667244927483904/241667244927483904/773691042922889246):

> for further reference I believe this is a issue with the new build of MariaDB 10.5.7 (released 3rd of November) from what I can see multiple people have been having the issue with MySql no longer being the correct database format in the config file, and you now need to change it to MariaDB

**Comment by Fifa12fcb** [comment]
Hello,

looking further into this I can see this isn't a error on your end but more a error with MariaDB - https://jira.mariadb.org/browse/MDEV-24121

**Comment by lucko** [comment]
I've upgraded the MySQL driver in 00d4a2a1dac1b4ebcb067f746010b35d8c889669 from 5.0 to 8.0.

That may resolve the issue, if not, we will just need to wait for the MariaDB server fix to filter back down - not much more I can do!
