### ISSUE TITLE
I have problem

### ISSUE THREAD

**Issue by zHackyBR** [lucko/LuckPerms#2708]
[15:05:48 INFO]: [LuckPerms] Enabling LuckPerms v5.1.93
[15:05:48 INFO]:         __    
[15:05:48 INFO]:   |    |__)   LuckPerms v5.1.93
[15:05:48 INFO]:   |___ |      Running on Bukkit - CraftBukkit
[15:05:48 INFO]: 
[15:05:48 INFO]: [LuckPerms] Loading configuration...
[15:05:50 INFO]: [LuckPerms] Loading storage provider... [MYSQL]
[15:05:50 WARN]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[15:05:50 WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[15:05:50 WARN]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[15:05:52 INFO]: [LuckPerms] Loading messaging service... [SQL]
[15:05:52 WARN]: java.lang.RuntimeException: java.sql.SQLException: Malformed communication packet
[15:05:52 WARN]:        at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:57)
[15:05:52 WARN]:        at me.lucko.luckperms.common.messaging.MessagingFactory$SqlMessengerProvider.obtain(MessagingFactory.java:154)
[15:05:52 WARN]:        at me.lucko.luckperms.common.messaging.LuckPermsMessagingService.<init>(LuckPermsMessagingService.java:73)
[15:05:52 WARN]:        at me.lucko.luckperms.common.messaging.MessagingFactory.getServiceFor(MessagingFactory.java:106)
[15:05:52 WARN]:        at me.lucko.luckperms.bukkit.messaging.BukkitMessagingFactory.getServiceFor(BukkitMessagingFactory.java:64)
[15:05:52 WARN]:        at me.lucko.luckperms.common.messaging.MessagingFactory.getInstance(MessagingFactory.java:84)
[15:05:52 WARN]:        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:152)
[15:05:52 WARN]:        at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:162)
[15:05:52 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[15:05:52 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[15:05:52 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[15:05:52 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[15:05:52 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[15:05:52 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199)
[15:05:52 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[15:05:52 WARN]:        at java.lang.Thread.run(Thread.java:823)
[15:05:52 WARN]: Caused by: 
[15:05:52 WARN]: java.sql.SQLException: Malformed communication packet
[15:05:52 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[15:05:52 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
[15:05:52 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
[15:05:52 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[15:05:52 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1281)
[15:05:52 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:787)
[15:05:52 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2020)
[15:05:52 WARN]:        at me.lucko.luckperms.lib.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[15:05:52 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[15:05:52 WARN]:        at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.init(AbstractSqlMessenger.java:79)
[15:05:52 WARN]:        at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:55)
[15:05:52 WARN]:        ... 15 more
[15:05:52 WARN]: [LuckPerms] Messaging service 'sql' not recognised.
[15:05:53 INFO]: [LuckPerms] Loading internal permission managers...
[15:05:53 INFO]: [LuckPerms] Performing initial data load...
[15:05:53 WARN]: java.util.concurrent.CompletionException: java.sql.SQLException: Malformed communication packet
[15:05:53 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:104)
[15:05:53 WARN]:        at me.lucko.luckperms.common.storage.Storage$$Lambda$183/00000000BCB2E760.run(Unknown Source)
[15:05:53 WARN]:        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
[15:05:53 WARN]:        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)
[15:05:53 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[15:05:53 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[15:05:53 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[15:05:53 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[15:05:53 WARN]: Caused by: 
[15:05:53 WARN]: java.sql.SQLException: Malformed communication packet
[15:05:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[15:05:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
[15:05:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
[15:05:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[15:05:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1281)
[15:05:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:787)
[15:05:53 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2020)
[15:05:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[15:05:53 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[15:05:53 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.selectGroups(SqlStorage.java:868)
[15:05:53 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:440)
[15:05:53 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$10(Storage.java:195)
[15:05:53 WARN]:        at me.lucko.luckperms.common.storage.Storage$$Lambda$182/00000000BCB2DB40.run(Unknown Source)
[15:05:53 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:99)
[15:05:53 WARN]:        ... 7 more
[15:05:54 INFO]: [LuckPerms] Successfully enabled. (took 6654ms)

**Comment by benwoo1110** [comment]
Change `storage-method` to `mariadb`

**Comment by zHackyBR** [comment]
[15:15:56 INFO]: [LuckPerms] Enabling LuckPerms v5.1.93
[15:15:56 INFO]:         __    
[15:15:56 INFO]:   |    |__)   LuckPerms v5.1.93
[15:15:56 INFO]:   |___ |      Running on Bukkit - CraftBukkit
[15:15:56 INFO]: 
[15:15:56 INFO]: [LuckPerms] Loading configuration...
[15:16:07 INFO]: [LuckPerms] Loading storage provider... [MARIADB]
[15:16:07 WARN]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[15:16:07 WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[15:16:07 WARN]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[15:16:07 INFO]: [LuckPerms] Loading messaging service... [SQL]
[15:16:08 INFO]: [LuckPerms] Loading internal permission managers...
[15:16:08 INFO]: [LuckPerms] Performing initial data load...
[15:16:08 WARN]: java.util.concurrent.CompletionException: java.sql.SQLSyntaxErrorException: (conn=27249) Table 's116528_redeshadeserver.luckperms_tracks' doesn't exist
[15:16:08 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:104)
[15:16:08 WARN]:        at me.lucko.luckperms.common.storage.Storage$$Lambda$192/00000000747ED100.run(Unknown Source)
[15:16:08 WARN]:        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
[15:16:08 WARN]:        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)
[15:16:08 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[15:16:08 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[15:16:08 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[15:16:08 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[15:16:08 WARN]: Caused by: 
[15:16:08 WARN]: java.sql.SQLSyntaxErrorException: (conn=27249) Table 's116528_redeshadeserver.luckperms_tracks' doesn't exist
[15:16:08 WARN]:        at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
[15:16:08 WARN]:        at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153)
[15:16:08 WARN]:        at me.lucko.luckperms.lib.mariadb.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:273)
[15:16:08 WARN]:        at me.lucko.luckperms.lib.mariadb.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
[15:16:08 WARN]:        at me.lucko.luckperms.lib.mariadb.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
[15:16:08 WARN]:        at me.lucko.luckperms.lib.mariadb.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
[15:16:08 WARN]:        at me.lucko.luckperms.lib.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[15:16:08 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[15:16:08 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.selectTracks(SqlStorage.java:968)
[15:16:08 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllTracks(SqlStorage.java:588)
[15:16:08 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$loadAllTracks$17(Storage.java:241)
[15:16:08 WARN]:        at me.lucko.luckperms.common.storage.Storage$$Lambda$216/0000000074015580.run(Unknown Source)
[15:16:08 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:99)
[15:16:08 WARN]:        ... 7 more
[15:16:08 WARN]: Caused by: 
[15:16:08 WARN]: me.lucko.luckperms.lib.mariadb.internal.util.exceptions.MariaDbSqlException: Table 's116528_redeshadeserver.luckperms_tracks' doesn't exist
[15:16:08 WARN]:        at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
[15:16:08 WARN]:        at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194)
[15:16:08 WARN]:        at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:177)
[15:16:08 WARN]:        at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:321)
[15:16:08 WARN]:        at me.lucko.luckperms.lib.mariadb.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
[15:16:08 WARN]:        ... 16 more
[15:16:08 WARN]: Caused by: 
[15:16:08 WARN]: java.sql.SQLException: Table 's116528_redeshadeserver.luckperms_tracks' doesn't exist
[15:16:08 WARN]:        at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1674)
[15:16:08 WARN]:        at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1536)
[15:16:08 WARN]:        at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1499)
[15:16:08 WARN]:        at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:318)
[15:16:08 WARN]:        ... 17 more
[15:16:09 INFO]: [LuckPerms] Successfully enabled. (took 12589ms)

**Comment by lucko** [comment]
>  Table 's116528_redeshadeserver.luckperms_tracks' doesn't exist

You seem to be missing one of the required tables, the easiest fix is to delete the database and let LuckPerms regenerate it (assuming you haven't started to setup LuckPerms yet)

If you can't do that, then you may need to recreate the table manually.
