### ISSUE TITLE
NPE on user join

### ISSUE THREAD

**Issue by DanyBv** [lucko/LuckPerms#271]
Somebody tried to connect to the server (Waterfall) and I got this error in console:

> java.util.concurrent.CompletionException: java.lang.NullPointerException
 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
 	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 	at java.lang.Thread.run(Thread.java:745)
 Caused by: java.lang.NullPointerException
 	at me.lucko.luckperms.common.event.EventFactory.handleUserLoad(EventFactory.java:207)
 	at me.lucko.luckperms.common.storage.AbstractStorage.lambda$loadUser$2(AbstractStorage.java:107)
 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
 	... 4 more

**Comment by lucko** [comment]
Can you update to the latest version & try again.
