### ISSUE TITLE
LuckPerms-Bukkit-5.1.93 not work's on bungee !

### ISSUE THREAD

**Issue by Matyyye** [lucko/LuckPerms#2715]
19:23:12 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
19:23:12 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.16-R0.4-SNAPSHOT:4199b0c:1537 by SpigotMC
19:23:12 [WARNING] Error enabling plugin LuckPerms
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:44)
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:327)
at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:235)
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:271)
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:63)
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
... 18 more
19:23:12 [INFO] Loaded plugin cmd_find version git:cmd_find:1.16-R0.4-SNAPSHOT:4199b0c:1537 by SpigotMC
19:23:12 [INFO] Loaded plugin cmd_server version git:cmd_server:1.16-R0.4-SNAPSHOT:4199b0c:1537 by SpigotMC
19:23:12 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.16-R0.4-SNAPSHOT:4199b0c:1537 by SpigotMC
19:23:12 [INFO] Loaded plugin cmd_send version git:cmd_send:1.16-R0.4-SNAPSHOT:4199b0c:1537 by SpigotMC
19:23:12 [INFO] Loaded plugin cmd_list version git:cmd_list:1.16-R0.4-SNAPSHOT:4199b0c:1537 by SpigotMC
19:23:12 [WARNING] Forced host server pvp is not defined
19:23:12 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.16-R0.4-SNAPSHOT:4199b0c:1537 by SpigotMC
19:23:12 [INFO] Enabled plugin cmd_find version git:cmd_find:1.16-R0.4-SNAPSHOT:4199b0c:1537 by SpigotMC
19:23:12 [INFO] Enabled plugin cmd_server version git:cmd_server:1.16-R0.4-SNAPSHOT:4199b0c:1537 by SpigotMC
19:23:12 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.16-R0.4-SNAPSHOT:4199b0c:1537 by SpigotMC
19:23:12 [INFO] Enabled plugin cmd_send version git:cmd_send:1.16-R0.4-SNAPSHOT:4199b0c:1537 by SpigotMC
19:23:12 [INFO] Enabled plugin cmd_list version git:cmd_list:1.16-R0.4-SNAPSHOT:4199b0c:1537 by SpigotMC

**Comment by Fefo6644** [comment]
You installed the Bukkit version of LuckPerms, use the Bungee version instead.
https://luckperms.net/download
