### ISSUE TITLE
Since 5.3.32, advanced achievements is spamming console errors related to luckperms

### ISSUE THREAD

**Issue by kelso6969** [lucko/LuckPerms#2721]
### Description

Using AdvancedAchievements 6.7.1
Updated to LuckPerms 5.3.32 and now console is spammed like crazy like this
````
[09:35:11 ERROR]: Could not pass event PlayerDropItemEvent to AdvancedAchievements v6.7.1
com.hm.achievement.exception.DatabaseReadError: Database read error while retrieving ItemDrops statistics.
        at com.hm.achievement.db.SQLReadOperation.executeOperation(SQLReadOperation.java:42) ~[?:?]
        at com.hm.achievement.db.AbstractDatabaseManager.getNormalAchievementAmount(AbstractDatabaseManager.java:370) ~[?:?]
        at com.hm.achievement.db.CacheManager.getAndIncrementStatisticAmount(CacheManager.java:164) ~[?:?]
        at com.hm.achievement.listener.statistics.AbstractListener.updateStatisticAndAwardAchievementsIfAvailable(AbstractListener.java:54) ~[?:?]
        at com.hm.achievement.listener.statistics.DropsListener.onPlayerDropItem(DropsListener.java:36) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor740.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-276]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-276]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-276]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.EntityHuman.a(EntityHuman.java:587) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.EntityPlayer.a(EntityPlayer.java:1970) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.EntityHuman.dropItem(EntityHuman.java:538) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1450) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-276]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.sql.SQLSyntaxErrorException: (conn=4093958) Could not set parameter in setObject, could not convert: class java.util.UUID to 1
        at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62) ~[?:?]
        at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:171) ~[?:?]
        at me.lucko.luckperms.lib.mariadb.BasePrepareStatement.setInternalObject(BasePrepareStatement.java:1149) ~[?:?]
        at me.lucko.luckperms.lib.mariadb.BasePrepareStatement.setObject(BasePrepareStatement.java:844) ~[?:?]
        at com.hm.achievement.db.AbstractDatabaseManager.lambda$getNormalAchievementAmount$8(AbstractDatabaseManager.java:363) ~[?:?]
        at com.hm.achievement.db.SQLReadOperation.executeOperation(SQLReadOperation.java:37) ~[?:?]
        ... 27 more
[09:35:18 WARN]: [AdvancedAchievements] Task #595 for AdvancedAchievements v6.7.1 generated an exception
com.hm.achievement.exception.DatabaseReadError: Database read error while retrieving DistanceFoot statistics.
        at com.hm.achievement.db.SQLReadOperation.executeOperation(SQLReadOperation.java:42) ~[?:?]
        at com.hm.achievement.db.AbstractDatabaseManager.getNormalAchievementAmount(AbstractDatabaseManager.java:370) ~[?:?]
        at com.hm.achievement.db.CacheManager.getAndIncrementStatisticAmount(CacheManager.java:164) ~[?:?]
        at com.hm.achievement.runnable.AchieveDistanceRunnable.updateDistance(AchieveDistanceRunnable.java:143) ~[?:?]
        at com.hm.achievement.runnable.AchieveDistanceRunnable.validateMovementAndUpdateDistance(AchieveDistanceRunnable.java:108) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085) ~[?:?]
        at com.hm.achievement.runnable.AchieveDistanceRunnable.run(AchieveDistanceRunnable.java:63) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-276]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-276]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.sql.SQLSyntaxErrorException: (conn=4093958) Could not set parameter in setObject, could not convert: class java.util.UUID to 1
        at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62) ~[?:?]
        at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:171) ~[?:?]
        at me.lucko.luckperms.lib.mariadb.BasePrepareStatement.setInternalObject(BasePrepareStatement.java:1149) ~[?:?]
        at me.lucko.luckperms.lib.mariadb.BasePrepareStatement.setObject(BasePrepareStatement.java:844) ~[?:?]
        at com.hm.achievement.db.AbstractDatabaseManager.lambda$getNormalAchievementAmount$8(AbstractDatabaseManager.java:363) ~[?:?]
        at com.hm.achievement.db.SQLReadOperation.executeOperation(SQLReadOperation.java:37) ~[?:?]
        ... 15 more
````

### Reproduction steps

Run advancedachievements, update luckperms and login, check console 

### Expected behaviour
no console spam

### Environment details

Paper(276) ,  luckperms 5.3.32, advancedachievements 6.7.1

https://gist.github.com/kelso6969/10a6159c26e4dcf885b680b7c9356031

### Any other relevant details

I reported to Advanced achievements first as well, but figured I'd cover both sides.

**Comment by lucko** [comment]
Should be fixed in v5.2.34
