### ISSUE TITLE
Error Luckperms-Bungee

### ISSUE THREAD

**Issue by Skytoone** [lucko/LuckPerms#2733]
```
18:30:44 [WARNING] [LuckPerms] A LinkageError has occurred whilst initialising Hikari. This is likely due to classloading conflicts between other plugins.
18:30:44 [WARNING] [LuckPerms] Please check for other plugins below (and try loading LuckPerms without them installed) before reporting the issue.
18:30:44 [WARNING] [LuckPerms] Class org.slf4j.LoggerFactory has been loaded by: ajQueue (net.md_5.bungee.api.plugin.PluginClassloader@6c779568)
18:30:44 [WARNING] [LuckPerms] Class org.slf4j.ILoggerFactory has been loaded by: ajQueue (net.md_5.bungee.api.plugin.PluginClassloader@6c779568)
18:30:44 [WARNING] [LuckPerms] Class org.slf4j.impl.StaticLoggerBinder has been loaded by: DynamicBungeeAuth (net.md_5.bungee.api.plugin.PluginClassloader@2cd2a21f)
18:30:44 [WARNING] Exception encountered when loading plugin: LuckPerms
java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:423)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
at me.lucko.luckperms.lib.hikari.HikariConfig.<clinit>(HikariConfig.java:51)
at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:115)
at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:155)
at me.lucko.luckperms.common.storage.Storage.init(Storage.java:116)
at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88)
at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:154)
at me.lucko.luckperms.bungee.LPBungeeBootstrap.onEnable(LPBungeeBootstrap.java:154)
at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) # #
```

**Comment by Laarryy** [comment]
Follow the issue template

**Comment by Laarryy** [comment]
And read the error.

**Comment by lucko** [comment]
The important part is this:

```
[LuckPerms] A LinkageError has occurred whilst initialising Hikari. This is likely due to classloading conflicts between other plugins.
[LuckPerms] Please check for other plugins below (and try loading LuckPerms without them installed) before reporting the issue.
[LuckPerms] Class org.slf4j.LoggerFactory has been loaded by: ajQueue (net.md_5.bungee.api.plugin.PluginClassloader@6c779568)
[LuckPerms] Class org.slf4j.ILoggerFactory has been loaded by: ajQueue (net.md_5.bungee.api.plugin.PluginClassloader@6c779568)
[LuckPerms] Class org.slf4j.impl.StaticLoggerBinder has been loaded by: DynamicBungeeAuth (net.md_5.bungee.api.plugin.PluginClassloader@2cd2a21f)
```

Two of your plugins (`ajQueue` and `DynamicBungeeAuth`) are incorrectly shading the SLF4J library (a library which LuckPerms also uses). This is causing problems when LuckPerms enables and tries to use it too.
