### ISSUE TITLE
java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/adventure/translation/Translator

### ISSUE THREAD

**Issue by axelrindle** [lucko/LuckPerms#2743]
### Description
After installing the plugin the following stacktrace is thrown at me on server startup:

```
[13:05:36] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:05:37] [main/INFO]: Reloading ResourceManager: Default, bukkit
[13:05:38] [Worker-Main-5/INFO]: Loaded 7 recipes
[13:05:40] [Server thread/INFO]: Starting minecraft server version 1.16.4
[13:05:40] [Server thread/INFO]: Loading properties
[13:05:41] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-a19903d-167ff59 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[13:05:42] [Server thread/INFO]: Debug logging is disabled
[13:05:42] [Server thread/INFO]: Server Ping Player Sample Count: 12
[13:05:42] [Server thread/INFO]: Using 4 threads for Netty based IO
[13:05:42] [Server thread/INFO]: Default game type: SURVIVAL
[13:05:42] [Server thread/INFO]: Generating keypair
[13:05:43] [Server thread/INFO]: Starting Minecraft server on *:25565
[13:05:43] [Server thread/INFO]: Using epoll channel type
[13:05:45] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[13:05:49] [Server thread/WARN]: Legacy plugin dynmap v3.1-beta5-431 does not specify an api-version.
[13:05:49] [Server thread/WARN]: Legacy plugin ServerListPlus v3.4.8 does not specify an api-version.
[13:05:49] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.2.41
[13:05:49] [Server thread/ERROR]: me/lucko/luckperms/lib/adventure/translation/Translator initializing LuckPerms v5.2.41 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/adventure/translation/Translator
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.load(AbstractLuckPermsPlugin.java:104) ~[?:?]
        at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onLoad(LPBukkitBootstrap.java:138) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:388) ~[spigot-1.16.4.jar:git-Spigot-a19903d-167ff59]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:185) ~[spigot-1.16.4.jar:git-Spigot-a19903d-167ff59]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.4.jar:git-Spigot-a19903d-167ff59]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-a19903d-167ff59]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.adventure.translation.Translator
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_275]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.16.4.jar:git-Spigot-a19903d-167ff59]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.4.jar:git-Spigot-a19903d-167ff59]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
        ... 7 more
```

### Reproduction steps
Not sure if this is reproducible...

### Expected behaviour
The plugin loads as expected.

### Environment details
| Component | Version |
| --- | --- |
| Spigot | CraftBukkit version git-Spigot-a19903d-167ff59 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT) |
| LuckPerms | 5.2.41 |
| Operating System | Debian 10.6 x64 |
| Java | openjdk version "1.8.0_275"<br>OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)<br>OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.275-b01, mixed mode) |

### Any other relevant details
The directory `LuckPerms/libs/` is created and filled with a number of `.jar` files.

**Comment by powercasgamer** [comment]
Delete the `libs/` folder and restart the server

**Comment by axelrindle** [comment]
Interesting... that fixed the issue.

What might have been the problem here?

**Comment by powercasgamer** [comment]
> Interesting... that fixed the issue.
> 
> What might have been the problem here?

One of the libs didn't download correctly. If everything is good you can close the issue.

**Comment by axelrindle** [comment]
Great! Thank you 👍
