### ISSUE TITLE
MongoDB SSLHandshakeException

### ISSUE THREAD

**Issue by nanitook** [lucko/LuckPerms#2763]
### Description
The plugin crash on startup while trying to connect to MongoDB.

These are the logs:
```
javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request
        at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
        at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:307) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:263) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:254) ~[?:?]
        at sun.security.ssl.SSLExtensions.<init>(SSLExtensions.java:90) ~[?:?]
        at sun.security.ssl.CertificateRequest$T13CertificateRequestMessage.<init>(CertificateRequest.java:818) ~[?:?]
        at sun.security.ssl.CertificateRequest$T13CertificateRequestConsumer.consume(CertificateRequest.java:922) ~[?:?]
        at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392) ~[?:?]
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443) ~[?:?]
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421) ~[?:?]
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:177) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:164) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1151) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1062) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:716) ~[?:?]
        at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:969) ~[?:?]
        at me.lucko.luckperms.lib.mongodb.internal.connection.SocketStream.write(SocketStream.java:99) ~[?:?]
        at me.lucko.luckperms.lib.mongodb.internal.connection.InternalStreamConnection.sendMessage(InternalStreamConnection.java:430) ~[?:?]
        ... 9 more
```

### Environment details

* Server type/version: `Waterfall` game version `1.16.4` build `384` and `Paper` game version `1.16.4` build `320`
* LuckPerms version: `Bungee and Bukkit 5.2.53`

**Comment by lucko** [comment]
Seems like you can fix this using a command-line flag: https://stackoverflow.com/a/61143833

I'm not sure there's anything I can do in LP to fix this, since if anything it's going to be a Mongo driver issue.
