### ISSUE TITLE
not work latest version 

### ISSUE THREAD

**Issue by successed** [lucko/LuckPerms#2778]
[09:36:52] [Server thread/INFO]: [LuckPerms] Loading configuration...
[09:36:52] [Server thread/INFO]: [LuckPerms] Loading storage provider... [H2]
[09:36:53] [Server thread/ERROR]: Error occurred while enabling LuckPerms v5.2.35 (Is it up to date?)
java.lang.NoSuchMethodError: com.google.common.collect.Range.closed(Ljava/lang/Comparable;Ljava/lang/Comparable;)Lcom/google/common/collect/Range;
	at me.lucko.luckperms.common.util.Predicates.notInRange(Predicates.java:72) ~[?:?]
	at me.lucko.luckperms.common.commands.generic.permission.PermissionInfo.<init>(PermissionInfo.java:54) ~[?:?]
	at me.lucko.luckperms.common.commands.generic.permission.CommandPermission.<init>(CommandPermission.java:38) ~[?:?]
	at me.lucko.luckperms.common.commands.user.UserParentCommand.<init>(UserParentCommand.java:69) ~[?:?]
	at me.lucko.luckperms.common.command.CommandManager.<init>(CommandManager.java:99) ~[?:?]
	at me.lucko.luckperms.bukkit.BukkitCommandExecutor.<init>(BukkitCommandExecutor.java:68) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitPlugin.registerCommands(LPBukkitPlugin.java:156) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:161) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:162) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot.jar:git-Spigot-1543]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [spigot.jar:git-Spigot-1543]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-1543]
	at org.bukkit.craftbukkit.v1_7_R3.CraftServer.loadPlugin(CraftServer.java:476) [spigot.jar:git-Spigot-1543]
	at org.bukkit.craftbukkit.v1_7_R3.CraftServer.enablePlugins(CraftServer.java:394) [spigot.jar:git-Spigot-1543]
	at net.minecraft.server.v1_7_R3.DedicatedServer.init(DedicatedServer.java:137) [spigot.jar:git-Spigot-1543]
	at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:458) [spigot.jar:git-Spigot-1543]
	at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1543]

**Comment by lucko** [comment]
Use the Bukkit-Legacy version: https://luckperms.net/download
