### ISSUE TITLE
MySQL no connect

### ISSUE THREAD

**Issue by LitMauurySsj** [lucko/LuckPerms#2786]
sorry my native language is not english

I have problems connecting luckperms to my database
I have the base in my vps so everything is by default
luckperms works fine being without database but when trying to connect this appears, my session data is correct

```
[luckperms-hikari housekeeper] DEBUG me.lucko.luckperms.lib.hikari.pool.HikariPool  - luckperms-hikari - Pool stats (total=0, active=0, idle=0, waiting=0)
815548 [luckperms-hikari housekeeper] DEBUG me.lucko.luckperms.lib.hikari.pool.HikariPool  - luckperms-hikari - Fill pool skipped, pool is at sufficient level.
818529 [luckperms-hikari connection adder] DEBUG me.lucko.luckperms.lib.hikari.pool.HikariPool  - luckperms-hikari - Cannot acquire connection from data source
me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
        at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
        at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
        at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
        at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
        at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
        at me.lucko.luckperms.lib.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
        at me.lucko.luckperms.lib.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
        at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:725)
        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:711)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: me.lucko.luckperms.lib.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
        at sun.reflect.GeneratedConstructorAccessor39.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at me.lucko.luckperms.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
        at me.lucko.luckperms.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
        at me.lucko.luckperms.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
        at me.lucko.luckperms.lib.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
        at me.lucko.luckperms.lib.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
        at me.lucko.luckperms.lib.mysql.cj.NativeSession.connect(NativeSession.java:144)
        at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956)
        at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
        ... 14 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at me.lucko.luckperms.lib.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
        at me.lucko.luckperms.lib.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
        ... 17 more
```

**Comment by lucko** [comment]
> Connection refused

Your database server is refusing the connection.

https://luckperms.net/wiki/Storage-system-errors

**Comment by liktome** [comment]
you can fix this?

**Comment by benwoo1110** [comment]
No, bcu the error isn't caused by luckperms.
