### ISSUE TITLE
Error Message 

### ISSUE THREAD

**Issue by AAWA-byt** [lucko/LuckPerms#2792]
[16:59:13] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.2.35
>[43,552s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[43,553s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[43,554s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[43,556s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader (file:/home/MiniPixel-1.16.4/plugins/LuckPerms-Bukkit-5.2.35%20(3).jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[16:59:13] [ForkJoinPool-3-worker-17/WARN]: java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[16:59:13] [ForkJoinPool-3-worker-17/WARN]:     at java.base/java.lang.Thread.start0(Native Method)
[16:59:13] [ForkJoinPool-3-worker-17/WARN]:     at java.base/java.lang.Thread.start(Thread.java:803)
[16:59:13] [ForkJoinPool-3-worker-17/WARN]:     at java.base/java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1329)
[16:59:13] [ForkJoinPool-3-worker-17/WARN]:     at java.base/java.util.concurrent.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1352)
[16:59:13] [ForkJoinPool-3-worker-17/WARN]:     at java.base/java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1476)
[16:59:13] [ForkJoinPool-3-worker-17/WARN]:     at java.base/java.util.concurrent.ForkJoinPool.deregisterWorker(ForkJoinPool.java:1458)
[16:59:13] [ForkJoinPool-3-worker-17/WARN]:     at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:193)
[16:59:13] [ForkJoinPool-3-worker-51/INFO]: [LuckPerms] It is safe to ignore any warning printed following this message starting with 'WARNING: An illegal reflective access operation has occurred, Illegal reflective access by me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader'. This is intended, and will not have any impact on the operation of LuckPerms.
[16:59:13] [ForkJoinPool-3-worker-3/WARN]: java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[16:59:13] [ForkJoinPool-3-worker-3/WARN]:      at java.base/java.lang.Thread.start0(Native Method)
[16:59:13] [ForkJoinPool-3-worker-3/WARN]:      at java.base/java.lang.Thread.start(Thread.java:803)
[16:59:13] [ForkJoinPool-3-worker-3/WARN]:      at java.base/java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1329)
[16:59:13] [ForkJoinPool-3-worker-3/WARN]:      at java.base/java.util.concurrent.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1352)
[16:59:13] [ForkJoinPool-3-worker-3/WARN]:      at java.base/java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1476)
[16:59:13] [ForkJoinPool-3-worker-3/WARN]:      at java.base/java.util.concurrent.ForkJoinPool.deregisterWorker(ForkJoinPool.java:1458)
[16:59:13] [ForkJoinPool-3-worker-3/WARN]:      at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:193)

When I start my server this the error message the console is sending.

**Comment by benwoo1110** [comment]
Looks like your server hardware just doesn't have enough thread to work with. But in any case, **follow the issue template**.

**Comment by AAWA-byt** [comment]
What would be enough thread?

**Comment by lucko** [comment]
It varies, but usually at least 1000 are available - likelihood is that something is using lots of them up.

However, that error is unrelated to the LP error message. That is fixed by updating to a newer version: https://luckperms.net/download

**Comment by zbw818** [comment]
I encountered the same problem, but after querying I found that the number of processes did not exceed the limit. Has your problem been solved? How to solve this problem?

**Comment by Laarryy** [comment]
If you have this same error, @zbw818, please open a new issue and fill out the form as detailed as possible rather than commenting on old, closed issues.
