### ISSUE TITLE
database

### ISSUE THREAD

**Issue by gamernathanyt** [lucko/LuckPerms#2834]
i get this error when i try to connect it to mysq 

```
l[10:54:45 INFO]: [LuckPerms] Enabling LuckPerms v5.2.90
[10:54:45 INFO]:         __
[10:54:45 INFO]:   |    |__)   LuckPerms v5.2.90
[10:54:45 INFO]:   |___ |      Running on Bukkit - CraftBukkit
[10:54:45 INFO]:
[10:54:45 INFO]: [LuckPerms] Loading configuration...
[10:54:45 INFO]: [LuckPerms] Loading storage provider... [MYSQL]
[10:54:45 WARN]: [Server thread] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Starting...
[10:54:45 WARN]: [Server thread] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Start completed.
[10:54:47 INFO]: [LuckPerms] Loading messaging service... [SQL]
[10:54:47 ERROR]: [LuckPerms] Exception occurred whilst enabling SQL messaging service
java.lang.RuntimeException: java.sql.SQLException: Malformed communication packet
        at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:57) ~[LuckPerms-Bukkit-5.2.90.jar:?]
        at me.lucko.luckperms.common.messaging.MessagingFactory$SqlMessengerProvider.obtain(MessagingFactory.java:154) ~[LuckPerms-Bukkit-5.2.90.jar:?]
        at me.lucko.luckperms.common.messaging.LuckPermsMessagingService.<init>(LuckPermsMessagingService.java:72) ~[LuckPerms-Bukkit-5.2.90.jar:?]
        at me.lucko.luckperms.common.messaging.MessagingFactory.getServiceFor(MessagingFactory.java:106) [LuckPerms-Bukkit-5.2.90.jar:?]
        at me.lucko.luckperms.bukkit.messaging.BukkitMessagingFactory.getServiceFor(BukkitMessagingFactory.java:64) [LuckPerms-Bukkit-5.2.90.jar:?]
        at me.lucko.luckperms.common.messaging.MessagingFactory.getInstance(MessagingFactory.java:84) [LuckPerms-Bukkit-5.2.90.jar:?]
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:157) [LuckPerms-Bukkit-5.2.90.jar:?]
        at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:162) [LuckPerms-Bukkit-5.2.90.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.sql.SQLException: Malformed communication packet
        at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-driver-8.0.22-remapped.jar:8.0.22]
        at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-driver-8.0.22-remapped.jar:8.0.22]
        at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-driver-8.0.22-remapped.jar:8.0.22]
        at me.lucko.luckperms.lib.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:637) ~[mysql-driver-8.0.22-remapped.jar:8.0.22]
        at me.lucko.luckperms.lib.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:418) ~[mysql-driver-8.0.22-remapped.jar:8.0.22]
        at me.lucko.luckperms.lib.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql-driver-8.0.22-remapped.jar:8.0.22]
        at me.lucko.luckperms.lib.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[hikari-3.4.5-remapped.jar:?]
        at me.lucko.luckperms.lib.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[hikari-3.4.5-remapped.jar:?]
        at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.init(AbstractSqlMessenger.java:79) ~[LuckPerms-Bukkit-5.2.90.jar:?]
        at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:55) ~[LuckPerms-Bukkit-5.2.90.jar:?]
        ... 15 more
[10:54:47 WARN]: [LuckPerms] Messaging service 'sql' not recognised.
[10:54:47 INFO]: [LuckPerms] Loading internal permission managers...
[10:54:47 INFO]: [LuckPerms] Performing initial data load...
[10:54:47 WARN]: java.util.concurrent.CompletionException: java.sql.SQLException: Malformed communication packet
[10:54:47 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:105)
[10:54:47 WARN]:        at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
[10:54:47 WARN]:        at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source)
[10:54:47 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[10:54:47 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
[10:54:47 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[10:54:47 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[10:54:47 WARN]: Caused by: java.sql.SQLException: Malformed communication packet
[10:54:47 WARN]:        at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[10:54:47 WARN]:        at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[10:54:47 WARN]:        at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[10:54:47 WARN]:        at me.lucko.luckperms.lib.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:637)
[10:54:47 WARN]:        at me.lucko.luckperms.lib.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:418)
[10:54:47 WARN]:        at me.lucko.luckperms.lib.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
[10:54:47 WARN]:        at me.lucko.luckperms.lib.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[10:54:47 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[10:54:47 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.selectGroups(SqlStorage.java:894)
[10:54:47 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:464)
[10:54:47 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$10(Storage.java:194)
[10:54:47 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:100)
[10:54:47 WARN]:        ... 6 more
[10:54:47 INFO]: [LuckPerms] Successfully enabled. (took 2469ms)
```

**Comment by lucko** [comment]
There's something wrong with your MySQL server, or you've configured it incorrectly.
https://luckperms.net/wiki/Storage-system-errors

That's all I can tell you, sorry.
