### ISSUE TITLE
Issue with Pre-login UUIDs

### ISSUE THREAD

**Issue by JezWalmsley** [lucko/LuckPerms#2839]
I have enabled bungee on all my sponge and spigot servers and enabled IP forwarding

```
WARNING A permission check was made for player UploadKingYT - 56855605-4a13-4fc6-9bfb-07f777ef08a6, but LuckPerms does not have any permissions data loaded for them. Perhaps their UUID has been altered since login?
20.01 09:07:20 [Server] INFO java.lang.Exception
20.01 09:07:20 [Server] INFO at me.lucko.luckperms.bungee.listeners.BungeePermissionCheckListener.onPlayerPermissionCheck(BungeePermissionCheckListener.java:65)
20.01 09:07:20 [Server] INFO at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
20.01 09:07:20 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20.01 09:07:20 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498)
20.01 09:07:20 [Server] INFO at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
20.01 09:07:20 [Server] INFO at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
20.01 09:07:20 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:399)
20.01 09:07:20 [Server] INFO at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:551)
20.01 09:07:20 [Server] INFO at net.md_5.bungee.api.plugin.Command.hasPermission(Command.java:67)
20.01 09:07:20 [Server] INFO at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:635)
20.01 09:07:20 [Server] INFO at net.md_5.bungee.protocol.packet.Commands.handle(Commands.java:231)
20.01 09:07:20 [Server] INFO at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105)
20.01 09:07:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
20.01 09:07:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
20.01 09:07:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
20.01 09:07:20 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
20.01 09:07:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
20.01 09:07:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
20.01 09:07:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
20.01 09:07:20 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
20.01 09:07:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
20.01 09:07:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
20.01 09:07:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
20.01 09:07:20 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
20.01 09:07:20 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
20.01 09:07:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
20.01 09:07:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
20.01 09:07:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
20.01 09:07:20 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
20.01 09:07:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
20.01 09:07:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
20.01 09:07:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
20.01 09:07:20 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
20.01 09:07:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
20.01 09:07:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
20.01 09:07:20 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
20.01 09:07:20 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
20.01 09:07:20 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
20.01 09:07:20 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
20.01 09:07:20 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
20.01 09:07:20 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
20.01 09:07:20 [Server] INFO at java.lang.Thread.run(Thread.java:748)
```

**Comment by lucko** [comment]
In the future, please create issues using one of the available templates: https://github.com/lucko/LuckPerms/issues/new/choose

It makes things much easier, and ensures we have all the information needed.

I suspect the issue is being caused by one of your other plugins altering player UUIDs on login, but since you only included a partial log I can't say for sure.
