### ISSUE TITLE
Luck perms not start in my server (1.7.10) - using version legacy for version 1.7.10

### ISSUE THREAD

**Issue by iAm6oy** [lucko/LuckPerms#2862]
this is the error 
> [23:43:45 INFO]: [LuckPerms] Enabling LuckPerms v5.2.94
> [23:43:45 INFO]: __
> [23:43:45 INFO]: | |__) LuckPerms v5.2.94
> [23:43:45 INFO]: |___ | Running on Bukkit - CraftBukkit
> [23:43:45 INFO]:
> [23:43:45 INFO]: [LuckPerms] Loading configuration...
> [23:43:46 INFO]: [LuckPerms] Loading storage provider... [MYSQL]
> [23:43:46 INFO]: luckperms-hikari - Starting...
> [23:43:46 INFO]: luckperms-hikari - Start completed.
> [23:43:47 INFO]: [LuckPerms] Loading messaging service... [SQL]
> [23:43:48 ERROR]: Error occurred while enabling LuckPerms v5.2.94 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/common/commands/user/UserParentCommand
at me.lucko.luckperms.common.command.CommandManager.<init>(CommandManager.java:93) ~[?:?]
at me.lucko.luckperms.bukkit.BukkitCommandExecutor.<init>(BukkitCommandExecutor.java:68) ~[?:?]
at me.lucko.luckperms.bukkit.LPBukkitPlugin.registerCommands(LPBukkitPlugin.java:156) ~[?:?]
at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:163) ~[?:?]
at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:162) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[server.jar:git-PaperSpigot-ea452ce]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [server.jar:git-PaperSpigot-ea452ce]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [server.jar:git-PaperSpigot-ea452ce]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [server.jar:git-PaperSpigot-ea452ce]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [server.jar:git-PaperSpigot-ea452ce]
at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:170) [server.jar:git-PaperSpigot-ea452ce]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:496) [server.jar:git-PaperSpigot-ea452ce]
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [server.jar:git-PaperSpigot-ea452ce]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.common.commands.user.UserParentCommand
at java.net.URLClassLoader$1.run(URLClassLoader.java:371) ~[?:1.8.0_275]
at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_275]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_275]
at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_275]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-PaperSpigot-ea452ce]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-PaperSpigot-ea452ce]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
... 13 more
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
at java.util.zip.ZipFile.read(Native Method) ~[?:1.8.0_275]
at java.util.zip.ZipFile.access$1400(ZipFile.java:60) ~[?:1.8.0_275]
at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:734) ~[?:1.8.0_275]
at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:434) ~[?:1.8.0_275]
at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:1.8.0_275]
at sun.misc.Resource.getBytes(Resource.java:124) ~[?:1.8.0_275]
at java.net.URLClassLoader.defineClass(URLClassLoader.java:463) ~[?:1.8.0_275]
at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_275]
at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_275]
at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_275]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_275]
at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_275]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-PaperSpigot-ea452ce]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-PaperSpigot-ea452ce]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
... 13 more

**Comment by lucko** [comment]
Try deleting and re-downloading the jar file. Seems like it has been corrupted somehow.
