### ISSUE TITLE
sql leak

### ISSUE THREAD

**Issue by batkins62** [lucko/LuckPerms#287]
Log: https://pastebin.com/sTr8Ls94
stack trace:
[16:18:48 WARN]: [luckperms housekeeper] WARN com.zaxxer.hikari.pool.ProxyLeakTask - Connection leak detection triggered for com.mysql.jdbc.JDBC4Connection@d242ede, stack trace follows
[16:18:48 WARN]: java.lang.Exception: Apparent connection leak detected
[16:18:48 WARN]:        at me.lucko.luckperms.common.storage.backing.sqlprovider.MySQLProvider.getConnection(MySQLProvider.java:118)
[16:18:48 WARN]:        at me.lucko.luckperms.common.storage.backing.SQLBacking.saveGroup(SQLBacking.java:736)
[16:18:48 WARN]:        at me.lucko.luckperms.common.storage.AbstractStorage.lambda$saveGroup$8(AbstractStorage.java:172)
[16:18:48 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[16:18:48 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[16:18:48 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[16:18:48 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[16:18:48 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[16:18:48 WARN]:        at java.lang.Thread.run(Thread.java:748)
[16:18:49 WARN]: [Craft Scheduler Thread - 26] INFO com.zaxxer.hikari.pool.ProxyLeakTask - Previously reported leaked connection com.mysql.jdbc.JDBC4Connection@d242ede was returned to the pool (unleaked)

**Comment by lucko** [comment]
```
[16:18:49 WARN]: [Craft Scheduler Thread - 26] INFO com.zaxxer.hikari.pool.ProxyLeakTask - Previously reported leaked connection com.mysql.jdbc.JDBC4Connection@d242ede was returned to the pool (unleaked)
```

Not an issue. I guess your server must've lagged for a second, which caused a false positive.
