### ISSUE TITLE
java.lang.NoClassDefFoundError: com/imaginarycode/minecraft/redisbungee/RedisBungee

### ISSUE THREAD

**Issue by MisterAssm** [lucko/LuckPerms#2981]
I am using on my RedisBungee server, problem is that when I run ANY COMMAND, I get a classNotFoundException.

I am using the latest version of LuckpermsBungeecord, LuckPerms v5.3.21
On the latest version of Bungeecord

```
20:03:56 [INFO] CONSOLE executed command: /lpb creategroup admin Admin
20:03:56 [INFO] [LP] admin was successfully created.
20:03:56 [WARNING] [LuckPerms] An exception was thrown by me.lucko.luckperms.bungee.context.RedisBungeeCalculator whilst calculating static contexts
java.lang.NoClassDefFoundError: com/imaginarycode/minecraft/redisbungee/RedisBungee
    at me.lucko.luckperms.bungee.context.RedisBungeeCalculator.calculate(RedisBungeeCalculator.java:45)
    at me.lucko.luckperms.common.context.ContextManager.calculateStatic(ContextManager.java:146)
    at me.lucko.luckperms.common.context.ContextManager.access$000(ContextManager.java:52)
    at me.lucko.luckperms.common.context.ContextManager$StaticLookupCache.supply(ContextManager.java:179)
    at me.lucko.luckperms.common.context.ContextManager$StaticLookupCache.supply(ContextManager.java:172)
    at me.lucko.luckperms.common.cache.ExpiringCache.get(ExpiringCache.java:64)
    at me.lucko.luckperms.common.context.ContextManager.getStaticQueryOptions(ContextManager.java:90)
    at me.lucko.luckperms.common.context.ContextManager.getStaticContext(ContextManager.java:94)
    at me.lucko.luckperms.common.sender.Sender.getNameWithLocation(Sender.java:79)
    at me.lucko.luckperms.common.actionlog.LoggedAction$Builder.source(LoggedAction.java:296)
    at me.lucko.luckperms.common.commands.group.CreateGroup.execute(CreateGroup.java:107)
    at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:56)
    at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:48)
    at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:264)
    at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:166)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.imaginarycode.minecraft.redisbungee.RedisBungee
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    ... 19 more
20:03:56 [WARNING] [LuckPerms] An exception was thrown by me.lucko.luckperms.bungee.context.RedisBungeeCalculator whilst calculating the context of subject GregouTim
java.lang.NoClassDefFoundError: com/imaginarycode/minecraft/redisbungee/RedisBungee
    at me.lucko.luckperms.bungee.context.RedisBungeeCalculator.calculate(RedisBungeeCalculator.java:45)
    at net.luckperms.api.context.StaticContextCalculator.calculate(StaticContextCalculator.java:73)
    at me.lucko.luckperms.common.context.ContextManager.calculate(ContextManager.java:131)
    at me.lucko.luckperms.lib.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:141)
    at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2344)
    at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
    at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2342)
    at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2325)
    at me.lucko.luckperms.lib.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
    at me.lucko.luckperms.lib.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:54)
    at me.lucko.luckperms.bungee.context.BungeeContextManager.getQueryOptions(BungeeContextManager.java:73)
    at me.lucko.luckperms.bungee.listeners.BungeePermissionCheckListener.onPlayerPermissionCheck(BungeePermissionCheckListener.java:72)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:412)
    at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:551)
    at me.lucko.luckperms.bungee.BungeeSenderFactory.hasPermission(BungeeSenderFactory.java:76)
    at me.lucko.luckperms.bungee.BungeeSenderFactory.hasPermission(BungeeSenderFactory.java:40)
    at me.lucko.luckperms.common.sender.AbstractSender.hasPermission(AbstractSender.java:99)
    at me.lucko.luckperms.common.sender.Sender.hasPermission(Sender.java:137)
    at me.lucko.luckperms.common.command.access.CommandPermission.isAuthorized(CommandPermission.java:193)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
    at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:313)
    at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
    at me.lucko.luckperms.common.actionlog.LogDispatcher.broadcast(LogDispatcher.java:75)
    at me.lucko.luckperms.common.actionlog.LogDispatcher.dispatch(LogDispatcher.java:86)
    at me.lucko.luckperms.common.actionlog.LoggedAction.submit(LoggedAction.java:136)
    at me.lucko.luckperms.common.commands.group.CreateGroup.execute(CreateGroup.java:109)
    at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:56)
    at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:48)
    at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:264)
    at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:166)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by galexrt** [comment]
Same here with LuckPerms v5.3.21 on Waterfall build 405.

The following exceptions are being spammed over and over again when a user joins and plays on any server:

```
[12:29:49 WARN] [LuckPerms]: An exception was thrown by me.lucko.luckperms.bungee.context.RedisBungeeCalculator whilst calculating the context of subject Galexrt
java.lang.NoClassDefFoundError: com/imaginarycode/minecraft/redisbungee/RedisBungee
	at me.lucko.luckperms.bungee.context.RedisBungeeCalculator.calculate(RedisBungeeCalculator.java:45) ~[?:?]
	at net.luckperms.api.context.StaticContextCalculator.calculate(StaticContextCalculator.java:73) ~[?:?]
	at me.lucko.luckperms.common.context.ContextManager.calculate(ContextManager.java:131) ~[?:?]
	at me.lucko.luckperms.lib.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:141) ~[?:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2369) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1932) ~[?:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2342) ~[?:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2325) ~[?:?]
	at me.lucko.luckperms.lib.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108) ~[?:?]
	at me.lucko.luckperms.lib.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:54) ~[?:?]
	at me.lucko.luckperms.bungee.context.BungeeContextManager.getQueryOptions(BungeeContextManager.java:73) ~[?:?]
	at me.lucko.luckperms.bungee.listeners.BungeePermissionCheckListener.onPlayerPermissionCheck(BungeePermissionCheckListener.java:72) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor18.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:573) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at ultrastaffchatpro.K68gCGc2nu.hasP(SourceFile:20) ~[?:?]
	at ultrastaffchatpro.ta5TFVLxMe.onLeave(SourceFile:22) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at net.md_5.bungee.connection.UpstreamBridge.disconnected(UpstreamBridge.java:66) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at net.md_5.bungee.netty.HandlerBoss.channelInactive(HandlerBoss.java:60) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:819) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9aecc59:405]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[12:29:49 WARN] [LuckPerms]: An exception was thrown by me.lucko.luckperms.bungee.context.RedisBungeeCalculator whilst calculating static contexts
java.lang.NoClassDefFoundError: com/imaginarycode/minecraft/redisbungee/RedisBungee
	at me.lucko.luckperms.bungee.context.RedisBungeeCalculator.calculate(RedisBungeeCalculator.java:45) ~[?:?]
	at me.lucko.luckperms.common.context.ContextManager.calculateStatic(ContextManager.java:146) ~[?:?]
	at me.lucko.luckperms.common.context.ContextManager.access$000(ContextManager.java:52) ~[?:?]
	at me.lucko.luckperms.common.context.ContextManager$StaticLookupCache.supply(ContextManager.java:179) ~[?:?]
	at me.lucko.luckperms.common.context.ContextManager$StaticLookupCache.supply(ContextManager.java:172) ~[?:?]
	at me.lucko.luckperms.common.cache.ExpiringCache.get(ExpiringCache.java:64) ~[?:?]
	at me.lucko.luckperms.common.context.ContextManager.getStaticQueryOptions(ContextManager.java:90) ~[?:?]
	at me.lucko.luckperms.common.api.implementation.ApiContextManager.getStaticQueryOptions(ApiContextManager.java:98) ~[?:?]
	at com.djrapitops.extension.LuckPermsExtension.getMetaData(LuckPermsExtension.java:160) ~[?:?]
	at com.djrapitops.extension.LuckPermsExtension.prefix(LuckPermsExtension.java:128) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.djrapitops.plan.extension.implementation.providers.Parameters$PlayerParameters.usingOn(Parameters.java:97) ~[?:?]
	at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:48) ~[?:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer$Gatherer.gather(ProviderValueGatherer.java:195) ~[?:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer$Gatherer.gather(ProviderValueGatherer.java:185) ~[?:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer.updateValues(ProviderValueGatherer.java:152) ~[?:?]
	at com.djrapitops.plan.extension.ExtensionSvc.updatePlayerValues(ExtensionSvc.java:158) ~[?:?]
	at com.djrapitops.plan.extension.ExtensionSvc.updatePlayerValues(ExtensionSvc.java:149) ~[?:?]
	at com.djrapitops.plan.gathering.listeners.bungee.PlayerOnlineListener.lambda$beforeLogout$3(PlayerOnlineListener.java:130) ~[?:?]
	at com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by thenilsdev** [comment]
Same here. Thought it was due to the switch to Docker but seems to be a general problem

```
[03:10:01 INFO]: [LP] Running LuckPerms v5.3.3 by Luck.
[03:10:01 INFO]: [LP] -  Platform: BungeeCord
[03:10:01 INFO]: [LP] -  Server Brand: Waterfall
[03:10:01 INFO]: [LP] -  Server Version:
[03:10:01 INFO]: [LP]      git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:004e802:406
[03:10:01 INFO]: [LP] -  Storage:
[03:10:01 INFO]: [LP]      Type: MongoDB
[03:10:01 INFO]: [LP]      Ping: 4ms
[03:10:01 INFO]: [LP]      Connected: true
[03:10:01 INFO]: [LP] -  Extensions:
[03:10:01 INFO]: [LP]      None
[03:10:01 INFO]: [LP] -  Messaging: Redis
[03:10:01 INFO]: [LP] -  Instance:
[03:10:01 INFO]: [LP]      Static contexts: (server=proxy)
[03:10:01 INFO]: [LP]      Online Players: 1 (1 unique)
[03:10:01 INFO]: [LP]      Uptime: 2m 52s
[03:10:01 INFO]: [LP]      Local Data: 1 users, 62 groups, 4 tracks
```

```
[03:09:11 INFO]: NilsDev executed command: /lpb
[03:09:11 WARN] [LuckPerms]: An exception was thrown by me.lucko.luckperms.bungee.context.RedisBungeeCalculator whilst calculating the context of subject NilsDev
java.lang.NoClassDefFoundError: com/imaginarycode/minecraft/redisbungee/RedisBungee
        at me.lucko.luckperms.bungee.context.RedisBungeeCalculator.calculate(RedisBungeeCalculator.java:45) ~[?:?]
        at net.luckperms.api.context.StaticContextCalculator.calculate(StaticContextCalculator.java:73) ~[?:?]
        at me.lucko.luckperms.common.context.ContextManager.calculate(ContextManager.java:131) ~[?:?]
        at me.lucko.luckperms.lib.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:141) ~[?:?]
        at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2369) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877) ~[?:1.8.0_212]
        at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2342) ~[?:?]
        at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2325) ~[?:?]
        at me.lucko.luckperms.lib.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108) ~[?:?]
        at me.lucko.luckperms.lib.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:54) ~[?:?]
        at me.lucko.luckperms.bungee.context.BungeeContextManager.getQueryOptions(BungeeContextManager.java:73) ~[?:?]
        at me.lucko.luckperms.bungee.listeners.BungeePermissionCheckListener.onPlayerPermissionCheck(BungeePermissionCheckListener.java:72) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[Waterfall-1.16-406.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:004e802:406]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[Waterfall-1.16-406.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:004e802:406]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[Waterfall-1.16-406.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:004e802:406]
        at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:573) ~[Waterfall-1.16-406.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:004e802:406]
        at me.lucko.luckperms.bungee.BungeeSenderFactory.hasPermission(BungeeSenderFactory.java:76) ~[?:?]
        at me.lucko.luckperms.bungee.BungeeSenderFactory.hasPermission(BungeeSenderFactory.java:40) ~[?:?]
        at me.lucko.luckperms.common.sender.AbstractSender.hasPermission(AbstractSender.java:99) ~[?:?]
        at me.lucko.luckperms.common.sender.Sender.hasPermission(Sender.java:137) ~[?:?]
        at me.lucko.luckperms.common.command.access.CommandPermission.isAuthorized(CommandPermission.java:193) ~[?:?]
        at me.lucko.luckperms.common.command.abstraction.Command.isAuthorized(Command.java:187) ~[?:?]
        at me.lucko.luckperms.common.command.abstraction.ParentCommand.lambda$isAuthorized$17(ParentCommand.java:181) ~[?:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:1.8.0_212]
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[?:1.8.0_212]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_212]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_212]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_212]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:1.8.0_212]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:1.8.0_212]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449) ~[?:1.8.0_212]
        at me.lucko.luckperms.common.command.abstraction.ParentCommand.isAuthorized(ParentCommand.java:181) ~[?:?]
        at me.lucko.luckperms.common.command.CommandManager.lambda$hasPermissionForAny$4(CommandManager.java:179) ~[?:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:1.8.0_212]
        at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:302) ~[?:1.8.0_212]
        at com.google.common.collect.CollectSpliterators$1WithCharacteristics.tryAdvance(CollectSpliterators.java:60) ~[Waterfall-1.16-406.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:004e802:406]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_212]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_212]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_212]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:1.8.0_212]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:1.8.0_212]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449) ~[?:1.8.0_212]
        at me.lucko.luckperms.common.command.CommandManager.hasPermissionForAny(CommandManager.java:179) ~[?:?]
        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:196) ~[?:?]
        at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:150) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_212]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[Waterfall-1.16-406.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:004e802:406]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by lucko** [comment]
Which version of RedisBungee are you using?

**Comment by galexrt** [comment]
@lucko RedisBungee `0.6-SNAPSHOT` from here https://www.spigotmc.org/resources/redisbungee.87700/ / https://github.com/Limework/RedisBungee

**Comment by lucko** [comment]
Seems like that fork has broken API compatibility in some way.. I've added an extra check to try to work around that.

**Comment by ham1255** [comment]
> Seems like that fork has broken API compatibility in some way.. I've added an extra check to try to work around that.

in that fork i did not change the api any shape or form i just added option ssl? but it seems like luckperms have issue for example after the error it seems gone tried both old one + fork i made which is 0.6 on limework org

**Comment by ham1255** [comment]
from what i see on bungee gradlew file it uses 0.4 `com.imaginarycode.minecraft:RedisBungee:0.4` and last version of redis bungee when dev quit developing it is 0.5

**Comment by ham1255** [comment]
this should be closed now since it was merged!

**Comment by lucko** [comment]
Sweet, thanks for the heads up!

In which case, yep, make sure you update BungeeCord to latest & things should work!
