### ISSUE TITLE
Redis pubsub connection dropped, trying to re-open the connection

### ISSUE THREAD

**Issue by junebug12851** [lucko/LuckPerms#2998]
### Description
I've setup a managed Redis database through DigitalOcean, it has the default username, a password, a host address and custom port.

I entered this in the config.yml

```yml
# Settings for Redis.
# Port 6379 is used by default; set address to "host:port" if differs
redis:
  enabled: true
  address: "host:port"
  password: "###"
```

and this error floods my console

```
[01:46:53 WARN]: [LuckPerms] Redis pubsub connection dropped, trying to re-open the connection
me.lucko.luckperms.lib.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
        at me.lucko.luckperms.lib.jedis.util.Pool.getResource(Pool.java:59) ~[?:?]
        at me.lucko.luckperms.lib.jedis.JedisPool.getResource(JedisPool.java:288) ~[?:?]
        at me.lucko.luckperms.common.messaging.redis.RedisMessenger$Subscription.run(RedisMessenger.java:91) ~[?:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: me.lucko.luckperms.lib.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
        at me.lucko.luckperms.lib.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:202) ~[?:?]
        at me.lucko.luckperms.lib.jedis.util.RedisInputStream.readByte(RedisInputStream.java:43) ~[?:?]
        at me.lucko.luckperms.lib.jedis.Protocol.process(Protocol.java:155) ~[?:?]
        at me.lucko.luckperms.lib.jedis.Protocol.read(Protocol.java:220) ~[?:?]
        at me.lucko.luckperms.lib.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:278) ~[?:?]
        at me.lucko.luckperms.lib.jedis.Connection.getStatusCodeReply(Connection.java:196) ~[?:?]
        at me.lucko.luckperms.lib.jedis.BinaryJedis.auth(BinaryJedis.java:2269) ~[?:?]
        at me.lucko.luckperms.lib.jedis.JedisFactory.makeObject(JedisFactory.java:134) ~[?:?]
        at me.lucko.luckperms.lib.commonspool2.impl.GenericObjectPool.create(GenericObjectPool.java:899) ~[?:?]
        at me.lucko.luckperms.lib.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429) ~[?:?]
        at me.lucko.luckperms.lib.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:354) ~[?:?]
        at me.lucko.luckperms.lib.jedis.util.Pool.getResource(Pool.java:50) ~[?:?]
        ... 8 more
```

I can't seem to find any help on this

### Environment details

* Server type/version: `Paper` running version `1.16.5` build `585`
* LuckPerms version: `v5.3.21`

**Comment by lucko** [comment]
Does it connect initially then drop out later, or never connect?

The latter would indicate perhaps some sort of firewall problem or misconfiguration. The former sounds like an issue either with the Jedis or perhaps a problem with your Redis server timing out.
