### ISSUE TITLE
Error netty io on join player to the server on waterfall

### ISSUE THREAD

**Issue by steveq7** [lucko/LuckPerms#3019]
player join to the server - waterfall #415

Error:

[15:33:22] [Netty Worker IO Thread #18/WARN] [LuckPerms]: A permission check was made for player LavishKK - 269bd77d-c867-30c2-96a5-aa9eec454a29, but LuckPerms does not have any permissions data loaded for them. Perhaps their UUID has been altered since login?
java.lang.Exception: null
	at me.lucko.luckperms.bungee.listeners.BungeePermissionCheckListener.onPlayerPermissionCheck(BungeePermissionCheckListener.java:65) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor40.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:573) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at dev.jaqobb.abps.listener.PlayerChatListener.onPlayerChat(PlayerChatListener.java:29) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor153.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:155) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:81) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at com.lahuca.botsentry.bungee.m.channelRead(Unknown Source) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e28d922:415]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by lucko** [comment]
Please don't ignore the template... it's there for a reason.
