### ISSUE TITLE
Getting ready for Java 16

### ISSUE THREAD

**Issue by Grizzly90** [lucko/LuckPerms#3022]
As mojang announced, that the latest snapshot requires Java 16 and some projects already announced, also push to Java 16 you maybe need to have a look at this exception: 

22:54:49 WARN]: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @8b7e800
[22:54:49 WARN]:     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[22:54:49 WARN]:     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[22:54:49 WARN]:     at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
[22:54:49 WARN]:     at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
[22:54:49 WARN]:     at me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader.lambda$new$0(ReflectionClassLoader.java:64)

**Comment by emilyy-dev** [comment]
1. Please, **do not ignore** the issue template!
2. Update LuckPerms https://luckperms.net/download
