### ISSUE TITLE
error when player joins the server

### ISSUE THREAD

**Issue by LOLEMO** [lucko/LuckPerms#3066]
when a player joins my server i have this error in the console and i can't use luckperms in the game
`[10:00:35 INFO]: UUID of player emo14 is 4bac439d-34d2-39bf-8e44-c7601dd8fffe
[10:00:35 ERROR]: Could not pass event PlayerJoinEvent to LuckPerms v5.3.3
java.lang.NoSuchMethodError: us.myles.ViaVersion.api.Via.getManager()Lus/myles/ViaVersion/ViaManager;
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitFacet$ViaHook.apply(BukkitFacet.java:346) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitFacet$ViaHook.apply(BukkitFacet.java:343) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.viaversion.ViaFacet.findConnection(ViaFacet.java:92) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.viaversion.ViaFacet.findProtocol(ViaFacet.java:96) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.viaversion.ViaFacet.isApplicable(ViaFacet.java:88) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.facet.Facet.of(Facet.java:97) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.facet.FacetAudience.<init>(FacetAudience.java:90) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudience.<init>(BukkitAudience.java:78) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:162) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:71) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.facet.FacetAudienceProvider.lambda$addViewer$0(FacetAudienceProvider.java:76) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_282]
        at me.lucko.luckperms.lib.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:75) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$new$3(BukkitAudiencesImpl.java:101) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$registerEvent$5(BukkitAudiencesImpl.java:215) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [server.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [server.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346) [server.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) [server.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [server.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [server.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [server.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [server.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [server.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]`

**Comment by lucko** [comment]
Update to the latest version
