### ISSUE TITLE
IllegalStateException repeatedly in log

### ISSUE THREAD

**Issue by SlimeDog** [lucko/LuckPerms#3079]
### Description

Spigot 1.17-3149
One of these every 30 seconds on a quiescent server (ie., no players connected):
```
[17:01:11] [ForkJoinPool-3-worker-53/WARN]: java.lang.RuntimeException: Exception occurred whilst generating event instance
[17:01:11] [ForkJoinPool-3-worker-53/WARN]:     at me.lucko.luckperms.common.event.EventDispatcher.generate(EventDispatcher.java:122)
[17:01:11] [ForkJoinPool-3-worker-53/WARN]:     at me.lucko.luckperms.common.event.EventDispatcher.post(EventDispatcher.java:127)
[17:01:11] [ForkJoinPool-3-worker-53/WARN]:     at me.lucko.luckperms.common.event.EventDispatcher.lambda$postAsync$0(EventDispatcher.java:143)
[17:01:11] [ForkJoinPool-3-worker-53/WARN]:     at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434)
[17:01:11] [ForkJoinPool-3-worker-53/WARN]:     at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[17:01:11] [ForkJoinPool-3-worker-53/WARN]:     at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[17:01:11] [ForkJoinPool-3-worker-53/WARN]:     at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[17:01:11] [ForkJoinPool-3-worker-53/WARN]:     at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[17:01:11] [ForkJoinPool-3-worker-53/WARN]:     at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[17:01:11] [ForkJoinPool-3-worker-53/WARN]: Caused by: java.lang.RuntimeException: java.lang.BootstrapMethodError: java.lang.IllegalStateException: zip file closed
[17:01:11] [ForkJoinPool-3-worker-53/WARN]:     at me.lucko.luckperms.common.event.gen.GeneratedEventClass.lambda$static$0(GeneratedEventClass.java:70)
[17:01:11] [ForkJoinPool-3-worker-53/WARN]:     at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
[17:01:11] [ForkJoinPool-3-worker-53/WARN]:     at me.lucko.luckperms.common.cache.LoadingMap.get(LoadingMap.java:67)
[17:01:11] [ForkJoinPool-3-worker-53/WARN]:     at me.lucko.luckperms.common.event.gen.GeneratedEventClass.generate(GeneratedEventClass.java:81)
[17:01:11] [ForkJoinPool-3-worker-53/WARN]:     at me.lucko.luckperms.common.event.EventDispatcher.generate(EventDispatcher.java:120)
[17:01:11] [ForkJoinPool-3-worker-53/WARN]:     ... 8 more
[17:01:11] [ForkJoinPool-3-worker-53/WARN]: Caused by: java.lang.BootstrapMethodError: java.lang.IllegalStateException: zip file closed
[17:01:11] [ForkJoinPool-3-worker-53/WARN]:     at me.lucko.luckperms.common.event.gen.GeneratedEventClass.<init>(GeneratedEventClass.java:120)
[17:01:11] [ForkJoinPool-3-worker-53/WARN]:     at me.lucko.luckperms.common.event.gen.GeneratedEventClass.lambda$static$0(GeneratedEventClass.java:68)
[17:01:11] [ForkJoinPool-3-worker-53/WARN]:     ... 12 more
```

### Reproduction steps

1. Upgrade to LuckPerms 5.3.48
2. Restart the server
3. Observe errors in console log

### Expected behaviour

No errors

### Environment details

* Server type/version: `Spigot 1.17-3149`
* LuckPerms version: `5.3.48`

Default config.yml with the following exceptions:
```
storage-method: yaml
messaging-service: none
push-log-entries: false
broadcast-received-log-entries: false
log-notify: false
apply-default-negated-permissions-before-wildcards: true
enable-ops: false
auto-op: true
```

**Comment by SlimeDog** [comment]
WARNings have disappeared with Spigot 1.17-3151. Leaving the issue open for someone to decide if that change makes sense.

**Comment by emilyy-dev** [comment]
Have you run `/reload` on the server or used "plugman" to reload LuckPerms?

**Comment by SlimeDog** [comment]
Of course not!

**Comment by SlimeDog** [comment]
This was opened in early days of 1.17. Changes to Spigot and/or other plugins resolved the issue. It has not recurred.
