### ISSUE TITLE
i got an issue with editor and applying 

### ISSUE THREAD

**Issue by RIPISDRAD** [lucko/LuckPerms#3087]
hey there 1.16.5
there isthis error while editing
```
[19:21:09] [Server thread/INFO]: RIPISDEAD issued server command: /lp editor
[19:21:19] [ForkJoinPool-1-worker-1/WARN]: [LuckPerms] Command execution [editor] has not completed. Trace: 
  java.base@16.0.1/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
  java.base@16.0.1/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
  java.base@16.0.1/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
  java.base@16.0.1/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
  java.base@16.0.1/java.net.InetAddress.getAllByName0(Unknown Source)
  java.base@16.0.1/java.net.InetAddress.getAllByName(Unknown Source)
  java.base@16.0.1/java.net.InetAddress.getAllByName(Unknown Source)
  me.lucko.luckperms.lib.okhttp3.Dns.lambda$static$0(Dns.java:39)
  me.lucko.luckperms.lib.okhttp3.Dns$$Lambda$4696/0x0000000801932cb0.lookup(Unknown Source)
  me.lucko.luckperms.lib.okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:171)
  me.lucko.luckperms.lib.okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:135)
  me.lucko.luckperms.lib.okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:187)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
  me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
  me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
  me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
  me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:78)
  me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:98)
  me.lucko.luckperms.common.webeditor.WebEditorRequest.createSession(WebEditorRequest.java:175)
  me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:111)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:56)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:48)
  me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:236)
  me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:150)
  me.lucko.luckperms.common.command.CommandManager$$Lambda$7610/0x0000000802314000.get(Unknown Source)
  java.base@16.0.1/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
  java.base@16.0.1/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
  java.base@16.0.1/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
  java.base@16.0.1/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
  java.base@16.0.1/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
  java.base@16.0.1/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
  java.base@16.0.1/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: java.lang.RuntimeException: Error uploading data to bytebin
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.common.webeditor.WebEditorRequest.createSession(WebEditorRequest.java:180)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:111)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:56)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:48)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:236)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:150)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: Caused by: java.net.UnknownHostException: No such host is known (bytebin.lucko.me)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.lib.okhttp3.Dns.lambda$static$0(Dns.java:39)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:171)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:135)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:187)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:78)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:98)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	at me.lucko.luckperms.common.webeditor.WebEditorRequest.createSession(WebEditorRequest.java:175)
[19:21:21] [ForkJoinPool-1-worker-53/WARN]: 	... 12 more
```

**Comment by lucko** [comment]
Try setting your machines DNS server to use Google/Cloudflare instead, use `8.8.8.8` or `1.1.1.1`

**Comment by RIPISDRAD** [comment]
Tnx man it get solved after updating
