### ISSUE TITLE
Could not pass event PlayerCommandPreprocessEvent to LuckPerms v5.3.47 error

### ISSUE THREAD

**Issue by Wiseared** [lucko/LuckPerms#3097]
Hello, today I came across this error on my server running luckperms. This error happens when you just run "/". As error message it gives me:

```
[Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to LuckPerms v5.3.47
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [server.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [server.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1391) [server.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1234) [server.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-dcd1643-e60fc34]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_292]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_292]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-dcd1643-e60fc34]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at bukkit.metrics.craftbukkit._b.pc(_b.java:48) ~[server.jar:git-Spigot-dcd1643-e60fc34]
	at sun.reflect.GeneratedMethodAccessor129.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-dcd1643-e60fc34]
	... 16 more
```

Hopefully this gets fixed soon, if I did anything wrong let me know so I can change version or whatever.

**Comment by lucko** [comment]
Either you're using a non-standard server jar, or you have a plugin that is doing something very strange with event listeners.

`bukkit.metrics.craftbukkit._b.pc` should not be there, no idea where it came from though.
