### ISSUE TITLE
Crash on startup on Paper 1.17.1

### ISSUE THREAD

**Issue by EggAllocationService** [lucko/LuckPerms#3099]
### Description

Starting the server will result in LuckPerms spamming console with `IllegalStateException: zip file closed` when checking permission nodes in plugins. The server will then crash when finished loading with the following exception:
```
Description: Exception in server tick loop

java.lang.IllegalStateException: zip file closed
        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:828)
        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:327)
        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:513)
        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:573)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        at me.lucko.luckperms.bukkit.inject.server.LuckPermsSubscriptionMap.get(LuckPermsSubscriptionMap.java:87)
        at me.lucko.luckperms.bukkit.inject.server.LuckPermsSubscriptionMap.get(LuckPermsSubscriptionMap.java:65)
        at org.bukkit.plugin.SimplePluginManager.getPermissionSubscriptions(SimplePluginManager.java:834)
        at org.bukkit.permissions.Permission.getPermissibles(Permission.java:159)
        at org.bukkit.permissions.Permission.recalculatePermissibles(Permission.java:169)
        at org.bukkit.permissions.Permission.<init>(Permission.java:68)
        at org.bukkit.permissions.Permission.<init>(Permission.java:32)
        at org.bukkit.util.permissions.DefaultPermissions.registerPermission(DefaultPermissions.java:49)
        at org.bukkit.util.permissions.DefaultPermissions.registerCorePermissions(DefaultPermissions.java:87)
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:443)
        at app//net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
        at app//net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306)
        at app//net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126)
        at app//net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

### Reproduction steps
1. Install luckperms 5.3.51 on paper 1.17.1 build 90
2. start server
3. server crashes

### Expected behaviour

Server doesn't crash

### Environment details

* OS: Ubuntu 18.04
* Java: Amazon Coretto 16.0.1
* Server type/version: `Paper 1.17.1 build 90`
* LuckPerms version: `5.3.51 (latest at time of submission)`

**Comment by HauserGrim** [comment]
Full log please.

**Comment by lucko** [comment]
Please try updating Paper to a newer build

**Comment by Wastinqs** [comment]
same here and I don't want to update because most of my plugins run on 1.17.1 paper on java17. So what are available solutions for this?

My server just restarts and tries to enable luckperms, then it freezes and shuts down.....

06.08 13:36:41 [Server] INFO Enabling LuckPerms v5.4.41
06.08 13:39:34 [Multicraft] Received stop command
06.08 13:39:34 [Multicraft] Stopping server!
06.08 13:40:45 [Multicraft] Terminating server via signal
06.08 13:41:45 [Multicraft] Forcefully killing server
06.08 13:41:56 [Multicraft] Failed to kill server! (PID: 27130) It might have been shut down in the mean time, otherwise please try to end it manually.
06.08 13:41:59 [Multicraft] Server stopped
