### ISSUE TITLE
ClassNotFoundException: com.mysql.jdbc.jdbc2.optional.MysqlDataSource

### ISSUE THREAD

**Issue by Eufranio** [lucko/LuckPerms#31]
I can't load LuckPerms in my Sponge server, I get that error in startup:
```
[22:31:24] [Server thread/ERROR] [Sponge/sponge]: Could not pass FMLPreInitializationEvent to Plugin{id=luckperms, name=LuckPerms, version=2.12.19, description=A permissions plugin, authors=[Luck], source=/home/fracica/SERVIDOR/Teste/mods/LuckPermsSponge-2.12.19.jar}
java.lang.RuntimeException: java.lang.ClassNotFoundException: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
	at me.lucko.luckperms.lib.hikari.util.UtilityElf.createInstance(UtilityElf.java:90) ~[UtilityElf.class:?]
	at me.lucko.luckperms.lib.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:314) ~[PoolBase.class:?]
	at me.lucko.luckperms.lib.hikari.pool.PoolBase.<init>(PoolBase.java:108) ~[PoolBase.class:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool.<init>(HikariPool.java:99) ~[HikariPool.class:?]
	at me.lucko.luckperms.lib.hikari.HikariDataSource.<init>(HikariDataSource.java:71) ~[HikariDataSource.class:?]
	at me.lucko.luckperms.common.storage.methods.MySQLDatastore.init(MySQLDatastore.java:80) ~[MySQLDatastore.class:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_91]
	at me.lucko.luckperms.common.storage.SplitDatastore.init(SplitDatastore.java:49) ~[SplitDatastore.class:?]
	at me.lucko.luckperms.common.storage.StorageFactory.getDatastore(StorageFactory.java:80) ~[StorageFactory.class:?]
	at me.lucko.luckperms.sponge.LPSpongePlugin.onEnable(LPSpongePlugin.java:137) ~[LPSpongePlugin.class:?]
	at org.spongepowered.common.event.listener.GamePreInitializationEventListener_LPSpongePlugin_onEnable6.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2098-5.1.0-BETA-1814]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:356) [SpongeModEventManager.class:1.10.2-2098-5.1.0-BETA-1814]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:397) [SpongeModEventManager.class:1.10.2-2098-5.1.0-BETA-1814]
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:227) [SpongeMod.class:1.10.2-2098-5.1.0-BETA-1814]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzd000(LoadController.java:53) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) [ld.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
	at me.lucko.luckperms.lib.hikari.util.UtilityElf.createInstance(UtilityElf.java:77) ~[UtilityElf.class:?]
	... 42 more
```
I configured LuckPerms to run with MySQL, and I have the driver, I have an other 1.7.10 server running and other plugin that uses that driver, then...)
Running LuckPermsSponge-2.12.19, on a 1.10.2 Sponge server.
SpongeForge version: 1.10.2-2098-5.1.0-BETA-1814
Forge version: 1.10.2-12.18.2.2107

**Comment by Eufranio** [comment]
Thanks, nice work! 😄

**Comment by lucko** [comment]
Ya, thank you for reminding me! 

Somebody told me about this weeks ago, and I just completely forgot about it. As far as I know, in the pre API 5.0.0 releases, the connector was provided in the server jar, but I guess not anymore. 😄 

I tested briefly and it seems to work. :)
