### ISSUE TITLE
cant use lp editor

### ISSUE THREAD

**Issue by aboodjun** [lucko/LuckPerms#3102]
### Description

whenever i use the command /lp edior this error pops up and i cant use it
``` BigWillyBilly69 issued server command: /lp editor
[05:22:04] [luckperms-scheduler-worker-2/WARN]: [LuckPerms] Command execution [editor] has not completed. Trace: 
  java.base@11/java.net.PlainSocketImpl.socketConnect(Native Method)
  java.base@11/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
  java.base@11/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
  java.base@11/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
  java.base@11/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
  java.base@11/java.net.Socket.connect(Socket.java:591)
  me.lucko.luckperms.lib.okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
  me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
  me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
  me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
  me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
  me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
  me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:78)
  me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:98)
  me.lucko.luckperms.common.webeditor.WebEditorRequest.createSession(WebEditorRequest.java:174)
  me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:55)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:47)
  me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:262)
  me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:166)
  me.lucko.luckperms.common.command.CommandManager$$Lambda$6646/0x0000000801b21840.run(Unknown Source)
  java.base@11/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
  java.base@11/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  java.base@11/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  java.base@11/java.lang.Thread.run(Thread.java:834)
[05:22:09] [luckperms-command-executor/WARN]: java.lang.RuntimeException: Error uploading data to bytebin
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.common.webeditor.WebEditorRequest.createSession(WebEditorRequest.java:179)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:55)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:47)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:262)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:166)
[05:22:09] [luckperms-command-executor/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
[05:22:09] [luckperms-command-executor/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[05:22:09] [luckperms-command-executor/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[05:22:09] [luckperms-command-executor/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[05:22:09] [luckperms-command-executor/WARN]: Caused by: java.io.InterruptedIOException: timeout
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.timeoutExit(Transmitter.java:109)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.maybeReleaseConnection(Transmitter.java:302)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.noMoreExchanges(Transmitter.java:267)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:237)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:78)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:98)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.common.webeditor.WebEditorRequest.createSession(WebEditorRequest.java:174)
[05:22:09] [luckperms-command-executor/WARN]: 	... 9 more
[05:22:09] [luckperms-command-executor/WARN]: Caused by: java.net.SocketException: Socket closed
[05:22:09] [luckperms-command-executor/WARN]: 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:403)
[05:22:09] [luckperms-command-executor/WARN]: 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
[05:22:09] [luckperms-command-executor/WARN]: 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
[05:22:09] [luckperms-command-executor/WARN]: 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
[05:22:09] [luckperms-command-executor/WARN]: 	at java.base/java.net.Socket.connect(Socket.java:591)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[05:22:09] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
[05:22:09] [luckperms-command-executor/WARN]: 	... 14 more
```
and sometimes when i do /lp reloadconfig it works 

### Reproduction steps

i did /lp editor
1. Open the config.yml file and set example to true.
2. Restart the server
3. Run /lp user example permission set x from the console

### Expected behaviour

to open editor

### Environment details

1.16.5
* Server type/version: `ExampleSpigot` running version `1.12.2` build `???`
* LuckPerms version: `v???`
1.16.5 spigot , latest version

**Comment by lucko** [comment]
Your server can't connect to bytebin - the content storage facility used by the editor.

Are you sure it has an available internet connection? Perhaps a firewall rule is blocking it?
