### ISSUE TITLE
Errors on Velocity

### ISSUE THREAD

**Issue by SlimeDog** [lucko/LuckPerms#3114]
### Description

- Errors on Velocity start-up (see below)
- The permissions tree is empty (only root .)

### Reproduction steps

1. Install Velocity and LuckPerms-Velocity
2. Restart the proxy
3. Run /lp tree
4. Tree is empty https://luckperms.net/treeview/V1GdGW1vdd
5. See errors below

### Environment details

* Server type/version: `Velocity 3.0.0`
* LuckPerms version: `LuckPerms-Velocity-5.3.53`

```
[10:21:05] [main/INFO]: Loaded plugin luckperms 5.3.53 by Luck
[10:21:06] [Velocity Async Event Executor - #0/INFO]:   |    |__)   LuckPerms v5.3.53
[10:21:06] [Velocity Task Scheduler - #5/INFO]: Intercepted connection to metadata.luckperms.net
[10:21:06] [Velocity Task Scheduler - #5/INFO]: Intercepted connection to metadata.luckperms.net
[10:21:06] [Velocity Task Scheduler - #5/INFO]: Intercepted connection to metadata.luckperms.net (104.26.15.192)
[10:21:06 INFO] [luckperms]: Performing initial data load...
[10:21:06 ERROR]: java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'me.lucko.luckperms.lib.configurate.yaml.YAMLConfigurationLoader$Builder me.lucko.luckperms.lib.configurate.yaml.YAMLConfigurationLoader$Builder.setFlowStyle(me.lucko.luckperms.lib.yaml.DumperOptions$FlowStyle)'
[10:21:06 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
[10:21:06 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
[10:21:06 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1803)
[10:21:06 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:203)
[10:21:06 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[10:21:06 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[10:21:06 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:831)
[10:21:06 ERROR]: Caused by: java.lang.NoSuchMethodError: 'me.lucko.luckperms.lib.configurate.yaml.YAMLConfigurationLoader$Builder me.lucko.luckperms.lib.configurate.yaml.YAMLConfigurationLoader$Builder.setFlowStyle(me.lucko.luckperms.lib.yaml.DumperOptions$FlowStyle)'
[10:21:06 ERROR]:       at me.lucko.luckperms.common.storage.implementation.file.loader.YamlLoader.loader(YamlLoader.java:43)
[10:21:06 ERROR]:       at me.lucko.luckperms.common.storage.implementation.file.SeparatedConfigurateStorage.readFile(SeparatedConfigurateStorage.java:119)
[10:21:06 ERROR]:       at me.lucko.luckperms.common.storage.implementation.file.SeparatedConfigurateStorage.readFile(SeparatedConfigurateStorage.java:108)
[10:21:06 ERROR]:       at me.lucko.luckperms.common.storage.implementation.file.AbstractConfigurateStorage.loadGroup(AbstractConfigurateStorage.java:255)
[10:21:06 ERROR]:       at me.lucko.luckperms.common.util.Iterators.tryIterate(Iterators.java:41)
[10:21:06 ERROR]:       at me.lucko.luckperms.common.storage.implementation.file.SeparatedConfigurateStorage.loadAllGroups(SeparatedConfigurateStorage.java:307)
[10:21:06 ERROR]:       at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$10(Storage.java:194)
[10:21:06 ERROR]:       at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:100)
[10:21:06 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
[10:21:06 ERROR]:       ... 4 more
```

### Any other relevant details

plugins/luckperms/config.yml
```
server: global
use-server-uuid-cache: false
storage-method: yaml
data:
  address: localhost
  database: minecraft
  username: root
  password: ''
  pool-settings:
    maximum-pool-size: 10
    minimum-idle: 10
    maximum-lifetime: 1800000 # 30 minutes
    keepalive-time: 0
    connection-timeout: 5000 # 5 seconds
    properties:
      useUnicode: true
      characterEncoding: utf8
  table-prefix: 'luckperms_'
  mongodb-collection-prefix: ''
  mongodb-connection-uri: ''
split-storage:
  enabled: false
  methods:
    user: h2
    group: h2
    track: h2
    uuid: h2
    log: h2
sync-minutes: -1
watch-files: true
messaging-service: none
auto-push-updates: true
push-log-entries: false
broadcast-received-log-entries: false
redis:
  enabled: false
  address: localhost
  password: ''
rabbitmq:
  enabled: false
  address: localhost
  vhost: '/'
  username: 'guest'
  password: 'guest'
temporary-add-behaviour: deny
primary-group-calculation: parents-by-weight
argument-based-command-permissions: false
require-sender-group-membership-to-modify: false
log-notify: false
log-notify-filtered-descriptions:
auto-install-translations: true
meta-formatting:
  prefix:
    format:
      - "highest"
    duplicates: first-only
    start-spacer: ""
    middle-spacer: " "
    end-spacer: ""
  suffix:
    format:
      - "highest"
    duplicates: first-only
    start-spacer: ""
    middle-spacer: " "
    end-spacer: ""
inheritance-traversal-algorithm: depth-first-pre-order
post-traversal-inheritance-sort: false
context-satisfy-mode: at-least-one-value-per-key
disabled-contexts:
include-global: true
include-global-world: true
apply-global-groups: true
apply-global-world-groups: true
meta-value-selection-default: inheritance
meta-value-selection:
apply-wildcards: true
apply-sponge-implicit-wildcards: false
apply-default-negated-permissions-before-wildcards: true
apply-regex: true
apply-shorthand: true
apply-bukkit-child-permissions: true
apply-bukkit-default-permissions: true
apply-bukkit-attachment-permissions: true
world-rewrite:
  world_nether: world
  world_the_end: world
  world_blackdog_nether: world_blackdog
  world_blackdog_the_end: world_blackdog
  world_city_nether: world_city
  world_city_the_end: world_city
  world_skyblock_nether: world_skyblock
  world_skyblock_the_end: world_skyblock
  world_whitedog_nether: world_whitedog
  world_whitedog_the_end: world_whitedog
  world_yellowdog_nether: world_yellowdog
  world_yellowdog_the_end: world_yellowdog
group-weight:
enable-ops: false
auto-op: true
commands-allow-op: true
vault-unsafe-lookups: false
vault-group-use-displaynames: true
vault-npc-group: default
vault-npc-op-status: false
use-vault-server: false
vault-server: global
vault-include-global: true
vault-ignore-world: false
debug-logins: false
allow-invalid-usernames: false
skip-bulkupdate-confirmation: false
prevent-primary-group-removal: false
update-client-command-list: true
register-command-list-data: true
resolve-command-selectors: false
colored-logger: false
```

**Comment by nayneyT** [comment]
Hi.

LuckPerms for velocity uses the lpv command tree.

However, velocity v3 is not working for me yet. There is an issue out for it already to be updated to work with v3.

**Comment by SlimeDog** [comment]
Just for the record, the error still occurs with the latest `3.0.0/dev` build `(3.0.1-b51)` released two days ago.

**Comment by lucko** [comment]
I can't reproduce:

<img width="1156" alt="Screenshot 2021-07-30 at 10 12 46" src="https://user-images.githubusercontent.com/8352868/127630769-ead4fd3f-a527-401a-8305-a3fda180300b.png">

https://luckperms.net/treeview/R5EEhvOm6e

(you need to trigger some permission checks before the tree will be populated with some entries)

**Comment by SlimeDog** [comment]
Velocity 3.0.1-b52

tree produced by `lpv tree`
https://luckperms.net/treeview/gTPQ2imKiz

**Comment by lucko** [comment]
Still can't reproduce even using 3.0.1-SNAPSHOT.

Could you try deleting the `/plugins/luckperms/libs` directory then restarting your proxy. Did you perhaps copy that over from a Bukkit server?

**Comment by SlimeDog** [comment]
> Could you try deleting the `/plugins/luckperms/libs` directory then restarting your proxy. Did you perhaps copy that over from a Bukkit server?

I did -- not very wise. Problem resolved. Thanks.
