### ISSUE TITLE
Databse in use Error

### ISSUE THREAD

**Issue by GamerCoder215** [lucko/LuckPerms#3117]
### Description

I got this error after using CrazyAdvancementsAPI
```
5.07 12:24:57 [Server] ERROR Exception occurred whilst loading data for 8069233e-5b25-410c-9475-daa6a044c365 - GamerCoder215
25.07 12:24:57 [Server] INFO java.util.concurrent.CompletionException: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-199]
25.07 12:24:57 [Server] INFO at me.lucko.luckperms.common.storage.Storage.lambda$future$0(Storage.java:92) ~[?:?]
25.07 12:24:57 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
25.07 12:24:57 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) ~[?:?]
25.07 12:24:57 [Server] INFO at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
25.07 12:24:57 [Server] INFO at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
25.07 12:24:57 [Server] INFO at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
25.07 12:24:57 [Server] INFO at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
25.07 12:24:57 [Server] INFO at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
25.07 12:24:57 [Server] INFO Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-199]
```

### Reproduction steps

1. Install CrazyAdvancementsAPI
2. Reload server
3. Logout
4. When you try to rejoin, database error

### Expected behaviour

Normal Server

### Environment details

* Server type/version: `PaperMC` running version `1.17.1` 
* LuckPerms version: `v5.3.53`

**Comment by benwoo1110** [comment]
Always restart the server, do no reload.
