### ISSUE TITLE
Redis pubsub connection dropped

### ISSUE THREAD

**Issue by weihao** [lucko/LuckPerms#3150]
```
nginx_1       | 192.168.128.1 [31/Aug/2021:11:58:47 +0000] TCP 200 5 35 600.100 "192.168.128.2:6379" "35" "5" "0.000"
nginx_1       | 192.168.128.1 [31/Aug/2021:11:58:52 +0000] TCP 200 51 77 600.006 "192.168.128.2:6379" "77" "51" "0.000"
bungeecord_1  | [11:58:52 WARN] [LuckPerms]: Redis pubsub connection dropped, trying to re-open the connection
bungeecord_1  | me.lucko.luckperms.lib.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
bungeecord_1  |         at me.lucko.luckperms.lib.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:202) ~[?:?]
bungeecord_1  |         at me.lucko.luckperms.lib.jedis.util.RedisInputStream.readByte(RedisInputStream.java:43) ~[?:?]
bungeecord_1  |         at me.lucko.luckperms.lib.jedis.Protocol.process(Protocol.java:155) ~[?:?]
bungeecord_1  |         at me.lucko.luckperms.lib.jedis.Protocol.read(Protocol.java:220) ~[?:?]
bungeecord_1  |         at me.lucko.luckperms.lib.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:283) ~[?:?]
bungeecord_1  |         at me.lucko.luckperms.lib.jedis.Connection.getUnflushedObjectMultiBulkReply(Connection.java:245) ~[?:?]
bungeecord_1  |         at me.lucko.luckperms.lib.jedis.JedisPubSub.process(JedisPubSub.java:131) ~[?:?]
bungeecord_1  |         at me.lucko.luckperms.lib.jedis.JedisPubSub.proceed(JedisPubSub.java:125) ~[?:?]
bungeecord_1  |         at me.lucko.luckperms.lib.jedis.Jedis.subscribe(Jedis.java:2898) ~[?:?]
bungeecord_1  |         at me.lucko.luckperms.common.messaging.redis.RedisMessenger$Subscription.run(RedisMessenger.java:96) ~[?:?]
bungeecord_1  |         at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[Waterfall-1.17-448.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
bungeecord_1  |         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
bungeecord_1  |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
bungeecord_1  |         at java.lang.Thread.run(Unknown Source) [?:?]
bungeecord_1  | [11:58:57 INFO] [LuckPerms]: Redis pubsub connection re-established
```

Jedis connect initially then drop out later. Can the stacktrace be hidden?

**Comment by lucko** [comment]
I don't see the benefit of hiding the stack trace - it is useful for debugging and isn't doing any harm? :p

**Comment by weihao** [comment]
Make a feature flag and set the log level if it is useful. This is spamming my logs every minute and my setup has multiple instances of bungeecord and servers.
