### ISSUE TITLE
Unable to open the web editor

### ISSUE THREAD

**Issue by FZDNSZYT** [lucko/LuckPerms#3157]
Tips in the game: Cannot communicate with the network editor, check the console for errors.
Error report when starting the web editor:
```
[LuckPerms] Command execution [editor] has not completed. Trace: 
  java.base@16.0.2/sun.nio.ch.Net.poll(Native Method)
  java.base@16.0.2/sun.nio.ch.NioSocketImpl.park(NioSocketImpl.java:181)
  java.base@16.0.2/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:548)
  java.base@16.0.2/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
  java.base@16.0.2/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
  java.base@16.0.2/java.net.Socket.connect(Socket.java:645)
  me.lucko.luckperms.lib.okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
  me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
  me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
  me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
  me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
  me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
  me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:78)
  me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:98)
  me.lucko.luckperms.common.webeditor.WebEditorRequest.createSession(WebEditorRequest.java:174)
  me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:55)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:47)
  me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:262)
  me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:166)
  me.lucko.luckperms.common.command.CommandManager$$Lambda$7155/0x000000080222f6a8.run(Unknown Source)
  java.base@16.0.2/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
  java.base@16.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
  java.base@16.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
  java.base@16.0.2/java.lang.Thread.run(Thread.java:831)
[14:15:31 WARN]: java.lang.RuntimeException: Error uploading data to bytebin
[14:15:31 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorRequest.createSession(WebEditorRequest.java:179)
[14:15:31 WARN]:        at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
[14:15:31 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:55)
[14:15:31 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:47)
[14:15:31 WARN]:        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:262)
[14:15:31 WARN]:        at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:166)
[14:15:31 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
[14:15:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[14:15:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[14:15:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[14:15:31 WARN]: Caused by: java.io.InterruptedIOException: timeout
[14:15:31 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.timeoutExit(Transmitter.java:109)
[14:15:31 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.maybeReleaseConnection(Transmitter.java:302)
[14:15:31 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.noMoreExchanges(Transmitter.java:267)
[14:15:31 WARN]:        at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:237)
[14:15:31 WARN]:        at me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
[14:15:31 WARN]:        at me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
[14:15:31 WARN]:        at me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:78)
[14:15:31 WARN]:        at me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:98)
[14:15:31 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorRequest.createSession(WebEditorRequest.java:174)
[14:15:31 WARN]:        ... 9 more
[14:15:31 WARN]: Caused by: java.io.IOException: Canceled
[14:15:31 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:82)
[14:15:31 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[14:15:31 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[14:15:31 WARN]:        at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
[14:15:31 WARN]:        ... 14 more
```

**Comment by ky678** [comment]
I have the same problem, someone please help

**Comment by FZDNSZYT** [comment]
I asked someone to check the error log and the link timed out. It may be that the Luck Perms server has crashed.

**Comment by Crrack404** [comment]
I have the issue, too. And the issue is still exists until now.

**Comment by juzijun233** [comment]
same question

**Comment by lucko** [comment]
Please provide some screenshots of the command output, any editor links (if any) it gives you, and your console logs.

**Comment by ky678** [comment]
I think it was an internet issue for me because I fixed the issue by using a vpn(I am in China so the server might have been blocked)

**Comment by juzijun233** [comment]
> 
> 
> Please provide some screenshots of the command output, any editor links (if any) it gives you, and your console logs.

https://paste.helpch.at/raw/qipacihifo

**Comment by yuanling-origin** [comment]
> Please provide some screenshots of the command output, any editor links (if any) it gives you, and your console logs.
Its logs are as follows:

```
[16:00:25 INFO]: [LP] Preparing a new editor session, please wait...
[16:00:35 WARN]: [LuckPerms] Command execution [editor] has not completed. Trace: 
  java.base@16.0.2/sun.nio.ch.Net.poll(Native Method)
  java.base@16.0.2/sun.nio.ch.NioSocketImpl.park(NioSocketImpl.java:181)
  java.base@16.0.2/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:548)
  java.base@16.0.2/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
  java.base@16.0.2/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
  java.base@16.0.2/java.net.Socket.connect(Socket.java:645)
  me.lucko.luckperms.lib.okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
  me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
  me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
  me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
  me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
  me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
  me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:78)
  me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:98)
  me.lucko.luckperms.common.webeditor.WebEditorRequest.createSession(WebEditorRequest.java:174)
  me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:55)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:47)
  me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:262)
  me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:166)
  me.lucko.luckperms.common.command.CommandManager$$Lambda$6152/0x0000000802093448.run(Unknown Source)
  java.base@16.0.2/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
  java.base@16.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
  java.base@16.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
  java.base@16.0.2/java.lang.Thread.run(Thread.java:831)
[16:00:40 WARN]: java.lang.RuntimeException: Error uploading data to bytebin
[16:00:40 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorRequest.createSession(WebEditorRequest.java:179)
[16:00:40 WARN]:        at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
[16:00:40 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:55)
[16:00:40 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:47)
[16:00:40 WARN]:        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:262)
[16:00:40 WARN]:        at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:166)
[16:00:40 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
[16:00:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[16:00:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[16:00:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[16:00:40 WARN]: Caused by: java.io.InterruptedIOException: timeout
[16:00:40 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.timeoutExit(Transmitter.java:109)
[16:00:40 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.maybeReleaseConnection(Transmitter.java:302)
[16:00:40 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.noMoreExchanges(Transmitter.java:267)
[16:00:40 WARN]:        at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:237)
[16:00:40 WARN]:        at me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
[16:00:40 WARN]:        at me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
[16:00:40 WARN]:        at me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:78)
[16:00:40 WARN]:        at me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:98)
[16:00:40 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorRequest.createSession(WebEditorRequest.java:174)
[16:00:40 WARN]:        ... 9 more
[16:00:40 WARN]: Caused by: java.io.IOException: Canceled
[16:00:40 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:82)
[16:00:40 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[16:00:40 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[16:00:40 WARN]:        at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
[16:00:40 WARN]:        ... 14 more
[16:00:40 INFO]: [LP] Unable to communicate with the editor. Check the console for errors.
```

**Comment by FZDNSZYT** [comment]
The log I posted is the error log displayed on the console after I use the command "/lp editor". It is in yellow font. It was still available a few days ago, and the URL of the web editor cannot be popped up since yesterday.

**Comment by FZDNSZYT** [comment]
This problem occurred yesterday, that is, on September 8. The server was restarted and there was no other error reported. The web editor error cannot be repaired.

**Comment by FZDNSZYT** [comment]
> 我认为这是一个互联网问题对我来说， 因为我修复了这个问题使用 vpn （我在中国， 所以服务器可能已被阻止）

"VPN" does not fix this error, I have tried it.

**Comment by FZDNSZYT** [comment]
> > 请提供命令输出的一些屏幕截图、它为您提供的任何编辑器链接（如果有）以及您的控制台日志。
> 
> 重新：
> 其日志如下：
> 
> ```
> [16:00:25 INFO]: [LP] Preparing a new editor session, please wait...
> [16:00:35 WARN]: [LuckPerms] Command execution [editor] has not completed. Trace: 
>   java.base@16.0.2/sun.nio.ch.Net.poll(Native Method)
>   java.base@16.0.2/sun.nio.ch.NioSocketImpl.park(NioSocketImpl.java:181)
>   java.base@16.0.2/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:548)
>   java.base@16.0.2/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
>   java.base@16.0.2/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
>   java.base@16.0.2/java.net.Socket.connect(Socket.java:645)
>   me.lucko.luckperms.lib.okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
>   me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
>   me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
>   me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
>   me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
>   me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
>   me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
>   me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
>   me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>   me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
>   me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
>   me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>   me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
>   me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
>   me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>   me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
>   me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>   me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
>   me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
>   me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
>   me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
>   me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:78)
>   me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:98)
>   me.lucko.luckperms.common.webeditor.WebEditorRequest.createSession(WebEditorRequest.java:174)
>   me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
>   me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:55)
>   me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:47)
>   me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:262)
>   me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:166)
>   me.lucko.luckperms.common.command.CommandManager$$Lambda$6152/0x0000000802093448.run(Unknown Source)
>   java.base@16.0.2/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
>   java.base@16.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
>   java.base@16.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
>   java.base@16.0.2/java.lang.Thread.run(Thread.java:831)
> [16:00:40 WARN]: java.lang.RuntimeException: Error uploading data to bytebin
> [16:00:40 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorRequest.createSession(WebEditorRequest.java:179)
> [16:00:40 WARN]:        at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
> [16:00:40 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:55)
> [16:00:40 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:47)
> [16:00:40 WARN]:        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:262)
> [16:00:40 WARN]:        at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:166)
> [16:00:40 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
> [16:00:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
> [16:00:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
> [16:00:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
> [16:00:40 WARN]: Caused by: java.io.InterruptedIOException: timeout
> [16:00:40 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.timeoutExit(Transmitter.java:109)
> [16:00:40 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.maybeReleaseConnection(Transmitter.java:302)
> [16:00:40 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.noMoreExchanges(Transmitter.java:267)
> [16:00:40 WARN]:        at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:237)
> [16:00:40 WARN]:        at me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
> [16:00:40 WARN]:        at me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
> [16:00:40 WARN]:        at me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:78)
> [16:00:40 WARN]:        at me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:98)
> [16:00:40 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorRequest.createSession(WebEditorRequest.java:174)
> [16:00:40 WARN]:        ... 9 more
> [16:00:40 WARN]: Caused by: java.io.IOException: Canceled
> [16:00:40 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:82)
> [16:00:40 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> [16:00:40 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> [16:00:40 WARN]:        at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
> [16:00:40 WARN]:        ... 14 more
> [16:00:40 INFO]: [LP] Unable to communicate with the editor. Check the console for errors.
> ```

It’s almost exactly the same as my problem, the connection timed out

**Comment by yuanling-origin** [comment]
Issue solved when I connect to US proxy server by VPN, so I think Luckperms editor's Internet connecting process is blocked, excatly.

**Comment by klskk23** [comment]
I have the issue, too.And the issue solved when I connect to US proxy server by VPN

**Comment by lucko** [comment]
All of those logs indicate that the connection to bytebin (the service LuckPerms and the editor uses to store/transmit data) is being blocked.

Unfortunately not an issue I can fix at my end, the access control settings are already as minimal as possible.

**Comment by juzijun233** [comment]
> 
> 
> All of those logs indicate that the connection to bytebin (the service LuckPerms and the editor uses to store/transmit data) is being blocked.
> 
> Unfortunately not an issue I can fix at my end, the access control settings are already as minimal as possible.

Which sites does the plug-in need to visit? I try to add it to the VPN settings

**Comment by Turbotailz** [comment]
The URL is https://bytebin.lucko.me/

Alternatively you may consider hosting the web service yourself:
https://github.com/LuckPerms/web-installer
