### ISSUE TITLE
Error -> Messaging service.

### ISSUE THREAD

**Issue by RiDiCage** [lucko/LuckPerms#3159]
I'm trying to set up luckperms with minecraft spigot server 1.17.1 but I keep getting the following error (see serverlog below).

```
This server is running
CraftBukkit version: 3238-Spigot-6c1c1b2-9217b52
MC: 1.17.1
Implementing API version: 1.17.1-R0.1-SNAPSHOT
```

It doesn't matter what I do. The messaging service stays on and keeps saying that these attempts are not recognized in config.yml
( SQL / sql / MySQL / mysql ).

I have tried luckperms bukkit and bukkit legacy and both get the same error.

What can I do to fix this error?

```
[Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.3.65
[Server thread/INFO]: LuckPerms v5.3.65
[Server thread/INFO]: Running on Bukkit - CraftBukkit
[Server thread/INFO]: [LuckPerms] Loading configuration...
[Server thread/INFO]: [LuckPerms] Loading storage provider... [MYSQL]
[Server thread/INFO]: luckperms-hikari - Starting...
[Server thread/INFO]: luckperms-hikari - Start completed.
[Server thread/INFO]: [LuckPerms] Loading messaging service... [SQL]
[Server thread/ERROR]: [LuckPerms] Exception occurred whilst enabling SQL messaging service java.lang.RuntimeException: java.sql.SQLException: Malformed communication packet at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:57)
~[?:?] at me.lucko.luckperms.common.messaging.MessagingFactory$SqlMessengerProvider.obtain(MessagingFactory.java:191)
~[?:?] at me.lucko.luckperms.common.messaging.LuckPermsMessagingService.<init>(LuckPermsMessagingService.java:71)
~[?:?] at me.lucko.luckperms.common.messaging.MessagingFactory.getServiceFor(MessagingFactory.java:121)
~[?:?] at me.lucko.luckperms.bukkit.messaging.BukkitMessagingFactory.getServiceFor(BukkitMessagingFactory.java:64)
~[?:?] at me.lucko.luckperms.common.messaging.MessagingFactory.getInstance(MessagingFactory.java:89)
~[?:?] at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:164)
~[?:?] at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:175)
~[?:?] at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:51)
~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
~[server.jar:3238-Spigot-6c1c1b2-9217b52] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
~[server.jar:3238-Spigot-6c1c1b2-9217b52] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
~[server.jar:3238-Spigot-6c1c1b2-9217b52] at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:511)
~[server.jar:3238-Spigot-6c1c1b2-9217b52] at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:425)
~[server.jar:3238-Spigot-6c1c1b2-9217b52] at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:234)
~[server.jar:3238-Spigot-6c1c1b2-9217b52] at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010)
~[server.jar:3238-Spigot-6c1c1b2-9217b52] at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305)
~[server.jar:3238-Spigot-6c1c1b2-9217b52] at java.lang.Thread.run(Thread.java:831) [?:?] Caused by: java.sql.SQLException: Malformed communication packet at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
~[?:?] at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
~[?:?] at me.lucko.luckperms.lib.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:637)
~[?:?] at me.lucko.luckperms.lib.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:418)
~[?:?] at me.lucko.luckperms.lib.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
~[?:?] at me.lucko.luckperms.lib.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
~[?:?] at me.lucko.luckperms.lib.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
~[?:?] at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.init(AbstractSqlMessenger.java:79)
~[?:?] at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:55)
~[?:?] ... 17 more
[Server thread/WARN]: [LuckPerms] Messaging service 'sql' not recognised.
[Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[Server thread/INFO]: [LuckPerms] Performing initial data load...
[Server thread/WARN]: java.util.concurrent.CompletionException: java.sql.SQLException: Malformed communication packet
[Server thread/WARN]: at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:106)
[Server thread/WARN]: at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
[Server thread/WARN]: at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792)
[Server thread/WARN]: at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[Server thread/WARN]: at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[Server thread/WARN]: at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[Server thread/WARN]: at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[Server thread/WARN]: at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[Server thread/WARN]: Caused by: java.sql.SQLException: Malformed communication packet
[Server thread/WARN]: at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[Server thread/WARN]: at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[Server thread/WARN]: at me.lucko.luckperms.lib.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:637)
[Server thread/WARN]: at me.lucko.luckperms.lib.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:418)
[Server thread/WARN]: at me.lucko.luckperms.lib.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
[Server thread/WARN]: at me.lucko.luckperms.lib.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[Server thread/WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[Server thread/WARN]: at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.selectGroups(SqlStorage.java:909)
[Server thread/WARN]: at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:468)
[Server thread/WARN]: at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$10(Storage.java:195)
[Server thread/WARN]: at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:101)
[Server thread/WARN]: ... 7 more
[Server thread/INFO]: [LuckPerms] Successfully enabled. (took 1437ms)
```

**Comment by RiDiCage** [comment]
I found a way that works for me.
Instead of storage-method MySQL, set to MariaDB and enter the port of MySQL (3306) after the hostname.

```
storage-method: MariaDB

data:
	# address: Domainname or IP address : MySQLpoort
	address: 192.168.1.1:3306
	
	# database: Databasename
	database: luckperms_minecraft
	
	# username: your MySQL username for the database
	# password: your MySQL password for the database
```
