### ISSUE TITLE
startup: Error loading locale file: id_ID.properties

### ISSUE THREAD

**Issue by mrfloris** [lucko/LuckPerms#3165]
### Description

The other day when 5.3.67 came out I've /stop and replaced the jar and started the server. I didn't notice it then, but now I did when I did a stop and start today and spotted the startup error regarding locale file.

```
[11:19:57 INFO]: [LuckPerms] Enabling LuckPerms v5.3.67
[11:19:58 INFO]:         __
[11:19:58 INFO]:   |    |__)   LuckPerms v5.3.67
[11:19:58 INFO]:   |___ |      Running on Bukkit - Paper
[11:19:58 INFO]:
[11:19:58 INFO]: [LuckPerms] Loading configuration...
[11:19:58 INFO]: [LuckPerms] Loading storage provider... [H2]
[11:19:58 INFO]: [LuckPerms] Loading internal permission managers...
[11:19:59 INFO]: [LuckPerms] Performing initial data load...
[11:19:59 INFO]: [LuckPerms] Successfully enabled. (took 1411ms)
[11:19:59 INFO]: [LimitPillagers] Enabling LimitPillagers v3.0.1
[11:19:59 INFO]: [LimitPillagers] Registering commands...
[11:19:59 INFO]: [LimitPillagers] Registering listeners...
[11:19:59 INFO]: [LimitPillagers] Loading config.yml...
[11:19:59 INFO]: [LimitPillagers] Registering metrics...
[11:19:59 INFO]: [LimitPillagers] Done and enabled in 13,08ms
[11:19:59 INFO]: [Vault] Enabling Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[11:19:59 WARN]: [Vault] Loaded class com.Zrips.CMI.Modules.Economy.Economy from CMI v9.0.4.1 which is not a depend, softdepend or loadbefore of this plugin.
[11:19:59 INFO]: [Vault] [Economy] CMI Economy found: Waiting
[11:19:59 WARN]: [LuckPerms] Error loading locale file: id_ID.properties
java.lang.IllegalArgumentException: Invalid key (and 377 more)
        at me.lucko.luckperms.lib.adventure.translation.TranslationRegistry.registerAll(TranslationRegistry.java:216) ~[?:?]
        at me.lucko.luckperms.lib.adventure.translation.TranslationRegistry.registerAll(TranslationRegistry.java:179) ~[?:?]
        at me.lucko.luckperms.common.locale.TranslationManager.loadCustomTranslationFile(TranslationManager.java:161) ~[?:?]
        at me.lucko.luckperms.common.locale.TranslationManager.loadCustom(TranslationManager.java:125) ~[?:?]
        at me.lucko.luckperms.common.locale.TranslationManager.reload(TranslationManager.java:92) ~[?:?]
        at me.lucko.luckperms.common.locale.TranslationRepository.downloadAndInstallTranslations(TranslationRepository.java:199) ~[?:?]
        at me.lucko.luckperms.common.locale.TranslationRepository.refresh(TranslationRepository.java:137) ~[?:?]
        at me.lucko.luckperms.common.locale.TranslationRepository.lambda$scheduleRefresh$0(TranslationRepository.java:96) ~[?:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.IllegalArgumentException: Translation already exists: luckperms.command.misc.loading.error.user for id_ID
        at me.lucko.luckperms.lib.adventure.translation.TranslationRegistryImpl$Translation.register(TranslationRegistryImpl.java:120) ~[?:?]
        at me.lucko.luckperms.lib.adventure.translation.TranslationRegistryImpl.register(TranslationRegistryImpl.java:52) ~[?:?]
        at me.lucko.luckperms.lib.adventure.translation.TranslationRegistry.registerAll(TranslationRegistry.java:203) ~[?:?]
        ... 13 more
[11:19:59 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[11:19:59 WARN]: [LuckPerms] Error loading locale file: iw_IL.properties
java.lang.IllegalArgumentException: Invalid key (and 309 more)
        at me.lucko.luckperms.lib.adventure.translation.TranslationRegistry.registerAll(TranslationRegistry.java:216) ~[?:?]
        at me.lucko.luckperms.lib.adventure.translation.TranslationRegistry.registerAll(TranslationRegistry.java:179) ~[?:?]
        at me.lucko.luckperms.common.locale.TranslationManager.loadCustomTranslationFile(TranslationManager.java:161) ~[?:?]
        at me.lucko.luckperms.common.locale.TranslationManager.loadCustom(TranslationManager.java:125) ~[?:?]
        at me.lucko.luckperms.common.locale.TranslationManager.reload(TranslationManager.java:92) ~[?:?]
        at me.lucko.luckperms.common.locale.TranslationRepository.downloadAndInstallTranslations(TranslationRepository.java:199) ~[?:?]
        at me.lucko.luckperms.common.locale.TranslationRepository.refresh(TranslationRepository.java:137) ~[?:?]
        at me.lucko.luckperms.common.locale.TranslationRepository.lambda$scheduleRefresh$0(TranslationRepository.java:96) ~[?:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.IllegalArgumentException: Translation already exists: luckperms.command.misc.loading.error.user for he_IL
        at me.lucko.luckperms.lib.adventure.translation.TranslationRegistryImpl$Translation.register(TranslationRegistryImpl.java:120) ~[?:?]
        at me.lucko.luckperms.lib.adventure.translation.TranslationRegistryImpl.register(TranslationRegistryImpl.java:52) ~[?:?]
        at me.lucko.luckperms.lib.adventure.translation.TranslationRegistry.registerAll(TranslationRegistry.java:203) ~[?:?]
        ... 13 more
[11:19:59 INFO]: [Vault] Enabled Version 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[11:19:59 INFO]: [LuckPerms] Registered Vault permission & chat hook.
```

### Reproduction steps

I can reproduce it with /stop and start, but that doesn't help you. We have a few years of data and updates, and even imported data. I've never had any issues. After the last jar update when I restart I get an invalid key and it spits out an error. 

### Expected behaviour

To not have an issue with a language file I am not using.

### Environment details

```
> ver
[11:33:59 INFO]: Checking version, please wait...
[11:33:59 INFO]: This server is running Paper version git-Paper-266 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 0d19cd7)
You are running the latest version
Previous version: git-Paper-265 (MC: 1.17.1)
> ver LuckPerms
[11:34:02 INFO]: LuckPerms version 5.3.67
[11:34:02 INFO]: A permissions plugin
[11:34:02 INFO]: Website: https://luckperms.net
[11:34:02 INFO]: Author: Luck
>

<!-- If you think it would be helpful, please also include a "pastebin" of any relevant config files or log output. You should use https://gist.github.com/ to upload, then include the link below. -->


### Any other relevant details
<!-- Please include any other relevant details in the space below. -->

I never use a language file or configure one, we use the default, and we want english. I've never touched this particular file it complained about.

Maybe relevant that we're on Java17, who knows.. though it wasn't an issue before.
```
openjdk 17 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)
```

**Comment by lucko** [comment]
Thanks - the easiest fix is to just delete the `plugins/LuckPerms/translations/` directory and allow it to be regenerated. :)

I've made some changes to minimise the error, so the full stack trace is no longer displayed.
