### ISSUE TITLE
I have a Problem my Server Crashes-

### ISSUE THREAD

**Issue by gsichtheft** [lucko/LuckPerms#3173]
[20:37:34 WARN]: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 15722ms.
[20:37:34 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[20:37:34 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:151)
[20:37:34 WARN]:        at me.lucko.luckperms.common.messaging.sql.SqlMessenger.getConnection(SqlMessenger.java:85)
[20:37:34 WARN]:        at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.pollMessages(AbstractSqlMessenger.java:96)
[20:37:34 WARN]:        at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$ErrorReportingRunnable.run(AbstractJavaScheduler.java:124)
[20:37:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[20:37:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[20:37:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
[20:37:34 WARN]: Caused by: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
[20:37:34 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:37:34 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[20:37:34 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:37:34 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1897)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1217)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[20:37:34 WARN]:        at jdk.internal.reflect.GeneratedConstructorAccessor128.newInstance(Unknown Source)
[20:37:34 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:37:34 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:725)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:711)
[20:37:34 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[20:37:34 WARN]:        ... 3 more
[20:37:34 WARN]: Caused by: java.net.SocketException: Connection attempt exceeded defined timeout.
[20:37:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.StandardSocketFactory.resetLoginTimeCountdown(StandardSocketFactory.java:249)
[20:37:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.StandardSocketFactory.afterHandshake(StandardSocketFactory.java:90)
>
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-14-thread-2"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Spigot Metrics Thread"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "luckperms-scheduler-worker-260"
[20:37:34 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1895)
[20:37:34 WARN]:        ... 24 more

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "Craft Scheduler Thread - 1717"
[21:35:55 WARN]:        ... 9 more

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Craft Scheduler Thread - 10296"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Craft Scheduler Thread - 10298"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Thread-115"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "luckperms-scheduler-worker-264"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "luckperms-scheduler-worker-267"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "luckperms-scheduler-worker-265"

Its not the Memory it has enough and its also not the HDD space and also not the login data to the MySQL

**Comment by gsichtheft** [comment]
What I forgot to say is that this happens like 10- 20 Hours after the Server has Started

**Comment by benwoo1110** [comment]
https://luckperms.net/wiki/Storage-system-errors
