### ISSUE TITLE
Error in BungeeCord Version: LuckPerms-Bungee-3.2.20

### ISSUE THREAD

**Issue by PabloGamer380YT** [lucko/LuckPerms#332]
18:27:58 [WARNING] Exception encountered when loading plugin: LuckPerms
java.lang.NoSuchMethodError: net.md_5.bungee.config.Configuration.contains(Ljava/lang/String;)Z
	at me.lucko.luckperms.bungee.BungeeConfig.contains(BungeeConfig.java:80)
	at me.lucko.luckperms.common.config.ConfigKeys.lambda$static$0(ConfigKeys.java:116)
	at me.lucko.luckperms.common.config.keys.AbstractKey.get(AbstractKey.java:41)
	at me.lucko.luckperms.common.config.AbstractConfiguration.lambda$new$0(AbstractConfiguration.java:42)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache$UnboundedLocalLoadingCache.lambda$new$0(UnboundedLocalCache.java:922)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.lambda$computeIfAbsent$2(UnboundedLocalCache.java:235)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.computeIfAbsent(UnboundedLocalCache.java:231)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:67)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at me.lucko.luckperms.common.config.AbstractConfiguration.loadAll(AbstractConfiguration.java:58)
	at me.lucko.luckperms.bungee.LPBungeePlugin.onEnable(LPBungeePlugin.java:132)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:267)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by EmanYm** [comment]
What version Forge?
Spigot, Bukkit or Sponge?
What version Bungeecord?
What version LuckPerms-Bungee

Make sure the versions match across the board.

**Comment by lucko** [comment]
Update to the latest version of BungeeCord.
