### ISSUE TITLE
Error on server stop when no players connect.

### ISSUE THREAD

**Issue by RussianRonin** [lucko/LuckPerms#343]
So if I start and stop my server pretty quickly, it will spit out this error. If someone connects, it is fine.

Let me know if you need any more details.

[19:15:42 WARN]: [LuckPerms] Plugin LuckPerms v3.2.20 generated an exception while executing task 40
java.lang.NullPointerException: null
        at me.lucko.luckperms.common.tasks.UpdateTask.run(UpdateTask.java:43) ~[?:?]
        at me.lucko.luckperms.bukkit.LPBukkitPlugin$1.perform(LPBukkitPlugin.java:253) ~[?:?]
        at me.lucko.luckperms.bukkit.LPBukkitPlugin$1.perform(LPBukkitPlugin.java:250) ~[?:?]
        at me.lucko.luckperms.common.utils.BufferedRequest$Processor.run(BufferedRequest.java:117) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-23b6354-0481ae9]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by lucko** [comment]
It only happens if you quickly stop after starting the server. You'll find that other plugins will have similar issues with this. 

The tasks do get cancelled when the server stops, but in some cases, the task has already started. 

Anyway, you can just ignore the error. It's not anything to be worried about.
