### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xKendu** [lucko/LuckPerms#404]
Error, when bungeecord plugin start.
01:07:24 [INFO] §f§b               __       §3 __   ___  __         __  
01:07:24 [INFO] §f§b    |    |  | /  ` |__/ §3|__) |__  |__)  |\/| /__` 
01:07:24 [INFO] §f§b    |___ \__/ \__, |  \ §3|    |___ |  \  |  | .__/ 
01:07:24 [INFO] §f 
01:07:24 [INFO] §f§2  Loading version §bv3.2.57§2 on Bungee - BungeeCord
01:07:24 [INFO] §f§8  Running on server version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:7d2c2ab:1119
01:07:24 [INFO] §f 
01:07:24 [INFO] §f§7§l[§bL§3P§7§l] §3Loading configuration...
01:07:24 [WARNING] Exception encountered when loading plugin: LuckPerms
java.lang.NoSuchMethodError: net.md_5.bungee.config.Configuration.contains(Ljava/lang/String;)Z
	at me.lucko.luckperms.bungee.BungeeConfig.contains(BungeeConfig.java:80)
	at me.lucko.luckperms.common.config.ConfigKeys.lambda$static$0(ConfigKeys.java:116)
	at me.lucko.luckperms.common.config.keys.AbstractKey.get(AbstractKey.java:41)
	at me.lucko.luckperms.common.config.AbstractConfiguration.lambda$new$0(AbstractConfiguration.java:42)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache$UnboundedLocalLoadingCache.lambda$new$0(UnboundedLocalCache.java:922)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.lambda$computeIfAbsent$2(UnboundedLocalCache.java:235)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.computeIfAbsent(UnboundedLocalCache.java:231)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:67)
	at java.lang.Iterable.forEach(Unknown Source)
	at me.lucko.luckperms.common.config.AbstractConfiguration.loadAll(AbstractConfiguration.java:58)
	at me.lucko.luckperms.bungee.LPBungeePlugin.onEnable(LPBungeePlugin.java:139)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:256)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
01:07:24 [INFO] Enabled plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:7d2c2ab:1119 by SpigotMC
01:07:24 [WARNING] Exception encountered when loading plugin: BungeeChat
java.lang.IllegalStateException: API is not loaded.
	at me.lucko.luckperms.LuckPerms.getApi(LuckPerms.java:52)
	at dev.aura.bungeechat.hook.LuckPermsHook.<init>(LuckPermsHook.java:18)
	at dev.aura.bungeechat.module.perms.LuckPermsModule.onEnable(LuckPermsModule.java:14)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at dev.aura.bungeechat.api.module.ModuleManager.enableModules(ModuleManager.java:47)
	at dev.aura.bungeechat.BungeeChat.onEnable(BungeeChat.java:106)
	at dev.aura.bungeechat.BungeeChat.onEnable(BungeeChat.java:67)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:256)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by xKendu** [comment]
version BungeeCord-Bootstrap:1.8-SNAPSHOT:7d2c2ab:1119 by md_5

**Comment by BrainStone** [comment]
Update your bungee

**Comment by xKendu** [comment]
On new bungee version, spigot 1.7-1.8 not working..

**Comment by BrainStone** [comment]
Use Hexacord (a modified bungeecord) for older versions

**Comment by lucko** [comment]
Your options are:

* [Travertine](https://ci.aquifermc.org/job/Travertine/)
* [HexaCord](https://github.com/HexagonMC/BungeeCord/releases)


The older BungeeCord versions are not supported by LuckPerms.
