### ISSUE TITLE
Could not pass AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by PaXo0** [lucko/LuckPerms#417]
Hi i want to use LuckPerms with deluxechat but it keeps giving me an error and im not quite sure how to fix it here is the error

```
[13:39:28 ERROR]: Could not pass event AsyncPlayerChatEvent to DeluxeChat v1.6.5.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1084) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1022) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_141]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_141]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
Caused by: ru.tehkode.permissions.exceptions.PermissionsNotAvailable: Permissions manager is not accessable. Is the PermissionsEx plugin enabled?
        at ru.tehkode.permissions.bukkit.PermissionsEx.getPermissionManager(PermissionsEx.java:405) ~[?:?]
        at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getUser(Permission_PermissionsEx.java:243) ~[?:?]
        at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getPrimaryGroup(Permission_PermissionsEx.java:264) ~[?:?]
        at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[?:?]
        at me.clip.deluxechat.hooks.VaultHook.opHasPermission(VaultHook.java:380) ~[?:?]
        at me.clip.deluxechat.DeluxeChat.getPlayerFormat(DeluxeChat.java:657) ~[?:?]
        at me.clip.deluxechat.listeners.AsyncPlayerChatListener.onChat(AsyncPlayerChatListener.java:70) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_141]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-db6de12-18fbb24]
        ... 11 more
```

**Comment by lucko** [comment]
You need to uninstall PEX.
