### ISSUE TITLE
Cannot parse MetaStackElement

### ISSUE THREAD

**Issue by mrcoffee1026** [lucko/LuckPerms#436]
Get error in console now, i don't think this was showing up before but it appeared suddenly... doesn't seem to be effecting much of anything but I still want it gone:

```
[12:29:52] [Server thread/INFO]: [0;32;22m  Loading version [0;36;1mv3.2.68[0;32;22m on Bukkit - CraftBukkit[m
[12:29:52] [Server thread/INFO]: [0;30;1m  Running on server version git-Spigot-5340a52-e1f296d (MC: 1.12.1) - 1.12.1-R0.1-SNAPSHOT[m
[12:29:52] [Server thread/INFO]:  [m
[12:29:52] [Server thread/INFO]: [0;37;22m[21m[[0;36;1mL[0;36;22mP[0;37;22m[21m] [0;36;22mLoading configuration...[m
[12:29:52] [Server thread/WARN]: java.lang.IllegalArgumentException: Cannot parse MetaStackElement: 
[12:29:52] [Server thread/WARN]: 	at me.lucko.luckperms.common.metastacking.definition.StandardStackElements.parseFromString(StandardStackElements.java:87)
[12:29:52] [Server thread/WARN]: 	at me.lucko.luckperms.common.metastacking.definition.StandardStackElements.lambda$parseList$0(StandardStackElements.java:93)
```
...
goes on for ages after that.

Any help on this would be appreciated

**Comment by lucko** [comment]
Can you pastebin your config file please.

**Comment by mrcoffee1026** [comment]
sorry, relevant lines:
https://pastebin.com/8f76t3hD

**Comment by lucko** [comment]
> config file

not server log :P

**Comment by mrcoffee1026** [comment]
ugh, sorry...
https://pastebin.com/Wis8fh5u

**Comment by lucko** [comment]
Line 197 is empty -- it shouldn't be. :)

Set it to `"highest"` if you don't know what else to put.
