### ISSUE TITLE
Java 9 Plus Spigot 1.12.2 error

### ISSUE THREAD

**Issue by wherkamp** [lucko/LuckPerms#483]
I was testing the latest version of Java and Spigot on my test server and this error is happening.
The commands are not working.
if you would like to look play.kinglinux.com is the ip.

`18:23:27 INFO]: [LuckPerms] Loading LuckPerms v3.3.13
[18:23:27 INFO]: [LP] Identified the following dependencies: [CAFFEINE]
[18:23:27 INFO]: [LuckPerms] [ERROR] Failed to load jar for dependency CAFFEINE
[18:23:27 WARN]: java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
[18:23:27 WARN]:        at me.lucko.luckperms.common.dependencies.DependencyManager.loadJar(DependencyManager.java:141)
[18:23:27 WARN]:        at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependencies(DependencyManager.java:106)
[18:23:27 WARN]:        at me.lucko.luckperms.bukkit.LPBukkitPlugin.onLoad(LPBukkitPlugin.java:157)
[18:23:27 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:313)
[18:23:27 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205)
[18:23:27 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[18:23:27 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[18:23:27 INFO]: [ServerInfo] Loading ServerInfo v1.7.3
[18:23:27 INFO]: [Vault] Loading Vault v1.6.1
[18:23:27 INFO]: [Essentials] Loading Essentials v2.0.1-b530
[18:23:27 INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.8.2
[18:23:27 INFO]: [UltraChat] Loading UltraChat v1.8.2
[18:23:27 INFO]: [VeinMiner] Loading VeinMiner v1.11.3
[18:23:27 INFO]: [EssentialsXMPP] Loading EssentialsXMPP v2.0.1-b530
[18:23:27 INFO]: [LuckPerms] Enabling LuckPerms v3.3.13
[18:23:27 INFO]:                __        __   ___  __         __  
[18:23:27 INFO]:     |    |  | /  ` |__/ |__) |__  |__)  |\/| /__` 
[18:23:27 INFO]:     |___ \__/ \__, |  \ |    |___ |  \  |  | .__/ 
[18:23:27 INFO]:  
[18:23:27 INFO]:   Loading version v3.3.13 on Bukkit - CraftBukkit
[18:23:27 INFO]:   Running on server version git-Spigot-7754231-94b0980 (MC: 1.12.2) - 1.12.2-R0.1-SNAPSHOT
[18:23:27 INFO]:  
[18:23:27 INFO]: [LP] Loading configuration...
[18:23:27 ERROR]: Error occurred while enabling LuckPerms v3.3.13 (Is it up to date?)
java.lang.NoClassDefFoundError: com/github/benmanes/caffeine/cache/Caffeine
        at me.lucko.luckperms.common.config.AbstractConfiguration.<init>(AbstractConfiguration.java:47) ~[?:?]
        at me.lucko.luckperms.bukkit.BukkitConfig.<init>(BukkitConfig.java:43) ~[?:?]
        at me.lucko.luckperms.bukkit.LPBukkitPlugin.enable(LPBukkitPlugin.java:192) ~[?:?]
        at me.lucko.luckperms.bukkit.LPBukkitPlugin.onEnable(LPBukkitPlugin.java:175) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Spigot-7754231-94b0980]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-7754231-94b0980]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [server.jar:git-Spigot-7754231-94b0980]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [server.jar:git-Spigot-7754231-94b0980]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [server.jar:git-Spigot-7754231-94b0980]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206) [server.jar:git-Spigot-7754231-94b0980]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-7754231-94b0980]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: com.github.benmanes.caffeine.cache.Caffeine
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-Spigot-7754231-94b0980]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-7754231-94b0980]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 12 more
`

**Comment by lucko** [comment]
This is fixed already in the latest dev builds.   
https://ci.lucko.me/job/LuckPerms/

I'll push a release to Spigot soon. :)

**Comment by wherkamp** [comment]
I was just trying to compile my own copy to see if that fixed it. Thank you.
