### ISSUE TITLE
Nullpointer on user migration bungeeperms

### ISSUE THREAD

**Issue by MWFIAE** [lucko/LuckPerms#514]
```
[23:17:08 INFO]: [LP] MIGRATION [BungeePerms] > Starting user migration.
[23:17:11 ERROR]: java.util.concurrent.CompletionException: java.lang.NullPointerException
[23:17:11 ERROR]:       at 
java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
[23:17:11 ERROR]:       at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
[23:17:11 ERROR]:       at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
[23:17:11 ERROR]:       at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
[23:17:11 ERROR]:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[23:17:11 ERROR]:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[23:17:11 ERROR]:       at java.lang.Thread.run(Thread.java:748)
```

```
[23:17:11 ERROR]: Caused by: java.lang.NullPointerException
[23:17:11 ERROR]:       at me.lucko.luckperms.common.storage.backing.sql.SQLBacking.saveUUIDData(SQLBacking.java:993)
[23:17:11 ERROR]:       at me.lucko.luckperms.common.storage.AbstractStorage.lambda$saveUUIDData$16(AbstractStorage.java:250)
[23:17:11 ERROR]:       at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[23:17:11 ERROR]:       ... 4 more
```

Thx for helping!

**Comment by mat41997** [comment]
you can put this error here
https://gist.github.com/
