### ISSUE TITLE
Transient permissions not working

### ISSUE THREAD

**Issue by Kainzo** [lucko/LuckPerms#528]
Hey @lucko 
First off, love the plugin and thanks so much for the support so far!

Heroes can grant permission-skills to players via class/level and remove them if they lose a level or change class.  These permission skills are permission-nodes granted to the player as a transient permission.  This is the example config for that.   I can say 100% that the "permission-skill" has been granted to the player but the nodes aren't working for them.  They cannot use this simple Lighter when restricted via WorldGuard

> 

ArtisanCrafter:
    usage: Provides Lighter, Shear, and LavaBucket Use.
    permissions:
    - wg.fire
    - wg.lavabucket
    - wg.shears

This pulls from WorldGuard's blacklist.txt which you can find the permission creation here. 

> 

#Lighters
[259,51]
ignore-groups=founder,admin,mod6
ignore-perms=wg.fire
on-use=deny,tell
message=Restricted
comment=fire starter!

My assumptions here.... something isnt working nicely with the SuperPermissions between LuckPerms and Heroes that was working fine via zPerms or bPerms.  We are a rather large server and this move was done because I do feel that LuckPerms is the better permissions, I just need to make sure all systems are functional before fully moving.

**Comment by i9hdkill** [comment]
@Kainzo Did it solve the issue for you? At least for us the issue persists. For us it isn't WorldGuard, but Crackshot.

**Comment by lucko** [comment]
Just decompiled Crackshot, the issue there is still related to this ticket, but just slightly different.

Basically, it's using attachments to set a permission only for a split second. 

![](https://i.imgur.com/ynmerxo.png)

That's one example, but you get the point.

The LP implementation of PermissionAttachment doesn't apply changes instantly - they're applied and propagated to the Users permission calculators asynchronously to avoid blocking the main thread whilst the caches are re-populated.

I'll have to work around this, as I can see it's going to become an issue.

**Comment by i9hdkill** [comment]
Getting this from time to time:
`[22:55:01] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set final java.util.Map field org.bukkit.permissions.PermissibleBase.permissions to me.lucko.luckperms.bukkit.model.LPPermissionAttachment
[22:55:01] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[22:55:01] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[22:55:01] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
[22:55:01] [Server thread/WARN]: 	at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:77)
[22:55:01] [Server thread/WARN]: 	at java.lang.reflect.Field.set(Field.java:764)
[22:55:01] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.model.LPPermissionAttachment.injectFakeMap(LPPermissionAttachment.java:137)
[22:55:01] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.model.LPPermissionAttachment.<init>(LPPermissionAttachment.java:108)
[22:55:01] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.model.LPPermissible.addAttachment(LPPermissible.java:176)
[22:55:01] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.model.LPPermissible.addAttachment(LPPermissible.java:67)
[22:55:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.addAttachment(CraftHumanEntity.java:124)
[22:55:01] [Server thread/WARN]: 	at com.shampaggon.crackshot.CSDirector$4.run(CSDirector.java:2042)
[22:55:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[22:55:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[22:55:01] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[22:55:01] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[22:55:01] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[22:55:01] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[22:55:01] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)`

**Comment by lucko** [comment]
Yeah, that's thrown whenever a plugin sets a permission via an attachment.

Working on a fix atm.

**Comment by lucko** [comment]
a115ff8ce2b70ebd00e1d84ecd464ff45d1e993b

**Comment by lucko** [comment]
That should also resolve your issue with Crackshot @i9hdkill

**Comment by i9hdkill** [comment]
Thanks a lot! Will test when we updated our plugins depending on LP API and we start on that when the api refatoring is done.

**Comment by MagicBroker** [comment]
tzpőú
7
