### ISSUE TITLE
LuckPerms not starting: org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml

### ISSUE THREAD

**Issue by damianocasula** [lucko/LuckPerms#592]
I get these warnings when starting my server with LuckPerms and Vault.
Vault loads, LuckPerms doesn't:

[09:29:03 WARN]: org.bukkit.plugin.InvalidPluginException: org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
[09:29:03 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:76)
[09:29:03 WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
[09:29:03 WARN]: 	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:356)
[09:29:03 WARN]: 	at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
[09:29:03 WARN]: 	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[09:29:03 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[09:29:03 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[09:29:03 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:674)
[09:29:03 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:637)
[09:29:03 WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:464)
[09:29:03 WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
[09:29:03 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[09:29:03 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[09:29:03 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[09:29:03 WARN]: Caused by: org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
[09:29:03 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:158)
[09:29:03 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:74)
[09:29:03 WARN]: 	... 13 more
[09:29:03 WARN]: Caused by: java.util.zip.ZipException: error in opening zip file
[09:29:03 WARN]: 	at java.util.zip.ZipFile.open(Native Method)
[09:29:03 WARN]: 	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
[09:29:03 WARN]: 	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
[09:29:03 WARN]: 	at java.util.jar.JarFile.<init>(JarFile.java:166)
[09:29:03 WARN]: 	at java.util.jar.JarFile.<init>(JarFile.java:130)
[09:29:03 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:146)
[09:29:03 WARN]: 	... 14 more

**Comment by damianocasula** [comment]
@lucko I'm using PlugMan to see if I can get your plugin to work, I've got this problem also before installing PlugMan. Anyways it still doesn't work now that I removed PlugMan.

**Comment by lucko** [comment]
Can you show me the new error?

**Comment by damianocasula** [comment]
[11:09:27 ERROR]: Could not load 'plugins/LuckPerms.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:158) ~[PaperSpigot-latest.jar:git-Paper-1270]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136) [PaperSpigot-latest.jar:git-Paper-1270]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:307) [PaperSpigot-latest.jar:git-Paper-1270]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:225) [PaperSpigot-latest.jar:git-Paper-1270]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot-latest.jar:git-Paper-1270]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_151]
	at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_151]
	at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_151]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_151]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:146) ~[PaperSpigot-latest.jar:git-Paper-1270]
	... 5 more

@lucko

**Comment by lucko** [comment]
Can you try downloading a fresh jar from https://ci.lucko.me/job/LuckPerms/

Seems like the copy you have has been corrupted in some way.

**Comment by damianocasula** [comment]
Working now, thank you so much @lucko.
