### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by S3nS3IW00** [lucko/LuckPerms#603]
Hello dear developers!

I have a question. How can I add a player to group with api? I don't understand it in Developer API :/ Please help with code.

**Comment by lucko** [comment]
`user.setPermission(luckPermsApi.buildGroupNode(...))`

**Comment by S3nS3IW00** [comment]
luckPermsApi is LuckPerms.getApi();?

**Comment by lucko** [comment]
Yes.

**Comment by S3nS3IW00** [comment]
but buildGroupNode() method doesn't exist.

**Comment by lucko** [comment]
Re-read what I said.

**Comment by S3nS3IW00** [comment]
user.setPermission((Node) LuckPerms.getApi().buildGroupNode("ender"));

**Comment by lucko** [comment]
Again, that's not the method I said. It's `makeGroupNode`, not `buildGroupNode`.

Secondly, you shouldn't be casting the Node.Builder to Node. Call the `#build` method.

**Comment by S3nS3IW00** [comment]
Ok, I am not English :D So please explain it in code.

**Comment by lucko** [comment]
I've already given you an example, and there are more examples on the wiki page. (which I've also linked already)

**Comment by S3nS3IW00** [comment]
But I don't understand the Developer api :/ I can't do this :/ If I run the "lp user <user> parent set <group>" command, I have an error in console...Why?

**Comment by lucko** [comment]
I don't know? Can you show me the error?

**Comment by S3nS3IW00** [comment]
Yes.

**Comment by S3nS3IW00** [comment]
[17:31:38 ERROR]: Command Dispatched Async: lp user S3nS3IW00 parent set vip
[17:31:38 ERROR]: Please notify author of plugin causing this execution to fix this bug! see: http://bit.ly/1oSiM6C
java.lang.Throwable: null
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:656) [patched_1.12.2.jar:git-Paper-1262]
        at hu.endercraft.managers.termekManager.giveVIP(termekManager.java:19) [ECCore.jar:?]
        at hu.endercraft.events.EventHandlers.onChat(EventHandlers.java:643) [ECCore.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor53.execute(Unknown Source) [?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) [patched_1.12.2.jar:git-Paper-1262]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) [patched_1.12.2.jar:git-Paper-1262]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [patched_1.12.2.jar:git-Paper-1262]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1262]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:497) [patched_1.12.2.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1386) [patched_1.12.2.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1301) [patched_1.12.2.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.12.2.jar:git-Paper-1262]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

**Comment by S3nS3IW00** [comment]
I dispached in my plugin ConsoleSender()

**Comment by S3nS3IW00** [comment]
Bukkit.dispatchCommand(Bukkit.getConsoleSender(), "lp user "+player.getName()+" parent set vip");

**Comment by S3nS3IW00** [comment]
The specified player getting the rank, but its flood my console.

**Comment by lucko** [comment]
That's not a LuckPerms related error.

You're dispatching the command from an async thread, which is unsafe.

**Comment by S3nS3IW00** [comment]
This is a LuckPerms error. Another command is run without error.

**Comment by lucko** [comment]
No it's not. Read what the message says.

**Comment by lucko** [comment]
```
[17:31:38 ERROR]: Please notify author of plugin causing this execution to fix this bug! see: http://bit.ly/1oSiM6C
java.lang.Throwable: null
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:656) [patched_1.12.2.jar:git-Paper-1262]
at hu.endercraft.managers.termekManager.giveVIP(termekManager.java:19) [ECCore.jar:?]
at hu.endercraft.events.EventHandlers.onChat(EventHandlers.java:643) [ECCore.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor53.execute(Unknown Source) [?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) [patched_1.12.2.jar:git-Paper-1262]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) [patched_1.12.2.jar:git-Paper-1262]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [patched_1.12.2.jar:git-Paper-1262]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1262]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:497) [patched_1.12.2.jar:git-Paper-1262]
at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1386) [patched_1.12.2.jar:git-Paper-1262]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1301) [patched_1.12.2.jar:git-Paper-1262]
at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.12.2.jar:git-Paper-1262]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```

The error was thrown because the command was invoked async. It has *nothing* to do with the command actually being ran.

The error also directs you to a forum post which explains the issue in more detail.

https://www.spigotmc.org/threads/plugins-triggering-commands-async.31815/

**Comment by S3nS3IW00** [comment]
Its very interesting, why show the error only in LuckPerms command :D

**Comment by lucko** [comment]
Ok sure, believe whatever you want.

I'm not going to waste any more of my time.

**Comment by S3nS3IW00** [comment]
I believe, this is not LuckPerms error, but I don't know why only in LuckPerms.

**Comment by S3nS3IW00** [comment]
Hello lucko!

I solved the problem. I'm sorry, because, I think the problem is in your plugin. I just need, to dispatch the command in bukkitrunnable. So really sorry! Have a good develop!
