### ISSUE TITLE
Fix zPermissions migration

### ISSUE THREAD

**Issue by lucko** [lucko/LuckPerms#61]
Needs a general cleanup.

```
>lp migration zpermissions world
[08:44:11 INFO]: [LuckPerms] zPermissions Migration: Starting group migration.
[08:44:11 WARN]: java.lang.NullPointerException
[08:44:11 WARN]: at me.lucko.luckperms.bukkit.migration.MigrationZPermissions.migrateEntity(MigrationZPermissions.java:134)
[08:44:11 WARN]: at me.lucko.luckperms.bukkit.migration.MigrationZPermissions.execute(MigrationZPermissions.java:87)
[08:44:11 WARN]: at me.lucko.luckperms.common.commands.MainCommand.execute(MainCommand.java:88)
[08:44:11 WARN]: at me.lucko.luckperms.common.commands.migration.MigrationMainCommand.execute(MigrationMainCommand.java:119)
[08:44:11 WARN]: at me.lucko.luckperms.common.commands.migration.MigrationMainCommand.execute(MigrationMainCommand.java:37)
[08:44:11 WARN]: at me.lucko.luckperms.common.commands.CommandManager.onCommand(CommandManager.java:152)
[08:44:11 WARN]: at me.lucko.luckperms.common.commands.CommandManager.lambda$onCommand$1(CommandManager.java:98)
[08:44:11 WARN]: at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[08:44:11 WARN]: at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[08:44:11 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[08:44:11 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[08:44:11 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[08:44:11 WARN]: at java.lang.Thread.run(Thread.java:745)
```

**Comment by melinstagibson** [comment]
Any eta for this? because im waiting for this to switch :/

**Comment by lucko** [comment]
Uhh - hopefully towards the end of this week. I don't have much time at the moment.

**Comment by lucko** [comment]
Are you using the latest version?
