### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by terrainwax** [lucko/LuckPerms#616]
```
java.lang.Error
	at com.google.common.collect.Iterators.forArray(Iterators.java:1053)
	at com.google.common.collect.RegularImmutableList.listIterator(RegularImmutableList.java:106)
	at com.google.common.collect.RegularImmutableAsList.listIterator(RegularImmutableAsList.java:55)
	at com.google.common.collect.ImmutableList.listIterator(ImmutableList.java:344)
	at com.google.common.collect.ImmutableList.iterator(ImmutableList.java:340)
	at com.google.common.collect.RegularImmutableMap$EntrySet.iterator(RegularImmutableMap.java:196)
	at com.google.common.collect.RegularImmutableMap$EntrySet.iterator(RegularImmutableMap.java:188)
	at com.google.common.collect.Sets.hashCodeImpl(Sets.java:1341)
	at com.google.common.collect.ImmutableSet.hashCode(ImmutableSet.java:403)
	at com.google.common.collect.ImmutableMap.hashCode(ImmutableMap.java:515)
	at com.google.common.collect.AbstractMultimap.hashCode(AbstractMultimap.java:228)
	at com.google.common.collect.ImmutableMultimap.hashCode(ImmutableMultimap.java:64)
	at me.lucko.luckperms.api.context.ImmutableContextSet.hashCode(ImmutableContextSet.java:268)
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:1942)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:67)
	at me.lucko.luckperms.sponge.service.CompatibilityUtil.convertContexts(CompatibilityUtil.java:68)
	at me.lucko.luckperms.sponge.service.proxy.api6.SubjectProxy.lambda$getActiveContexts$11(SubjectProxy.java:147)
	at me.lucko.luckperms.sponge.service.proxy.api6.SubjectProxy$$Lambda$1073/26773687.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
	at me.lucko.luckperms.sponge.service.proxy.api6.SubjectProxy.getActiveContexts(SubjectProxy.java:147)
	at net.minecraft.entity.player.EntityPlayerMP.getActiveContexts(EntityPlayerMP.java:2494)
	at net.minecraft.entity.player.EntityPlayerMP.hasPermission(EntityPlayerMP.java:2458)
	at br.net.fabiozumbi12.RedProtect.Sponge.RPPermHandler.hasPerm(RPPermHandler.java:18)
	at br.net.fabiozumbi12.RedProtect.Sponge.Region.checkAllowedPlayer(Region.java:1487)
	at br.net.fabiozumbi12.RedProtect.Sponge.Region.allowEffects(Region.java:1374)
	at br.net.fabiozumbi12.RedProtect.Sponge.listeners.RPPlayerListener.onPlayerMovement(RPPlayerListener.java:650)
	at org.spongepowered.common.event.listener.MoveEntityEventListener_RPPlayerListener_onPlayerMovement176.handle(Unknown Source)
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:342)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326)
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143)
	at net.minecraft.network.NetHandlerPlayServer.redirect$throwMoveEvent$zhf000(NetHandlerPlayServer.java:2192)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:406)
	at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(SourceFile:126)
	at net.minecraft.network.play.client.CPacketPlayer$PositionRotation.func_148833_a(SourceFile:18)
	at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157)
	at org.spongepowered.common.network.PacketUtil$$Lambda$1179/1289582687.call(Unknown Source)
	at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:163)
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156)
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjj000(SourceFile:539)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(SourceFile:45)
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:239)
	at net.minecraft.server.MinecraftServer.redirect$onRun$zhp000(MinecraftServer.java:3948)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by terrainwax** [comment]
Version 1.10.2
Sponge 1.10.2 2777
Forge 1.10.2 lastest

**Comment by lucko** [comment]
Is that the full error?

**Comment by terrainwax** [comment]
yes

**Comment by lucko** [comment]
Ok well, there's no reason for a `java.lang.Error` to be thrown on that line, so my assumption is some other code is forcefully halting that thread, or there's some issue with the guava dependency being loaded.

It's not a LP issue - you could try reporting it to Sponge to see what they think. I imagine they'll probably say the same thing though.
