### ISSUE TITLE
MongoDB Bulk Updating

### ISSUE THREAD

**Issue by dbluk** [lucko/LuckPerms#621]
I attempted to use a bulk update using MongoDB as storage. Maybe due to the command being built for SQL? __(1.8.8 Paperspigot, v3.3.13)__

---

> lp bulkupdate all update permission group.tmod "permission == group.trialmod"
[LP] Bulk update operation was queued. (UPDATE all SET permission='group.tmod' WHERE permission = 'group.trialmod';)
[LP] Run /lp bulkupdate confirm 2171 to execute the update.
        >lp bulkupdate confirm 2171

        [LP] Running bulk update.
        java.lang.IllegalArgumentException: Invalid BSON field name kitpvp.switcher
               at org.bson.AbstractBsonWriter.writeName(AbstractBsonWriter.java:516)
               at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:188)
               at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:172)
               at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:189)
               at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:131)
               at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:45)
               at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
               at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
               at com.mongodb.connection.UpdateCommandMessage.writeTheWrites(UpdateCommandMessage.java:85)
               at com.mongodb.connection.UpdateCommandMessage.writeTheWrites(UpdateCommandMessage.java:43)
               at com.mongodb.connection.BaseWriteCommandMessage.encodeMessageBodyWithMetadata(BaseWriteCommandMessage.java:129)
               at com.mongodb.connection.RequestMessage.encodeWithMetadata(RequestMessage.java:160)
               at com.mongodb.connection.WriteCommandProtocol.sendMessage(WriteCommandProtocol.java:220)
               at com.mongodb.connection.WriteCommandProtocol.execute(WriteCommandProtocol.java:101)
               at com.mongodb.connection.UpdateCommandProtocol.execute(UpdateCommandProtocol.java:64)
               at com.mongodb.connection.UpdateCommandProtocol.execute(UpdateCommandProtocol.java:37)
               at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:168)
               at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:289)
               at com.mongodb.connection.DefaultServerConnection.updateCommand(DefaultServerConnection.java:143)
               at com.mongodb.operation.MixedBulkWriteOperation$Run$3.executeWriteCommandProtocol(MixedBulkWriteOperation.java:490)
               at com.mongodb.operation.MixedBulkWriteOperation$Run$RunExecutor.execute(MixedBulkWriteOperation.java:656)
               at com.mongodb.operation.MixedBulkWriteOperation$Run.execute(MixedBulkWriteOperation.java:409)
               at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:177)
               at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:168)
               at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:422)
               at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:413)
               at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:168)
               at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:74)
               at com.mongodb.Mongo.execute(Mongo.java:845)
               at com.mongodb.Mongo$2.execute(Mongo.java:828)
               at com.mongodb.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:550)
               at com.mongodb.MongoCollectionImpl.replaceOne(MongoCollectionImpl.java:369)
               at com.mongodb.MongoCollectionImpl.replaceOne(MongoCollectionImpl.java:364)
               at me.lucko.luckperms.common.storage.backing.mongodb.MongoDBBacking.lambda$applyBulkUpdate$8(MongoDBBacking.java:296)
               at me.lucko.luckperms.common.storage.backing.mongodb.MongoDBBacking.call(MongoDBBacking.java:79)
               at me.lucko.luckperms.common.storage.backing.mongodb.MongoDBBacking.applyBulkUpdate(MongoDBBacking.java:266)
               at me.lucko.luckperms.common.storage.AbstractStorage.lambda$applyBulkUpdate$1(AbstractStorage.java:101)
               at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
               at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
               at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
               at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
               at java.lang.Thread.run(Thread.java:748)
        [LP] Bulk update failed. Check the console for errors.

**Comment by lucko** [comment]
Update to the latest version. (this was fixed months ago) :)

https://ci.lucko.me/job/LuckPerms/
