### ISSUE TITLE
Issues with Skript

### ISSUE THREAD

**Issue by FallingCactus** [lucko/LuckPerms#630]
Hey i seem to be having issues when using skript plugin...

```
[13:29:50 INFO]: BigSpikyCactus issued server command: /p SandoGO
[13:29:50 INFO]: BigSpikyCactus [d38f650b-bc7c-46be-a415-3322507e2e12]: /p SandoGO
[13:29:52 ERROR]: Could not pass event InventoryClickEvent to Skript v2.2-dev32c
java.lang.NullPointerException: name
        at me.lucko.luckperms.bukkit.model.LPPermissible.addAttachment(LPPermissible.java:204) ~[?:?]
        at me.lucko.luckperms.bukkit.model.LPPermissible.addAttachment(LPPermissible.java:67) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.addAttachment(CraftHumanEntity.java:128) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at com.github.tukenuke.tuske.util.CommandUtils.runCommand(CommandUtils.java:37) ~[?:?]
        at com.github.tukenuke.tuske.sections.gui.EffFormatGUI.lambda$execute$0(EffFormatGUI.java:132) ~[?:?]
        at com.github.tukenuke.tuske.manager.gui.GUI.run(GUI.java:29) ~[?:?]
        at com.github.tukenuke.tuske.manager.gui.GUIManager$1.onClick(GUIManager.java:149) ~[?:?]
        at com.github.tukenuke.tuske.listeners.GUIListener.onEvent(GUIListener.java:57) ~[?:?]
        at com.github.tukenuke.tuske.manager.gui.v2.SkriptGUIEvent.check(SkriptGUIEvent.java:39) ~[?:?]
        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:145) ~[?:?]
        at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:109) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

**Comment by spannerman79** [comment]
Make sure you are running the most recent builds of Luckperms https://ci.lucko.me/job/LuckPerms/lastStableBuild/

**Comment by lucko** [comment]
It's not a LuckPerms error. You need to report the issue to the author of `com.github.tukenuke.tuske`
