### ISSUE TITLE
Dependency injection error caused by PluginClassLoader impl changes

### ISSUE THREAD

**Issue by Fader-GumGum** [lucko/LuckPerms#648]
Got these errors with the latest Spigot build: 
This server is running CraftBukkit version git-Spigot-b66ad9e-b5a10a9 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

https://pastebin.com/raw/N1yrzW7i

```
[10:27:16] [Server thread/ERROR]: Error occurred while enabling LuckPerms v4.0.72 (Is it up to date?)
java.lang.NoClassDefFoundError: com/github/benmanes/caffeine/cache/CacheLoader
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_151]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_151]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:142) ~[spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:191) ~[spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at me.lucko.luckperms.bukkit.LPBukkitPlugin.enable(LPBukkitPlugin.java:191) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitPlugin.onEnable(LPBukkitPlugin.java:175) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206) [spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: com.github.benmanes.caffeine.cache.CacheLoader
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:146) ~[spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	... 19 more
```

**Comment by lucko** [comment]
Can you try updating Spigot again?

**Comment by lucko** [comment]
Seems to be caused by a recent Spigot change.
I've reported it here: https://hub.spigotmc.org/jira/browse/SPIGOT-3723

In the meantime, you'll need to use a Spigot build which is at least a couple of days old.

**Comment by shadowcaptain21** [comment]
same here

https://pastebin.com/RpwLdHuk

**Comment by lucko** [comment]
The latest build of LuckPerms will fix the issue.
https://ci.lucko.me/job/LuckPerms/

I'm going to leave this ticket open - I remain hopeful that md-5 will revert the change in Bukkit, which'll mean I can remove the workaround in LP.

**Comment by Fader-GumGum** [comment]
Thanks for this fix. Seems to work fine now.

**Comment by lucko** [comment]
Spigot resolved the issue, so the workaround in LP has been reverted.

https://github.com/lucko/LuckPerms/commit/717347273d7dc63ae449633969eaa2c559a2b19f
