### ISSUE TITLE
java.lang.NullPointerException: sender

### ISSUE THREAD

**Issue by QuinnTDIP** [lucko/LuckPerms#701]
When loading LP for the first time, I get this error:

```java.lang.NullPointerException: sender
	at me.lucko.luckperms.common.commands.sender.SenderFactory.wrap(SenderFactory.java:63) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitPlugin.getConsoleSender(LPBukkitPlugin.java:522) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitPlugin.onLoad(LPBukkitPlugin.java:154) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:303) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.<init>(CraftServer.java:260) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
	at net.minecraft.server.v1_11_R1.PlayerList.<init>(PlayerList.java:73) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:185) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:521) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```
Any ideas or suggestions? I really want to make the jump from PEX
[EDIT] Gets same error on shutdown.

**Comment by spannerman79** [comment]
`craftbukkit` <- don't use craftbukkit.

**Comment by QuinnTDIP** [comment]
oh, well than. That sucks, *sigh* Back to PEX.

**Comment by spannerman79** [comment]
...seriously?  Who in their right mind uses craftbukkit when there is Spigot, or PaperSpigot, or two other forks that run rings around craftbukkit.....

**Comment by QuinnTDIP** [comment]
I regret to say, I don't really understand how to install spigot, craftbukkit is just download and boom, it works.

**Comment by spannerman79** [comment]
> I regret to say, I don't really understand how to install spigot, craftbukkit is just download and boom, it works.

For someone that is a [Developer Program Member](https://developer.github.com/), one that would (or should) be able to read how to read documentation & able to use build tools, which are outlined on SpigotMC's page well....

**Comment by QuinnTDIP** [comment]
I just haven't made the switch yet. I'm looking into it, because PEX is starting to be a pain.

**Comment by lucko** [comment]
Issue is caused by a CraftBukkit bug/inconsistency which was fixed 6 (ish) months ago.

https://hub.spigotmc.org/jira/browse/SPIGOT-3461

If you want to use CraftBukkit + LP, you need to use the latest versions.

> I regret to say, I don't really understand how to install spigot, craftbukkit is just download and boom, it works.

Spigot is exactly the same. It's just a jar you have to run.

**Comment by QuinnTDIP** [comment]
Ahhh, I use 1.11.2 craftbukkit because.... Logic....

**Comment by BrainStone** [comment]
*cough* https://www.spigotmc.org/wiki/spigot-installation/ *cough*
