### ISSUE TITLE
mysql Error

### ISSUE THREAD

**Issue by Kapakulia** [lucko/LuckPerms#716]
```
> [19:31:41 INFO]: [LP] Loading configuration...
> [19:31:41 INFO]: [LP] Identified the following dependencies: [MYSQL_DRIVER, HIKARI]
> [19:31:41 INFO]: [LP] Loading storage provider... [MYSQL]
> [19:31:41 ERROR]: Error occurred while enabling LuckPerms v4.0.80 (Is it up to date?)
java.lang.NoSuchMethodError: com.zaxxer.hikari.util.UtilityElf.a(Ljava/lang/String;)Ljava/lang/String;
at com.zaxxer.hikari.HikariConfig.validate(Unknown Source) ~[?:?]
at com.zaxxer.hikari.HikariDataSource.<init>(Unknown Source) ~[?:?]
at me.lucko.luckperms.common.storage.dao.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:104) ~[?:?]
at me.lucko.luckperms.common.storage.dao.sql.SqlDao.init(SqlDao.java:155) ~[?:?]
at me.lucko.luckperms.common.storage.AbstractStorage.init(AbstractStorage.java:120) ~[?:?]
at me.lucko.luckperms.common.storage.wrappings.PhasedStorage.init(PhasedStorage.java:83) ~[?:?]
at me.lucko.luckperms.common.storage.wrappings.BufferedOutputStorage.init(BufferedOutputStorage.java:46) ~[?:?]
at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:112) ~[?:?]
at me.lucko.luckperms.bukkit.LPBukkitPlugin.enable(LPBukkitPlugin.java:214) ~[?:?]
at me.lucko.luckperms.bukkit.LPBukkitPlugin.onEnable(LPBukkitPlugin.java:175) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [spigot.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [spigot.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [spigot.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203) [spigot.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [spigot.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
> [19:31:41 INFO]: [LuckPerms] Disabling LuckPerms v4.0.80
> [19:31:41 INFO]: [LP] Closing storage...
> [19:31:41 ERROR]: Error occurred while disabling LuckPerms v4.0.80 (Is it up to date?)
java.lang.NullPointerException
at me.lucko.luckperms.bukkit.LPBukkitPlugin.onDisable(LPBukkitPlugin.java:365) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [spigot.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) [spigot.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [spigot.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [spigot.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [spigot.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203) [spigot.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [spigot.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by lucko** [comment]
Please try updating to the latest version.

https://ci.lucko.me/job/LuckPerms/

**Comment by lucko** [comment]
> Luck - Today at 18:48
@Kapakulia did updating fix the issue?

> Kapakulia - Today at 18:51
@Luck Yes
