### ISSUE TITLE
I'm always getting this error. When I'm trying to join my server for the first time.

### ISSUE THREAD

**Issue by DrOreo002** [lucko/LuckPerms#721]
```
30.01 10:04:46 [Server] WARN WARN com.zaxxer.hikari.pool.PoolBase - luckperms - Failed to validate connection com.mysql.jdbc.JDBC4Connection@5a573f87 (No operations allowed after connection closed.)
30.01 10:04:46 [Server] INFO [ERROR] Exception occured whilst loading data for 3a2d779e-6263-3def-af95-499cb2454ae4 - DrOreo002
30.01 10:04:46 [Server] WARN java.util.concurrent.CompletionException: java.sql.SQLTransientConnectionException: luckperms - Connection is not available, request timed out after 5013ms.
30.01 10:04:46 [Server] WARN at me.lucko.luckperms.common.storage.AbstractStorage.lambda$makeFuture$0(AbstractStorage.java:87)
30.01 10:04:46 [Server] WARN at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
30.01 10:04:46 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
30.01 10:04:46 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
30.01 10:04:46 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
30.01 10:04:46 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
30.01 10:04:46 [Server] WARN at java.lang.Thread.run(Thread.java:748)
30.01 10:04:46 [Server] WARN Caused by: java.sql.SQLTransientConnectionException: luckperms - Connection is not available, request timed out after 5013ms.
30.01 10:04:46 [Server] WARN at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:666)
30.01 10:04:46 [Server] WARN at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:182)
30.01 10:04:46 [Server] WARN at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
30.01 10:04:46 [Server] WARN at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
30.01 10:04:46 [Server] WARN at me.lucko.luckperms.common.storage.dao.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:141)
30.01 10:04:46 [Server] WARN at me.lucko.luckperms.common.storage.dao.sql.SqlDao.getName(SqlDao.java:990)
30.01 10:04:46 [Server] WARN at me.lucko.luckperms.common.storage.dao.SplitStorageDao.getName(SplitStorageDao.java:203)
30.01 10:04:46 [Server] WARN at me.lucko.luckperms.common.storage.AbstractStorage.lambda$getName$20(AbstractStorage.java:286)
30.01 10:04:46 [Server] WARN at me.lucko.luckperms.common.storage.AbstractStorage.lambda$makeFuture$0(AbstractStorage.java:84)
30.01 10:04:46 [Server] WARN ... 6 more
30.01 10:04:46 [Server] WARN Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
30.01 10:04:46 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
30.01 10:04:46 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
30.01 10:04:46 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
30.01 10:04:46 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.Util.getInstance(Util.java:408)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:5498)
30.01 10:04:46 [Server] WARN at com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:551)
30.01 10:04:46 [Server] WARN at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:172)
30.01 10:04:46 [Server] WARN at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:171)
30.01 10:04:46 [Server] WARN ... 13 more
30.01 10:04:46 [Server] WARN Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
30.01 10:04:46 [Server] INFO The last packet successfully received from the server was 788,407 milliseconds ago.  The last packet sent successfully to the server was 5,010 milliseconds ago.
30.01 10:04:46 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
30.01 10:04:46 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
30.01 10:04:46 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
30.01 10:04:46 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3559)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3459)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3900)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2438)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
30.01 10:04:46 [Server] WARN at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:168)
30.01 10:04:46 [Server] WARN ... 14 more
30.01 10:04:46 [Server] WARN Caused by: java.net.SocketTimeoutException: Read timed out
30.01 10:04:46 [Server] WARN at java.net.SocketInputStream.socketRead0(Native Method)
30.01 10:04:46 [Server] WARN at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
30.01 10:04:46 [Server] WARN at java.net.SocketInputStream.read(SocketInputStream.java:171)
30.01 10:04:46 [Server] WARN at java.net.SocketInputStream.read(SocketInputStream.java:141)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:101)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:144)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3008)
30.01 10:04:46 [Server] WARN at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3469)
30.01 10:04:46 [Server] WARN ... 23 more
```

Also, I'm using the LuckPerms version 4.0.61. And my server are using BungeeCord

**Comment by lucko** [comment]
https://github.com/lucko/LuckPerms/wiki/FAQ#mysql-no-operations-allowed-after-connection-closed-error

**Comment by DrOreo002** [comment]
Uhh, I cannot find the option on the config.yml file

**Comment by DrOreo002** [comment]
Hey, sorry for the late reply. I've found the option but I'm still getting that error. Why?

**Comment by lucko** [comment]
> In general it looks like your MySQL server is having connectivity issues.

Nothing to do with LuckPerms. It's a MySQL driver error.

**Comment by DrOreo002** [comment]
I've contacted the support on my host. And I've followed what he said and it still not working :/
btw, the mysql that I use to store the data is on a different host from the server that I got the error form. Can it be the problem?

**Comment by lucko** [comment]
Could be? I don't know.

There are some pointers here you can try

https://github.com/lucko/LuckPerms/wiki/FAQ#luckperms-cannot-connect-to-my-mysql-server

but again:

> Nothing to do with LuckPerms. It's a MySQL driver error.
