### ISSUE TITLE
IncompatibleClassChangeError on Thermos 1.7.10

### ISSUE THREAD

**Issue by wConstruct** [lucko/LuckPerms#725]
enable-ops false doesnt work

```
Could not pass event ServerCommandEvent to LuckPerms v4.0.119
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:471) [lt.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:433) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IncompatibleClassChangeError
	at me.lucko.luckperms.bukkit.listeners.BukkitPlatformListener.handleCommand(BukkitPlatformListener.java:83) ~[?:?]
	at me.lucko.luckperms.bukkit.listeners.BukkitPlatformListener.onServerCommand(BukkitPlatformListener.java:57) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.UNOFFICIAL]
	... 8 more
```

https://github.com/CyberdyneCC/Thermos/releases 58 build

**Comment by lucko** [comment]
Thermos issue - nothing to do with LuckPerms, I can't do anything to fix it.
