### ISSUE TITLE
Error on Import from file to mysql 

### ISSUE THREAD

**Issue by joeymaeuslp** [lucko/LuckPerms#728]
java.io.IOException: Der Prozess kann nicht auf die Datei zugreifen, da ein anderer Prozess einen Teil der Datei gesperrt hat
[18:06:25 WARN]:        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
[18:06:25 WARN]:        at sun.nio.ch.FileDispatcherImpl.read(Unknown Source)
[18:06:25 WARN]:        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
[18:06:25 WARN]:        at sun.nio.ch.IOUtil.read(Unknown Source)
[18:06:25 WARN]:        at sun.nio.ch.FileChannelImpl.read(Unknown Source)
[18:06:25 WARN]:        at sun.nio.ch.ChannelInputStream.read(Unknown Source)
[18:06:25 WARN]:        at sun.nio.ch.ChannelInputStream.read(Unknown Source)
[18:06:25 WARN]:        at sun.nio.ch.ChannelInputStream.read(Unknown Source)
[18:06:25 WARN]:        at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
[18:06:25 WARN]:        at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
[18:06:25 WARN]:        at sun.nio.cs.StreamDecoder.read(Unknown Source)
[18:06:25 WARN]:        at java.io.InputStreamReader.read(Unknown Source)
[18:06:25 WARN]:        at java.io.BufferedReader.fill(Unknown Source)
[18:06:25 WARN]:        at java.io.BufferedReader.readLine(Unknown Source)
[18:06:25 WARN]:        at java.io.BufferedReader.readLine(Unknown Source)
[18:06:25 WARN]:        at java.nio.file.Files.readAllLines(Unknown Source)
[18:06:25 WARN]:        at me.lucko.luckperms.common.commands.impl.misc.ImportCommand.execute(ImportCommand.java:77)
[18:06:25 WARN]:        at me.lucko.luckperms.common.commands.abstraction.SingleCommand.execute(SingleCommand.java:51)
[18:06:25 WARN]:        at me.lucko.luckperms.common.commands.abstraction.SingleCommand.execute(SingleCommand.java:43)
[18:06:25 WARN]:        at me.lucko.luckperms.common.commands.CommandManager.execute(CommandManager.java:197)
[18:06:25 WARN]:        at me.lucko.luckperms.common.commands.CommandManager.lambda$onCommand$0(CommandManager.java:142)
[18:06:25 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
[18:06:25 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[18:06:25 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[18:06:25 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by BrainStone** [comment]
Mind to explain the what you did to get this error?

Also on the wiki is a page that explains the process for Changing Storage types

**Comment by joeymaeuslp** [comment]
iam use the plugin on a localhost server (bungeecrd) when i will import the yaml stoarge to mysql i became this error

**Comment by lucko** [comment]
Not a LuckPerms issue.

Make sure your server instance has access to the directory its running in.
