### ISSUE TITLE
Error on Joining

### ISSUE THREAD

**Issue by joeymaeuslp** [lucko/LuckPerms#738]
I cant Join my Server Help mee

: Exception in thread "Craft Scheduler Thread - 964"
[11:06:42 WARN]: org.apache.commons.lang.UnhandledException: Plugin LuckPerms v4.0.126 generated an exception while executing task 18287
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.CompletionException: java.sql.SQLTransientConnectionException: luckperms - Connection is not available, request timed out after 5000ms.
        at me.lucko.luckperms.common.storage.AbstractStorage.lambda$makeFuture$1(AbstractStorage.java:97)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
Caused by: java.sql.SQLTransientConnectionException: luckperms - Connection is not available, request timed out after 5000ms.
        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:666)
        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:182)
        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
        at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:95)
        at me.lucko.luckperms.common.storage.dao.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:140)
        at me.lucko.luckperms.common.storage.dao.sql.SqlDao.loadAllGroups(SqlDao.java:621)
        at me.lucko.luckperms.common.storage.AbstractStorage.lambda$loadAllGroups$9(AbstractStorage.java:212)
        at me.lucko.luckperms.common.storage.AbstractStorage.lambda$makeFuture$1(AbstractStorage.java:94)
        ... 6 more
Caused by: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: User 'ni883803_6sql7' has exceeded the 'max_user_connections' resource (current value: 30)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at me.lucko.luckperms.lib.mysql.jdbc.Util.getInstance(Util.java:408)
        at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
        at me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
        at me.lucko.luckperms.lib.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
        at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428)
        at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136)
        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:459)
        at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$200(HikariPool.java:70)
        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:696)
        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:682)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 more

**Comment by spannerman79** [comment]
When you downloaded luckperms, did you in fact read the little snippet of info that was right beside the links?
Spigot/Bukkit (**1.8.8 or higher**) –> LuckPerms-Bukkit

**Comment by joeymaeuslp** [comment]
I have the same error sent in. luck then said I should take the version but the version makes the same errors you can fix this Time OUT exeptions of Craft Sheduler please PEX has such errors not synonymous

**Comment by spannerman79** [comment]
> Caused by: java.util.concurrent.CompletionException: java.sql.SQLTransientConnectionException: luckperms - Connection is not available, **request timed out after 5000ms.**

Not a luckperms issue.  Check your DB

**Comment by spannerman79** [comment]
And dupe #737

**Comment by joeymaeuslp** [comment]
that is a Luckperms error at PermissonsEX the error is not synonymous that is due to your timeout settings are completely superfluous

and yes the other submission is from me because the error so very often (every 30 minutes) occurs and the support of my database says that is because of the plugin

**Comment by spannerman79** [comment]
> and yes the other submission is from me because the error so very often (every 30 minutes) occurs and the support of my database says that is because of the plugin

Your "support of my database" is full of cr@p.  Here is the **default** mysqld settings;

https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_interactive_timeout

`Default 28800` = 480 minutes.

Adjust your Luckperms config to fit into your 30 min window or tell your "support of my database" that they should try and bark up another tree

**Comment by joeymaeuslp** [comment]
As you always escalate all the same when you find a bug in your plugins learn to program or program to your knowledge and do not dare to big projects if you do not have enough experience in things mysql xd

**Comment by lucko** [comment]
> As you always escalate all the same when you find a bug in your plugins learn to program or program to your knowledge and do not dare to big projects if you do not have enough experience in things mysql xd

What?

The error has nothing to do with LuckPerms, it's coming from the MySQL driver & [Hikari](https://github.com/brettwooldridge/HikariCP) - again, nothing to do with me.

You can try tweaking the timeout settings in the config file.
