### ISSUE TITLE
Sorry i make New Issue MYSQL Error please use better MySql

### ISSUE THREAD

**Issue by JoeyPlayzTV** [lucko/LuckPerms#751]
what you've sent me there I've done everything please just use better mysql connector programming your own your plugin is useless without mysql

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[20:23:54 WARN]:        at sun.reflect.GeneratedConstructorAccessor67.newInstance(Unknown Source)
[20:23:54 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:23:54 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[20:23:54 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[20:23:54 WARN]:        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
[20:23:54 WARN]:        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:343)
[20:23:54 WARN]:        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2334)
[20:23:54 WARN]:        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
[20:23:54 WARN]:        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
[20:23:54 WARN]:        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
[20:23:54 WARN]:        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[20:23:54 WARN]:        at sun.reflect.GeneratedConstructorAccessor45.newInstance(Unknown Source)
[20:23:54 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:23:54 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[20:23:54 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[20:23:54 WARN]:        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
[20:23:54 WARN]:        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
[20:23:54 WARN]:        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
[20:23:54 WARN]:        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
[20:23:54 WARN]:        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
[20:23:54 WARN]:        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
[20:23:54 WARN]:        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:459)
[20:23:54 WARN]:        at com.zaxxer.hikari.pool.HikariPool.access$200(HikariPool.java:70)
[20:23:54 WARN]:        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:696)
[20:23:54 WARN]:        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:682)
[20:23:54 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:23:54 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[20:23:54 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[20:23:54 WARN]:        ... 1 more
[20:23:54 WARN]: Caused by: java.net.ConnectException: Connection refused (Connection refused)
[20:23:54 WARN]:        at java.net.PlainSocketImpl.socketConnect(Native Method)
[20:23:54 WARN]:        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[20:23:54 WARN]:        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[20:23:54 WARN]:        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[20:23:54 WARN]:        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[20:23:54 WARN]:        at java.net.Socket.connect(Socket.java:589)
[20:23:54 WARN]:        at java.net.Socket.connect(Socket.java:538)
[20:23:54 WARN]:        at java.net.Socket.<init>(Socket.java:434)
[20:23:54 WARN]:        at java.net.Socket.<init>(Socket.java:244)
[20:23:54 WARN]:        at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:254)
[20:23:54 WARN]:        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:292)
[20:23:54 WARN]:        ... 23 more

**Comment by JoeyPlayzTV** [comment]
user have all access your plugin ist shit

**Comment by lucko** [comment]
> user have all access your plugin ist shit

There's no need to be rude. :(

Please don't open new issues for the same question.

You can reply here: #750
