### ISSUE TITLE
The server crashed violently. (NukkitX)

### ISSUE THREAD

**Issue by AlekEagleYT** [lucko/LuckPerms#772]
After updating everything to the newest version, the nukkit server crashed very violently. Here is what it spit out:
```
11:16:55 [INFO] AlekEagleYT[/192.168.0.56:45147] logged in with entity id 1 at (world, 94.926, 71.0, 138.9589)
11:16:55 [EMERGENCY] Exception happened while ticking server
11:16:55 [ALERT] java.lang.IncompatibleClassChangeError: Found interface cn.nukkit.math.AxisAlignedBB, but class was expected
        at de.kniffo80.mobplugin.entities.BaseEntity.move(BaseEntity.java:309)
        at de.kniffo80.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:177)
        at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:164)
        at cn.nukkit.level.Level.doTick(Level.java:743)
        at cn.nukkit.Server.checkTickUpdates(Server.java:993)
        at cn.nukkit.Server.tick(Server.java:1079)
        at cn.nukkit.Server.tickProcessor(Server.java:842)
        at cn.nukkit.Server.start(Server.java:819)
        at cn.nukkit.Server.<init>(Server.java:502)
        at cn.nukkit.Nukkit.main(Nukkit.java:102)

11:16:55 [ALERT]
"ForkJoinPool.commonPool-worker-0" Id=63 WAITING on java.util.concurrent.ForkJoinPool@1788dc2
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.ForkJoinPool@1788dc2
        at java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1824)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1693)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


"ForkJoinPool.commonPool-worker-3" Id=62 TIMED_WAITING on java.util.concurrent.ForkJoinPool@1788dc2
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.ForkJoinPool@1788dc2
        at java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1824)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1693)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


"ForkJoinPool.commonPool-worker-2" Id=61 WAITING on java.util.concurrent.ForkJoinPool@1788dc2
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.ForkJoinPool@1788dc2
        at java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1824)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1693)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


"Nukkit Asynchronous Task Handler #5" Id=56 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@ec8271
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@ec8271
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ...


"pool-6-thread-1" Id=55 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@44effb
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@44effb
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ...


"Nukkit Asynchronous Task Handler #5" Id=52 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@ec8271
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@ec8271
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ...


"pool-5-thread-1" Id=35 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@3ee258
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@3ee258
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ...


"Timer-1" Id=34 TIMED_WAITING on java.util.TaskQueue@1676900
        at java.lang.Object.wait(Native Method)
        -  waiting on java.util.TaskQueue@1676900
        at java.util.TimerThread.mainLoop(Timer.java:552)
        at java.util.TimerThread.run(Timer.java:505)


"Nukkit Asynchronous Task Handler #2" Id=30 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at me.lucko.luckperms.common.treeview.PermissionVault.run(PermissionVault.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

        Number of locked synchronizers = 1
        - java.util.concurrent.ThreadPoolExecutor$Worker@187d2f4


"Nukkit Asynchronous Task Handler #1" Id=29 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at me.lucko.luckperms.common.verbose.VerboseHandler.run(VerboseHandler.java:134)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

        Number of locked synchronizers = 1
        - java.util.concurrent.ThreadPoolExecutor$Worker@8f047a


"Nukkit Asynchronous Task Handler #0" Id=28 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@ec8271
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@ec8271
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ...


"Thread-10" Id=27 TIMED_WAITING on cn.nukkit.utils.Watchdog@1a49597
        at java.lang.Object.wait(Native Method)
        -  waiting on cn.nukkit.utils.Watchdog@1a49597
        at cn.nukkit.utils.Watchdog.run(Watchdog.java:58)


"Timer-0" Id=26 WAITING on java.util.TaskQueue@b2972f
        at java.lang.Object.wait(Native Method)
        -  waiting on java.util.TaskQueue@b2972f
        at java.lang.Object.wait(Object.java:502)
        at java.util.TimerThread.mainLoop(Timer.java:526)
        at java.util.TimerThread.run(Timer.java:505)


"luckperms-fallback-3" Id=25 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@1699283
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@1699283
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ...


"luckperms-fallback-2" Id=24 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@1699283
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@1699283
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ...


"luckperms-fallback-1" Id=23 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@1699283
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@1699283
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ...


"luckperms-fallback-0" Id=22 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@1699283
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@1699283
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ...


"MVStore background writer nio:/media/root/ALEKEAGLE/server/plugins/LuckPerms/luckperms-h2.mv.db" Id=20 TIMED_WAITING on java.lang.Object@132c1c7
        at java.lang.Object.wait(Native Method)
        -  waiting on java.lang.Object@132c1c7
        at org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:2715)


"Thread-7" Id=18 RUNNABLE (in native)
        at sun.nio.fs.LinuxWatchService.poll(Native Method)
        at sun.nio.fs.LinuxWatchService.access$600(LinuxWatchService.java:47)
        at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:314)
        at java.lang.Thread.run(Thread.java:745)


"threadDeathWatcher-3-1" Id=17 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:150)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)


"nioEventLoopGroup-2-1" Id=16 RUNNABLE (in native)
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        -  locked io.netty.channel.nio.SelectedSelectionKeySet@6dffdb
        -  locked java.util.Collections$UnmodifiableSet@ac0a56
        -  locked sun.nio.ch.EPollSelectorImpl@1b4754a
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:759)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:400)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
        ...


"RakNet Thread #13" Id=13 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at cn.nukkit.raknet.server.SessionManager.tickProcessor(SessionManager.java:96)
        at cn.nukkit.raknet.server.SessionManager.run(SessionManager.java:70)
        at cn.nukkit.raknet.server.SessionManager.<init>(SessionManager.java:58)
        at cn.nukkit.raknet.server.RakNetServer.run(RakNetServer.java:101)


"RCON" Id=12 RUNNABLE (in native)
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        -  locked sun.nio.ch.Util$2@c3a4c2
        -  locked java.util.Collections$UnmodifiableSet@1b50de6
        -  locked sun.nio.ch.EPollSelectorImpl@16b487c
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
        at cn.nukkit.network.rcon.RCONServer.run(RCONServer.java:84)


"Console" Id=9 RUNNABLE (in native)
        at java.io.FileInputStream.read0(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:207)
        at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166)
        -  locked jline.internal.NonBlockingInputStream@173767e
        at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:135)
        at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:243)
        at jline.internal.InputStreamReader.read(InputStreamReader.java:257)
        -  locked jline.internal.NonBlockingInputStream@173767e
        at jline.internal.InputStreamReader.read(InputStreamReader.java:194)
        -  locked jline.internal.NonBlockingInputStream@173767e
        at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2143)
        ...


"NonBlockingInputStreamThread" Id=11 WAITING on jline.internal.NonBlockingInputStream@173767e owned by "Console" Id=9
        at java.lang.Object.wait(Native Method)
        -  waiting on jline.internal.NonBlockingInputStream@173767e
        at jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275)
        at java.lang.Thread.run(Thread.java:745)


"Logger" Id=7 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at cn.nukkit.utils.MainLogger.waitForMessage(MainLogger.java:231)
        at cn.nukkit.utils.MainLogger.run(MainLogger.java:165)


"process reaper" Id=8 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@6522a6
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@6522a6
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ...


"Signal Dispatcher" Id=4 RUNNABLE


"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@11cdeb1
        at java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.ReferenceQueue$Lock@11cdeb1
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)


"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@4551c6
        at java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.Reference$Lock@4551c6
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)


"main" Id=1 RUNNABLE
        at sun.management.ThreadImpl.dumpThreads0(Native Method)
        at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:446)
        at cn.nukkit.utils.Utils.getAllThreadDumps(Utils.java:113)
        at cn.nukkit.Server.tickProcessor(Server.java:875)
        at cn.nukkit.Server.start(Server.java:819)
        at cn.nukkit.Server.<init>(Server.java:502)
        at cn.nukkit.Nukkit.main(Nukkit.java:102)
```
It clashes very violently with the mob plugin for NukkitX

**Comment by lucko** [comment]
Error has nothing to do with LuckPerms.

**Comment by AlekEagleYT** [comment]
ok
