### ISSUE TITLE
Incompatibility with Multiverse-Core v2.5-b699?

### ISSUE THREAD

**Issue by JonCris** [lucko/LuckPerms#794]
I'm using LuckPerms 4.1.5 on Spigot 1.8.8 on my test server, Multiverse didn't throw this error when using previous versions, it is only when I install 4.1.5 that this happens:
Multivers works but all my worlds become unloaded.
```
[22:23:00 INFO]: [Multiverse-Core] Enabling Multiverse-Core v2.5-b699
[22:23:00 INFO]: [Votifier] Votifier enabled on socket /0:0:0:0:0:0:0:0:8192.
[22:23:00 ERROR]: Error occurred while enabling Multiverse-Core v2.5-b699 (Is it up to date?)
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.containsValue(ConcurrentHashMap.java:979) ~[?:1.8.0_111]
	at com.google.common.collect.ForwardingMap.containsValue(ForwardingMap.java:95) ~[spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at org.bukkit.plugin.SimplePluginManager.recalculatePermissionDefaults(SimplePluginManager.java:619) ~[spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:664) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:310) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```
Not sure if this is a LuckPerms issue but it only happens when upgrading LuckPerms.

**Comment by lucko** [comment]
Thanks for reporting :)

https://ci.lucko.me/job/LuckPerms/
