### ISSUE TITLE
Verbose error

### ISSUE THREAD

**Issue by LogGits** [lucko/LuckPerms#822]
Using the command `/lp verbose on chatcontrol`
causes this error:
```
52Exception in thread "luckperms-fallback-0" java.lang.NullPointerException
at me.lucko.luckperms.common.locale.message.Message.format(Message.java:439)
at me.lucko.luckperms.common.locale.message.Message.asString(Message.java:483)
at me.lucko.luckperms.common.locale.message.Message.asString(Message.java:463)
at me.lucko.luckperms.common.command.utils.MessageUtils.contextSetToString(MessageUtils.java:204)
at me.lucko.luckperms.common.verbose.VerboseListener.sendNotification(VerboseListener.java:152)
at me.lucko.luckperms.common.verbose.VerboseListener.acceptData(VerboseListener.java:134)
at me.lucko.luckperms.common.verbose.VerboseHandler.flush(VerboseHandler.java:143)
at me.lucko.luckperms.common.verbose.VerboseHandler.run(VerboseHandler.java:121)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```
and then after that `/lp verbose off` causes this error:
```
java.lang.NullPointerException
at me.lucko.luckperms.common.locale.message.Message.format(Message.java:439)
at me.lucko.luckperms.common.locale.message.Message.asString(Message.java:483)
at me.lucko.luckperms.common.locale.message.Message.asString(Message.java:463)
at me.lucko.luckperms.common.command.utils.MessageUtils.contextSetToString(MessageUtils.java:204)
at me.lucko.luckperms.common.verbose.VerboseListener.sendNotification(VerboseListener.java:152)
at me.lucko.luckperms.common.verbose.VerboseListener.acceptData(VerboseListener.java:134)
at me.lucko.luckperms.common.verbose.VerboseHandler.flush(VerboseHandler.java:143)
at me.lucko.luckperms.common.verbose.VerboseHandler.unregisterListener(VerboseHandler.java:108)
at me.lucko.luckperms.common.commands.misc.VerboseCommand.execute(VerboseCommand.java:109)
at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:50)
at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:42)
at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:202)
at me.lucko.luckperms.common.command.CommandManager.lambda$onCommand$0(CommandManager.java:147)
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```
Im on the build 4.1.29 and paperspigot version (1329)

**Comment by 3TUSK** [comment]
Can confirm this is happening on my side as well.
I am using:
* SponegForge-1.12.2-2611-7.1.0-BETA-2918
* LuckPerms-Sponge-4.1.29

<details>
<summary>

Sample output  produced by executing executing `lp group default permission set luckperms.* true` in server console
</summary>

````
> lp group default permission set luckperms.* true
[16:43:45] [pool-4-thread-1/INFO] [STDERR]: [me.lucko.luckperms.common.command.CommandManager:execute:206]: java.lang.NullPointerException
[16:43:45] [pool-4-thread-1/INFO] [STDERR]: [me.lucko.luckperms.common.command.CommandManager:execute:206]: 	at me.lucko.luckperms.common.locale.message.Message.format(Message.java:439)
[16:43:45] [pool-4-thread-1/INFO] [STDERR]: [me.lucko.luckperms.common.command.CommandManager:execute:206]: 	at me.lucko.luckperms.common.locale.message.Message.asString(Message.java:483)
[16:43:45] [pool-4-thread-1/INFO] [STDERR]: [me.lucko.luckperms.common.command.CommandManager:execute:206]: 	at me.lucko.luckperms.common.locale.message.Message.asString(Message.java:463)
[16:43:45] [pool-4-thread-1/INFO] [STDERR]: [me.lucko.luckperms.common.command.CommandManager:execute:206]: 	at me.lucko.luckperms.common.command.utils.MessageUtils.contextSetToString(MessageUtils.java:197)
[16:43:45] [pool-4-thread-1/INFO] [STDERR]: [me.lucko.luckperms.common.command.CommandManager:execute:206]: 	at me.lucko.luckperms.common.commands.generic.permission.PermissionSet.execute(PermissionSet.java:82)
[16:43:45] [pool-4-thread-1/INFO] [STDERR]: [me.lucko.luckperms.common.command.CommandManager:execute:206]: 	at me.lucko.luckperms.common.command.abstraction.SharedMainCommand.execute(SharedMainCommand.java:99)
[16:43:45] [pool-4-thread-1/INFO] [STDERR]: [me.lucko.luckperms.common.command.CommandManager:execute:206]: 	at me.lucko.luckperms.common.command.abstraction.SharedMainCommand.execute(SharedMainCommand.java:49)
[16:43:45] [pool-4-thread-1/INFO] [STDERR]: [me.lucko.luckperms.common.command.CommandManager:execute:206]: 	at me.lucko.luckperms.common.command.abstraction.MainCommand.execute(MainCommand.java:103)
[16:43:45] [pool-4-thread-1/INFO] [STDERR]: [me.lucko.luckperms.common.command.CommandManager:execute:206]: 	at me.lucko.luckperms.common.command.abstraction.MainCommand.execute(MainCommand.java:46)
[16:43:45] [pool-4-thread-1/INFO] [STDERR]: [me.lucko.luckperms.common.command.CommandManager:execute:206]: 	at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:202)
[16:43:45] [pool-4-thread-1/INFO] [STDERR]: [me.lucko.luckperms.common.command.CommandManager:execute:206]: 	at me.lucko.luckperms.common.command.CommandManager.lambda$onCommand$0(CommandManager.java:147)
[16:43:45] [pool-4-thread-1/INFO] [STDERR]: [me.lucko.luckperms.common.command.CommandManager:execute:206]: 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[16:43:45] [pool-4-thread-1/INFO] [STDERR]: [me.lucko.luckperms.common.command.CommandManager:execute:206]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[16:43:45] [pool-4-thread-1/INFO] [STDERR]: [me.lucko.luckperms.common.command.CommandManager:execute:206]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[16:43:45] [pool-4-thread-1/INFO] [STDERR]: [me.lucko.luckperms.common.command.CommandManager:execute:206]: 	at java.lang.Thread.run(Thread.java:748)
````
</details>

Downgrade to build `#576` can workaround this issue.
