### ISSUE TITLE
Update checking

### ISSUE THREAD

**Issue by SlimeDog** [lucko/LuckPerms#828]
Spigot 1.12.2
LuckPerms 4.1.29

Does LP checks for updates? If yes, is it configurable? I do not find a reference (but may have missed it).

**Comment by lucko** [comment]
No it doesn't, as explained [here](https://github.com/lucko/LuckPerms/wiki/External-connections-and-3rd-party-software).

* Automatically updating is a big security risk. (what happens when someone hacks into the update server and deploys malicious code to all users?!)

* Automatic update *notifications* don't really work for LuckPerms, as there's an update pretty much every day.

https://github.com/lucko/LuckPerms/graphs/commit-activity

**Comment by SlimeDog** [comment]
Thanks. I agree, and I disable all updates and update checking.

I asked because it appears that a lucko app is attempting to check version, and I'm blocking it with NetworkInterceptor, so fires an error.
```
[08:10:05] [Thread-189/WARN]: java.io.IOException: Connect failed
[08:10:05] [Thread-189/WARN]:   at me.lucko.networkinterceptor.interceptors.SecurityManagerInterceptor.checkConnect(SecurityManagerInterceptor.java:31)
[08:10:05] [Thread-189/WARN]:   at java.net.Socket.connect(Socket.java:584)
[08:10:05] [Thread-189/WARN]:   at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
[08:10:05] [Thread-189/WARN]:   at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[08:10:05] [Thread-189/WARN]:   at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1040)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1038)
[08:10:05] [Thread-189/WARN]:   at java.security.AccessController.doPrivileged(Native Method)
[08:10:05] [Thread-189/WARN]:   at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1037)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482)
[08:10:05] [Thread-189/WARN]:   at java.security.AccessController.doPrivileged(Native Method)
[08:10:05] [Thread-189/WARN]:   at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
[08:10:05] [Thread-189/WARN]:   at java.net.URL.openStream(URL.java:1045)
[08:10:05] [Thread-189/WARN]:   at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:72)
[08:10:05] [Thread-189/WARN]:   at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:456)
```

**Comment by lucko** [comment]
I need to see the full error to explain the nature of the check.

You might be able to work it out from reading:
https://github.com/lucko/LuckPerms/wiki/External-connections-and-3rd-party-software

most likely

https://github.com/lucko/LuckPerms/wiki/External-connections-and-3rd-party-software#downloading-libraries

**Comment by SlimeDog** [comment]
That was the complete error message.

**Comment by SlimeDog** [comment]
It looks to be these:
>    104.27.200.92
>    104.27.201.92

If they are blocked, the error is triggered.

**Comment by lucko** [comment]
Those are CloudFlare IPs, doesn't provide much help :p

**Comment by lucko** [comment]
Also btw, the error you posted doesn't indicate it's LuckPerms at all.

**Comment by SlimeDog** [comment]
Ah, CloudFlare IPs. Apologies. Sheesh.

Agreed. Not LuckPerms. Over to the other issue.
