### ISSUE TITLE
Nukkit 

### ISSUE THREAD

**Issue by EnterTG** [lucko/LuckPerms#859]
wlaczanie LuckPerms v4.1.43
20:55:50 [INFO]                __        __   ___  __         __
20:55:50 [INFO]     |    |  | /  ` |__/ |__) |__  |__)  |\/| /__`
20:55:50 [INFO]     |___ \__/ \__, |  \ |    |___ |  \  |  | .__/
20:55:50 [INFO]
20:55:50 [INFO]   Loading version v4.1.43 on Nukkit - Nukkit
20:55:50 [INFO]   Running on server version v1.2.10 - 1.0dev
20:55:50 [INFO]
20:55:50 [INFO] Epoll is unavailable. Reverting to NioEventLoop.
20:55:50 [INFO] [LP] Loading configuration...
20:55:51 [ERROR] [LuckPerms] Plugin LuckPerms v4.1.43 has failed to register events for class me.lucko.luckperms.nukkit.listeners.NukkitConnectionListener because cn/nukkit/event/player/PlayerAsyncPreLoginEvent does not exist.
20:55:51 [INFO] [LP] Loading storage provider... [H2]
20:55:51 [INFO] [LP] Loading internal permission managers...
20:55:51 [INFO] [LP] Performing initial data load...
20:55:51 [INFO] [LP] Successfully enabled. (took 831ms)
20:55:51 [INFO] Przygotowywanie poziomu "world"
20:55:51 [ALERT] java.lang.RuntimeException: java.lang.ClassCastException: me.lucko.luckperms.nukkit.model.server.LPSubscriptionMap$LPSubscriptionValueSet cannot be cast to java.util.WeakHashMap
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:450)
        at cn.nukkit.Server.enablePlugin(Server.java:660)
        at cn.nukkit.Server.enablePlugins(Server.java:649)
        at cn.nukkit.Server.<init>(Server.java:493)
        at cn.nukkit.Nukkit.main(Nukkit.java:102)
Caused by: java.lang.ClassCastException: me.lucko.luckperms.nukkit.model.server.LPSubscriptionMap$LPSubscriptionValueSet cannot be cast to java.util.WeakHashMap
        at cn.nukkit.plugin.PluginManager.subscribeToPermission(PluginManager.java:374)
        at cn.nukkit.permission.PermissibleBase.recalculatePermissions(PermissibleBase.java:130)
        at me.lucko.luckperms.nukkit.model.permissible.MonitoredPermissibleBase.recalculatePermissions(MonitoredPermissibleBase.java:132)
        at cn.nukkit.command.ConsoleCommandSender.recalculatePermissions(ConsoleCommandSender.java:68)
        at cn.nukkit.plugin.PluginManager.dirtyPermissibles(PluginManager.java:366)
        at cn.nukkit.plugin.PluginManager.calculatePermissionDefault(PluginManager.java:354)
        at cn.nukkit.plugin.PluginManager.addPermission(PluginManager.java:318)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:444)
        ... 4 more

20:55:51 [ALERT] java.lang.RuntimeException: java.lang.ClassCastException: me.lucko.luckperms.nukkit.model.server.LPSubscriptionMap$LPSubscriptionValueSet cannot be cast to java.util.WeakHashMap
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:450)
        at cn.nukkit.Server.enablePlugin(Server.java:660)
        at cn.nukkit.Server.enablePlugins(Server.java:649)

**Comment by lucko** [comment]
You need to use the latest version of NukkitX.
