### ISSUE TITLE
/lp editor not working

### ISSUE THREAD

**Issue by 4kz** [lucko/LuckPerms#874]
Issue trying to use /lp editor

[01:42:35] [pool-9-thread-1/WARN]: java.lang.RuntimeException: java.net.ConnectException: Failed to connect to bytebin.lucko.me/2400:cb00:2048:1:0:0:681b:976a:443
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.common.utils.web.StandardPastebin.post(StandardPastebin.java:156)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.common.utils.web.StandardPastebin.postJson(StandardPastebin.java:123)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.common.commands.impl.misc.EditorCommand.execute(EditorCommand.java:105)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.common.commands.abstraction.SingleCommand.execute(SingleCommand.java:51)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.common.commands.abstraction.SingleCommand.execute(SingleCommand.java:43)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.common.commands.CommandManager.execute(CommandManager.java:201)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.common.commands.CommandManager.lambda$onCommand$0(CommandManager.java:146)
[01:42:35] [pool-9-thread-1/WARN]: 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[01:42:35] [pool-9-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[01:42:35] [pool-9-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[01:42:35] [pool-9-thread-1/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[01:42:35] [pool-9-thread-1/WARN]: Caused by: java.net.ConnectException: Failed to connect to bytebin.lucko.me/2400:cb00:2048:1:0:0:681b:976a:443
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:240)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:158)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.common.utils.web.HttpClient$LuckPermsUserAgentInterceptor.intercept(HttpClient.java:87)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:77)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.common.utils.web.HttpClient.makeCall(HttpClient.java:60)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.common.utils.web.StandardPastebin.post(StandardPastebin.java:141)
[01:42:35] [pool-9-thread-1/WARN]: 	... 10 more
[01:42:35] [pool-9-thread-1/WARN]: Caused by: java.net.ConnectException: Network is unreachable
[01:42:35] [pool-9-thread-1/WARN]: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[01:42:35] [pool-9-thread-1/WARN]: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[01:42:35] [pool-9-thread-1/WARN]: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[01:42:35] [pool-9-thread-1/WARN]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[01:42:35] [pool-9-thread-1/WARN]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[01:42:35] [pool-9-thread-1/WARN]: 	at java.net.Socket.connect(Socket.java:589)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.platform.Platform.connectSocket(Platform.java:125)
[01:42:35] [pool-9-thread-1/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:238)
[01:42:35] [pool-9-thread-1/WARN]: 	... 32 more

**Comment by lucko** [comment]
Your server cannot connect to bytebin.lucko.me

There's nothing I can do about this, you need to contact your hosting provider.

**Comment by SwAtRaNgEr** [comment]
i self-host and its still an issue after mirgrating to bungee.

**Comment by Andre601** [comment]
Please do not comment on already closed issues, especially if they are quite outdated and (most likely) not about the topic you mean.
There is currently an open issue (#1860) which is about current issues with the web editor (and also other affected sites from Luck, like his CI server).
