### ISSUE TITLE
NullPointerException getDataDirectory

### ISSUE THREAD

**Issue by Sir-Will** [lucko/LuckPerms#875]
Updated from LuckPerms-Sponge-4.0.80 to LuckPerms-Sponge-4.1.44.jar and now getting this error:

spongeforge-1.12.2-2611-7.1.0-BETA-2990
```
[09:05:09] [Server thread/ERROR]: [Sponge]: Could not pass FMLPreInitializationEvent to Plugin{id=luckperms, name=LuckPerms, version=4.1.44, description=A permissions plugin, url=https://github.com/lucko/LuckPerms, authors=[Luck], source=plugins/LuckPerms-Sponge-4.1.44.jar}
java.lang.NullPointerException: null
	at me.lucko.luckperms.sponge.LPSpongeBootstrap.getDataDirectory(LPSpongeBootstrap.java:248) ~[LPSpongeBootstrap.class:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.getSaveDirectory(DependencyManager.java:82) ~[DependencyManager.class:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependencies(DependencyManager.java:127) ~[DependencyManager.class:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.load(AbstractLuckPermsPlugin.java:97) ~[AbstractLuckPermsPlugin.class:?]
	at me.lucko.luckperms.sponge.LPSpongeBootstrap.onEnable(LPSpongeBootstrap.java:159) ~[LPSpongeBootstrap.class:?]
	at org.spongepowered.common.event.listener.GamePreInitializationEventListener_LPSpongeBootstrap_onEnable39.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2611-7.1.0-BETA-2990]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:335) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2990]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:368) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2990]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:213) [SpongeImpl.class:1.12.2-2611-7.1.0-BETA-2990]
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:240) [SpongeMod.class:1.12.2-2611-7.1.0-BETA-2990]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by lucko** [comment]
```
java.lang.NullPointerException: null
	at me.lucko.luckperms.sponge.LPSpongeBootstrap.getDataDirectory(LPSpongeBootstrap.java:248)
```

https://github.com/lucko/LuckPerms/blob/e4e93b1af1ef9db3b4dcfbb0d27b2940067dd924/sponge/src/main/java/me/lucko/luckperms/sponge/LPSpongeBootstrap.java#L245-L255

I don't see how/why `serverRoot` would be null. Perhaps a filesystem permission issue?

Do you have any ideas?

**Comment by Sir-Will** [comment]
4.0.80 works fine so permissions shouldn't be the issue.
Sponge config is set to `config-dir=plugins` and `plugins-dir=plugins`

**Comment by lucko** [comment]
Ah okay that's probably why

**Comment by lucko** [comment]
Thanks for reporting :)

**Comment by Sir-Will** [comment]
Works now, thanks.
