### ISSUE TITLE
Issue on Bungeecord join or quit

### ISSUE THREAD

**Issue by TehGreekGamerJIM** [lucko/LuckPerms#888]
Here is the error appearing with the join or quit of a player

```
14:58:37 [WARNING] Plugin performed restricted action, please inform them to use proper API methods: Illegal thread group access
java.security.AccessControlException: Plugin violation: Illegal thread group access
    at net.md_5.bungee.BungeeSecurityManager.checkRestricted(BungeeSecurityManager.java:39)
    at net.md_5.bungee.BungeeSecurityManager.checkAccess(BungeeSecurityManager.java:62)
    at java.lang.ThreadGroup.checkAccess(ThreadGroup.java:315)
    at java.lang.Thread.init(Thread.java:391)
    at java.lang.Thread.init(Thread.java:349)
    at java.lang.Thread.‹init›(Thread.java:596)
    at java.util.concurrent.ForkJoinWorkerThread.‹init›(ForkJoinWorkerThread.java:94)
    at java.util.concurrent.ForkJoinWorkerThread$InnocuousForkJoinWorkerThread.‹init›(ForkJoinWorkerThread.java:226)
    at java.util.concurrent.ForkJoinPool$InnocuousForkJoinWorkerThreadFactory$1.run(ForkJoinPool.java:3468)
    at java.util.concurrent.ForkJoinPool$InnocuousForkJoinWorkerThreadFactory$1.run(ForkJoinPool.java:3466)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.util.concurrent.ForkJoinPool$InnocuousForkJoinWorkerThreadFactory.newThread(ForkJoinPool.java:3465)
    at java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1482)
    at java.util.concurrent.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1514)
    at java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1631)
    at java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:2411)
    at java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2645)
    at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.scheduleDrainBuffers(BoundedLocalCache.java:1080)
    at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.afterRead(BoundedLocalCache.java:846)
    at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2012)
    at me.lucko.luckperms.lib.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
    at me.lucko.luckperms.lib.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:67)
    at me.lucko.luckperms.common.utils.CollationKeyCache.compareStrings(CollationKeyCache.java:72)
    at me.lucko.luckperms.common.node.NodeComparator.compare(NodeComparator.java:68)
    at me.lucko.luckperms.common.node.NodeComparator.compare(NodeComparator.java:33)
    at java.util.Collections$ReverseComparator2.compare(Collections.java:5178)
    at java.util.TreeMap.put(TreeMap.java:552)
    at java.util.TreeSet.add(TreeSet.java:255)
    at com.google.common.collect.AbstractMapBasedMultimap.put(AbstractMapBasedMultimap.java:202)
    at com.google.common.collect.AbstractSetMultimap.put(AbstractSetMultimap.java:121)
    at me.lucko.luckperms.common.model.NodeMap.add(NodeMap.java:209)
    at me.lucko.luckperms.common.model.NodeMap.setContent(NodeMap.java:281)
    at me.lucko.luckperms.common.model.PermissionHolder.setEnduringNodes(PermissionHolder.java:283)
    at me.lucko.luckperms.common.storage.dao.sql.SqlDao.loadGroup(SqlDao.java:594)
    at me.lucko.luckperms.common.storage.dao.sql.SqlDao.loadAllGroups(SqlDao.java:621)
    at me.lucko.luckperms.common.storage.AbstractStorage.lambda$loadAllGroups$10(AbstractStorage.java:219)
    at me.lucko.luckperms.common.storage.AbstractStorage$$Lambda$87/1380924218.run(Unknown Source)
    at me.lucko.luckperms.common.storage.AbstractStorage.lambda$makeFuture$1(AbstractStorage.java:97)
    at me.lucko.luckperms.common.storage.AbstractStorage$$Lambda$88/1105628551.run(Unknown Source)
    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by lucko** [comment]
The message is being printed by BungeeCord, not LuckPerms. It's warning you of something which is really a non-issue, which is why I assume it has been removed in the newer releases of BungeeCord.

You should update to the latest version of BungeeCord.
