### ISSUE TITLE
Webeditor and permission tree can't be open

### ISSUE THREAD

**Issue by timo003002** [lucko/LuckPerms#894]
Since two days I get this error when I try to generate a permissiontree:
 
```
[13:42:39 INFO]: [LP] Generating permission tree...
[13:42:45 WARN]: java.lang.RuntimeException: Connection returned response code: 401 - Unauthorized
[13:42:45 WARN]:        at me.lucko.luckperms.common.utils.PasteUtils.paste(PasteUtils.java:84)
[13:42:45 WARN]:        at me.lucko.luckperms.common.treeview.TreeView.uploadPasteData(TreeView.java:183)
[13:42:45 WARN]:        at me.lucko.luckperms.common.commands.impl.misc.TreeCommand.execute(TreeCommand.java:119)
[13:42:45 WARN]:        at me.lucko.luckperms.common.commands.abstraction.SingleCommand.execute(SingleCommand.java:51)
[13:42:45 WARN]:        at me.lucko.luckperms.common.commands.abstraction.SingleCommand.execute(SingleCommand.java:43)
[13:42:45 WARN]:        at me.lucko.luckperms.common.commands.CommandManager.execute(CommandManager.java:197)
[13:42:45 WARN]:        at me.lucko.luckperms.common.commands.CommandManager.lambda$onCommand$0(CommandManager.java:142)
[13:42:45 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[13:42:45 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:42:45 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:42:45 WARN]:        at java.lang.Thread.run(Thread.java:748)
[13:42:45 INFO]: [LP] Permission tree URL:
[13:42:45 WARN]: java.lang.IllegalStateException: content must be set
[13:42:45 WARN]:        at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
[13:42:45 WARN]:        at me.lucko.luckperms.lib.text.TextComponent$Builder.build(TextComponent.java:260)
[13:42:45 WARN]:        at me.lucko.luckperms.common.commands.impl.misc.TreeCommand.execute(TreeCommand.java:126)
[13:42:45 WARN]:        at me.lucko.luckperms.common.commands.abstraction.SingleCommand.execute(SingleCommand.java:51)
[13:42:45 WARN]:        at me.lucko.luckperms.common.commands.abstraction.SingleCommand.execute(SingleCommand.java:43)
[13:42:45 WARN]:        at me.lucko.luckperms.common.commands.CommandManager.execute(CommandManager.java:197)
[13:42:45 WARN]:        at me.lucko.luckperms.common.commands.CommandManager.lambda$onCommand$0(CommandManager.java:142)
[13:42:45 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[13:42:45 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:42:45 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:42:45 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

Tested on two completely separate servers.

**Comment by lucko** [comment]
You need to update to the latest version.
