### ISSUE TITLE
LuckPerms not works ( SPIGOT 1.8.8, Viaversion 1.8.8 - 1.12, BungeeCord server)

### ISSUE THREAD

**Issue by Killers0992** [lucko/LuckPerms#900]
Commands not works /lp /luckperms 
```
[09:36:08] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v4.1.61
[09:36:11] [Server thread/INFO]: [LuckPerms] [ERROR] Exception whilst downloading dependency CAFFEINE
[09:36:11] [Server thread/WARN]: java.net.NoRouteToHostException: No route to host (Host unreachable)
[09:36:11] [Server thread/WARN]: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[09:36:11] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[09:36:11] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[09:36:11] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[09:36:11] [Server thread/WARN]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[09:36:11] [Server thread/WARN]: 	at java.net.Socket.connect(Socket.java:589)
[09:36:11] [Server thread/WARN]: 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
[09:36:11] [Server thread/WARN]: 	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[09:36:11] [Server thread/WARN]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[09:36:11] [Server thread/WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[09:36:11] [Server thread/WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[09:36:11] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[09:36:11] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[09:36:11] [Server thread/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[09:36:11] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
[09:36:11] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
[09:36:11] [Server thread/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[09:36:11] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
[09:36:11] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
[09:36:11] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[09:36:11] [Server thread/WARN]: 	at java.net.URL.openStream(URL.java:1045)
[09:36:11] [Server thread/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManager.downloadDependency(DependencyManager.java:209)
[09:36:11] [Server thread/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependencies(DependencyManager.java:139)
[09:36:11] [Server thread/WARN]: 	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.load(AbstractLuckPermsPlugin.java:98)
[09:36:11] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onLoad(LPBukkitBootstrap.java:118)
[09:36:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297)
[09:36:11] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198)
[09:36:11] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[09:36:11] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[09:36:14] [Server thread/INFO]: [LuckPerms] [ERROR] Exception whilst downloading dependency OKIO
[09:36:14] [Server thread/WARN]: java.net.NoRouteToHostException: No route to host (Host unreachable)
[09:36:14] [Server thread/WARN]: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[09:36:14] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[09:36:14] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[09:36:14] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[09:36:14] [Server thread/WARN]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[09:36:14] [Server thread/WARN]: 	at java.net.Socket.connect(Socket.java:589)
[09:36:14] [Server thread/WARN]: 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
[09:36:14] [Server thread/WARN]: 	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[09:36:14] [Server thread/WARN]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[09:36:14] [Server thread/WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[09:36:14] [Server thread/WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[09:36:14] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[09:36:14] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[09:36:14] [Server thread/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[09:36:14] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
[09:36:14] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
[09:36:14] [Server thread/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[09:36:14] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
[09:36:14] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
[09:36:14] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[09:36:14] [Server thread/WARN]: 	at java.net.URL.openStream(URL.java:1045)
[09:36:14] [Server thread/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManager.downloadDependency(DependencyManager.java:209)
[09:36:14] [Server thread/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependencies(DependencyManager.java:139)
[09:36:14] [Server thread/WARN]: 	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.load(AbstractLuckPermsPlugin.java:98)
[09:36:14] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onLoad(LPBukkitBootstrap.java:118)
[09:36:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297)
[09:36:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198)
[09:36:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[09:36:14] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[09:36:17] [Server thread/INFO]: [LuckPerms] [ERROR] Exception whilst downloading dependency OKHTTP
[09:36:17] [Server thread/WARN]: java.net.NoRouteToHostException: No route to host (Host unreachable)
[09:36:17] [Server thread/WARN]: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[09:36:17] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[09:36:17] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[09:36:17] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[09:36:17] [Server thread/WARN]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[09:36:17] [Server thread/WARN]: 	at java.net.Socket.connect(Socket.java:589)
[09:36:17] [Server thread/WARN]: 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
[09:36:17] [Server thread/WARN]: 	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[09:36:17] [Server thread/WARN]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[09:36:17] [Server thread/WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[09:36:17] [Server thread/WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[09:36:17] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[09:36:17] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[09:36:17] [Server thread/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[09:36:17] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
[09:36:17] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
[09:36:17] [Server thread/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[09:36:17] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
[09:36:17] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
[09:36:17] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[09:36:17] [Server thread/WARN]: 	at java.net.URL.openStream(URL.java:1045)
[09:36:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManager.downloadDependency(DependencyManager.java:209)
[09:36:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependencies(DependencyManager.java:139)
[09:36:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.load(AbstractLuckPermsPlugin.java:98)
[09:36:17] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onLoad(LPBukkitBootstrap.java:118)
[09:36:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297)
[09:36:17] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198)
[09:36:17] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[09:36:17] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Andre601** [comment]
Put that error on hastebin next time.

DO you use the BungeeCord-version of LuckPerms, if that happens on BungeeCord?

**Comment by Killers0992** [comment]
I use LuckPerms bukkit on a server connected with bungeecord or survival

**Comment by lucko** [comment]
Your server needs to be able to connect to the internet the first time LuckPerms enables.

More specifically, it needs to be able to connect to https://repo1.maven.org/
