### ISSUE TITLE
Latest nukkit version doesn't work

### ISSUE THREAD

**Issue by nilsbrychzy** [lucko/LuckPerms#902]
```
23:46:02 [INFO] Enabling LuckPerms v4.1.61
23:46:02 [INFO]                __        __   ___  __         __
23:46:02 [INFO]     |    |  | /  ` |__/ |__) |__  |__)  |\/| /__`
23:46:02 [INFO]     |___ \__/ \__, |  \ |    |___ |  \  |  | .__/
23:46:02 [INFO]
23:46:02 [INFO]   Loading version v4.1.61 on Nukkit - Nukkit
23:46:02 [INFO]   Running on server version v1.2.13 - 1.0dev
23:46:02 [INFO]
23:46:02 [INFO] [LP] Loading configuration...
23:46:03 [INFO] [LP] Loading storage provider... [MYSQL]
> SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/root/dev/nukkit-1.0-SNAPSHOT.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/dev/plugins/LuckPerms/lib/slf4j_simple-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
Failed to instantiate SLF4J LoggerFactory
Reported exception:
java.lang.NoClassDefFoundError: org/slf4j/spi/LoggerFactoryBinder
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
        at me.lucko.luckperms.lib.hikari.HikariConfig.<clinit>(HikariConfig.java:52)
        at me.lucko.luckperms.common.storage.dao.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:77)
        at me.lucko.luckperms.common.storage.dao.sql.SqlDao.init(SqlDao.java:156)
        at me.lucko.luckperms.common.storage.AbstractStorage.init(AbstractStorage.java:130)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at me.lucko.luckperms.common.storage.wrappings.PhasedStorage.lambda$wrap$0(PhasedStorage.java:69)
        at com.sun.proxy.$Proxy8.init(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at me.lucko.luckperms.common.storage.wrappings.BufferedOutputStorage.lambda$wrap$0(BufferedOutputStorage.java:86)
        at com.sun.proxy.$Proxy9.init(Unknown Source)
        at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:115)
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:135)
        at me.lucko.luckperms.nukkit.LPNukkitBootstrap.onEnable(LPNukkitBootstrap.java:107)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:113)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:435)
        at cn.nukkit.Server.enablePlugin(Server.java:670)
        at cn.nukkit.Server.enablePlugins(Server.java:659)
        at cn.nukkit.Server.<init>(Server.java:428)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.ClassNotFoundException: org.slf4j.spi.LoggerFactoryBinder
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 44 more
23:46:03 [ALERT] java.lang.RuntimeException: java.lang.reflect.UndeclaredThrowableException
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439)
        at cn.nukkit.Server.enablePlugin(Server.java:670)
        at cn.nukkit.Server.enablePlugins(Server.java:659)
        at cn.nukkit.Server.<init>(Server.java:428)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.reflect.UndeclaredThrowableException
        at com.sun.proxy.$Proxy9.init(Unknown Source)
        at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:115)
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:135)
        at me.lucko.luckperms.nukkit.LPNukkitBootstrap.onEnable(LPNukkitBootstrap.java:107)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:113)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:435)
        ... 4 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at me.lucko.luckperms.common.storage.wrappings.BufferedOutputStorage.lambda$wrap$0(BufferedOutputStorage.java:86)
        ... 11 more
Caused by: java.lang.reflect.UndeclaredThrowableException
        at com.sun.proxy.$Proxy8.init(Unknown Source)
        ... 16 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at me.lucko.luckperms.common.storage.wrappings.PhasedStorage.lambda$wrap$0(PhasedStorage.java:69)
        ... 17 more
Caused by: java.lang.NoClassDefFoundError: org/slf4j/spi/LoggerFactoryBinder
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
        at me.lucko.luckperms.lib.hikari.HikariConfig.<clinit>(HikariConfig.java:52)
        at me.lucko.luckperms.common.storage.dao.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:77)
        at me.lucko.luckperms.common.storage.dao.sql.SqlDao.init(SqlDao.java:156)
        at me.lucko.luckperms.common.storage.AbstractStorage.init(AbstractStorage.java:130)
        ... 22 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.spi.LoggerFactoryBinder
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 44 more

23:46:03 [INFO] Disabling LuckPerms v4.1.61
23:46:03 [INFO] [LP] Closing storage...
23:46:03 [ALERT] java.lang.NullPointerException
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.disable(AbstractLuckPermsPlugin.java:206)
        at me.lucko.luckperms.nukkit.LPNukkitBootstrap.onDisable(LPNukkitBootstrap.java:115)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:91)
        at cn.nukkit.plugin.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:128)
        at cn.nukkit.plugin.PluginManager.disablePlugin(PluginManager.java:509)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:441)
        at cn.nukkit.Server.enablePlugin(Server.java:670)
        at cn.nukkit.Server.enablePlugins(Server.java:659)
        at cn.nukkit.Server.<init>(Server.java:428)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)

23:46:03 [INFO] Preparing level "world"
23:46:03 [INFO] NukkitPlotGenerator does not fully support: cn.nukkit.level.generator.Normal@16f15ae9
23:46:03 [ALERT] No level called "nether" found! Nether functionality will be disabled.
23:46:03 [INFO] Enabling FastAsyncWorldEdit v18.03.26-48992d2-1054-19.4.17
> Apr 08, 2018 11:46:04 PM com.boydti.fawe.nukkit.core.NukkitWorldEdit onEnable
INFO: WorldEdit for Nukkit (version 1.0.0) is loaded
23:46:05 [INFO] Enabling DbLib v0.2.2
23:46:05 [INFO] Starting GS4 status listener
23:46:05 [INFO] Setting query port to 20001
23:46:05 [INFO] Query is running on 0.0.0.0:20001
23:46:05 [INFO] Default game type: Survival Mode
23:46:05 [INFO] Done (6.059s)! For help, type "help" or "?"
> Apr 08, 2018 11:46:05 PM com.boydti.fawe.nukkit.optimization.FaweNukkit debug
INFO: &8(&4&lFAWE&8)&r&7 Optimizing PlotSquared
Apr 08, 2018 11:46:05 PM com.boydti.fawe.nukkit.optimization.FaweNukkit debug
INFO: &8(&4&lFAWE&8)&r&7  - QueueProvider: class com.boydti.fawe.regions.general.plot.FaweLocalBlockQueue
Apr 08, 2018 11:46:05 PM com.boydti.fawe.nukkit.optimization.FaweNukkit debug
INFO: &8(&4&lFAWE&8)&r&7  - HybridPlotManager.REGENERATIVE_CLEAR: false
Apr 08, 2018 11:46:05 PM com.boydti.fawe.nukkit.optimization.FaweNukkit debug
INFO: &8(&4&lFAWE&8)&r&7  - SchematicHandler: com.boydti.fawe.regions.general.plot.FaweSchematicHandler@2699b656
Apr 08, 2018 11:46:05 PM com.boydti.fawe.nukkit.optimization.FaweNukkit debug
INFO: &8(&4&lFAWE&8)&r&7  - ChunkManager: com.boydti.fawe.regions.general.plot.FaweChunkManager@5d67b2b3
Apr 08, 2018 11:46:05 PM com.boydti.fawe.nukkit.optimization.FaweNukkit debug
INFO: &8(&4&lFAWE&8)&r&7 Plugin 'PlotSquared' found. Using it now.
```

Version used: https://ci.nukkitx.com/job/NukkitX/job/1.2.13/lastSuccessfulBuild/artifact/target/nukkit-1.0-SNAPSHOT.jar (Latest 1.2.13)

**Comment by lucko** [comment]
This is a Nukkit issue, which is resolved in https://github.com/NukkitX/Nukkit/pull/212
