### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by SlimeDog** [lucko/LuckPerms#925]
Spigot 1.12.2
LuckPerms 4.1.69

Reference NPE error https://github.com/lucko/LuckPerms/issues/924

After which I cannot connect. Reverting to LP 4.1.68.
```
[07:16:59 INFO]: [LuckPerms] [WARN] Exception thrown whilst performing i/o: 3cf9b867-2577-49d1-affb-7ba8196a0d39
[07:16:59 WARN]: java.lang.NullPointerException
[07:16:59 WARN]:        at me.lucko.luckperms.common.storage.dao.file.SeparatedConfigurateDao.readFile(SeparatedConfigurateDao.java:78)
[07:16:59 WARN]:        at me.lucko.luckperms.common.storage.dao.file.AbstractConfigurateDao.loadUser(AbstractConfigurateDao.java:181)
[07:16:59 WARN]:        at me.lucko.luckperms.common.storage.AbstractStorage.lambda$loadUser$4(AbstractStorage.java:170)
[07:16:59 WARN]:        at me.lucko.luckperms.common.storage.AbstractStorage.lambda$makeFuture$0(AbstractStorage.java:89)
[07:16:59 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[07:16:59 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[07:16:59 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[07:16:59 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[07:16:59 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[07:16:59 WARN]:        at java.lang.Thread.run(Thread.java:748)
[07:16:59 INFO]: [LuckPerms] [ERROR] Exception occurred whilst loading data for 3cf9b867-2577-49d1-affb-7ba8196a0d39 - rambeau
[07:16:59 WARN]: java.util.concurrent.CompletionException: java.lang.NullPointerException
[07:16:59 WARN]:        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
[07:16:59 WARN]:        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
[07:16:59 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
[07:16:59 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[07:16:59 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[07:16:59 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[07:16:59 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[07:16:59 WARN]:        at java.lang.Thread.run(Thread.java:748)
[07:16:59 WARN]: Caused by: java.lang.NullPointerException
[07:16:59 WARN]:        at me.lucko.luckperms.common.storage.dao.file.SeparatedConfigurateDao.readFile(SeparatedConfigurateDao.java:78)
[07:16:59 WARN]:        at me.lucko.luckperms.common.storage.dao.file.AbstractConfigurateDao.loadUser(AbstractConfigurateDao.java:181)
[07:16:59 WARN]:        at me.lucko.luckperms.common.storage.AbstractStorage.lambda$loadUser$4(AbstractStorage.java:170)
[07:16:59 WARN]:        at me.lucko.luckperms.common.storage.AbstractStorage.lambda$makeFuture$0(AbstractStorage.java:89)
[07:16:59 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[07:16:59 WARN]:        ... 5 more
[07:16:59 INFO]: Disconnecting com.mojang.authlib.GameProfile@2f5c3061[id=3cf9b867-2577-49d1-affb-7ba8196a0d39,name=rambeau,properties={textures=[com.mojang.authlib.properties.Property@3551edc4]},legacy=false] (/108.226.240.191:53121): [LP] §cPermissions data could not be loaded. Please try again later.
[07:16:59 INFO]: com.mojang.authlib.GameProfile@2f5c3061[id=3cf9b867-2577-49d1-affb-7ba8196a0d39,name=rambeau,properties={textures=[com.mojang.authlib.properties.Property@3551edc4]},legacy=false] (/108.226.240.191:53121) lost connection: [LP] §cPermissions data could not be loaded. Please try again later.
```

**Comment by SlimeDog** [comment]
Confirmed fixed 4.1.70
