### ISSUE TITLE
Anyway to get rid of this error because someone uses a chinese character for suffix?

### ISSUE THREAD

**Issue by madtomic** [lucko/LuckPerms#951]
[14:01:36 WARN]: [] java.sql.SQLException: Incorrect string value: '\xE7\x8E\xA9&6\xE5...' for column 'msg' at row 1
[14:01:36 WARN]: []     at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[14:01:36 WARN]: []     at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[14:01:36 WARN]: []     at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[14:01:36 WARN]: []     at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[14:01:36 WARN]: []     at me.lucko.luckperms.lib.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1283)
[14:01:36 WARN]: []     at me.lucko.luckperms.lib.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:783)
[14:01:36 WARN]: []     at me.lucko.luckperms.lib.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
> [14:01:36 INFO]: [] [LP] [Sql Messaging] Sending user ping for 'madtomic' with id: cafb1b83-ae69-4ba3-b365-6cbd24afeb44
> [14:01:36 WARN]: []   at me.lucko.luckperms.lib.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[14:01:36 WARN]: []     at me.lucko.luckperms.lib.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[14:01:36 WARN]: []     at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.sendOutgoingMessage(AbstractSqlMessenger.java:76)
[14:01:36 WARN]: []     at me.lucko.luckperms.common.messaging.LuckPermsMessagingService.lambda$pushLog$2(LuckPermsMessagingService.java:131)
[14:01:36 WARN]: []     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[14:01:36 WARN]: []     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[14:01:36 WARN]: []     at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:01:36 WARN]: []     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:01:36 WARN]: []     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:01:36 WARN]: []     at java.lang.Thread.run(Unknown Source)

**Comment by lucko** [comment]
The error is being returned by your MySQL server, not LuckPerms, so, there's not really much I can do about it.

LP uses UTF-8 encoding when sending data to the SQL server, which is (as far as I know) the current best practice.
