### ISSUE TITLE
mysql

### ISSUE THREAD

**Issue by ProDash1998** [lucko/LuckPerms#957]
[20:49:26 ERROR]: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Out of range value for column 'accounts' at row 1
[20:49:26 ERROR]:       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3971)
[20:49:26 ERROR]:       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[20:49:26 ERROR]:       at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[20:49:26 ERROR]:       at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[20:49:26 ERROR]:       at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480)
[20:49:26 ERROR]:       at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1552)
[20:49:26 ERROR]:       at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2607)
[20:49:26 ERROR]:       at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1480)
[20:49:26 ERROR]:       at net.uraharanz.plugins.dba.utils.MySQL$1.run(MySQL.java:43)
[20:49:26 ERROR]:       at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
[20:49:26 ERROR]:       at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:49:26 ERROR]:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:49:26 ERROR]:       at java.lang.Thread.run(Unknown Source)

waterfall

**Comment by lucko** [comment]
Not a LuckPerms error, report to the author of `net.uraharanz.plugins.dba.utils.MySQL`

**Comment by ProDash1998** [comment]
sorry
