### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ProDash1998** [lucko/LuckPerms#962]
[LP] Loading configuration...
[13:13:39 INFO]: [LP] Loading storage provider... [MYSQL]
[13:13:39 INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms - Starting...
[13:13:39 INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms - Start completed.
[13:13:39 WARN]: java.sql.SQLException: Incorrect information in file: '.\rangi\luckperms_actions.frm'
[13:13:39 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[13:13:39 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
[13:13:39 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
[13:13:39 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[13:13:39 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[13:13:39 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2482)
[13:13:39 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2440)
[13:13:39 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
[13:13:39 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
[13:13:39 WARN]:        at me.lucko.luckperms.lib.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
[13:13:39 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
[13:13:39 WARN]:        at me.lucko.luckperms.common.storage.dao.sql.SqlDao.init(SqlDao.java:198)
[13:13:39 WARN]:        at me.lucko.luckperms.common.storage.AbstractStorage.init(AbstractStorage.java:130)
[13:13:39 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:13:39 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:13:39 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:13:39 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[13:13:39 WARN]:        at me.lucko.luckperms.common.storage.wrappings.PhasedStorage.lambda$wrap$0(PhasedStorage.java:69)
[13:13:39 WARN]:        at com.sun.proxy.$Proxy27.init(Unknown Source)
[13:13:39 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:13:39 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:13:39 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:13:39 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[13:13:39 WARN]:        at me.lucko.luckperms.common.storage.wrappings.BufferedOutputStorage.lambda$wrap$0(BufferedOutputStorage.java:86)
[13:13:39 WARN]:        at com.sun.proxy.$Proxy28.init(Unknown Source)
[13:13:39 WARN]:        at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:116)
[13:13:39 WARN]:        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:138)
[13:13:39 WARN]:        at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:138)
[13:13:39 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:13:39 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[13:13:39 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:13:39 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[13:13:39 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[13:13:39 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:227)
[13:13:39 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[13:13:39 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by ProDash1998** [comment]
I have a database enabled

**Comment by lucko** [comment]
Your MySQL server is returning this error

> Incorrect information in file: '.\rangi\luckperms_actions.frm'

Seems like some sort of data corruption there? Do you have any data already in the DB?
