### ISSUE TITLE
Problem enabling plugin in waterfall

### ISSUE THREAD

**Issue by iDavid86920** [lucko/LuckPerms#986]
Hello, i have a problem whit the plugin in waterfall thanks.

Error:
`[05:34:54] [main/WARN]: Error enabling plugin LuckPerms
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_162]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_162]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_162]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_162]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_162]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_162]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_162]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_162]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_162]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_162]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:34) ~[server.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:7aa12d5:174]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27) ~[server.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:7aa12d5:174]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_162]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:338) [server.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:7aa12d5:174]
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:246) [server.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:7aa12d5:174]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:272) [server.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:7aa12d5:174]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56) [server.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:7aa12d5:174]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) [server.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:7aa12d5:174]
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53) ~[server.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:7aa12d5:174]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27) ~[server.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:7aa12d5:174]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_162]
	... 18 more`

**Comment by merjilin** [comment]
You need to use the bungee version of Luckperms which is downloable here: https://luckperms.github.io/

You're currently attempting to use the bukkit version :)
